### PR TITLE
Decrease task priority slightly to deprioritize during contention

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
image

(The image is for when I was experimenting with the lowest priority.)

**Comment by bradyoo** [comment]
@calvinjia

**Comment by bradyoo** [comment]
It is unclear whether we want to do this.

**Comment by calvinjia** [comment]
@bradyoo What impact does this have on resource sharing? Should the thread priority be configurable?

**Comment by bradyoo** [comment]
It appears to have some small impact but it really depends on the
situation. For now, the intention for it to be slightly lower than all the
other things that could be running on the worker. We could make this
configurable but I would prefer not because we may want to reimplement
parts of this.

**Pull request closed without merging**
