### PR TITLE
Close UFS properly in UFSJournalV0 code

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
Not even sure if this code even gets run ever but...

**Comment by madanadit** [comment]
```
Tests in error: 
alluxio.client.fs.FreeAndDeleteIntegrationTest.deleteDir(alluxio.client.fs.FreeAndDeleteIntegrationTest)
  Run 1: FreeAndDeleteIntegrationTest.deleteDir:145 » TestTimedOut test timed out after...
  Run 2: FreeAndDeleteIntegrationTest.deleteDir:148 » TestTimedOut test timed out after...
```

**Comment by madanadit** [comment]
alluxio-bot, test this please.

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Comment by ZacBlanco** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please

**Pull request merged**
