### PR TITLE
Fix metric web ui can't resolve large number datapoints

### PR DESCRIPTION
**Pull request by bzheng888**
### What changes are proposed in this pull request?
Fix metric web ui will block when data points number too large to process

### Why are the changes needed?
This is a bug. metric web ui can't show pages, when there are too many data points. 

### Does this PR introduce any user facing changes?
No
Please list the user-facing changes introduced by your change, including
webui

### CODE REVIEW

**Review by maobaolong — CHANGES_REQUESTED** [review]
Thanks for the bug fix. Please care about the failed UT.

java.lang.AssertionError: expected:<20.0> but was:<10.0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:685)
	at alluxio.master.metrics.TimeSeriesStoreTest.orderedTimeSeries(TimeSeriesStoreTest.java:77)

**Review by maobaolong — APPROVED** [review]
Thanks for fixed the failed ut. LGTM

**Comment by bzheng888** [comment]
@tieujason330 PTAL!

**Review by tieujason330 — APPROVED** [review]
LGTM, thanks for making this change!

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
