### PR TITLE
[ALLUXIO-2277] Fix javadoc in StorageDir.java by "@lyzGithub"

### PR DESCRIPTION
**Pull request by lyzGithub**
https://alluxio.atlassian.net/browse/ALLUXIO-2277
This file often refers to metadata as "meta data". I correct this to "metadata".

### CODE REVIEW

**Comment by lyzGithub** [comment]
I just did it as simple homework. @AmplabJenkins

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by aaudiber** [comment]
Jenkins, test this please

**Comment by aaudiber** [comment]
Test failure looks unrelated

**Pull request merged**
