### PR TITLE
Fix metric worker.cacheBlockSize increases when cache already existed

### PR DESCRIPTION
**Pull request by flaming-archer**
### What changes are proposed in this pull request?

If cache already exists in Alluxio, when try to cache the same block, don't increase the metric worker.cacheBlockSize.

### Why are the changes needed?

The metric Worker.CacheBlocksSize is not correct. If data already exists in Alluxio, caching the same block again will increate metric Worker.cacheBlockSize.

### Does this PR introduce any user facing changes?

no

### CODE REVIEW

**Comment by ssz1997** [comment]
@flaming-archer Thanks for your contribution. Do you mind create an issue to explain a little bit more about why exactly is wrong? Thanks!

**Review by ssz1997 — CHANGES_REQUESTED** [review]
Thanks for the fix. The naming of the variables are a little confusing at first glance. Also, the result needs to be non-null to update the metrics, which is not correct. When caching fails, the result can still be null.
I think it's better to make the `CacheResult` an Enum to indicate the three results: success, fail, and already exist. When created it should be at fail state, just as it was set to false upon declaration previously. This solves the problem of not updating the metric when cache fails.

**Comment by ssz1997** [comment]
@jja725 Take a look at the change? Since the file was modified by you last time.

**Review by jja725 — COMMENTED** [review]
Agree with shawn. I would prefer to add an Enum with values: Succeed, Failed, AlreadyCached to simplify the code.

**Comment by flaming-archer** [comment]
Enum is a good idea, I have changed it.

**Review by ssz1997 — APPROVED** [review]
LGTM. Thanks for fixing the metrics. I'll update the PR title to be more clear.

**Review by jja725 — APPROVED** [review]

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
