### PR TITLE
Generate java files from .proto definitions automatically

### PR DESCRIPTION
**Pull request by maobaolong**
Instead of checking in the proto-generated java files into the code base, allow maven to automatically run protoc to generate those java files. This adds about 10 more seconds to the build time. To skip the building of the proto files, add `-Dskip.protoc` to the maven command.

### CODE REVIEW

**Comment by maobaolong** [comment]
@apc999  Please help me to review this PR, aimed to remove the generated file by protoc, Using proto maven plugin to help us download the right protoc version, and runing by default, skip by "mvn -Dskip.proto=true"

**Comment by gpang** [comment]
What would be the typical workflow? If we run `mvn clean install` will it remove the generated files, then regenerate them?

Is there some way to detect if the generate is necessary from updates to the .proto files, similar to how .java files are compiled?

**Comment by maobaolong** [comment]
@gpang  Sorry for the missing days. As we discussed at slack, 

After `mvn clean`  my target folder was deleted, and `mvn clean install` means clean first, then install. Although i execute `mvn install` ,  the generated source file ware updated as expected.

So, answer your question, 

- Yes, it will remove target dir, because i let the generate-source folder under target folder, so the generated files will be removed same time.
- No, but we don't need to care this thing, because every time we compile our project, the `protobuf-maven-plugin` will work as transparent. In fact we shouldn't treat the generated-source as our source.

**Comment by gpang** [comment]
@ggezer Are you saying that by default, the `mvn` command should not generate the files?

I think it should be generated by default, and skipped with a command-line flag. It could be similar to how we treat other build stages, like findbugs, checkstyle, javadoc, etc.

**Comment by ggezer** [comment]
@gpang I'm asking to have a `skipGenerate` profile that has `skip.proto` as `true`. So when under that profile proto generation will be suppressed.

**Comment by maobaolong** [comment]
@gpang Yeah, the default value of `skip.protoc` flag set to false, it means that protoc will be run as default, if you want to skip it, just set `-Dskip.protoc=true`.

**Comment by maobaolong** [comment]
@gpang Please take a look at this approach.

**Comment by gpang** [comment]
@maobaolong Can you update this documentation page as well? https://github.com/Alluxio/alluxio/blob/master/docs/en/contributor/Building-Alluxio-From-Source.md

I think you will also have to resolve the conflicts in the PR.

**Comment by maobaolong** [comment]
@gpang  Thank you for your review again, i updates the documents relates, and resolve the conflicts.
PTAL.

**Comment by maobaolong** [comment]
@gpang Is the failed tests caused by me?

The following is the part of jenkins report.
```
testCheckpointReplay(alluxio.server.ft.journal.MultiMasterJournalTest)  Time elapsed: 7.592 sec  <<< ERROR!
java.io.IOException: java.util.concurrent.TimeoutException: Timed out waiting for master starts serving RPCs options: WaitForOptions{interval=20, timeout=5000}
	at alluxio.server.ft.journal.MultiMasterJournalTest.before(MultiMasterJournalTest.java:53)
Caused by: java.util.concurrent.TimeoutException: Timed out waiting for master starts serving RPCs options: WaitForOptions{interval=20, timeout=5000}
	at alluxio.server.ft.journal.MultiMasterJournalTest.before(MultiMasterJournalTest.java:53)

testCheckpointReplay(alluxio.server.ft.journal.MultiMasterJournalTest)  Time elapsed: 7.762 sec  <<< ERROR!
java.io.IOException: java.util.concurrent.TimeoutException: Timed out waiting for master starts serving RPCs options: WaitForOptions{interval=20, timeout=5000}
	at alluxio.server.ft.journal.MultiMasterJournalTest.before(MultiMasterJournalTest.java:53)
Caused by: java.util.concurrent.TimeoutException: Timed out waiting for master starts serving RPCs options: WaitForOptions{interval=20, timeout=5000}
	at alluxio.server.ft.journal.MultiMasterJournalTest.before(MultiMasterJournalTest.java:53)

Running alluxio.server.ft.journal.TriggeredCheckpointTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.075 sec - in alluxio.server.ft.journal.TableMasterJournalIntegrationTest
Running alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 29.048 sec - in alluxio.server.ft.journal.TriggeredCheckpointTest
Running alluxio.server.ft.journal.ufs.RenameFailureJournalTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.307 sec - in alluxio.server.ft.journal.ufs.RenameFailureJournalTest
Running alluxio.server.ft.journal.ufs.SecondaryMasterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.552 sec - in alluxio.server.ft.journal.ufs.SecondaryMasterTest
Running alluxio.server.ft.journal.ufs.UfsConfigurationJournalTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 129.201 sec - in alluxio.server.ft.ZookeeperFailureIntegrationTest
Running alluxio.server.ft.journal.ufs.UfsJournalIntegrationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.902 sec - in alluxio.server.ft.journal.ufs.UfsConfigurationJournalTest
Running alluxio.server.health.BlockMasterIntegrityIntegrationTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.878 sec - in alluxio.server.health.BlockMasterIntegrityIntegrationTest
Running alluxio.server.health.JobMasterHealthCheckClientIntegrationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.082 sec - in alluxio.server.health.JobMasterHealthCheckClientIntegrationTest
Running alluxio.server.health.JobWorkerHealthCheckClientIntegrationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.215 sec - in alluxio.server.health.JobWorkerHealthCheckClientIntegrationTest
Running alluxio.server.health.MasterHealthCheckClientIntegrationTest
Tests run: 16, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 47.776 sec <<< FAILURE! - in alluxio.server.ft.journal.ufs.UfsJournalIntegrationTest
file(alluxio.server.ft.journal.ufs.UfsJournalIntegrationTest)  Time elapsed: 1.71 sec  <<< ERROR!
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: EOF while parsing checkpoint type. Was your checkpoint written by alluxio-1.x? See https://docs.alluxio.io/os/user/edge/en/operation/2.x-Upgrade.html for instructions on how to upgrade from alluxio-1.x to alluxio-2.x
	at alluxio.server.ft.journal.ufs.UfsJournalIntegrationTest.createFsMasterFromJournal(UfsJournalIntegrationTest.java:603)
	at alluxio.server.ft.journal.ufs.UfsJournalIntegrationTest.fileTestUtil(UfsJournalIntegrationTest.java:332)
	at alluxio.server.ft.journal.ufs.UfsJournalIntegrationTest.file(UfsJournalIntegrationTest.java:328)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: EOF while parsing checkpoint type. Was your checkpoint written by alluxio-1.x? See https://docs.alluxio.io/os/user/edge/en/operation/2.x-Upgrade.html for instructions on how to upgrade from alluxio-1.x to alluxio-2.x
	at alluxio.server.ft.journal.ufs.UfsJournalIntegrationTest.createFsMasterFromJournal(UfsJournalIntegrationTest.java:603)
	at alluxio.server.ft.journal.ufs.UfsJournalIntegrationTest.fileTestUtil(UfsJournalIntegrationTest.java:332)
	at alluxio.server.ft.journal.ufs.UfsJournalIntegrationTest.file(UfsJournalIntegrationTest.java:328)
Caused by: java.lang.IllegalStateException: EOF while parsing checkpoint type. Was your checkpoint written by alluxio-1.x? See https://docs.alluxio.io/os/user/edge/en/operation/2.x-Upgrade.html for instructions on how to upgrade from alluxio-1.x to alluxio-2.x
Caused by: java.io.EOFException

Running alluxio.server.health.ProxyHealthCheckClientIntegrationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.667 sec - in alluxio.server.health.MasterHealthCheckClientIntegrationTest
Running alluxio.server.health.WorkerHealthCheckClientIntegrationTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 172.253 sec - in alluxio.server.ft.journal.JournalBackupIntegrationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.441 sec - in alluxio.server.health.ProxyHealthCheckClientIntegrationTest
Running alluxio.server.tieredstore.LostStorageIntegrationTest
Running alluxio.server.tieredstore.SpecificTierWriteIntegrationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.124 sec - in alluxio.server.health.WorkerHealthCheckClientIntegrationTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 94.24 sec - in alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTest
Running alluxio.server.tieredstore.TierPromoteIntegrationTest
Running alluxio.server.tieredstore.TieredStoreIntegrationTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.181 sec - in alluxio.server.tieredstore.LostStorageIntegrationTest
Running alluxio.server.web.ServiceSocketBindIntegrationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.088 sec - in alluxio.server.tieredstore.TierPromoteIntegrationTest
Running alluxio.server.web.WebServerIntegrationTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.94 sec - in alluxio.server.tieredstore.SpecificTierWriteIntegrationTest
Running alluxio.testutils.underfs.sleeping.SleepingUnderFileSystemOptionsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.054 sec - in alluxio.testutils.underfs.sleeping.SleepingUnderFileSystemOptionsTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.026 sec - in alluxio.server.web.ServiceSocketBindIntegrationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.387 sec - in alluxio.server.tieredstore.TieredStoreIntegrationTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.742 sec - in alluxio.server.web.WebServerIntegrationTest

Results :

Tests in error: 
alluxio.server.ft.journal.MultiMasterJournalTest.testCheckpointReplay(alluxio.server.ft.journal.MultiMasterJournalTest)
  Run 1: MultiMasterJournalTest.before:53 » IO java.util.concurrent.TimeoutException: T...
  Run 2: MultiMasterJournalTest.before:53 » IO java.util.concurrent.TimeoutException: T...

Flaked tests: 
alluxio.client.fs.PersistPermissionIntegrationTest.syncPersistPermission(alluxio.client.fs.PersistPermissionIntegrationTest)
  Run 1: PersistPermissionIntegrationTest.before:43->AbstractFileOutStreamIntegrationTest.before:57 » Runtime
  Run 2: PASS

alluxio.server.ft.journal.ufs.UfsJournalIntegrationTest.file(alluxio.server.ft.journal.ufs.UfsJournalIntegrationTest)
  Run 1: UfsJournalIntegrationTest.file:328->fileTestUtil:332->createFsMasterFromJournal:603 » Runtime
  Run 2: PASS


Tests run: 1027, Failures: 0, Errors: 1, Skipped: 18, Flakes: 2
```

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by maobaolong** [comment]
@ggezer @gpang  Thank you for your review.

**Comment by maobaolong** [comment]
@gpang Is there anything else need me to do?

**Comment by gpang** [comment]
@maobaolong We are just started the release process for version 2.2, so I think we should wait until that is further along before we merge this change.

**Comment by gpang** [comment]
@maobaolong Hrmmm, I was trying to push to your branch in order to resolve conflicts, but I wasn't able to. Could you please resolve conflicts, and then I can merge? Thanks!

**Comment by maobaolong** [comment]
@gpang Sure, i've merge the master branch, thank you to remind me.

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Comment by maobaolong** [comment]
@gpang @ggezer @apc999  Thank you for your kindly review. 😁

**Pull request merged**
