### PR TITLE
Fix NPE for SerdeInfo

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Comment by yuzhu** [comment]
Failed tests: 
alluxio.job.migrate.MigrateIntegrationTest.migrateDirectory[0](alluxio.job.migrate.MigrateIntegrationTest)
  Run 1: MigrateIntegrationTest.migrateDirectory:92
  Run 2: MigrateIntegrationTest.migrateDirectory:92

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Comment by yuzhu** [comment]
@calvinjia NPE fix, PTAL

**Pull request merged**
