### PR TITLE
Add SKIPCI

### PR DESCRIPTION
**Pull request by bradyoo**
Adding SKIPCI or DOCFIX in the title of your pull request will skip all tests (except for checkstyle, findbugs, doc check)

### CODE REVIEW

**Comment by bradyoo** [comment]
This turned out to be a lot easier than I expected.

**Review by Xenorith — APPROVED** [review]
nice

**Comment by bradyoo** [comment]
bleh, I clicked the button instead of using the command :/

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
