### PR TITLE
[ALLUXIO-2335] Mark DefaultAsyncPersistHandler threadsafe

### PR DESCRIPTION
**Pull request by cmz2012**
[https://alluxio.atlassian.net/browse/ALLUXIO-2335](url)

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
@cmz2012 Thanks for the PR! It looks like your commit email address is not associated with your github account. Could you please [add the email to your github account](https://help.github.com/articles/adding-an-email-address-to-your-github-account/), or [modify your commit email address](http://stackoverflow.com/a/1320317/401884)?

**Comment by calvinjia** [comment]
@cmz2012 Any updates on this?

**Comment by yupeng9** [comment]
@cmz2012, thanks for your contribution. Feel free to reopen this PR after you update your github info.

**Pull request closed without merging**
