### PR TITLE
Fix reconnect logic of servicediscoveryrecipe

### PR DESCRIPTION
**Pull request by lucyge2022**
### What changes are proposed in this pull request?

when etcd lease keepalive client returned with onCompleted or onError, the lease might not directly get expired at the time, therefore we always new a lease to resume keepalive without explicitly checking isleaseexpired

### Why are the changes needed?

when etcd got induced network unstableness such as pkg loss, there's race condition in our reconnection logic from ServiceDiscoveryRecipe, where we directly check isLeaseExpired when we got terminal callback from keepalive client, but at the time the lease isn't expired yet. Hence we stop trying to create new lease to keepalive.

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Review by jiacheliu3 — APPROVED** [review]
LGTM thanks!

**Comment by jiacheliu3** [comment]
@lucyge2022 good to merge?

**Review by Kai-Zhang — APPROVED** [review]

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
I merged this PR as it is approved and doesn't seem to have pending work. Thanks! @lucyge2022

**Pull request merged**
