### PR TITLE
[ALLUXIO-2141] Remove extra line in UniqueFieldIndex containsObject()

### PR DESCRIPTION
**Pull request by branhao**
https://alluxio.atlassian.net/browse/ALLUXIO-2141

delete a line in UniqueFieldIndex containsObject

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by ifcharming** [comment]
@branhao thanks for the PR! Can you please sign the [contribution license agreement](http://cla.alluxio.org/). It only takes just minutes.

**Pull request merged**
