### PR TITLE
Improve error messages on master and worker

### LINKED ISSUE #12933: Excessive log errors on removing blocks already removed on worker
**Alluxio Version:**
2.4.1-2

**Describe the bug**

image

**Additional context**

Reported by Stephen Pu

### PR DESCRIPTION
**Pull request by apc999**
Fix #12933 #12934,

### CODE REVIEW

**Review by LuQQiu — APPROVED** [review]
Thanks for fixing the error messages! LGTM

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please

**Pull request merged**
