### PR TITLE
Enable client metrics by default

### PR DESCRIPTION
**Pull request by LuQQiu**

### CODE REVIEW

**Comment by ZacBlanco** [comment]
Can we target this for 2.3?

**Comment by LuQQiu** [comment]
@ZacBlanco This is a trial, I don't think we target this for 2.2

**Comment by LuQQiu** [comment]
alluxio.server.ft.journal.TableMasterJournalIntegrationTest (passed locally)
alluxio.client.cli.fsadmin.command.QuorumCommandIntegrationTest (timeout locally)
alluxio.server.ft.journal.JournalBackupIntegrationTest
alluxio.server.configuration.ConfigCheckerIntegrationTest
alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTest
alluxio.client.cli.fsadmin.pathconf.AddCommandIntegrationTest
alluxio.client.fs.FileSystemMasterRestartIntegrationTest
alluxio.client.hadoop.FileSystemUriIntegrationTes

**Comment by LuQQiu** [comment]
All tests using MultiProcessCluster failed looks like no master starts

**Pull request closed without merging**
