### PR TITLE
Refactor Metric key

### PR DESCRIPTION
**Pull request by LuQQiu**
This PR creates a single place (`MetricKey`) for storing all the alluxio metrics together with their name, description, metricType, and other information.

Metric name defined in the `MetricKey` is in format `<Cluster/Master/Worker/Client>.<MetricName>`.
For `Cluster` and `Master` metrics, the metric name recorded in the metrics system will be the same name as what they defined in `MetricKey`.
For `Worker` and `Client` metrics, instance hostname will be attached at the end like `Worker.<MetricName>.hostname` and `Client.<MetricName>.hostname|client_id`. The previous format is `Worker/Client.hostname.<MetricName>`. I change it for easy organization of all the metric keys.

### CODE REVIEW

**Comment by LuQQiu** [comment]
jenkins, test this please

**Comment by LuQQiu** [comment]
Tests in error: 
alluxio.client.cli.fs.command.CopyFromLocalCommandIntegrationTest.copyFromLocalLarge(alluxio.client.cli.fs.command.CopyFromLocalCommandIntegrationTest)
  Run 1: CopyFromLocalCommandIntegrationTest.copyFromLocalLarge:175 » Internal http2 ex...
  Run 2: CopyFromLocalCommandIntegrationTest.copyFromLocalLarge:175 » Internal http2 ex...

alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTest.restart(alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTest)
  Run 1: EmbeddedJournalIntegrationTest.restart:299 » Runtime alluxio.exception.status....
  Run 2: EmbeddedJournalIntegrationTest.restart:299 » Runtime alluxio.exception.status....

**Comment by LuQQiu** [comment]
jenkins, test this please

**Comment by LuQQiu** [comment]
alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTest.resizeCluster(alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTest)
  Run 1: EmbeddedJournalIntegrationTest.resizeCluster:110 » Timeout Timed out waiting f...
  Run 2: EmbeddedJournalIntegrationTest.resizeCluster:161 » Runtime alluxio.exception.s...

**Comment by LuQQiu** [comment]
jenkins, test this please

**Comment by LuQQiu** [comment]
`EmbeddedJournalIntegrationTest` keeps passed in local testing but keeps failed in PR buildings in this PR and other PRs.

**Comment by LuQQiu** [comment]
jenkins, test this please

**Comment by LuQQiu** [comment]
@calvinjia PTAL, thanks!

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Pull request merged**
