### PR TITLE
[SMALLFIX] Rename metric MasterHeartbeatTriggeredActiveJobSize

### PR DESCRIPTION
**Pull request by jiacheliu3**

### CODE REVIEW

**Review by LuQQiu — APPROVED** [review]

**Review by yuzhu — APPROVED** [review]

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Comment by jiacheliu3** [comment]
@Xenorith could you cherry pick this for me?

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
