### PR TITLE
[SMALLFIX]fix a word spell

### PR DESCRIPTION
**Pull request by tzattack**

### CODE REVIEW

**Comment by gpang** [comment]
@tzattack Thanks for your fix!

It looks like your commit is not associated with your github account. You can either add your email address to github (https://help.github.com/articles/adding-an-email-address-to-your-github-account/) or change the email address of your commits (http://stackoverflow.com/a/1320317/401884). Thanks!

**Comment by tzattack** [comment]
I have set the email address in my github account!Thanks

**Comment by gpang** [comment]
@tzattack Thanks for the fix!

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Pull request merged**
