### PR TITLE
[ALLUXIO-1750][ALLUXIO-1751] Use new Alluxio logo in web UI

### PR DESCRIPTION
**Pull request by uronce-cc**
https://alluxio.atlassian.net/browse/ALLUXIO-1751
https://alluxio.atlassian.net/browse/ALLUXIO-1750

### CODE REVIEW

**Comment by uronce-cc** [comment]
screen shot 2016-03-01 at 10 57 45 am

**Comment by aaudiber** [comment]
This might look better in white. I created a white version for the project docs: http://www.alluxio.org/documentation/v1.0.0/img/logo-white.png

**Comment by jsimsa** [comment]
alternatively, using the same shade of blue for the headings would also work for me

**Comment by uronce-cc** [comment]
I prefer to change the header background color to gray, and make the headings of the same shade of blue.

**Comment by uronce-cc** [comment]
let me try and upload a new look.

**Comment by uronce-cc** [comment]
screen shot 2016-03-01 at 1 47 19 pm

**Comment by jsimsa** [comment]
I like that a lot! LGTM

**Comment by apc999** [comment]
LGTM

shall we also backport this to branch 1.0?

**Comment by haoyuan** [comment]
agree with @apc999

**Comment by uronce-cc** [comment]
@apc999 @haoyuan I've backported it to branch-1.0, PTAL, Thanks!

**Pull request merged**
