### PR TITLE
[ALLUXIO-1757] OrangeFS under file system integration (implementation part).

### PR DESCRIPTION
**Pull request by pfxuan**
This is initial commit on Alluxio-OrangeFS integration using Direct Interface and JNI shim layer. We need to find a way to host orangefs-jni maven dependence. e.g. use www.orangefs.org subversion system to host its orangefs-jni maven files (http://www.orangefs.org/svn/orangefs/branches/maven-repository/).

### CODE REVIEW

**Comment by calvinjia** [comment]
@pfxuan Thanks for the integration, could you add a docs page describing how to setup Alluxio on OrangeFS?

**Comment by pfxuan** [comment]
@calvinjia, I will finish the documentation part in [ALLUXIO-1758](https://alluxio.atlassian.net/browse/ALLUXIO-1758).

**Comment by calvinjia** [comment]
@pfxuan sounds good, in the mean time do you mind merging the different parts into the `orangefs` working branch instead of `master`

**Comment by pfxuan** [comment]
@calvinjia, you means I should combine two different parts into this PR. Is this correct?

**Comment by calvinjia** [comment]
@pfxuan I created a branch called `orangefs` you can open the PRs to that branch one at a time and we can review them separately. When you are done with the feature, we can merge the `orangefs` branch back to `master`.

**Comment by pfxuan** [comment]
@calvinjia, got it. Thanks!

**Comment by calvinjia** [comment]
@pfxuan Could you close this PR and open another one directed to the `orangefs` branch?

**Comment by pfxuan** [comment]
Close this PR and move to `orangefs` branch.

**Pull request closed without merging**
