### PR TITLE
Update FUSE-based POSIX API docs

### PR DESCRIPTION
**Pull request by LuQQiu**

### CODE REVIEW

**Comment by LuQQiu** [comment]
Ready for review

**Comment by calvinjia** [comment]
@LuQQiu Could you change the language from `Alluxio-FUSE` (implementation) to `Alluxio POSIX API` (feature name)?

**Comment by apc999** [comment]
@calvinjia shall we change the filename to `POSIX-API.md` too?

**Comment by LuQQiu** [comment]
@apc999 @calvinjia changed the FUSE to POSIX API in both file name and contents. PTAL, thanks

**Pull request merged**
