### PR TITLE
Fix the cosn shaded pom

### PR DESCRIPTION
**Pull request by yuyang733**
Fix some errors in the pom.xml of the cosn shaded module, which causes
the cosn shaded jar not to be packaged correctly.

Before the repair, the dependent components that need to be included were not correctly specified in the pom file. Therefore, no code is correctly packaged into the cosn's shaded jar:
image

After repairing, it can be packaged correctly:

截屏2021-05-23 上午12 43 40

### CODE REVIEW

**Comment by maobaolong** [comment]
@yuyang733 Can you help to check if the shaded cosn module is necessary?

**Comment by yuyang733** [comment]
> @yuyang733 Can you help to check if the shaded cosn module is necessary?

In fact, I think it can also be removed. 
But if it is retained, it needs to be revised following this PR.

Do you recommend removing it ？

**Comment by maobaolong** [comment]
@yuyang733 Yeah, remove it is possible, please help to take a verify, thank you.

**Comment by yuyang733** [comment]
> @yuyang733 Yeah, remove it is possible, please help to take a verify, thank you.

Okay, I have verified that it can be removed, and the related dependencies are moved into the pom file of the underfs/cosn.

**Review by maobaolong — APPROVED** [review]
LGTM, thanks for this improvement

**Comment by maobaolong** [comment]
Hi @apc999 could you please help to approve running workflows? Thank you.

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
