### PR TITLE
Support statfs by Alluxio FUSE

### PR DESCRIPTION
**Pull request by liuhongtong**
Cherry-pick of existing commit.
orig-pr: Alluxio/alluxio#9418
orig-commit: Alluxio/alluxio@dcf782c8f057d07fe778980af6205e57da9803bd
orig-commit-author: liuhongtong <hongtongliu@126.com>

pr-link: Alluxio/alluxio#9563
change-id: cid-fdbc5bb9dbe116c0f3421d7b94ec36412d87be81

### CODE REVIEW

**Comment by gpang** [comment]
@liuhongtong Thanks for porting this! Did you cherry-pick the original commit: Alluxio/alluxio@dcf782c8f057d07fe778980af6205e57da9803bd

This PR doesn't look like a cherry-pick of the original change. Could you please cherry-pick (and possibly resolve conflicts) so we can track the same logical change in the various branches? Thanks!

**Comment by apc999** [comment]
@gpang it is the same change from original commit dcf782c, but due to the difference in client API across 1.8 and 2.0, directly cherry-pick can be very bad. Can we simply modify the PR description to include the change id to enable the tracking?

**Comment by gpang** [comment]
@apc999 ok. I updated the description

**Comment by apc999** [comment]
@liuhongtong  can you solve the conflict and I will merge this PR

**Comment by liuhongtong** [comment]
@apc999 I have resolved the conflict.  but jenkins does not do new build.

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
