### PR TITLE
Add information about collectInfo on user-cli and in bin/alluxio command

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
@ns1123

**Comment by bradyoo** [comment]
@gpang: Can you merge this for me?

**Comment by ZacBlanco** [comment]
I think @jiacheliu3 had a PR that was waiting to be merged that had some documentation for this command - though I'm not sure it touched the same file(s)

**Comment by jiacheliu3** [comment]
@ZacBlanco 
I have https://github.com/Alluxio/alluxio/pull/10926 that adds `collectInfo` to `Troubleshooting.md`. Bradley has added a good endpoint for me to link to :thumb

**Comment by bradyoo** [comment]
@ZacBlanco  Mind merging this for me?

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Comment by ZacBlanco** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please

**Pull request merged**
