### PR TITLE
[ALLUXIO-2260] Mark member variable mFormat as final in PropertyKeyFormat.java

### PR DESCRIPTION
**Pull request by zcw01**
https://alluxio.atlassian.net/browse/ALLUXIO-2260
Mark member variable mFormat as final in PropertyKeyFormat.java
ALLUXIO-2260

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
@zcw01 Thanks! Could you sign the CLA agreement?

**Comment by saltylin** [comment]
LGTM

**Pull request merged**
