### PR TITLE
[ALLUXIO-2192] Switch tenant and user order for swiftauth.

### PR DESCRIPTION
**Pull request by calvinjia**
https://alluxio.atlassian.net/browse/ALLUXIO-2192

### CODE REVIEW

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by ifcharming** [comment]
LGTM, thanks for the fix!

**Comment by apc999** [comment]
LGTM

**Pull request merged**
