### PR TITLE
Revert "[ALLUXIO-2160] Write unit tests for AlluxioMasterRestServiceHandler"

### PR DESCRIPTION
**Pull request by aaudiber**
Reverts Alluxio/alluxio#4119

After merging this we had tons of master build failures with 
```
getCapacityBytes(alluxio.master.AlluxioMasterRestServiceHandlerTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: Entry must be a Long! expected:<class java.lang.Long> but was:<class java.lang.String>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at alluxio.master.AlluxioMasterRestServiceHandlerTest.getCapacityBytes(AlluxioMasterRestServiceHandlerTest.java:205)

getUsedBytes(alluxio.master.AlluxioMasterRestServiceHandlerTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: Entry must be a Long! expected:<class java.lang.Long> but was:<class java.lang.String>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at alluxio.master.AlluxioMasterRestServiceHandlerTest.getUsedBytes(AlluxioMasterRestServiceHandlerTest.java:217)

getFreeBytes(alluxio.master.AlluxioMasterRestServiceHandlerTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: Entry must be a Long! expected:<class java.lang.Long> but was:<class java.lang.String>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at alluxio.master.AlluxioMasterRestServiceHandlerTest.getFreeBytes(AlluxioMasterRestServiceHandlerTest.java:230)

getUfsCapacityBytes(alluxio.master.AlluxioMasterRestServiceHandlerTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: Entry must be a Long! expected:<class java.lang.Long> but was:<class java.lang.String>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at alluxio.master.AlluxioMasterRestServiceHandlerTest.getUfsCapacityBytes(AlluxioMasterRestServiceHandlerTest.java:240)

getUfsUsedBytes(alluxio.master.AlluxioMasterRestServiceHandlerTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: Entry must be a Long! expected:<class java.lang.Long> but was:<class java.lang.String>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at alluxio.master.AlluxioMasterRestServiceHandlerTest.getUfsUsedBytes(AlluxioMasterRestServiceHandlerTest.java:250)
```

### CODE REVIEW

**Comment by aaudiber** [comment]
@schernolyas Could you look into why these tests fail sometimes?

**Comment by schernolyas** [comment]
Hi @aaudiber !
Of course! But ....get me link to log. I will see at Monday.

**Comment by schernolyas** [comment]
Hi @aaudiber !
The reason of the error is:
getRpcAddress(alluxio.master.AlluxioMasterRestServiceHandlerTest)  Time elapsed: 0.016 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<["localhost/127.0.0.1:8080"]> but was:<[Failed to login: java.lang.UnsatisfiedLinkError: Native Library /usr/java/jdk1.8.0_102/jre/lib/amd64/libjaas_unix.so already loaded in another classloader
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1907)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.sun.security.auth.module.UnixSystem.<init>(UnixSystem.java:48)
	at com.sun.security.auth.module.UnixLoginModule.login(UnixLoginModule.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at alluxio.security.LoginUser.login(LoginUser.java:87)
	at alluxio.security.LoginUser.get(LoginUser.java:57)
	at alluxio.RestUtils.call(RestUtils.java:43)
	at alluxio.master.AlluxioMasterRestServiceHandler.getRpcAddress(AlluxioMasterRestServiceHandler.java:124)

**Comment by schernolyas** [comment]
I got the exception then I run all tests of server core module.

**Comment by schernolyas** [comment]
check alluxio.security.LoginUser.
The singleton must be redevelop by ClassHolder scheme. 
I will analyse the problem.

**Comment by schernolyas** [comment]
https://alluxio.atlassian.net/browse/ALLUXIO-2399

**Pull request merged**
