### PR TITLE
[ALLUXIO-1785] Improve exception handling in AbstractFileSystem

### PR DESCRIPTION
**Pull request by YunLi1988**
https://alluxio.atlassian.net/browse/ALLUXIO-1785

### CODE REVIEW

**Comment by aaudiber** [comment]
Thanks for the PR @YunLi1988! Do you mind adding a link to the JIRA ticket in the description field for the pull request? See http://alluxio.org/documentation/master/en/Contributing-to-Alluxio.html#submitting-code

**Comment by aaudiber** [comment]
ok to test

**Comment by YunLi1988** [comment]
Have already tested it before its commit.

**Comment by aaudiber** [comment]
@YunLi1988 sorry, I was saying "ok to test" to trigger AmplabJenkins to run the build. Can you add a link to the JIRA ticket?

**Comment by YunLi1988** [comment]
got it. what do you mean by line to jira ticket?

https://alluxio.atlassian.net/browse/ALLUXIO-1785?filter=-1 is the link to
that issue.

Best,
Yun

**Comment by aaudiber** [comment]
Yea, like the JIRA links at the top of https://github.com/Alluxio/alluxio/pull/2883 or https://github.com/Alluxio/alluxio/pull/2885. There is a bot which looks for these links and automatically updates the JIRA ticket based on the status of the pull request.

**Comment by aaudiber** [comment]
+1 LGTM

**Comment by YunLi1988** [comment]
like the one added here https://github.com/Alluxio/alluxio/pull/2888?

Best,
Yun

**Comment by YunLi1988** [comment]
cool. Thanks!

**Pull request merged**
