### PR TITLE
Add bintray repo for jnr-fuse

### PR DESCRIPTION
**Pull request by gpang**

### CODE REVIEW

**Comment by apc999** [comment]
@gpang  what's the implication of this issue?

**Comment by gpang** [comment]
@apc999 the jnr-fuse dependency requires this repo, so any new/fresh machine will not be able to download the dependency without this PR.

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.3 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-1.8 please

**Pull request merged**
