### PR TITLE
[ALLUXIO-2839] Client Add userMustCacheList

### PR DESCRIPTION
**Pull request by Jason0812**
Address: https://alluxio.atlassian.net/browse/ALLUXIO-2839

### CODE REVIEW

**Comment by Jason0812** [comment]
alluxio-bot, check this please

**Comment by Jason0812** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
@Jason0812 Thanks for the contribution. Sorry for the long latency as the entire team is occupied by the new 1.5 release. I left some comments in the original JIRA ticket https://alluxio.atlassian.net/browse/ALLUXIO-2839 . Basically, we would like to learn more why this feature could help better (or equivalently, why setting the writetype per file is not a good idea in your case). We could move communication to the JIRA. Once we are the same page, we could come back on github. 

Thanks

**Comment by yupeng9** [comment]
@Jason0812 Are you still working on this PR?

**Comment by yupeng9** [comment]
Close it for now and please continue the discussion on the JIRA ticket.

**Pull request closed without merging**
