### PR TITLE
Add some instruction to find hdfs default port, the default port is n…

### PR DESCRIPTION
**Pull request by yuzhu**
…ot always 8020.

### CODE REVIEW

**Comment by yuzhu** [comment]
@apc999 PTAL. just small changes

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please.

**Pull request merged**
