### PR TITLE
Refactor docGen for extension

### PR DESCRIPTION
**Pull request by yyongycy**
### What changes are proposed in this pull request?
Extract the logic from main to other function.

### Why are the changes needed?

Refactor docGen for extension

### Does this PR introduce any user facing changes?
NA

### CODE REVIEW

**Comment by yyongycy** [comment]
@Xenorith Please take a look

**Review by Xenorith — APPROVED** [review]

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Comment by yyongycy** [comment]
Port to branch-3.0-preview

**Comment by yyongycy** [comment]
alluxio-bot, cherry-pick this to branch-3.0-preview please

**Pull request merged**
