### PR TITLE
Update ci version

### PR DESCRIPTION
**Pull request by fengshunli**
### What changes are proposed in this pull request?

Please outline the changes and how this PR fixes the issue.

https://github.com/Alluxio/alluxio/issues/16963

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

### CODE REVIEW

**Comment by Xenorith** [comment]
may i ask what is the motivation or benefit from the newer versions? or perhaps the older versions are becoming deprecated? @fengshunli 
there is a saying about "if it's not broken, don't fix it"

also please take notice of the request to sign the CLA. we cannot merge any contributions until the signed agreement is accepted, thanks.

**Comment by fengshunli** [comment]
The v2 version is just a demo version, the 3 version solves some risks, is safer and has more complete functions

**Comment by Xenorith** [comment]
this seems like the relevant news article regarding v2 -> v3: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by fengshunli** [comment]
You can see that version 3 has solved a lot of dependency compatibility and loopholes see https://github.com/actions/checkout/releases

**Comment by fengshunli** [comment]
CLA has been signed @Xenorith

**Review by Xenorith — APPROVED** [review]

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Pull request merged**
