### PR TITLE
Assign ErrorMessage before setting Status in Plans

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
@gpang Can you take a look at this? This should also be cherry-picked as well.

**Review by gpang — APPROVED** [review]
LGTM

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
