### PR TITLE
Fix the way we pass parameters to lerna so it is happy

### PR DESCRIPTION
**Pull request by yuzhu**
basically, maven puts a quote around each parameter, and forces npm to take the entire parameter as a single parameter.

### CODE REVIEW

**Comment by yuzhu** [comment]
@Xenorith with this change, do we want to pin to a specific version?  Looking at other open source project, particularly, lerna itself. it seems like they use `^x.y.z` most commonly.

**Comment by Xenorith** [comment]
hm in other places where we use lerna, we are using `~` to pin down the minor version, so i would prefer to maintain consistency, even though the usage/invocation pathway may be different

**Comment by yuzhu** [comment]
@Xenorith fixed version.

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Pull request merged**
