### PR TITLE
Add back Cephfs UFS

### PR DESCRIPTION
**Pull request by jhonxue**
Add the CephFS UFS

### CODE REVIEW

**Comment by jhonxue** [comment]
@maobaolong For, baolong left ufs cephfs modify work to me, so i modified and tested. Alluxio runUfsTest all passed!
@LuQQiu @apc999 i modify the code according your suggest. please review a again,thanks! alluxio runUfsTest all passed

**Comment by LuQQiu** [comment]
all tests passed
[alluxio@TENCENT64 ~/alluxio-2.6.0-tq-1.1.0]$ bin/alluxio runUfsTests --path cephfs://
Running test: createAtomicTest...
Passed the test!
Running test: createEmptyTest...
Passed the test!
Running test: createNoParentTest...
Passed the test!
Running test: createParentTest...
Passed the test!
Running test: createOpenTest...
Passed the test!
Running test: createOpenEmptyTest...
Passed the test!
Running test: createOpenAtPositionTest...
Passed the test!
Running test: createOpenLargeTest...
Passed the test!
Running test: createOpenExistingLargeFileTest...
Passed the test!
Running test: deleteFileTest...
Passed the test!
Running test: deleteDirTest...
Passed the test!
Running test: deleteLargeDirectoryTest...
Passed the test!
Running test: createDeleteFileConjuctionTest...
Passed the test!
Running test: createThenDeleteExistingDirectoryTest...
Passed the test!
Running test: existsTest...
Passed the test!
Running test: getDirectoryStatusTest...
Passed the test!
Running test: createThenGetExistingDirectoryStatusTest...
Passed the test!
Running test: getFileSizeTest...
Passed the test!
Running test: createThenGetExistingFileStatusTest...
Passed the test!
Running test: getFileStatusTest...
Passed the test!
Running test: createThenGetExistingStatusTest...
Passed the test!
Running test: getModTimeTest...
Passed the test!
Running test: getNonExistingDirectoryStatusTest...
Passed the test!
Running test: getNonExistingFileStatusTest...
Passed the test!
Running test: getNonExistingPathStatusTest...
Passed the test!
Running test: isFileTest...
Passed the test!
Running test: listStatusTest...
Passed the test!
Running test: listStatusEmptyTest...
Passed the test!
Running test: listStatusFileTest...
Passed the test!
Running test: listLargeDirectoryTest...
Passed the test!
Running test: listStatusRecursiveTest...
Passed the test!
Running test: mkdirsTest...
Passed the test!
Running test: objectCommonPrefixesIsDirectoryTest...
Passed the test!
Running test: objectCommonPrefixesListStatusNonRecursiveTest...
Passed the test!
Running test: objectCommonPrefixesListStatusRecursiveTest...
Passed the test!
Running test: objectNestedDirsListStatusRecursiveTest...
Passed the test!
Running test: renameFileTest...
Passed the test!
Running test: renameRenamableFileTest...
Passed the test!
Running test: renameDirectoryTest...
Passed the test!
Running test: renameDirectoryDeepTest...
Passed the test!
Running test: renameRenamableDirectoryTest...
Passed the test!
Running test: renameLargeDirectoryTest...
Passed the test!
Tests completed with 0 failed.

**Comment by LuQQiu** [comment]
@jhonxue Thanks for working on it! I modify the title and the PR descriptions since the title and description will be shown in the log commit message and should be clear for what this commit for.

**Comment by LuQQiu** [comment]
@jhonxue Please help fix the checkstyle issue

**Comment by jhonxue** [comment]
> @jhonxue Thanks for working on it! I modify the title and the PR descriptions since the title and description will be shown in the log commit message and should be clear for what this commit for.

ok,thanks

**Comment by jhonxue** [comment]
> @jhonxue Please help fix the checkstyle issue

ok.i will do it

**Comment by jhonxue** [comment]
@LuQQiu @apc999  I fixed the checkstyle issue. Now, all checks have passed! Please take a look. Thanks!

**Review by LuQQiu — APPROVED** [review]

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
