### PR TITLE
[ALLUXIO-1776] Add unit tests for IdUtils

### PR DESCRIPTION
**Pull request by breakdawn**
Add two unit tests for IdUtils.
mvn test passed.

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
hi @breakdawn  

Thanks for submitting this PR. We found your commits on GitHub aren't linked to a valid Github account yet (see your commits at https://github.com/amplab/tachyon/pull/2856/commits) where your icon is gray. 
For us to properly credit your contributions, could you please set up your Github account by following the Github instructions [here](https://help.github.com/articles/setting-your-email-in-git/)?

Thank you again for your contribution to Alluxio!

- Bin

**Comment by breakdawn** [comment]
Thanks for your guide, set up account now.

**Comment by apc999** [comment]
@breakdawn after you setup the account (basically just do `git config` for your email`, could you reopen the PR? You can close this one first, and simply re-submit your pull-request like a new one?

**Comment by breakdawn** [comment]
Sure, I'll reopen it.

**Pull request closed without merging**
