### PR TITLE
[SMALLFIX]remove the description

### PR DESCRIPTION
**Pull request by wyf19940202**
https://alluxio.atlassian.net/browse/ALLUXIO-2302

MG1633087

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by apc999** [comment]
LGTM
thanks for the patch

**Comment by entslscheia** [comment]
alluxio-bot, check this again please

**Comment by entslscheia** [comment]
alluxio-bot, check this please

**Pull request merged**
