### PR TITLE
[ALLUXIO-2495] Delete Test suffix in test name

### PR DESCRIPTION
**Pull request by jswudi**
https://alluxio.atlassian.net/browse/ALLUXIO-2495

### CODE REVIEW

**Comment by jswudi** [comment]
PTAL

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
add to whitelist

**Comment by jswudi** [comment]
Why test failed, it says "stderr: error: refs/remotes/origin/pr/1028/merge does not point to a valid object!"

**Pull request merged**
