### PR TITLE
[DOCFIX] Updated documentation footer with Open Source copyright information

### PR DESCRIPTION
**Pull request by waltonryan**
@aaudiber @jsimsa Updating the copyright information. I tested on chrome browser and displays correctly.

### CODE REVIEW

**Comment by waltonryan** [comment]
screen shot 2016-05-23 at 12 42 42 pm

**Comment by jsimsa** [comment]
LGTM

**Comment by waltonryan** [comment]
Updated favicon to alluxio favicon.

**Comment by apc999** [comment]
do we want this to be in branch 1.1?

**Comment by waltonryan** [comment]
Would it be substantial effort to include it in 1.1?

**Comment by apc999** [comment]
I would cherry-pick this to be in 1.1. 

Thanks!

**Pull request merged**
