### PR TITLE
Fix DynamicResourcePool IllegalArgumentException

### PR DESCRIPTION
**Pull request by secfree**
### What changes are proposed in this pull request?

1. BlockWorkerClientPool supports closing multi times
2. DynamicResourcePool support releasing multiple times for the same resource

### Why are the changes needed?

Fix https://github.com/Alluxio/alluxio/issues/15556

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Comment by secfree** [comment]
alluxio-bot, check this please

**Comment by dbw9580** [comment]
Can you try #15579 and see if it solves the error you were seeing?

**Comment by secfree** [comment]
> Hi @secfree, thanks for the PR, but a resource is not supposed to be released more than once. When this `IllegalArgumentException` is thrown, it suggests there is a bug somewhere else.
> 
> In your case, can you provide more details on why you are seeing the error in #15556 ? What were you trying to do with Alluxio before that error occured?

Thanks for your reply.

The location is here: https://github.com/Alluxio/alluxio/blob/master/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java#L574

```
    if (poolMap.containsKey(key)) {
      poolMap.get(key).release(client);
```

After the resource is GC, this `poolMap` still contains the key because GC does not remove the key from `poolMap`.

> but a resource is not supposed to be released more than once

As `BlockWorkerClient` is Closeable, and a Closeable instance supports closing multiple times - "If the stream is already closed then invoking this method has no effect." Each `close` will trigger `release` one time. The code is located at
https://github.com/Alluxio/alluxio/blob/master/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java#L534

If we want to avoid calling `release` multiple times, we may need to add a new field `isClosed` into `BlockWorkerClient`.  What do you think? @dbw9580

**Comment by secfree** [comment]
> Can you try #15579 and see if it solves the error you were seeing?

I will try this and update you.

**Comment by dbw9580** [comment]
@secfree 

If the proposed fix in #15579 does not work, then it is indeed the case that the closable resource was closed twice, not that the wrong key was computed when closing the resource.

Perhaps you can help us understand why the `ClosableResource` wrapping `BlockWorkerClient` was closed twice? To silence an error like this is easy, but to understand why there was an error in the first place is more important.

**Comment by secfree** [comment]
> Perhaps you can help us understand why the `ClosableResource` wrapping `BlockWorkerClient` was closed twice?

Only one business team was testing and they failed to reproduce the issue when we request them for full log.

For `ClosableResource`, as it support closing multiple times from the definition, so we should fix this part, right?

```
public interface Closeable extends AutoCloseable {

    /**
     * Closes this stream and releases any system resources associated
     * with it. If the stream is already closed then invoking this
     * method has no effect.
     * ...
     */
    public void close() throws IOException;
}

```

**Comment by HelloHorizon** [comment]
@dbw9580 any updates here?

**Comment by dbw9580** [comment]
> @dbw9580 any updates here?

As I mentioned in https://github.com/Alluxio/alluxio/pull/15562#issuecomment-1131321183, I think we need to understand first what is causing the error @secfree was seeing in #15556. I proposed a fix in https://github.com/Alluxio/alluxio/pull/15579 and @secfree may be able to provide more feedback.

> For ClosableResource, as it support closing multiple times from the definition, so we should fix this part, right?

This statement is correct, however, I think `ClosableResource` is supposed to implement `AutoCloseable` instead of `Closeable`. Many instances of this class are used to wrap a resource acquired from a resource pool, and the resource pool does not support releasing a resource more than once. We should change `ClosableResource` to implement `AutoClosable` instead.

**Comment by secfree** [comment]
As #15579 works but this not, so I will close this.

**Pull request closed without merging**
