### PR TITLE
[ALLUXIO-2254] Improve style in FileWorkerMasterSyncExecutorTest

### PR DESCRIPTION
**Pull request by wudapeng268**
https://alluxio.atlassian.net/browse/ALLUXIO-2254

### CODE REVIEW

**Comment by wudapeng268** [comment]
Yes,please test it

**Comment by wudapeng268** [comment]
Yes,please test it
@AmplabJenkins

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
LGTM, will merge after tests pass.

**Comment by gpang** [comment]
Jenkins, test this please

**Pull request merged**
