### PR TITLE
Remove disabling of web ui buttons

### PR DESCRIPTION
**Pull request by tieujason330**
- change for #9481 
- remove button disable logic for `FileView` and `Browse`
- kept disable logic in `Paginator` but changed color of selected item for extra clarity
Screen Shot 2019-07-17 at 16 35 05

### CODE REVIEW

**Comment by tieujason330** [comment]
@calvinjia PTAL, thanks

**Comment by calvinjia** [comment]
@tieujason330 Thanks for the fix! Do we still need the bookkeeping for `lastFetched` or any other state we used to facilitate this?

**Comment by tieujason330** [comment]
@calvinjia Good catch for `lastFetched`, I removed it from the edited components

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Pull request merged**
