### PR TITLE
[ALLUXIO-2797] Use precondition check chaining in FileInfo

### PR DESCRIPTION
**Pull request by sdevil507**
The preconditions check in setName(String name) can be chained to save a statement.

### CODE REVIEW

**Comment by sdevil507** [comment]
@alluxio-bot alluxio-bot, check this please

**Comment by sdevil507** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
Hey @sdevil507, do you mind signing the CLA? You can sign it here: http://cla.alluxio.org/

**Comment by yupeng9** [comment]
@sdevil507 can you sign the CLA?

**Comment by yupeng9** [comment]
@sdevil507 feel free to reopen this PR after you sign the CLA.

**Pull request closed without merging**
