### PR TITLE
[ALLUXIO-2670] add serial version uid to UfsBolckAccessTokenUnavailableException

### PR DESCRIPTION
**Pull request by HAO970422**
https://alluxio.atlassian.net/browse/ALLUXIO-2670
add serial version uid to UfsBolckAccessTokenUnavailableException

### CODE REVIEW

**Comment by peisun1115** [comment]
LGTM

**Comment by peisun1115** [comment]
Thanks for the improvement, can you sign the CLA? thank you

**Comment by aaudiber** [comment]
Hey @HAO970422, do you mind signing the CLA? You can sign it here: http://cla.alluxio.org/

**Comment by yupeng9** [comment]
@HAO970422 can you sign the CLA?

**Comment by yupeng9** [comment]
@HAO970422 feel free to reopen this PR after you sign the CLA.

**Pull request closed without merging**
