### PR TITLE
Add virtual block to load big file

### PR DESCRIPTION
**Pull request by jja725**
### What changes are proposed in this pull request?
Add virtual block to load big file

### Why are the changes needed?
na

### Does this PR introduce any user facing changes?
na

### CODE REVIEW

**Review by lucyge2022 — APPROVED** [review]
approved to the same PR for re-merging purpose

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Comment by jja725** [comment]
still having issue after rerun module  (alluxio.client.**,alluxio.master.**)

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Pull request closed without merging**
