### PR TITLE
Documentations layout & design changes

### PR DESCRIPTION
**Pull request by aunglinn**

### CODE REVIEW

**Comment by calvinjia** [comment]
Jenkins, ok to test

**Comment by uronce-cc** [comment]
Lack headings between "Overview" and "English":

screen shot 2016-03-23 at 10 22 02 am

**Comment by uronce-cc** [comment]
Some dropdown menus are not fully shown:

screen shot 2016-03-23 at 10 25 46 am

**Comment by saltylin** [comment]
@uronce-cc Did you generate the pages by using jekyll 3.1? I encountered the same problem when using this version.
toolbar
But the version 3.0.2 or the lower are ok. Maybe jekyll 3.1 has changed something core, or just a bug.

**Comment by uronce-cc** [comment]
@saltylin 
```
$ jekyll -version                                             
jekyll 3.1.2
```

**Comment by aaudiber** [comment]
Closing this for now, will reopen when I have cycles to find the root cause of the dropdown titles not displaying.

**Pull request closed without merging**
