### PR TITLE
Remove TransparentURI

### PR DESCRIPTION
**Pull request by ggezer**

### CODE REVIEW

**Comment by ggezer** [comment]
alluxio-bot, merge this please

**Comment by fennuzhichui** [comment]
is there any replacement for URI transform

**Comment by fennuzhichui** [comment]
@alluxio-bot

**Comment by Heltman** [comment]
Why remove it?

**Comment by flaming-archer** [comment]
Spark/hive preliminary testing shows that it cannot be used directly as they are based on the distributefilesystem. Trino and HDFS CLI can be used.

**Pull request merged**
