### PR TITLE
[DOCFIX] Update name Ants Programmatic AD

### PR DESCRIPTION
**Pull request by bqbtoan**
Update [Ants Programmatic AD](http://ants.vn/) > [ANTS Programmatic AD](http://ants.vn/)

### CODE REVIEW

**Comment by calvinjia** [comment]
Jenkins, ok to test.

**Comment by calvinjia** [comment]
@bqbtoan Thanks for the contribution! The change looks good to me. Could you sign the CLA before I merge this?

**Comment by calvinjia** [comment]
@bqbtoan Any update on this, did you have any issues with the CLA?

**Comment by aaudiber** [comment]
@bqbtoan I've resent the CLA document, please let me know if there are issues with filling it out

**Comment by yupeng9** [comment]
Hey @bqbtoan can you sign the CLA again, and then we can merge this PR.

**Comment by yupeng9** [comment]
@bqbtoan feel free to reopen this PR after you sign the CLA.

**Pull request closed without merging**
