### PR TITLE
Remove table module (2nd attempt)

### PR DESCRIPTION
**Pull request by apc999**
### What changes are proposed in this pull request?

This commit represents a second effort at removing the table module along with its associated definitions and properties. Our initial attempt, PR #17220, was reverted due to a conflict with Presto and Trino codebases, as some removed classes were still being referenced.

Unlike the previous attempt, this commit ensures that all externally referenced classes (e.g., TableMasterClient.java) remain within the codebase to prevent blocking older Presto/Trino builds with newer Alluxio clients post table module removal.

### Why are the changes needed?

Structured data service gets depreciated in 2.9 and should be removed in 300 or later.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including

1. catalog service removed
2. transformation removed
3. table command removed (CLI already removed in 2.9)

### CODE REVIEW

**Comment by apc999** [comment]
@JiamingMai @beinan, the first commit simply removes the table module by reverting the revert PR made by @JiamingMai. The second commit is the critical one that enables building with older versions of Trino/Presto. It does so by maintaining a select few necessary files.

**Review by beinan — APPROVED** [review]
lgtm, many thanks for cleaning up our code!

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by a516072575** [comment]
@apc999  Why delete this module

**Pull request merged**
