### PR TITLE
[DOCFIX] Add note in doc about automatic backup upon journal corruption

### PR DESCRIPTION
**Pull request by jenoudet**
Add note in doc about automatic backup upon journal corruption.

### CODE REVIEW

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks!

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
@Xenorith 2.9 pls thank you sir :P

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.9 please

**Pull request merged**
