### PR TITLE
[DOCFIX] Update scalability doc

### PR DESCRIPTION
**Pull request by jiacheliu3**
### What changes are proposed in this pull request?
Added a few improvements to the scalability doc

### CODE REVIEW

**Review by Xenorith — APPROVED** [review]
no major comments from me from a readability/spelling/grammar perspective

**Review by yuzhu — APPROVED** [review]

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
@Xenorith could you help cherry picking this? Thx

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Pull request merged**
