### PR TITLE
Add timestamps to maven log in jenkins build

### PR DESCRIPTION
**Pull request by ZacBlanco**

### CODE REVIEW

**Comment by ZacBlanco** [comment]
jenkins, test this please

**Comment by gpang** [comment]
@ZacBlanco is there a sample log output?

**Comment by ZacBlanco** [comment]
The maven log in jenkins before this change has an output like:

```
[INFO] Checking licenses...
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ alluxio-assembly-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /usr/src/alluxio/assembly/server/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ alluxio-assembly-server ---
[INFO] No sources to compile
[INFO] 
[INFO] >>> spotbugs-maven-plugin:3.1.12.2:check (default) > :spotbugs @ alluxio-assembly-server >>>
[INFO] 
[INFO] --- spotbugs-maven-plugin:3.1.12.2:spotbugs (spotbugs) @ alluxio-assembly-server ---
[INFO] 
[INFO] <<< spotbugs-maven-plugin:3.1.12.2:check (default) < :spotbugs @ alluxio-assembly-server <<<
[INFO] 
[INFO] 
[INFO] --- spotbugs-maven-plugin:3.1.12.2:check (default) @ alluxio-assembly-server ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ alluxio-assembly-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /usr/src/alluxio/assembly/server/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ alluxio-assembly-server ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ alluxio-assembly-server ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ alluxio-assembly-server ---
```

And now with this change it looks like

```
23:21:29.364 [INFO] --- license-maven-plugin:2.9:check (default) @ alluxio-minicluster ---
23:21:29.370 [INFO] Checking licenses...
23:21:29.388 [INFO] 
23:21:29.388 [INFO] <<< maven-source-plugin:2.3:jar (attach-sources) < generate-sources @ alluxio-minicluster <<<
23:21:29.389 [INFO] 
23:21:29.389 [INFO] 
23:21:29.389 [INFO] --- maven-source-plugin:2.3:jar (attach-sources) @ alluxio-minicluster ---
23:21:29.398 [INFO] Building jar: /usr/src/alluxio/minicluster/target/alluxio-minicluster-2.2.0-SNAPSHOT-sources.jar
23:21:29.405 [INFO] 
23:21:29.405 [INFO] --- maven-javadoc-plugin:2.9:jar (attach-javadoc) @ alluxio-minicluster ---
23:21:29.407 [INFO] Skipping javadoc generation
23:21:29.407 [INFO] 
23:21:29.407 [INFO] --- maven-install-plugin:2.4:install (default-install) @ alluxio-minicluster ---
23:21:29.408 [INFO] Installing /usr/src/alluxio/minicluster/target/alluxio-minicluster-2.2.0-SNAPSHOT.jar to /home/jenkins/.m2/repository/org/alluxio/alluxio-minicluster/2.2.0-SNAPSHOT/alluxio-minicluster-2.2.0-SNAPSHOT.jar
23:21:29.409 [INFO] Installing /usr/src/alluxio/minicluster/pom.xml to /home/jenkins/.m2/repository/org/alluxio/alluxio-minicluster/2.2.0-SNAPSHOT/alluxio-minicluster-2.2.0-SNAPSHOT.pom
23:21:29.411 [INFO] Installing /usr/src/alluxio/minicluster/target/alluxio-minicluster-2.2.0-SNAPSHOT-sources.jar to /home/jenkins/.m2/repository/org/alluxio/alluxio-minicluster/2.2.0-SNAPSHOT/alluxio-minicluster-2.2.0-SNAPSHOT-sources.jar
23:21:29.413 [INFO] 
23:21:29.414 [INFO] ---------------------< org.alluxio:alluxio-tests >----------------------
23:21:29.414 [INFO] Building Alluxio Tests 2.2.0-SNAPSHOT                            [54/54]
23:21:29.414 [INFO] --------------------------------[ jar ]---------------------------------
23:21:29.573 [INFO] 
23:21:29.573 [INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ alluxio-tests ---
23:21:29.575 [INFO] 
```

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Pull request merged**
