### PR TITLE
Remove BlockWorker.hasBlockMeta

### PR DESCRIPTION
**Pull request by rongrong**

### CODE REVIEW

**Review by beinan — APPROVED** [review]
lgtm

**Review by jja725 — APPROVED** [review]

**Review by beinan — CHANGES_REQUESTED** [review]
build failed by ```/usr/src/alluxio/core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java:[94,3] method does not override or implement a method from a supertype```

**Comment by rongrong** [comment]
@beinan build fixed, please take a look again. Thanks!

**Review by jja725 — APPROVED** [review]

**Review by beinan — APPROVED** [review]

**Comment by beinan** [comment]
alluxio-bot, merge this please.

**Pull request merged**
