### PR TITLE
[WIP][DOCFIX] Update K8s docs

### PR DESCRIPTION
**Pull request by madanadit**

### CODE REVIEW

**Comment by madanadit** [comment]
```
Tests in error: 
alluxio.client.fs.FreeAndDeleteIntegrationTest.deleteDir(alluxio.client.fs.FreeAndDeleteIntegrationTest)
  Run 1: FreeAndDeleteIntegrationTest.deleteDir:145 » TestTimedOut test timed out after...
  Run 2: FreeAndDeleteIntegrationTest.deleteDir:145 » TestTimedOut test timed out after...

alluxio.server.ft.ZookeeperFailureIntegrationTest.zkConnectionPolicy_Session(alluxio.server.ft.ZookeeperFailureIntegrationTest)
  Run 1: ZookeeperFailureIntegrationTest.zkConnectionPolicy_Session:139 » Timeout Timed...
  Run 2: ZookeeperFailureIntegrationTest.zkConnectionPolicy_Session:139 » Timeout Timed...

alluxio.server.ft.ZookeeperFailureIntegrationTest.zkConnectionPolicy_Standard(alluxio.server.ft.ZookeeperFailureIntegrationTest)
  Run 1: ZookeeperFailureIntegrationTest.zkConnectionPolicy_Standard:119 » Timeout Time...
  Run 2: ZookeeperFailureIntegrationTest.zkConnectionPolicy_Standard:119 » Timeout Time...

alluxio.server.ft.journal.ufs.UfsJournalIntegrationTest.file(alluxio.server.ft.journal.ufs.UfsJournalIntegrationTest)
  Run 1: UfsJournalIntegrationTest.file:328->fileTestUtil:332->createFsMasterFromJournal:603 » Runtime
  Run 2: UfsJournalIntegrationTest.file:328->fileTestUtil:332->createFsMasterFromJournal:603 » Runtime
```

**Comment by madanadit** [comment]
alluxio-bot, test this please.

**Comment by jiacheliu3** [comment]
Is this WIP?

**Comment by madanadit** [comment]
@jiacheliu3 yes

**Pull request closed without merging**
