### PR TITLE
[DOCFIX] Update transformation docs

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
@gpang

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Comment by gpang** [comment]
alluxio-bot, merge this to branch-2.3 please

**Comment by gpang** [comment]
alluxio-bot, cherry-pick this to branch-2.3 please

**Comment by gpang** [comment]
alluxio-bot, cherry-pick this to branch-2.3 please

**Pull request merged**
