### PR TITLE
Update jnr-fuse version

### PR DESCRIPTION
**Pull request by symious**
Update the version of jnr-fuse to solve the following error:
```
Could not find artifact com.github.serceman:jnr-fuse:jar:0.5.3
```

### CODE REVIEW

**Review by apc999 — APPROVED** [review]
Looks like 0.5.5 is the only available version at central now

https://mvnrepository.com/artifact/com.github.serceman/jnr-fuse

LGTM

**Comment by apc999** [comment]
@symious  can you sign our CLA https://cla.alluxio.org/ ? if you have already completed it, let me know

**Comment by symious** [comment]
@apc999 Thanks for the review, CLA signed.

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
