### PR TITLE
Update proto.lock

### PR DESCRIPTION
**Pull request by dbw9580**
#15241 updated the protobuf definitions, but did not update the lock file.

See also #14861.

### CODE REVIEW

**Review by yuzhu — APPROVED** [review]

**Review by luzhang6 — APPROVED** [review]

**Comment by luzhang6** [comment]
> #15241 updated the protobuf definitions, but did not update the lock file.
> 
> See also #14861.

@dbw9580 Can you pull latest master, update the lock file and resubmit? thanks!

**Comment by dbw9580** [comment]
@luzhang6 done.

**Comment by dbw9580** [comment]
Test failure not relevant.

```
alluxio.client.cli.fs.command.UpdateMountCommandTest  Time elapsed: 71.521 s  <<< ERROR!
java.lang.RuntimeException: Timed out waiting for process Alluxio job worker to start
```

**Comment by luzhang6** [comment]
> @luzhang6 done.

Thanks!

**Comment by dbw9580** [comment]
@yuzhu @luzhang6 are we ready to merge?

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
