### PR TITLE
[DOCFIX] Fix some cn client-metric table wording

### PR DESCRIPTION
**Pull request by voddle**
### What changes are proposed in this pull request?

Some wording in cn client-metric table

### Why are the changes needed?

Clarified some metric descriptions.

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Review by ssz1997 — COMMENTED** [review]
Thanks for your contribution.
1. You can change the title "Fixed" to "Fix" to fix the title check
2. Do you think “该客户端” sounds better than "这个客户端“? I'm ok with both but “该” sounds more formal.

**Comment by voddle** [comment]
> Thanks for your contribution.
> 
> 1. You can change the title "Fixed" to "Fix" to fix the title check
> 2. Do you think “该客户端” sounds better than "这个客户端“? I'm ok with both but “该” sounds more formal.

Sure, I think so.

**Review by ssz1997 — APPROVED** [review]

**Comment by voddle** [comment]
@jiacheliu3 could you merge this pls?

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
