### PR TITLE
[DOCFIX] minor format change of section header

### PR DESCRIPTION
**Pull request by unsleepy22**
Fixed markdown format of a section header in the doc.

### CODE REVIEW

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
add to whitelist

**Comment by gpang** [comment]
@unsleepy22 Thanks for this fix! Could you sign the cla before this can be merged?

**Comment by unsleepy22** [comment]
It's signed already

**Comment by aaudiber** [comment]
@unsleepy22 I've resent the CLA, could you try signing it again? Something must have gone wrong the first time

**Comment by unsleepy22** [comment]
@aaudiber should be ok now~

**Pull request merged**
