### PR TITLE
Rollback to use localcacheInStream for presto local cache

### PR DESCRIPTION
**Pull request by beinan**
### What changes are proposed in this pull request?

Rollback to use localcacheInStream for presto local cache

### Why are the changes needed?

Fix the oom and out of bound issue in prestodb's local cache

### Does this PR introduce any user facing changes?

no

### CODE REVIEW

**Comment by beinan** [comment]
@dbw9580 I think the LocalCacheFileSystem in alluxio.hadoop package I changed is just used by presto's local cache, so it should be no impact to alluxio worker or fuse sdk.  Could you help take a look? thanks!

**Review by ChunxuTang — APPROVED** [review]
LGTM

**Comment by beinan** [comment]
alluxio-bot, merge this please.

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Pull request merged**
