### PR TITLE
[ALLUXIO-1992] remotelly->remotely in WorkerSource

### PR DESCRIPTION
**Pull request by 6carol6**
[ALLUXIO-1992] remotelly->remotely in WorkerSource
https://alluxio.atlassian.net/browse/ALLUXIO-1992?jql=labels%20%3D%20NewContributor

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
LGTM, thank you for the improvement!

**Pull request merged**
