### PR TITLE
[ALLUXIO-1959] Add S3 server-side-encryption support.

### PR DESCRIPTION
**Pull request by ifcharming**
Addresses https://alluxio.atlassian.net/browse/ALLUXIO-1959

### CODE REVIEW

**Comment by ifcharming** [comment]
@calvinjia

**Comment by calvinjia** [comment]
The change looks good, were you able to verify this lets users interact with an encrypted S3?

**Comment by ifcharming** [comment]
yup, here is an example, `encrypted-s3-for-alluxio` is a bucket with S3 server-side-encryption enabled.
I was able to use shell to interact with the encrypted s3 bucket.
screen shot 2016-05-18 at 8 42 10 pm

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
