### PR TITLE
Update POSIX API documentation

### PR DESCRIPTION
**Pull request by ZacBlanco**
[skip ci]

### CODE REVIEW

**Comment by ZacBlanco** [comment]
unrelated failures - merging anyway

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Comment by ZacBlanco** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please

**Comment by jiacheliu3** [comment]
should this have a [DOCFIX] tag?

**Comment by ZacBlanco** [comment]
It's already merged. It doesn't really make a difference.

It only makes my life easier when I'm picking through commits to see what did and didn't make it into branch-2.2

**Pull request merged**
