### PR TITLE
[DOCFIX] Update tested Presto version

### PR DESCRIPTION
**Pull request by jiacheliu3**

### CODE REVIEW

**Comment by jiacheliu3** [comment]
@yuzhu Does it make sense to you to update the presto version according to our test? Thanks!

**Review by yuzhu — APPROVED** [review]

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
alluxio-bot, cherry-pick to branch-2.4 please

**Comment by jiacheliu3** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
