### PR TITLE
[ALLUXIO-2055] Fixed javadoc for NoSaslTransportProvider

### PR DESCRIPTION
**Pull request by yjguoo**
https://alluxio.atlassian.net/browse/ALLUXIO-2055

### CODE REVIEW

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by haoyuan** [comment]
Jenkins, add to whitelist

**Comment by haoyuan** [comment]
ok to test.

**Comment by apc999** [comment]
Thanks for the patch. LGTM

**Pull request merged**
