### PR TITLE
[DOCFIX] Rename some remaining Tachyon to Alluxio in docs

### PR DESCRIPTION
**Pull request by ifcharming**

### CODE REVIEW

**Comment by yupeng9** [comment]
Should this go to branch-1.0, too?

**Comment by ifcharming** [comment]
@yupeng9  Yes it should.
Not sure if it's too late since release 1.0 docs are already out?

**Comment by yupeng9** [comment]
We can push it to 1.0 branch, since we will have 1.0.1 release.

**Comment by ifcharming** [comment]
Sure, will have in a separate PR for branch-1.0

**Comment by yupeng9** [comment]
LGTM

**Comment by yupeng9** [comment]
LGTM. Thanks for the fix.

**Pull request merged**
