### PR TITLE
Wait on AlluxioStatusException as well in MultiMasterLocal AC

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
jenkins, test this please

**Comment by bradyoo** [comment]
Note that not only this one succeeded, this one actually succeeded on the first try. Which has never happened in the previous 10 builds.

**Comment by bradyoo** [comment]
Can you merge this for me?

**Comment by ZacBlanco** [comment]
jenkins, test this please

**Comment by bradyoo** [comment]
Yeah this doesn't actually do anything.

**Comment by bradyoo** [comment]
Actually, I'm wrong. It seems to help but is not a full fix.

**Comment by ZacBlanco** [comment]
jenkins, test this please

**Comment by ZacBlanco** [comment]
jenkins, test this please

**Comment by ZacBlanco** [comment]
jenkins, test this please

**Comment by ZacBlanco** [comment]
jenkins, test this please

**Comment by ZacBlanco** [comment]
wow, the last test had not a single failure/flake

**Comment by ZacBlanco** [comment]
jenkins, test this please

**Comment by ZacBlanco** [comment]
jenkins, test this please

**Comment by ZacBlanco** [comment]
jenkins, test this please

**Comment by ZacBlanco** [comment]
jenkins, test this please

**Comment by ZacBlanco** [comment]
if this next one succeeds I'll merge this

**Comment by ZacBlanco** [comment]
Looking good!

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Comment by ZacBlanco** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please

**Pull request merged**
