### PR TITLE
[ALLUXIO-1795] Improve javadoc

### PR DESCRIPTION
**Pull request by xxhuang**

### CODE REVIEW

**Comment by xxhuang** [comment]
Improve javadoc in TieredBlockStore#commitBlockInternal

**Comment by apc999** [comment]
Jenkins, ok to test

**Comment by apc999** [comment]
+1 LGTM!

Thanks for the improvement!

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Thanks for the PR @xxhuang !

**Comment by gpang** [comment]
LGTM

**Pull request merged**
