### PR TITLE
Support customize an uri translator

### LINKED ISSUE #14853: Support customize an uri translator
**Is your feature request related to a problem? Please describe.**

We can config MASTER_URI_TRANSLATOR_IMPL to a customized implementation which can translate the uri to a alluxio uri. For example:

- If we access /alluxio1, we can hash & mode and redirect this to /alluxio1.subdir1 or /alluxio1.subdir2.
- If we access /alluxio1, we can redirect this to /alluxio1.subdir1 or /alluxio1.subdir2 which is not busy than the other.
As conclusion, we want to extent to add some customized implementation for uri translator to translate the uri to which we want.

**Describe the solution you'd like**

Define a UriTranslator#Factory to create a customized uri translator, use the translator to translate the uri to another one by a specific implementation of UriTranslator

**Urgency**

Normal

**Additional context**

https://github.com/Alluxio/alluxio/pull/14718

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes are proposed in this pull request?

Fix #14853

Support customize an uri translator.

### Why are the changes needed?

Help developer to customized an specific uri translator.

### Does this PR introduce any user facing changes?

No.

### CODE REVIEW

**Comment by maobaolong** [comment]
@LuQQiu @jiacheliu3 Hi, please take a look at this PR, thanks a lot.

**Comment by jiacheliu3** [comment]
@maobaolong Could you explain the use case here?

**Comment by maobaolong** [comment]
@jiacheliu3 We can config MASTER_URI_TRANSLATOR_IMPL to a customized implementation which can translate the uri to a alluxio uri. For example:

- If we access /alluxio1, we can hash & mode and redirect this to /alluxio1.subdir1 or /alluxio1.subdir2.
- If we access /alluxio1, we can redirect this to /alluxio1.subdir1 or /alluxio1.subdir2 which is not busy than the other.

As conclusion, we want to extent to add some customized implementation for uri translator to translate the uri to which we want.

**Comment by LuQQiu** [comment]
@maobaolong can you help create a github issue explaining why this feature is required and how to use it?
(can copy your explanation there)

**Comment by maobaolong** [comment]
@LuQQiu I've create an issue about this, please take a look.

**Comment by HelloHorizon** [comment]
@jiacheliu3 @LuQQiu can you take another look?

**Comment by LuQQiu** [comment]
@maobaolong Please help @madanadit understand what's reason for adding this feature by replying in the linked jira ticket
@HelloHorizon it's more a feature discussion than a PR review. Will onhold the PR review until we have reach an consensus of why we need this feature and whether we should have this feature

**Pull request closed without merging**
