### PR TITLE
Remove the MasterInfo/Leader commands

### PR DESCRIPTION
**Pull request by yyongycy**
### What changes are proposed in this pull request?

Remove the MasterInfo/Leader/Load commands

### Why are the changes needed?

Remove the MasterInfo/Leader/Load commands

### Does this PR introduce any user facing changes?
NA

### CODE REVIEW

**Comment by yyongycy** [comment]
@jja725  please take a look, so far the master is only consumed by scheduler.

**Comment by jja725** [comment]
Let's postpone it after thinking potential usage

**Review by jja725 — APPROVED** [review]
Thanks for the cleanup, we gonna propose 1 master solution to the UC3 customers

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Pull request merged**
