### PR TITLE
Deflake stopAfterSecondaryTransition test

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Review by ZacBlanco — CHANGES_REQUESTED** [review]
Can we _not_ ignore this test since it is the only test providing critical coverage for the stop on demotion flag? Please try removing the `assertFalse` on lines 130/131 but leave the `assertFalse(m.isRunning())`. It should be more reliable since it won't be relying on checking the ports.

**Comment by bradyoo** [comment]
@ZacBlanco Okay. Will test with that.

**Comment by tieujason330** [comment]
i removed myself from review since i don't know much about this, but thanks for making this change for the master builds

**Review by ZacBlanco — APPROVED** [review]

**Review by gpang — APPROVED** [review]
LGTM

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Pull request merged**
