### PR TITLE
Fix metrics of Master.RpcQueueLength

### PR DESCRIPTION
**Pull request by jayzhenghan**
### What changes are proposed in this pull request?

Obtain accurate metrics of Master.RpcQueueLength

### Why are the changes needed?

method of getQueuedTaskCount cannot be collected correctly, so change collection method to getQueuedSubmissionCount.

### CODE REVIEW

**Comment by jayzhenghan** [comment]
In order to ensure the accuracy of the modification, If possible, I hope the development of ForkJoinPool will evaluate this PR，thanks

**Comment by jayzhenghan** [comment]
@ggezer Göktürk Gezer

**Comment by yuzhu** [comment]
@ggezer  the original intention is to display the total number of tasks (queued at the worker and queued in the rpc queue) in the rpc system. so should it be ` getQueuedTaskCount + getQueuedSubmissionCount` ?

**Comment by apc999** [comment]
@maobaolong who originally asked for this feature.  like to have your input too

**Comment by jayzhenghan** [comment]
> @ggezer the original intention is to display the total number of tasks (queued at the worker and queued in the rpc queue) in the rpc system. so should it be ` getQueuedTaskCount + getQueuedSubmissionCount` ?

After several stress tests, it is found that getQueuedTaskCount keeps returning 0

**Comment by maobaolong** [comment]
@yuzhu @apc999

**Review by ggezer — APPROVED** [review]

**Comment by ggezer** [comment]
alluxio-bot, merge this please

**Pull request merged**
