### PR TITLE
Support dynamic update HeartbeatThread tick interval

### PR DESCRIPTION
**Pull request by maobaolong**
Fix https://github.com/Alluxio/alluxio/issues/16733

### CODE REVIEW

**Review by LuQQiu — APPROVED** [review]

**Review by LuQQiu — CHANGES_REQUESTED** [review]
Sorry for mistakenly review the second commit only lol

**Comment by LuQQiu** [comment]
@maobaolong please help add a github issue and talks about why needs the changes? thanks

**Comment by maobaolong** [comment]
@LuQQiu Thanks for remind, i created a issue and link it to the description of this PR. PTAL.

**Comment by beinan** [comment]
@dbw9580 could you help take a look? since you're the expert of worker's heartbeat

**Comment by maobaolong** [comment]
Thanks @beinan @dbw9580 PTAL

**Comment by dbw9580** [comment]
Thanks for the improvement, I like the idea!

Since after this change, every heartbeat thread is a `Reconfigurable`, you can remove this from `DefaultFileSystemMaster`:

https://github.com/Alluxio/alluxio/blob/e6ed8dcca917b38ae853e6891ddb5c0012ebfd79/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java#L3994-L4002

**Comment by dbw9580** [comment]
Since the only occastion where `ReconfigurableRegistry.update` is called is in `FileSystemContext`, which only exists in clients, how does the server components get notified when their configuration changes?

https://github.com/Alluxio/alluxio/blob/03d42fe9091552c04a4658e70d5bfd472a3e17cd/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java#L436

**Comment by maobaolong** [comment]
@dbw9580 Thanks for your review, addressed your comment, and create a PR fix https://github.com/Alluxio/alluxio/pull/16764

**Review by dbw9580 — APPROVED** [review]
LGTM, thanks for this improvement!

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
