### PR TITLE
Support running on early-access JDK

### PR DESCRIPTION
**Pull request by wendigo**
### What changes are proposed in this pull request?

Alluxio doesn't work with early-access (EA) JDKs which makes it hard to do some forward-testing before new JDK is released.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

### CODE REVIEW

**Comment by wendigo** [comment]
CLA signed.

**Review by YichuanSun — APPROVED** [review]
Thanks for your contribution! LGTM

**Comment by wendigo** [comment]
@alluxio-bot recheck

**Comment by wendigo** [comment]
@YichuanSun thanks for the review!

**Comment by YichuanSun** [comment]
alluxio-bot, merge this please.

**Comment by YichuanSun** [comment]
alluxio-bot, merge this please.

**Comment by wendigo** [comment]
@YichuanSun can you release new version? I'd like to start testing it with JDK 23-ea

**Comment by YichuanSun** [comment]
> @YichuanSun can you release new version? I'd like to start testing it with JDK 23-ea

I don't really understand. Do you mean creating a new branch like "Alluxio-x.x.x-for-your-test"?

**Comment by wendigo** [comment]
I don't know how your automation works. I need 312 release

**Comment by YichuanSun** [comment]
I'm more confused, what is 312? Alluxio 3.1.2? Or anything else?

**Comment by wendigo** [comment]
image

Next version I suppose?

**Comment by wendigo** [comment]
Trino is currently using version 311 from mvncentral: https://mvnrepository.com/artifact/org.alluxio/alluxio-core-common/311

**Comment by YichuanSun** [comment]
I see. Sorry I don't have the right to do this.

**Comment by YichuanSun** [comment]
Maybe you can find any help in our slack channel, version release is out of my scope, actually I don't know how to do so.

**Pull request merged**
