### PR TITLE
Show correct Web UI metrics y-axis type for each graph

### LINKED ISSUE #12989: WebUI Metrics graphs all have % as Y axis
**Alluxio Version:**
2.5.0-SNAPSHOT

**Describe the bug**
The metrics graphs all have Y-axis % (0-100) when some values are raw throughput numbers.

**To Reproduce**
Open the metrics UI page.

**Expected behavior**
The Y-axis should match the type of data being displayed.

**Urgency**
High, many graphs are difficult to read / unreadable.

### PR DESCRIPTION
**Pull request by tieujason330**
fixes #12989

### CODE REVIEW

**Comment by tieujason330** [comment]
@LuQQiu ptal, thanks

**Comment by LuQQiu** [comment]
LGTM, thanks for updating the web UI metrics!

**Review by LuQQiu — APPROVED** [review]

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please

**Pull request merged**
