### PR TITLE
Reduce the default block size to 64 MB from 512 MB

### PR DESCRIPTION
**Pull request by apc999**
Fix https://github.com/Alluxio/alluxio/issues/9394 by reducing block size to 32 MB

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
@calvinjia I checked my previous notes and I was recommending 64MB as block size for TPC-DS workloads using Spark. So updated the block size to 64MB

**Comment by apc999** [comment]
Ping @calvinjia

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Pull request merged**
