### PR TITLE
[ALLUXIO-2315] Change "* @inheritDoc" to  "* {@inheritDoc}" in alluxio.underfs.swift.SwiftUnderFileSystem

### PR DESCRIPTION
**Pull request by artiit**
[https://alluxio.atlassian.net/browse/ALLUXIO-2315](url)
Fix wrong link in javadoc of alluxio.underfs.swift.SwiftUnderFileSystem#rename

### CODE REVIEW

**Comment by artiit** [comment]
alluxio-bot, check this please

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by artiit** [comment]
Please retest. 
------------------ Original ------------------

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
