### PR TITLE
Enable Dora in UT

### PR DESCRIPTION
**Pull request by huanghua78**
### What changes are proposed in this pull request?

Implements exists() and setAttribute().
Ignore some journal/master related UTs which are not applicable in Dora.

### Why are the changes needed?

Master/Journal services are not used in Dora.

### Does this PR introduce any user facing changes?
N/A

### CODE REVIEW

**Comment by huanghua78** [comment]
Please note, as we are moving to Dora only, some Master/Journal related tests are marked as `@Ignore `.
Please make sure this is OK.

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks for enabling dora in testing

**Review by beinan — APPROVED** [review]
lgtm

**Comment by beinan** [comment]
alluxio-bot, merge this please.

**Comment by beinan** [comment]
alluxio-bot, merge this please.

**Comment by beinan** [comment]
alluxio-bot, merge this please.

**Pull request merged**
