### PR TITLE
Print out PageStoreOptions correctly

### PR DESCRIPTION
**Pull request by apc999**
With this change, we can tell if `TimeBoundPageStore` is used when creation `PageStore` from logs

### CODE REVIEW

**Review by calvinjia — APPROVED** [review]

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.3 please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.3.0 please

**Pull request merged**
