### PR TITLE
Get User/Group/Permission of existed objects in OSS ufs

### PR DESCRIPTION
**Pull request by Jackson-Wang-7**
### What changes are proposed in this pull request?
Using the user of the OSS bucket to represent the user of the object loaded from OSS. 
Add the mapping way from OSS username to the custom username. 
Add the default permission mode for existing files loaded from OSS.

### Why are the changes needed?
the object loaded from OSS ufs will be null user, null group, and 777 by default.

### CODE REVIEW

**Comment by Jackson-Wang-7** [comment]
```
alluxio.underfs.oss.owner.id.to.username.mapping=1602444309173625=user1;xxxx=user2
alluxio.underfs.oss.default.mode=0770
```
after unmount and mount, we can see the file and directories loaded from UFS. the owner/group/permission mode will have the default value.
image

**Comment by yyongycy** [comment]
let's hold on it until more feedback

**Review by yyongycy — APPROVED** [review]
lgtm

**Comment by yyongycy** [comment]
> Add the configuration property to `alluxio-site.properties`
> 
> ```
> alluxio.underfs.oss.owner.id.to.username.mapping=160********625=user1;xxxx=user2
> alluxio.underfs.oss.default.mode=0770
> ```
> 
> After `unmount` and `mount`, we can see the file and directories loaded from UFS. The owner/group/permission mode will have the default value.
> 
> image

Please verify the metadata sync won't reset these value.

**Comment by Jackson-Wang-7** [comment]
> Please verify the metadata sync won't reset these value.

yes, I have tested it. it's ok, the metadata sync won't reset the user/group/mode value.

**Comment by Jackson-Wang-7** [comment]
alluxio-bot, merge this please

**Comment by Jackson-Wang-7** [comment]
alluxio-bot, cherry-pick this to branch-2.10 please

**Comment by Jackson-Wang-7** [comment]
alluxio-bot, cherry-pick this to branch-2.10 please

**Comment by jiacheliu3** [comment]
@Jackson-Wang-7 do we need  this in `main`? Thanks!

**Comment by Jackson-Wang-7** [comment]
@jiacheliu3 it's for OS 2.x, I'm not sure if it can be cherry-picked directly. We may need it for OS 3.x too.

**Comment by Jackson-Wang-7** [comment]
alluxio-bot, cherry-pick this to main please

**Pull request merged**
