### PR TITLE
[SMALLFIX]replace anonymous type with lambda_part1.

### PR DESCRIPTION
**Pull request by ITdoubleseven**
…ckStoreTest#getOutStreamUsingLocationPolicy

### CODE REVIEW

**Comment by ITdoubleseven** [comment]
I just changed the title so that it could be more intelligible.My work tested passed just now.Thank YOU!

----------
day day up.

--------------原始邮件--------------
发件人："Andrew Audibert "<notifications@github.com>;
发送时间：2018年10月23日(星期二) 晚上9:28
收件人："Alluxio/alluxio" <alluxio@noreply.github.com>;
抄送："ITdoubleseven "<mf1833024@smail.nju.edu.cn>;"Mention "<mention@noreply.github.com>;
主题：Re: [Alluxio/alluxio] [SMALLFIX]replace anonymous type withlambda_part1. (#8035)
-----------------------------------

 
@ITdoubleseven I don't see the changed file, can you open a new pull request with the intended change?

**Comment by aaudiber** [comment]
@ITdoubleseven The title is ok, but under "Files changed" I just see and empty .git-credentials file and a submodule

image

**Comment by ITdoubleseven** [comment]
IT told me that “test failed”at the first time I proposed the task(create a new PR),so I modified my code and then checked again(in the old PR) and finally passed.I do not know why this is happening as the picture shows.Need I create a new PR（Is it the only way to solve this）？

----------
day day up.

--------------原始邮件--------------
发件人："Andrew Audibert "<notifications@github.com>;
发送时间：2018年10月23日(星期二) 晚上10:20
收件人："Alluxio/alluxio" <alluxio@noreply.github.com>;
抄送："ITdoubleseven "<mf1833024@smail.nju.edu.cn>;"Mention "<mention@noreply.github.com>;
主题：Re: [Alluxio/alluxio] [SMALLFIX]replace anonymous type withlambda_part1. (#8035)
-----------------------------------

 
@ITdoubleseven The title is ok, but under "Files changed" I just see and empty .git-credentials file and a submodule

**Comment by ITdoubleseven** [comment]
I used "git add -A,git commit -m,git push origin" ,I want to know if my first PR changed file successfully？

----------
day day up.

--------------原始邮件--------------
发件人："Andrew Audibert "<notifications@github.com>;
发送时间：2018年10月24日(星期三) 凌晨2:25
收件人："Alluxio/alluxio" <alluxio@noreply.github.com>;
抄送："ITdoubleseven "<mf1833024@smail.nju.edu.cn>;"Mention "<mention@noreply.github.com>;
主题：Re: [Alluxio/alluxio] [SMALLFIX]replace anonymous type withlambda_part1. (#8035)
-----------------------------------

 
You need to add your changes using git add <changed file> and then commit with git commit. I suggest starting over with a new PR

**Pull request closed without merging**
