### PR TITLE
Align the rule to use whether a self signed or official ca

### PR DESCRIPTION
**Pull request by yyongycy**
### What changes are proposed in this pull request?

Align the rule to use whether a self signed or official ca

### Why are the changes needed?

Align the rule to use whether a self signed or official ca.

### Does this PR introduce any user facing changes?
NA

### CODE REVIEW

**Review by huanghua78 — COMMENTED** [review]
I don't have objections. But I am not an expert in this, please ask someone else to review this, too.

**Review by beinan — APPROVED** [review]
lgtm

**Comment by beinan** [comment]
alluxio-bot, merge this please.

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Pull request merged**
