### PR TITLE
[ALLUXIO-2131] ZSD New Contributor

### PR DESCRIPTION
**Pull request by shoudi**
https://alluxio.atlassian.net/browse/ALLUXIO-2131

### CODE REVIEW

**Comment by calvinjia** [comment]
Jenkins, ok to test.

**Comment by calvinjia** [comment]
@shoudi This change looks ready to merge, could you sign the CLA?

**Comment by aaudiber** [comment]
LGTM

**Comment by jsimsa** [comment]
was this meant to go to branch-1.2?

**Comment by aaudiber** [comment]
No, it should have gone to master. I've merged 1.2 into master so that the change is there as well.

**Pull request merged**
