### PR TITLE
[ALLUXIO-1735] Upgrades free Miredot license to open-source license.

### PR DESCRIPTION
**Pull request by DenEwout**
Dear maintainers of Alluxio,

We noticed you were using a free Miredot license for Alluxio. We thought we'd help you out and upgrade that license to an open-source license.

With this license you get access to all the paying features, free of charge. 

I tried building the project myself in order to fully test the license, but was not able to do that on my windows machine. It should be fine though. If you have any questions, problems or feedback, please let us know!

Kind Regards,
Ewout & The Miredot team.

P.S.: It will expire on 28/04/2018, we will send you another pull request with a license update before that happens.

Edit: added what I think was the original JIRA ticket for adding rest docs. 
Link: https://alluxio.atlassian.net/browse/ALLUXIO-1735

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by jsimsa** [comment]
LGTM

**Comment by jsimsa** [comment]
thanks @DenEwout ... any update on when is 2.0 coming out?

**Comment by DenEwout** [comment]
No problem at all. Feel free to contact us if you need any extra open source keys.

We've released our second release candidate and we're aiming to do the full release in the next couple of weeks. Using the release candidate will give you some cool extra features such as RAML output and support for multi-module poms (generating single documentation for multiple submodules). It also comes with more extensive framework support. To check it out, simply use version 2.0-RC2 using your open source key (or use our 1 month trial to run it on different projects).

It's not exactly clear yet on our site (with our new online licensing scheme), but we plan on keeping our promise for being free for open-source projects.

**Comment by jsimsa** [comment]
@DenEwout after switching to the open source license, we started seeing the following stack trace in our build logs:

```
...
[INFO] Built.
[INFO] Reading javadoc comments from sourcefiles...
[WARNING] No source files found in /Users/jsimsa/Projects/alluxio-fork/core/server/target/generated-sources/annotations !
[INFO] Read.
[INFO] Merging reflective and javadoc models...
java.lang.NoSuchMethodError: com.sun.tools.doclets.formats.html.ConfigurationImpl.getInstance()Lcom/sun/tools/doclets/formats/html/ConfigurationImpl;
	at com.qmino.miredot.construction.javadoc.TagFormatter.fixLinks(TagFormatter.java:230)
	at com.qmino.miredot.construction.javadoc.TagFormatter.tagToString(TagFormatter.java:122)
	at com.qmino.miredot.construction.javadoc.TagFormatter.tagsToString(TagFormatter.java:152)
	at com.qmino.miredot.construction.javadoc.UserTypeEnhancer.extractFullComment(UserTypeEnhancer.java:201)
	at com.qmino.miredot.construction.javadoc.UserTypeEnhancer.collectComments(UserTypeEnhancer.java:85)
	at com.qmino.miredot.construction.javadoc.UserTypeEnhancer.execute(UserTypeEnhancer.java:41)
	at com.qmino.miredot.construction.javadoc.RestModelEnhancer.execute(RestModelEnhancer.java:116)
	at com.qmino.miredot.javadoc.Doclet.start(Doclet.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
	at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
	at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
	at com.sun.tools.javadoc.Start.begin(Start.java:219)
	at com.sun.tools.javadoc.Start.begin(Start.java:205)
	at com.sun.tools.javadoc.Main.execute(Main.java:64)
	at com.qmino.miredot.application.MireDotPlugin.execute(MireDotPlugin.java:176)
	at com.qmino.miredot.maven.Mojo.execute(Mojo.java:177)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] MireDot: Completed
```

Any idea what might be causing it and how to get rid of it? Thanks.

**Comment by DenEwout** [comment]
Hi,

Sorry for the incredibly late reply, because the request got merged I lost sight of it. Is it still an issue?

If so, please create a support request on support@miredot.com and provide us with the output of:
`mvn package -X > output.log`

Kind regards,

Ewout.

**Pull request merged**
