### PR TITLE
[SMALLFIX] Minor fixes to common utilities.

### PR DESCRIPTION
**Pull request by jsimsa**

### CODE REVIEW

**Comment by bissont** [comment]
I think this commit makes "alluxio format" start to fail.

MacBook-Pro-3 ~/Documents/alluxio/
$ ./bin/alluxio format
Waiting for tasks to finish...
All tasks finished, please analyze the log at /Users/tim/Documents/alluxio/bin/../logs/task.log.
Formatting Alluxio Master @ Erins-MacBook-Pro-3.local
MacBook-Pro-3 ~/Documents/alluxio/

$ git co -b t2 61e5a2fb48ee377c2f256939ff395ae42543d751
M	conf/alluxio-site.properties.template
Switched to a new branch 't2'
MacBook-Pro-3 ~/Documents/alluxio/

$ ./bin/alluxio format
cat: /workers: No such file or directory
Waiting for tasks to finish...
All tasks finished, please analyze the log at /Users/tim/Documents/alluxio/bin/../logs/task.log.
Formatting Alluxio Master @ Erins-MacBook-Pro-3.local
log4j:ERROR Could not read configuration file from URL [file:/log4j.properties].
java.io.FileNotFoundException: /log4j.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:557)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:64)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
	at alluxio.cli.Format.<clinit>(Format.java:38)
log4j:ERROR Ignoring configuration file [file:/log4j.properties].
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Erins-MacBook-Pro-3 ~/Documents/alluxio/

$ git show 61e5a2fb48ee377c2f256939ff395ae42543d751
commit 61e5a2fb48ee377c2f256939ff395ae42543d751
Merge: ede2d3d 7592a4c
Author: Jiri Simsa <jsimsa@users.noreply.github.com>
Date:   Mon Jan 9 16:02:24 2017 -0800

    Merge pull request #4616 from jsimsa/utils

    [SMALLFIX] Minor fixes to common utilities.

**Comment by jsimsa** [comment]
thanks for reporting this ... I think the problem is actually in this PR https://github.com/Alluxio/alluxio/pull/4591

**Comment by jsimsa** [comment]
the last commit that has the problem is `git checkout 0f65b6f08ab4780dac1a3f80e28c3c1652ea30e9`

**Comment by jsimsa** [comment]
@bissont FYI https://github.com/Alluxio/alluxio/pull/4628

**Pull request merged**
