### PR TITLE
[ALLUXIO-­2784] replace Throwables.propagate with RuntimeException

### PR DESCRIPTION
**Pull request by shuanglzy**
JIRA Ticket: 
https://alluxio.atlassian.net/browse/ALLUXIO-2784

### CODE REVIEW

**Comment by aaudiber** [comment]
@shuanglzy It looks like the changes were lost when you fetched upstream. Can you add them again?

**Comment by shuanglzy** [comment]
@aaudiber The file I modified is core/server/worker/src/main/java/alluxio/worker/DefaultAlluxioWorker.java.
But I find the file is missing in upstream/master. Is it in plan?

**Comment by aaudiber** [comment]
@shuanglzy Ah, the file was renamed to `AlluxioWorkerProcess`. Could you apply your changes to the new file?

**Comment by aaudiber** [comment]
@shuanglzy Are you still planning on working on this?

**Comment by shuanglzy** [comment]
I'll submit it soon. ^_^

**Comment by shuanglzy** [comment]
This issue had been fixed. I'll close this PR.

**Pull request closed without merging**
