### PR TITLE
Downgrade hive client version in validation tools

### PR DESCRIPTION
**Pull request by yuzhu**
This should help with the validation tools working with older version of hive metastore.

### CODE REVIEW

**Comment by madanadit** [comment]
@Lu do you remember the implications of this change? I remember you and gene had some discussions about the hive client version

**Comment by yuzhu** [comment]
@madanadit @LuQQiu I was the one who bumped it from 2.3.6 to 3.x. Later I found that 2.3.7 worked best for hive metastore connection and built a compatibility layer for it but did not change validation tool's hive version to match that in the catalog service.

**Comment by madanadit** [comment]
sounds good, thx David

**Review by madanadit — APPROVED** [review]

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
