### PR TITLE
[ALLUXIO-2305] Improve logging in LeaderInquireClient

### PR DESCRIPTION
**Pull request by yanmengk**
https://alluxio.atlassian.net/browse/ALLUXIO-2305
I haved changed the 'create' to 'Creating'

### CODE REVIEW

**Comment by yanmengk** [comment]
@alluxio-bot alluxio-bot, check this please

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
@yanmengk Thanks for the PR! Could you please sign the CLA?

**Comment by yanmengk** [comment]
@gpang OK，I will.Thank you very much!

**Comment by yanmengk** [comment]
@AmplabJenkins Thanks.

**Comment by ifcharming** [comment]
LGTM, thank you for contributing to Alluxio!

**Pull request merged**
