### PR TITLE
Show inconsistent path list on WebUI

### PR DESCRIPTION
**Pull request by Yiran-wu**
#Show inconsistent path list on WebUI

Normal
image
 

Error(Inconsistent Files)  
image

### CODE REVIEW

**Comment by Yiran-wu** [comment]
alluxio-bot, check this please

**Comment by Yiran-wu** [comment]
alluxio-bot, check this please

**Comment by maobaolong** [comment]
add your email to github account

**Comment by Yiran-wu** [comment]
alluxio-bot, check this please

**Pull request closed without merging**
