### PR TITLE
[SMALLFIX] Use static imports for standard test utilities

### PR DESCRIPTION
**Pull request by ftbabi**
Use static imports for standard test utilities in /alluxio/core/common/src/test/java/alluxio/util/FormatUtilsTest.java

### CODE REVIEW

**Comment by aaudiber** [comment]
@ftbabi PR is good to merge once you've signed the CLA

**Comment by aaudiber** [comment]
@ftbabi please sign CLA as soon as you have a chance

**Comment by ftbabi** [comment]
I'm so sorry about my late and having a bad influence on your work. 
Wish you a good day.

**Comment by aaudiber** [comment]
@ftbabi no worries! thanks for signing :)

**Comment by aaudiber** [comment]
alluxio-bot, merge this please

**Pull request merged**
