### PR TITLE
Make DistributedCp/Mv not retry

### PR DESCRIPTION
**Pull request by bradyoo**
Reason: overwrite has been broken. Overwrite hasn't appeared to have worked since at least 2.0 or perhaps further back.

Both the createDirectory and createFile calls in MigrateDefinition is not overwriting version.

Thus, retrying is pointless because retries will always fail with the message of being unable to overwrite.

### CODE REVIEW

**Comment by bradyoo** [comment]
@gpang

**Comment by bradyoo** [comment]
@gpang: Can you take a look at this?

**Comment by bradyoo** [comment]
Ping @gpang

**Comment by bradyoo** [comment]
Ping @gpang.

**Comment by bradyoo** [comment]
Ping @gpang

**Comment by bradyoo** [comment]
Ping @gpang

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
