### PR TITLE
Fix isMounted should not invoke ufs, if not /metrics page very slowly

### PR DESCRIPTION
**Pull request by flaming-archer**
### What changes are proposed in this pull request?

isMounted would not invoke ufs.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
   If you fix a bug, describe the bug.
    We mount many hdfs path to alluxio. When we open the /metrics page , find it is very very slow, about 30 mins.
Then debug it , cause of many metrics  will invoke isMounteds method one by one ,and the isMounteds will invoke all mounted path to see it's capacity twice. But it has no meanings, because we just  want to known it is mounted or not. We can justice it in memory.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs no
  2. addition or removal of property keys no
  3. webui yes, will improve metrics page performance while we have many mounted path.

### CODE REVIEW

**Comment by flaming-archer** [comment]
> alluxio-bot, check this please

alluxio-bot, check this please

**Comment by flaming-archer** [comment]
> alluxio-bot, check this please

alluxio-bot, check this please

**Comment by flaming-archer** [comment]
> Automated checks report:
> 
> * Commits associated with Github account: PASS
> * PR title follows the conventions: FAIL
>   
>   * The title of the PR does not pass all the checks. Please fix the following issues:
>     
>     * Title is too long (98 characters). Must be at most 72 characters.
> 
> Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.



> Automated checks report:
> 
> * Commits associated with Github account: PASS
> * PR title follows the conventions: FAIL
>   
>   * The title of the PR does not pass all the checks. Please fix the following issues:
>     
>     * Title is too long (98 characters). Must be at most 72 characters.
> 
> Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.
alluxio-bot, check this please

**Comment by flaming-archer** [comment]
> 

alluxio-bot, check this please

**Comment by flaming-archer** [comment]
> Automated checks report:
> 
> * Commits associated with Github account: PASS
> * PR title follows the conventions: FAIL
>   
>   * The title of the PR does not pass all the checks. Please fix the following issues:
>     
>     * Title is too long (98 characters). Must be at most 72 characters.
> 
> Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.

alluxio-bot, check this please

**Comment by flaming-archer** [comment]
> Automated checks report:
> 
> * Commits associated with Github account: PASS
> * PR title follows the conventions: FAIL
>   
>   * The title of the PR does not pass all the checks. Please fix the following issues:
>     
>     * Title is too long (98 characters). Must be at most 72 characters.
> 
> Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.

alluxio-bot, check this please

**Comment by flaming-archer** [comment]
> 

alluxio-bot, check this please

**Comment by flaming-archer** [comment]
> Automated checks report:
> 
> * Commits associated with Github account: PASS
> * PR title follows the conventions: FAIL
>   
>   * The title of the PR does not pass all the checks. Please fix the following issues:
>     
>     * Title is too long (98 characters). Must be at most 72 characters.
> 
> Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.

alluxio-bot, check this please

**Comment by flaming-archer** [comment]
> 
alluxio-bot, check this please

**Comment by flaming-archer** [comment]
I think the failed tests is caused by other reasons, not mine.

**Comment by flaming-archer** [comment]
@yuzhu @LuQQiu  @Xenorith @apc999 Pls help to review.

**Review by Xenorith — CHANGES_REQUESTED** [review]
the change makes sense to me; it is not necessary to populate the full info about the mount to perform the calculations needed for the metrics page because we are only checking against the value of `MountPointInfo.getUfsUri()` in `isMounted()`.

can you take a look at the failing unit test `alluxio.master.meta.AlluxioMasterRestServiceHandlerTest.isMounted`? i believe it is due to your changes as it was not failing previously. the other unit test failure is unrelated

**Comment by flaming-archer** [comment]
> the change makes sense to me; it is not necessary to populate the full info about the mount to perform the calculations needed for the metrics page because we are only checking against the value of `MountPointInfo.getUfsUri()` in `isMounted()`.
> 
> can you take a look at the failing unit test `alluxio.master.meta.AlluxioMasterRestServiceHandlerTest.isMounted`? i believe it is due to your changes as it was not failing previously. the other unit test failure is unrelated

Change now, I test fine in my local machine now.

**Review by LuQQiu — APPROVED** [review]
LGTM, @flaming-archer can you help take a look at other places where also called `getMountPointInfoSummary` especially through RPC, and see whether those calls can be changed to `invokeUfs=false` to improve performance?

**Comment by LuQQiu** [comment]
Error: 3.320 [ERROR] Failures: 
Error: 3.320 [ERROR] alluxio.util.JvmPauseMonitorTest.testMockedInfoPause
Error: 3.320 [ERROR]   Run 1: JvmPauseMonitorTest.testMockedInfoPause:116 expected:<2> but was:<1>
Error: 3.320 [ERROR]   Run 2: JvmPauseMonitorTest.testMockedInfoPause:103 expected:<1> but was:<0>
16:04:03.321 [INFO]

**Comment by LuQQiu** [comment]
Error: 2.642 [ERROR] Errors: 
Error: 2.642 [ERROR] alluxio.server.configuration.ConfigCheckerIntegrationTest.multiNodes
Error: 2.642 [ERROR]   Run 1: ConfigCheckerIntegrationTest.multiNodes:144->getReport:182 » Timeout Timed out...
Error: 2.642 [ERROR]   Run 2: ConfigCheckerIntegrationTest.multiNodes:144->getReport:182 » Timeout Timed out...

**Review by Xenorith — APPROVED** [review]
defer to @LuQQiu to merge when ready

**Comment by flaming-archer** [comment]
> testMockedInfoPause
I check all the call methods below.
FileSystemMaster.getMountPointInfoSummary()  (alluxio.master.file)
    FileSystemMasterClientServiceHandler.getMountTable(GetMountTablePRequest, 
              StreamObserver<GetMountTablePResponse>)  (alluxio.master.file)        --the client rpc maybe need ufs info,so cannot change to invokeUfs=false
    AlluxioMasterRestApiTest.getMountPoints()  (alluxio.client.rest). --- this changed ok now , but other pepole maybe want to  
 visit ufs later.                         
    AlluxioMasterRestServiceHandler.getMountPointsInternal()  (alluxio.master.meta). --- this method will be called by other methods which will use ufs capicity. So cannot change to invokeUfs=false
    AlluxioMasterRestServiceHandler.getUfsCapacityInternal()  (alluxio.master.meta) --- this method used ufs capacity, so cannot change to invokeUfs=false
    MultiUfsMountIntegrationTest.mountAfterMasterRestart()  (alluxio.client.fs) --- this changed ok now , but other pepole maybe want to  visit ufs later.     

So two methods can change  invokeUfs to false, but other pepole maybe want to visit ufs later. So i think not change will be better.

**Comment by flaming-archer** [comment]
> Error: 3.320 [ERROR] Failures: Error: 3.320 [ERROR] alluxio.util.JvmPauseMonitorTest.testMockedInfoPause Error: 3.320 [ERROR] Run 1: JvmPauseMonitorTest.testMockedInfoPause:116 expected:<2> but was:<1> Error: 3.320 [ERROR] Run 2: JvmPauseMonitorTest.testMockedInfoPause:103 expected:<1> but was:<0> 16:04:03.321 [INFO]

I test ok in my local env ,  maybe this is in other pr?

**Comment by flaming-archer** [comment]
> Error: 2.642 [ERROR] Errors: Error: 2.642 [ERROR] alluxio.server.configuration.ConfigCheckerIntegrationTest.multiNodes Error: 2.642 [ERROR] Run 1: ConfigCheckerIntegrationTest.multiNodes:144->getReport:182 » Timeout Timed out... Error: 2.642 [ERROR] Run 2: ConfigCheckerIntegrationTest.multiNodes:144->getReport:182 » Timeout Timed out...

I test ok in my local env ,  maybe this is in other pr too?

**Comment by flaming-archer** [comment]
@Xenorith  @LuQQiu hello, ,Can be merged now.

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
