### PR TITLE
Revert "Avoid loads ufs jars multiple times during journal formatting"

### PR DESCRIPTION
**Pull request by apc999**
This reverts commit 22b67274fd032ce46532c3e21a46e973c7ccc307.

Release tests are failing on format

@maobaolong

### CODE REVIEW

**Review by LuQQiu — APPROVED** [review]

**Comment by LuQQiu** [comment]
@maobaolong the related failed logs when trying to format the HDFS
2020-12-14 10:24:04,839 INFO  UfsJournal - Formatting hdfs://master_adress/alluxio_journal/BlockMaster/v1
2020-12-14 10:24:04,847 ERROR Format - Failed to format
java.io.IOException: Failed to create hdfs://master_adress/alluxio_journal/BlockMaster/v1
	at alluxio.master.journal.ufs.UfsJournal.format(UfsJournal.java:439)
	at alluxio.master.journal.ufs.UfsJournalSystem.format(UfsJournalSystem.java:205)
	at alluxio.cli.Format.format(Format.java:124)
	at alluxio.cli.Format.main(Format.java:98)

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by maobaolong** [comment]
@LuQQiu @apc999 Thank you for revert the problem commit, and sorry for the affect.

After a quick look at the related code, I found some following possible problem.

```java

  public void format() throws IOException {
    URI location = getLocation();
    LOG.info("Formatting {}", location);
    if (mUfs.isDirectory(location.toString())) {
      for (UfsStatus status : mUfs.listStatus(location.toString())) {
        String childPath = URIUtils.appendPathOrDie(location, status.getName()).toString();
        if (status.isDirectory()
            && !mUfs.deleteDirectory(childPath, DeleteOptions.defaults().setRecursive(true))
            || status.isFile() && !mUfs.deleteFile(childPath)) {
          throw new IOException(String.format("Failed to delete %s", childPath));
        }
      }
    } else if (!mUfs.mkdirs(location.toString())) {
      throw new IOException(String.format("Failed to create %s", location));
    }

```

The `mUfs` in the above format method, I think it wasn't the `hdfs` UnderFilesystem, it maybe `local` UnderFilesystem.

Because the following method

```java

  @Override
  public UfsClient getJournal() {
    synchronized (this) {
      if (mJournalUfsClient == null) {
        addMount(IdUtils.UFS_JOURNAL_MOUNT_ID, new AlluxioURI("/dummy_journal_mount_point"),
            UfsJournal.getJournalUfsConf());
        try {
          mJournalUfsClient = get(IdUtils.UFS_JOURNAL_MOUNT_ID);
        } catch (NotFoundException | UnavailableException e) {
          throw new RuntimeException("We should never reach here", e);
        }
      }
      return mJournalUfsClient;
    }
  }
```
The ufsUri is `/dummy_journal_mount_point`, so the UnderFilesystem cannot be `HdfsUnderFilesystem`.

**Comment by maobaolong** [comment]
Seems we cannot use `master.getMasterContext().getUfsManager().getJournal().acquireUfsResource().get()` to replace `UnderFileSystem.Factory.create(location.toString(), getJournalUfsConf()` simply.

**Comment by apc999** [comment]
@maobaolong  thanks for getting to the root cause, mind creating a new PR with test covered?

**Comment by maobaolong** [comment]
@apc999 Now, I have no idea to fix this PR, let me think about it 🤔

**Comment by apc999** [comment]
@LuQQiu  can you help Baolong on more details? e.g., command we run? or more logs?

**Comment by maobaolong** [comment]
@apc999 @LuQQiu A new fix PR just created, Hope to fix this issue, if you have a test, I'd like to run it on local.

**Pull request merged**
