### PR TITLE
[SMALLFIX] Change import of three functions in org.junit.Assert

### PR DESCRIPTION
**Pull request by IrisuMakina**
Change "import org.junit.Assert;" to 
"import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertFalse;"
and remove all the "Assert."

Besides,when I use "mvn clean install -DskipTests",there will be an error in building Alluxio UI 2.1.0-SNAPSHOT. It occurs when frontend-maven-plugin:1.6:install-node-and-npm. It has to download https://nodejs.org/dist/v10.11.0/node-v10.11.0-linux-x86.tar.gz which is not exist.

### CODE REVIEW

**Comment by IrisuMakina** [comment]
alluxio-bot, check this please

At 2019-07-26 04:43:02, "alluxio-bot" <notifications@github.com> wrote:


Automated checks report:

Commits associated with Github account: PASS
PR title follows the conventions: FAIL
The title of the PR does not pass all the checks. Please fix the following issues:
Title is too long (87 characters). Must be at most 72 characters.
First word must be capitalized

Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.

**Comment by IrisuMakina** [comment]
alluxio-bot, check this please

At 2019-07-26 04:52:16, "alluxio-bot" <notifications@github.com> wrote:


Automated checks report:

Commits associated with Github account: PASS
PR title follows the conventions: FAIL
The title of the PR does not pass all the checks. Please fix the following issues:
First word must be capitalized

Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.

**Comment by IrisuMakina** [comment]
alluxio-bot, check this please

At 2019-07-26 04:55:04, "alluxio-bot" <notifications@github.com> wrote:


Automated checks report:

Commits associated with Github account: PASS
PR title follows the conventions: FAIL
The title of the PR does not pass all the checks. Please fix the following issues:
First word must be capitalized

Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
