### PR TITLE
Upgrade kryo from 4.0.2 to 5.0.0-RC8

### PR DESCRIPTION
**Pull request by Xenorith**
dependency diff
before
```
[INFO] +- com.esotericsoftware:kryo:jar:4.0.2:compile
[INFO] |  +- com.esotericsoftware:reflectasm:jar:1.11.3:compile
[INFO] |  |  \- org.ow2.asm:asm:jar:5.0.4:compile
[INFO] |  +- com.esotericsoftware:minlog:jar:1.3.0:compile
[INFO] |  \- org.objenesis:objenesis:jar:2.5.1:compile
```
after
```
[INFO] +- com.esotericsoftware:kryo:jar:5.0.0-RC8:compile
[INFO] |  +- com.esotericsoftware:reflectasm:jar:1.11.8:compile
[INFO] |  +- org.objenesis:objenesis:jar:3.0.1:compile
[INFO] |  \- com.esotericsoftware:minlog:jar:1.3.1:compile
```

### CODE REVIEW

**Comment by yuzhu** [comment]
@Xenorith OS tarball generation successful?

**Comment by Xenorith** [comment]
yup, OS tarball generation good

**Comment by yuzhu** [comment]
https://github.com/EsotericSoftware/kryo/wiki/Migration-to-v5
seems like they don't have backcompat at all? 

so we won't be able to read old checkpoints if we upgrade? that seems like a problem..

@gpang knows more about checkpoints

**Comment by gpang** [comment]
We will not be able to merge this until we do some journal testing.

**Comment by yuzhu** [comment]
closing this as this introduces serious backcompat issues.

**Pull request closed without merging**
