### PR TITLE
[DOCFIX]Update "System Configuration" to "Configuration" in docs to be consistent with the Web UI navigation bar

### PR DESCRIPTION
**Pull request by zhanglijunlily**
"System Configuration" has been updated to "Configuration" in the Web UI navigation bar.

### CODE REVIEW

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
LGTM, thanks for the improvement!

**Comment by ifcharming** [comment]
Can you please add the JIRA ticket in the PR title and description?

**Comment by apc999** [comment]
LGTM

**Pull request merged**
