### PR TITLE
Update guava to fix some CVEs

### PR DESCRIPTION
**Pull request by ddadaal**
### What changes are proposed in this pull request?

Try updating guava to resolve some CVEs.

### Why are the changes needed?

Some CVEs are caused by guava. This PR updates guava to a fixed version.

### Does this PR introduce any user facing changes?

No.

### CODE REVIEW

**Review by yuzhu — COMMENTED** [review]
why not use the latest version 31.0.1-jre?

**Comment by ddadaal** [comment]
Just use the latest 31.0.1-jre and try again

**Comment by ddadaal** [comment]
Failed test cases:
- FileOutStreamIntegrationTest.cancelWrite: flakey

**Comment by yyongycy** [comment]
Please check the test failure.

**Review by yuzhu — APPROVED** [review]

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by ddadaal** [comment]
Old failures: #7, #14

**Pull request merged**
