### PR TITLE
Upgrade mockito-all (1.10.19) to mockito-core (3.4.4)

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
@yuzhu can you review? Also going to run java 11 test on this.

**Comment by bradyoo** [comment]
jenkins, test this with java 11 please

**Comment by yuzhu** [comment]
@bradyoo did you run ospublish on this?

**Comment by bradyoo** [comment]
OSPublish worked.. Can you merge it for me?

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
