### PR TITLE
Replace anonymous class with lambda

### PR DESCRIPTION
**Pull request by AryehAlexander**

### CODE REVIEW

**Comment by apc999** [comment]
@AryehAlexander the build does not pass and looks like related to your change.
Can you double check in our local environment?

**Comment by AryehAlexander** [comment]
@apc999 Figured it out, i wasnt building/checkstyle-(ing) correctly. Ran with find-bugs locally and it cleared. 

(unused import caused the problem)

how can i re-run tests?

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
