### PR TITLE
 [SMALLFIX]Improve Naming in FileSystemAclIntegrationTest

### PR DESCRIPTION
**Pull request by ZhangFanruo**
Improve Naming in FileSystemAclIntegrationTest,in the test s3GetPermission, rename the file /objectFileA to /s3GetPermissionFile.

### CODE REVIEW

**Comment by ZhangFanruo** [comment]
alluxio-bot, check this please

**Comment by ZhangFanruo** [comment]
@aaudiber PTAL.

**Comment by ZhangFanruo** [comment]
Merge

**Comment by ZhangFanruo** [comment]
@aaudiber PTAL.

**Comment by newnius** [comment]
LGTM

**Pull request merged**
