### PR TITLE
Fix JobServiceSummary for workflows

### PR DESCRIPTION
**Pull request by bradyoo**
Should be patched for 2.1 

Fixes https://github.com/Alluxio/alluxio/issues/10647

CC: @calvinjia

### CODE REVIEW

**Comment by gpang** [comment]
@bradyoo If this is fixing a bug, can you create a github issue with the bug report, and link it in the PR description?

**Comment by bradyoo** [comment]
Will do.

**Comment by bradyoo** [comment]
alluxio.server.ft.ZookeeperFailureIntegrationTest.zkConnectionPolicy_Session(alluxio.server.ft.ZookeeperFailureIntegrationTest)
  Run 1: ZookeeperFailureIntegrationTest.zkConnectionPolicy_Session:139 » Timeout Timed...
  Run 2: ZookeeperFailureIntegrationTest.zkConnectionPolicy_Session:139 » Timeout Timed...


flake.

**Comment by bradyoo** [comment]
alluxio-bot, test this please.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please.

**Comment by bradyoo** [comment]
@calvinjia: I was wrong about this needing a cherry-pick to 2.1 because Workflows are not a thing in 2.1 :/

**Pull request merged**
