### PR TITLE
Avoid exception when audit log is used with NOSASL authentication

### LINKED ISSUE #9294: Make audit log not depend on authentication type
**Alluxio Version:**
1.8+

**Describe the bug**
If audit log is enabled and authentication is NOSASL, any operation will fail with "authentication not enabled" error. 
**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**
Authentication should not be a dependency for audit log. If a user is not identified, audit log should log "N/A".
**Urgency**
medium
**Additional context**
Can be worked around by enabling authentication but disable authorization.

### LINKED ISSUE #9295: Web UI error when authentication is SIMPLE but authorization is disabled
**Alluxio Version:**
Alluxio 1.8
**Describe the bug**

**To Reproduce**
set auth type to SIMPLE and disable authorization, web UI file browser will show error.
**Expected behavior**
Web UI should be usable.
**Urgency**
high, it makes webUI file browsing unusable

**Additional context**
IMG_5343

### PR DESCRIPTION
**Pull request by bf8086**
Cherry-pick of existing commit.
orig-pr: Alluxio/alluxio#9645
orig-commit: Alluxio/alluxio@0e3a152f9670ea9617313b3a221a9014b70c5192
orig-commit-author: bf8086 <binfeng@alluxio.com>

pr-link: Alluxio/alluxio#9664
change-id: cid-838211044d298fb42335b77f1c9c509fd42d185e

### CODE REVIEW

**Comment by bf8086** [comment]
@gpang PTAL.

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
