### PR TITLE
[DOCFIX] Fix fuse doc picture

### PR DESCRIPTION
**Pull request by LuQQiu**
Fix fuse doc picture

### CODE REVIEW

**Review by Xenorith — APPROVED** [review]
did you do a quick search across the docs folder for similar urls?

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
> did you do a quick search across the docs folder for similar urls?

did some manual search in fuse docs...
i previously do this way in fuse docs to directly show graph in github repo (back when the dora doc is not online)

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
