### PR TITLE
change varible mId to final long

### PR DESCRIPTION
**Pull request by wanyy6**
https://alluxio.atlassian.net/browse/ALLUXIO-2296

### CODE REVIEW

**Comment by gpang** [comment]
It looks like your commits on GitHub aren't linked to a valid Github account yet. For us to properly credit your contributions, could you associate your email address to your Github account? You can either [add an email to your github account](https://help.github.com/articles/adding-an-email-address-to-your-github-account/), or [change the email for your commits](http://stackoverflow.com/questions/750172/change-the-author-and-committer-name-and-e-mail-of-multiple-commits-in-git/1320317#1320317).

**Comment by wanyy6** [comment]
@gpang  I have added my email. Thank you.

**Comment by jsimsa** [comment]
Jenkins, ok to test

**Comment by jsimsa** [comment]
LGTM

**Pull request merged**
