### PR TITLE
[DOCFIX] Remove HTML in Overview and Getting Started docs

### PR DESCRIPTION
**Pull request by Xenorith**
@dborkar fysa

### CODE REVIEW

**Comment by Xenorith** [comment]
jenkins, test this please

**Comment by calvinjia** [comment]
Test failures are unrelated and flaky.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to master please.

**Pull request merged**
