### PR TITLE
Remove rocks page store log from PageStoreDir

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes are proposed in this pull request?

This PR aim to fix bug related to a wrong named logger.

### Why are the changes needed?

Correct the logger name.

### CODE REVIEW

**Comment by maobaolong** [comment]
@apc999 This is back ported from master-2.x branch, would you like to take a look at this PR?

**Review by ChunxuTang — APPROVED** [review]
LGTM.

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
