### PR TITLE
[SMALLFIX] Improve directories permission propagation to UFS.

### PR DESCRIPTION
**Pull request by ifcharming**
One TODO still left in `FileDataManager.java` when delegation is turned on, because worker can't easily get the status of a Alluxio directory.

### CODE REVIEW

**Comment by ifcharming** [comment]
@jsimsa @apc999

**Comment by gpang** [comment]
@ifcharming Thanks for the fix! Is there any way to test these 3 ufs dir creations?

**Comment by ifcharming** [comment]
@gpang , I've added some more integration tests to cover the dir permission checks. PTAL

**Comment by jsimsa** [comment]
LGTM

**Comment by gpang** [comment]
Thanks for the fix!

**Comment by gpang** [comment]
LGTM

**Pull request merged**
