### PR TITLE
Give more clear description to bytes and throughput metrics

### PR DESCRIPTION
**Pull request by LuQQiu**
BytesReadAlluxio metrics only represent the remote Alluxio read metrics, modify the description to be clearer.

### CODE REVIEW

**Review by apc999 — APPROVED** [review]

**Review by yuzhu — COMMENTED** [review]
do you  mind changing the metric key name as well? `CLUSTER_BYTES_READ_ALLUXIO` sounds like the total number of bytes read through alluxio.
Also,  I was under the impression that CLUSTER_BYTES_READ_ALLUXIO and CLUSTER_BYTES_READ_DOMAIN could include UFS reads as well? https://github.com/Alluxio/alluxio/blob/master/core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java#L256

**Comment by LuQQiu** [comment]
They didn't include UFS reads, will update the names

**Review by rastogiasr — COMMENTED** [review]
Lu - it is possible to change CLUSTER_BYTES_READ_ALLUXIO to be CLUSTER_BYTES_REMOTE_READ_ALLUXIO and add a CLUSTER_TOTAL_BYTES_READ_ALLUXIO which is the sum of short circuit(or via domain sockets),remote and UFS. The naming of metrics is confusing otherwise.

**Comment by yuzhu** [comment]
checkstyle?

**Comment by LuQQiu** [comment]
@yuzhu Thanks! PTAL

**Review by yuzhu — APPROVED** [review]
LGTM, thanks for fixing this!

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
