### PR TITLE
 [DOCFIX] replace META_INF with META-INF

### PR DESCRIPTION
**Pull request by tilumi**
Extension will not be loaded when putting meta in META_INF, using META-INF is correct

### CODE REVIEW

**Comment by madanadit** [comment]
Thanks @tilumi for your contribution. Can you please sign the CLA?

**Comment by aaudiber** [comment]
@tilumi Please sign the CLA. You can access it at this link: https://cla.alluxio.org/

**Comment by apc999** [comment]
@tilumi Please sign the CLA. You can access it at this link: https://cla.alluxio.org/

**Comment by apc999** [comment]
@tilumi can you sign the CLA and resolve the merge conflict? 
otherwise, we could not merge your PR.

**Comment by ZacBlanco** [comment]
This PR is quite old. I'm going to close it. I think the most recent page is also updated properly.

https://docs.alluxio.io/os/user/stable/en/ufs/Ufs-Extension-API.html

**Pull request closed without merging**
