### PR TITLE
Fix leader master priority always shows 0

### PR DESCRIPTION
**Pull request by bzheng888**
### What changes are proposed in this pull request?
Fix the problem that leader priority always shows 0 when use 'bin/alluxio fsadmin journal quorum info' command get raft information.
### Why are the changes needed?
Shell command shows wrong information about the leader priority.
### Does this PR introduce any user facing changes?
No
Please list the user-facing changes introduced by your change, including
No

### CODE REVIEW

**Review by maobaolong — APPROVED** [review]
Good catch, LGTM, thanks for your contribution!

**Review by ggezer — APPROVED** [review]
Thanks for catching this @bzheng888 !

**Comment by jenoudet** [comment]
Thanks for the fix. Could you merge master into your branch? The test that was failing should be removed from master and so your fix should pass all tests.

**Comment by ggezer** [comment]
@bzheng888 @jenoudet We don't prefer merge commits in PRs. Please remove merge commit and rebase on master.

**Pull request closed without merging**
