### PR TITLE
Switch to console mode from bash for code block

### PR DESCRIPTION
**Pull request by apc999**
Cherrypick PR #9463 from 2.1-SNAPSHOT to 2.0 branch

pr-link: Alluxio/alluxio#9463
change-id: cid-651e28074d70ca09ddc0b5541a158c421feec694

### CODE REVIEW

**Comment by ZacBlanco** [comment]
Were there additional changes that were required to cherry pick this to 2.0?

**Comment by apc999** [comment]
@ZacBlanco resolved conflicts in two files that differ slightly in 2.0 branch and master branch. Otherwise there is no particularly required change

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
