### PR TITLE
Sort sections in pom files

### PR DESCRIPTION
**Pull request by dbw9580**
### What changes are proposed in this pull request?

Sort sections in pom files.

1. A new maven plugin `sortpom` is introduced to sort the pom files.

2. A template file `build/sortpom/alluxio_pom.xml` is used as a reference for the orders of the sections in the pom files. Notably, dependencies will be sorted by their scope first, then by group ID and artifact ID.

3. A build time check is added to validate if the pom files are well sorted. If changes to the pom files will cause them to be unsorted, the sortpom plugin will fail the build with an error. The plugin offers a way to automatically fix unsorted poms by running `mvn sortpom:sort`.

4. Differentiation between internal and external dependencies, is removed. They exist now as comments in the pom files. However, the convention of separating external and internal dependencies is not well observed, and multiple violations occur throughout the codebase. After this PR, the dependencies are sorted lexically, which ensures all Alluxio internal dependencies are always grouped together.

### Why are the changes needed?

A sorted pom file helps reduce merge conflicts, easier to spot duplicate dependencies.

### Does this PR introduce any user facing changes?

No.

### CODE REVIEW

**Comment by dbw9580** [comment]
@yyongycy @apc999 FYI

**Review by Xenorith — APPROVED** [review]
losing the manually grouping of dependencies is not so bad compared to an automatic way to sort everything. and comments embedded within a specific xml block are preserved, so in the worst case, we could paste the group header comments into each applicable dependency if someone insisted that we keep this information

**Comment by yyongycy** [comment]
This is really a good tool, really appreciate. 
Is it enabled all the time in the style check? 
Another question is whether there is a way to detect the redundant dependencies. Not sure if that part can be added.

Following is a trade-off, I don't have too much concern, and most of the time it can be told by the names. 
> Differentiation between internal and external dependencies, is removed. They exist now as comments in the pom files. However, the convention of separating external and internal dependencies is not well observed, and multiple violations occur throughout the codebase. After this PR, the dependencies are sorted lexically, which ensures all Alluxio internal dependencies are always grouped together.

**Comment by dbw9580** [comment]
> Is it enabled all the time in the style check?

Yes, it's run as part of the `validate` phase of every build.

> whether there is a way to detect the redundant dependencies

This is #17896.

**Review by yyongycy — APPROVED** [review]
lgtm

**Comment by dbw9580** [comment]
alluxio-bot, merge this please

**Pull request merged**
