### PR TITLE
[SMALLFIX] Change source code

### PR DESCRIPTION
**Pull request by qunqunqun**
Use static imports for standard test utilities in /alluxio/core/common/src/test/java/alluxio/security/LoginUserTest.java.
Change 'import org.junit.Assert' to 'import static org.junit.Assert.assertNotNull' and 'import static org.junit.Assert.assertEquals'.
AND update relative methods.
AND Put the static imports before non-static imports.

### CODE REVIEW

**Comment by newnius** [comment]
Jenkins, test this please

**Comment by newnius** [comment]
Jenkins, test this please

**Comment by newnius** [comment]
LGTM

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Pull request merged**
