### PR TITLE
Upgrade SpotBugs maven plugin from 3.1.12.2 to 4.0.4

### PR DESCRIPTION
**Pull request by ZacBlanco**

### CODE REVIEW

**Comment by yuzhu** [comment]
there are still some instances of findbugs in our pom.xml. are those needed? can we remove them or replace them?

**Comment by ZacBlanco** [comment]
all instances of `findbugs` were removed in https://github.com/Alluxio/alluxio/pull/10407. Everything is SpotBugs now

**Comment by yuzhu** [comment]
oh i was looking at findbugs-annotations, is there a spotbugs replacement for the annotation package as well?

**Comment by ZacBlanco** [comment]
see edit above

**Comment by yuzhu** [comment]
did ospublish run ok?

**Comment by ZacBlanco** [comment]
Yes, its marked in the spreadsheet

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
