### PR TITLE
[DOCFIX] Add javadoc for ServiceSocketBindIntegrationTest

### PR DESCRIPTION
**Pull request by fanshiqing**

### CODE REVIEW

**Comment by aaudiber** [comment]
Jenkins, test this please

**Comment by aaudiber** [comment]
Jenkins, test this please

**Comment by aaudiber** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
alluxio.master.MasterFaultToleranceIntegrationTest.workerReRegister is flaky in master branch now

**Pull request merged**
