### PR TITLE
Replace anonymous by lambda in AbstractClient.java

### PR DESCRIPTION
**Pull request by Oscilloputer0627**

### CODE REVIEW

**Comment by Oscilloputer0627** [comment]
Jenkins, please test

**Comment by apc999** [comment]
@Oscilloputer0627 can you remove your change on `webui/npm-shrinkwrap.json` from this PR?

**Comment by Oscilloputer0627** [comment]
> @Oscilloputer0627 can you remove your change on `webui/npm-shrinkwrap.json` from this PR?

Yeah, sure but I didn't actually change that

**Comment by Oscilloputer0627** [comment]
> @Oscilloputer0627 can you remove your change on `webui/npm-shrinkwrap.json` from this PR?

must be someone else

**Comment by apc999** [comment]
Can you then overwrite `webui/npm-shrinkwrap.json` by the content of https://raw.githubusercontent.com/Alluxio/alluxio/master/webui/npm-shrinkwrap.json  in order to revert the change in this PR.

Plus, can you sign a contribution license agreement. https://cla.alluxio.org/ ?

**Comment by Oscilloputer0627** [comment]
> Can you then overwrite `webui/npm-shrinkwrap.json` by the content of https://raw.githubusercontent.com/Alluxio/alluxio/master/webui/npm-shrinkwrap.json in order to revert the change in this PR.
> 
> Plus, can you sign a contribution license agreement. https://cla.alluxio.org/ ?

As your instruction sir. I did exactly what you asked

**Comment by Oscilloputer0627** [comment]
Jenkins, please test

**Comment by Oscilloputer0627** [comment]
> Can you then overwrite `webui/npm-shrinkwrap.json` by the content of https://raw.githubusercontent.com/Alluxio/alluxio/master/webui/npm-shrinkwrap.json in order to revert the change in this PR.
> 
> Plus, can you sign a contribution license agreement. https://cla.alluxio.org/ ?

I really didn't see the difference....  webui/npm-shrinkwrap.json  is replaced as you said.

**Comment by apc999** [comment]
@Oscilloputer0627 the pull request becomes now only changing `webui/npm-shrinkwrap.json`. How about creating a new PR changing only `AbstractClient.java`? Feel free to close this  PR

**Comment by Oscilloputer0627** [comment]
> @Oscilloputer0627 the pull request becomes now only changing `webui/npm-shrinkwrap.json`. How about creating a new PR changing only `AbstractClient.java`? Feel free to close this PR
Ok sir, as you wish, thanks for your attention.

**Pull request closed without merging**
