### PR TITLE
[ALLUXIO-2938] Improve javadoc in RetryHandlingMetaMasterClient 

### PR DESCRIPTION
**Pull request by hpnhxxwn**
https://alluxio.atlassian.net/browse/ALLUXIO-2938

### CODE REVIEW

**Comment by hpnhxxwn** [comment]
I have already signed the agreement...

**Comment by hpnhxxwn** [comment]
reevaluate

**Comment by apc999** [comment]
@hpnhxxwn  there might be issues with the license service. would you mind to sign it again
 [sign a contribution license agreement](http://cla.alluxio.org).

**Comment by hpnhxxwn** [comment]
reevaluate

**Pull request merged**
