### PR TITLE
Show progress for taking/applying backups

### PR DESCRIPTION
**Pull request by ggezer**
Fixes https://github.com/Alluxio/alluxio/issues/8979

pr-link: Alluxio/alluxio#9776
change-id: cid-454919455509f5c8df366e556b90db0803b64015

### CODE REVIEW

**Comment by ggezer** [comment]
Jenkins, test this please

**Comment by ggezer** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
