### PR TITLE
Make standby master keep MountTable up-to-date

### PR DESCRIPTION
**Pull request by codings-dan**
### What changes are proposed in this pull request?

Keep the MountTable on the standby master up-to-date before switching to primary.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?
No

### CODE REVIEW

**Comment by codings-dan** [comment]
@maobaolong Could you help take a look at the pull request，thanks in advance!

**Comment by maobaolong** [comment]
@codings-dan Not sure the failed ut related to this PR, just page it here and re-run the test for you.

```
Error: 5.223 [ERROR] Tests run: 5, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 151.235 s <<< FAILURE! - in alluxio.client.cli.job.DistributedCommandsStatsTest
Error: 5.229 [ERROR] alluxio.client.cli.job.DistributedCommandsStatsTest.testAsyncPersistCancelStats  Time elapsed: 31.268 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<Status: [CANCE]LED> but was:<Status: [FAI]LED>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at alluxio.client.cli.job.DistributedCommandsStatsTest.testAsyncPersistCancelStats(DistributedCommandsStatsTest.java:234)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at alluxio.testutils.LocalAlluxioClusterResource$ResetRule$1.evaluate(LocalAlluxioClusterResource.java:320)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by codings-dan** [comment]
@maobaolong Thanks for helping re-run the test, all test have passed, PTAL

**Comment by elega** [comment]
Hi thanks for putting up the PR. I understand the goal of the PR in general and let's discuss offline this Friday.

**Review by elega — APPROVED** [review]

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks for the catch!

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by codings-dan** [comment]
@maobaolong @elega @jiacheliu3 Thanks a lot for reviewing the pull request!

**Pull request merged**
