### PR TITLE
[SMALLFIX] Fix format error in bin/alluxio

### PR DESCRIPTION
**Pull request by lshmouse**
As title~

### CODE REVIEW

**Comment by gpang** [comment]
Thanks for submitting a pull request to Alluxio!

We found your commits on GitHub aren't linked to a valid Github account yet (see your commits at https://github.com/Alluxio/alluxio/pull/3056/commits).

For us to properly credit your contributions, could you please set up your Github account by following the Github instructions https://help.github.com/articles/setting-your-email-in-git/ ?

Thanks!

**Comment by lshmouse** [comment]
Done~  Should I push a new request?

**Comment by gpang** [comment]
@lshmouse maybe closing this and opening a new pull request might work?

**Comment by lshmouse** [comment]
@gpang Thanks ~

**Pull request closed without merging**
