### PR TITLE
Fix helm template

### PR DESCRIPTION
**Pull request by ssz1997**
1. Fuse client has been removed. Remove it from the `helm-generate.sh` script.

2. Global mounts in master template is broken. Copy the format from worker, which works.

### CODE REVIEW

**Comment by ssz1997** [comment]
Need to update chart and changelog

**Review by jiacheliu3 — APPROVED** [review]
LGTM, good to merge after the changelog is updated. Thanks for the improvements!

**Comment by jiacheliu3** [comment]
Also please double check if the Alluxio on k8s doc needs to be updated correspondingly. That can be done in a separate PR.

**Comment by ssz1997** [comment]
> Also please double check if the Alluxio on k8s doc needs to be updated correspondingly. That can be done in a separate PR.

Nothing needs to be updated. Also there's no user-facing change.

**Review by ZhuTopher — APPROVED** [review]

**Comment by ssz1997** [comment]
Error: 4.332 [ERROR] Crashed tests:
Error: 4.332 [ERROR] alluxio.master.AlluxioMasterProcessTest

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
