### PR TITLE
Add Job service metrics

### PR DESCRIPTION
**Pull request by jja725**
### What changes are proposed in this pull request?
add metrics for job service

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

### CODE REVIEW

**Comment by yuzhu** [comment]
@jja725 sorry this one was forgetten, could you fix the conflict and the rest looks good.

**Comment by jja725** [comment]
> @jja725 sorry this one was forgetten, could you fix the conflict and the rest looks good.

resolved, PTAL!

**Comment by yuzhu** [comment]
before we have automated tests for metrics, what kind of manual testing did you do for this? @jja725

**Comment by jja725** [comment]
> before we have automated tests for metrics, what kind of manual testing did you do for this? @jja725
I just run my unit test one by one(It passed test when running individually but would fail if running together). Also, I try to submit distributedLoad requests and check the metrics

**Review by yuzhu — APPROVED** [review]
LGTM

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
