### PR TITLE
Implement fuse flush function

### PR DESCRIPTION
**Pull request by Binyang2014**

### CODE REVIEW

**Review by apc999 — APPROVED** [review]

**Comment by LuQQiu** [comment]
@Binyang2014 This PR is still useful, could you solve the conflicts and update the PR?

**Comment by Binyang2014** [comment]
@LuQQiu Do I need to wait for your PR: https://github.com/Alluxio/alluxio/pull/13113 merge back to master?

**Comment by LuQQiu** [comment]
That PR merges Master into a feature branch and is unrelated to this PR.

**Review by LuQQiu — APPROVED** [review]
LGTM！ Thanks for resolving the conflicts and implement the fuse flush!

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
