### PR TITLE
Remove webui unit tests

### PR DESCRIPTION
**Pull request by bradyoo**
There are no webui unit tests.

### CODE REVIEW

**Comment by bradyoo** [comment]
@yuzhu This is a fairly easy one. Can you take a look?

**Comment by gpang** [comment]
I think I split up the webui intentionally, because then we don't have to build the webui in some cases. Do we want to force all the runs to build the webui?

**Comment by bradyoo** [comment]
It's a small addition to the beginning of the test for the unit tests and in return you don't need another. The reality is that technically, I don't even need to include webui in the other one because there are 0 webui unit tests and build/checkstyle should cover the case anyways.

**Comment by gpang** [comment]
hrmmm, I see. Yeah, it looks like we don't even need to add it back to the other ones. This should be good then. Thanks!

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Pull request merged**
