### PR TITLE
[SMALLFIX] Update Fingerprint.java

### PR DESCRIPTION
**Pull request by MhDang**
Add @Nullable annotation if the method may return null in /alluxio/core/common/src/main/java/alluxio/underfs/Fingerprint.java

### CODE REVIEW

**Comment by aaudiber** [comment]
@MhDang the `@Nullable` change looks good. Can you revert the changes to npm-shrinkwrap.json?

**Comment by MhDang** [comment]
@aaudiber Hi, thanks for your advice. The changes in npm-shrinkwrap.json are due to I run "mvn clean install -DskipTests" in my local machine, and I get SUCCESS. If I revert the changes to npm-shrinkwarp.json, I will get "Merged build finished. Test FAILed." You can see my first commit.

**Comment by aaudiber** [comment]
@MhDang The failing test looks unrelated to npm. Can you try again without the shrinkwrap changes?

**Comment by MhDang** [comment]
@aaudiber Hello, it works this time. Thanks a lot for your guidance.

**Comment by aaudiber** [comment]
alluxio-bot, merge this please

**Pull request merged**
