### PR TITLE
[DOCFIX] Update documentation for ls command

### PR DESCRIPTION
**Pull request by peisun1115**

### CODE REVIEW

**Comment by peisun1115** [comment]
@calvinjia

**Comment by calvinjia** [comment]
alluxio-bot, check this please.

**Comment by calvinjia** [comment]
LGTM

**Comment by gpang** [comment]
this looks good, but should this go to branch-1.2?

**Comment by peisun1115** [comment]
@gpang moved to https://github.com/Alluxio/alluxio/pull/3693

**Pull request closed without merging**
