### PR TITLE
Fix docGen and update config/metrics

### PR DESCRIPTION
**Pull request by LuQQiu**
### What changes are proposed in this pull request?

Fix docGen and update configuration/metrics

### Why are the changes needed?

Otherwise propertykey and metrics are outdated

### Does this PR introduce any user facing changes?

Yes, docs

### CODE REVIEW

**Comment by LuQQiu** [comment]
@apc999 @beinan @HelloHorizon needed to run `docGen` for each release to update configuration/metrics. I will also update the release doc, thanks

**Comment by LuQQiu** [comment]
@Xenorith PTAL, thanks

**Review by Xenorith — APPROVED** [review]

**Review by Limuzhou — APPROVED** [review]

**Comment by LuQQiu** [comment]
Thanks for reviewing!

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
