### PR TITLE
Revert "[ALLUXIO-1749] Make thrift largest frame size adjustable"

### PR DESCRIPTION
**Pull request by apc999**
Reverts Alluxio/alluxio#2784

I don't really see the difference in thrift transport frame size between 0.9.2 and 0.9.3 
(see:
https://github.com/apache/thrift/blob/0.9.2/lib/java/src/org/apache/thrift/transport/TFramedTransport.java#L30 and
https://github.com/apache/thrift/blob/0.9.3/lib/java/src/org/apache/thrift/transport/TFramedTransport.java#L30)

This size was larger in earlier version (https://github.com/apache/thrift/blob/0.7.x/lib/java/src/org/apache/thrift/transport/TFramedTransport.java)

@pfxuan , could you provide more information on your previous PR (ALLUXIO-1749)

### CODE REVIEW

**Comment by apc999** [comment]
this PR @pfxuan mentioned is really for thrift-0.8, not for thrift-0.9.3
https://issues.apache.org/jira/browse/THRIFT-1205

**Comment by pfxuan** [comment]
@apc999, I'm not sure this PR is a correct approach to solve the thrift frame size related exceptions. But it works for current issues. The followings are two examples to reproduce the problem:

1) Run some MapReduce workloads atop Alluxio cluster. e.g. load K-means or TestDFSIO workloads. 
2) One of Alluxio' users met a similar issue recently: https://groups.google.com/forum/?fromgroups#!searchin/alluxio-users/frame$20size$20/alluxio-users/CZc1mhWmAZc/ywhb1Hx5AwAJ

**Comment by apc999** [comment]
thanks @pfxuan for the quick feedback. To better understand the MapReduce workloads, could you describe which hadoop version you are using, and which jar file from Alluxio you put into hadoop class path?  

I suspect the root cause is because the server side is using a different version of thrift than the client side (for some reason). It could be classpath setting, or it could be some wrong POM setting. My concern for the previous PR you provide is that only setting the max frame size might not cover all cases if there is indeed version mismatch. It will be helpful if you could provide more info for me to reproduce the problem. 

Thanks

**Comment by pfxuan** [comment]
@apc999, it looks I can not reproduce this issue anymore. Like you said, the problem should be caused by mismatched thrift version at client and server sides. 

To systematically detect and investigate such subtle issues, we probably need to apply some real workloads atop of Alluxio cluster with different configurations. I happened to create JIRA issue recently: [ALLUXIO-1802](https://alluxio.atlassian.net/browse/ALLUXIO-1802) and will try to build a simple prototype, called alluxio-smoke-tests, at: https://github.com/pfxuan/alluxio-smoke-tests. I hope it can save our time for reproducing those subtle issues.

**Comment by calvinjia** [comment]
@apc999 could we open this to branch-1.0 as well?

**Comment by apc999** [comment]
@calvinjia  will do

**Comment by apc999** [comment]
@calvinjia Conflicts resolved, PTAL

**Comment by apc999** [comment]
@calvinjia  the patch to branch-1.0 is here
https://github.com/Alluxio/alluxio/pull/2881

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
