### PR TITLE
[SMALLFIX] Use static imports for standard test utilities in PairTest

### PR DESCRIPTION
**Pull request by captainzmc**
fix https://github.com/Alluxio/new-contributor-tasks/issues/502

### CODE REVIEW

**Review by maobaolong — APPROVED** [review]
Thanks for your contribution, LGTM for this improvement, look forward for your further contribution start from this.

**Comment by captainzmc** [comment]
> Thanks for your contribution, LGTM for this improvement, look forward for your further contribution start from this.

Thanks for @maobaolong’s  review. This is my first PR at Alluxio.

**Review by gpang — APPROVED** [review]
@captainzmc Thanks for your contribution!

LGTM

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
