### PR TITLE
Add missing category in metrics docs generation

### PR DESCRIPTION
**Pull request by lucyge2022**
### What changes are proposed in this pull request?

Missing "proxy" in the defined categories to generate metrics csv/yaml

### Why are the changes needed?

bin/alluxio docGen will not dump NPE

### Does this PR introduce any user facing changes?
N/A

### CODE REVIEW

**Comment by Xenorith** [comment]
can you point out which PR/commit introduced this problem if you have that information?

**Comment by Xenorith** [comment]
suggest to rename PR to be more descriptive; ex. `Add missing category in metrics docs generation`

**Comment by lucyge2022** [comment]
> 

latest modification seems to be this commit, but it wasn't removing 'proxy', not sure if the proxy category wasn't there at that time or proxy metrics doc was added some time later and wasn't added into the category. Any insights @LuQQiu ?    https://github.com/Alluxio/alluxio/commit/1384aeb0e6877c9ac00ea683beebf349983318ba

**Comment by lucyge2022** [comment]
> suggest to rename PR to be more descriptive; ex. `Add missing category in metrics docs generation`

done

**Comment by lucyge2022** [comment]
> can you point out which PR/commit introduced this problem if you have that information?

latest modification seems to be this commit, but it wasn't removing 'proxy', not sure if the proxy category wasn't there at that time or proxy metrics doc was added some time later and wasn't added into the category. Any insights @LuQQiu ?    https://github.com/Alluxio/alluxio/commit/1384aeb0e6877c9ac00ea683beebf349983318ba

**Comment by Xenorith** [comment]
oh i had thought you did a bisect between good/bad commits and found the offending one. my guess would be that there is an addition or modification of a metric that ended up being categorized under proxy, but since it wasn't listed -> error.

i'd like to understand the underlying reason of how this happened to be able to prevent any future occurrences from happening. for example, is there better source for listing the possible categories than to write them as a list of strings as they currently are?

**Comment by lucyge2022** [comment]
> oh i had thought you did a bisect between good/bad commits and found the offending one. my guess would be that there is an addition or modification of a metric that ended up being categorized under proxy, but since it wasn't listed -> error.
> 
> i'd like to understand the underlying reason of how this happened to be able to prevent any future occurrences from happening. for example, is there better source for listing the possible categories than to write them as a list of strings as they currently are?

so this generate() func is trying to prepare a cvs and yml writer based on possible categories that our metrics key names might have, since all metrics key will have the form of  <metric_group>.<metric_name> (such as Cluster.metrics1 Proxy.metric2 ...) , I can get rid of the CATEGORY definition, and based on all the metrics key and extrapolate the categories from there?

**Comment by Xenorith** [comment]
dynamically determining the list of categories from the existing metric keys seems preferable, even if it's a bit slower to generate

**Comment by lucyge2022** [comment]
> dynamically determining the list of categories from the existing metric keys seems preferable, even if it's a bit slower to generate

done

**Review by Xenorith — APPROVED** [review]

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Pull request merged**
