### PR TITLE
Update pom.xml to use correct version

### PR DESCRIPTION
**Pull request by ZacBlanco**

### CODE REVIEW

**Comment by ZacBlanco** [comment]
@calvinjia 

@madanadit

**Comment by calvinjia** [comment]
@ZacBlanco Thanks, do you mind also updating the other places which need it? (libexec, Dockerfile, k8s templates, doc config?)

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please.

**Comment by ZacBlanco** [comment]
This already targeted branch-2.0

**Pull request merged**
