### PR TITLE
[DOCFIX] Update Caching.md

### PR DESCRIPTION
**Pull request by tomscut**
Correct typos for Caching.md.

### CODE REVIEW

**Comment by tomscut** [comment]
Hi @maobaolong , could you please take a look. Thanks you.

**Review by maobaolong — APPROVED** [review]
Thanks for the improvement, it look good to me. Look forward to see your further contribution start with this.

**Comment by tomscut** [comment]
> Thanks for the improvement, it look good to me. Look forward to see your further contribution start with this.

Thanks @maobaolong for your review and encouragement.

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by tomscut** [comment]
Thanks @apc999 for the review.

**Pull request merged**
