### PR TITLE
Add local read benchmarks for PagedBlockStore

### PR DESCRIPTION
**Pull request by YangchenYe323**
### What changes are proposed in this pull request?
Added benchmarks for `PagedBlockStore` that read from local storage rather than UFS. 

### Why are the changes needed?
This piece is missing as `PagedBlockStore` didn't support creating local blocks then.

### Does this PR introduce any user facing changes?
No.

### CODE REVIEW

**Comment by YangchenYe323** [comment]
@beinan @dbw9580 Would you like to take a look? Should be pretty quick.

**Review by dbw9580 — APPROVED** [review]
LGTM, thanks!

**Comment by shangxinli** [comment]
Any benchmarking number you can share?

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
