### PR TITLE
Port changes from [#10384] to branch-2.1

### PR DESCRIPTION
**Pull request by jiacheliu3**
The original PR corrects `Chart.yaml` key `apiVersion` in Helm Chart.

pr-link: Alluxio/alluxio#10384
change-id: cid-cf15b0fd4caeee8b16cb68852f25ee55654fccd6

### CODE REVIEW

**Comment by jiacheliu3** [comment]
alluxio-bot, test this please

**Comment by jiacheliu3** [comment]
alluxio-bot, test this please

**Comment by ZacBlanco** [comment]
@jiacheliu3 do we need to update `docs/config.yml`?

**Comment by jiacheliu3** [comment]
@ZacBlanco yea...That should be done in a separate PR and can be cherry-picked by alluxio-bot.

**Comment by madanadit** [comment]
@jiacheliu3 @ZacBlanco Yes, I wanted the config change in a separate PR as well. The tricky part there is that branch-2.1 docs are used for released 2.1 (which is on version 0.5.1) :-(

**Comment by jiacheliu3** [comment]
@madanadit Do you mind merging this?

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Pull request merged**
