### PR TITLE
Reduce spammy logs

### PR DESCRIPTION
**Pull request by gpang**
These log messages can be very spammy, so use the sampling logger.

pr-link: Alluxio/alluxio#9709
change-id: cid-749e87e3dec96958e9513b5c77155500c7c0f426

### CODE REVIEW

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
Maybe late to comment on a cherry-pick PR:
- I suggest to create a `AlluxioLogger` implementing log4j `Logger` interface, and use our factory to get the logger `LoggerFactory.getLogger`. In this new Logger, you can specify the sampling rate as a overriding method, e.g.,

`LOG.sampleDebug(sampleRate, "Unexpected exception encountered when starting a replication / eviction job (uri={})", uri);`

**Comment by calvinjia** [comment]
@apc999 I'm going to merge this PR for now. In parallel we can consider whether or not to change our sampling logger strategy in a separate issue.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Pull request merged**
