### PR TITLE
Fix AlluxioJniFuseFileSystemTest

### PR DESCRIPTION
**Pull request by secfree**
### What changes are proposed in this pull request?

Fix AlluxioJniFuseFileSystemTest and enable it.

Fixed test cases
- create
- write
- flush

### Why are the changes needed?

Currently AlluxioJniFuseFileSystemTest is still ignored and there are three cases failing if testing them after #15983 and #16011

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Comment by HelloHorizon** [comment]
Ping @LuQQiu @ssz1997

**Comment by LuQQiu** [comment]
@LuQQiu ping myself for making sure tests passed

**Review by yyongycy — APPROVED** [review]
LGTM

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Pull request merged**
