### PR TITLE
[ALLUXIO-2306]Improved javadoc in LeaderSelectorClient (member variables) 

### PR DESCRIPTION
**Pull request by XinyuYAN**
https://alluxio.atlassian.net/browse/ALLUXIO-2306

### CODE REVIEW

**Comment by XinyuYAN** [comment]
alluxio-bot, check this please

**Comment by XinyuYAN** [comment]
alluxio-bot, check this please

**Comment by gpang** [comment]
@XinyuYAN Thanks for the PR! It looks like your commits are not associated with your github account. You can change the email address on your commits with [these instructions](http://stackoverflow.com/questions/750172/change-the-author-and-committer-name-and-e-mail-of-multiple-commits-in-git/1320317#1320317).

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Pull request merged**
