### PR TITLE
Remove dependency: commons-lang 2.x and commons-httpclient 3.x

### PR DESCRIPTION
**Pull request by witgo**
Remove the older versions of these libraries, since it is not a good practice to use different versions of commons-lang and httpclient in the same project.

### CODE REVIEW

**Comment by witgo** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
@witgo  can you provide a bit more information in the motivation of this change? It will help us decide the priority of the change

**Comment by witgo** [comment]
It is not a good practice to use different versions of commons-lang and httpclient in the same project.

**Comment by witgo** [comment]
ping @apc999 @madanadit

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by witgo** [comment]
ping

**Comment by witgo** [comment]
ping @gpang  @apc999

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by witgo** [comment]
@gpang   could you please take a look this ?

**Comment by witgo** [comment]
ping

**Comment by witgo** [comment]
@ZacBlanco Can you take a look?

**Comment by yuzhu** [comment]
@witgo I have tagged @bradyoo who is changing a lot of dependency versions as part of the effort to support java 11. I just want both of you to be aware of each other's effort.

**Comment by bradyoo** [comment]
This one looks good to me. I have been avoiding all the large-ish code switching efforts altogether. Really sad about needing to urlencode one of the / but otherwise fine. LGTM. We should actually merge this. @yuzhu mind merging it?

**Pull request merged**
