### PR TITLE
Fix UI Overview page error when journal file type is nfs

### PR DESCRIPTION
**Pull request by packageman**
### What changes are proposed in this pull request?

Add `mDiskType` property in class JournalDiskInfo.java and compose a complete disk path with schema based on disk type.

### Why are the changes needed?

Fix https://github.com/Alluxio/alluxio/issues/14915

### Does this PR introduce any user facing changes?

No.

### CODE REVIEW

**Comment by packageman** [comment]
> Hi @packageman, please fix the style issues before we can review your PR. You can run `mvn checkstyle:checkstyle` to investigate these issues.

@jenoudet Fixed.

**Comment by packageman** [comment]
@jenoudet I rebased my PR and run tests locally and all passed. Please help to run the tests again.

**Comment by HelloHorizon** [comment]
@jenoudet @tcrain can you take a look?

**Comment by packageman** [comment]
> @jenoudet @tcrain can you take a look?

@jenoudet @tcrain Is there any updates on this PR?

**Comment by jenoudet** [comment]
```
Error: 1.714 [ERROR] Errors: 
Error: 1.714 [ERROR] alluxio.client.cli.JournalToolTest.dumpHeapCheckpointFromEmbeddedJournal
Error: 1.715 [ERROR]   Run 1: JournalToolTest.dumpHeapCheckpointFromEmbeddedJournal » Runtime java.lang.Runt...
Error: 1.715 [ERROR]   Run 2: JournalToolTest.dumpHeapCheckpointFromEmbeddedJournal » Runtime java.lang.Runt...
```

**Comment by packageman** [comment]
@jenoudet Could you please take a look at this PR?

**Review by jenoudet — APPROVED** [review]

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Pull request merged**
