### PR TITLE
[ALLUXIO-2946] Throw more fine-grained exceptions in RPC client calls

### PR DESCRIPTION
**Pull request by gurmeetb**
https://alluxio.atlassian.net/browse/ALLUXIO-2946

### CODE REVIEW

**Comment by yupeng9** [comment]
@gurmeetb thanks for the improvement. Can you resolve the conflicts?

**Comment by gurmeetb** [comment]
@yupeng9 Did the merge with resolving conflicts, but it still shows as conflict since we change IOException to AlluxioStatusException as per JIRA. We will need to ignore this conflict and merge latest from branch ALLUXIO-2946. 

Kindly suggest if you see issues around same.

**Comment by yupeng9** [comment]
@gurmeetb can you merge master? It should fix the failing tests.

**Comment by yupeng9** [comment]
@gurmeetb hey can you resolve the conflicts again?

**Comment by gurmeetb** [comment]
@yupeng9 Sure, just did it, I see Jenkins is still running. Hope this time we are able to merge before we merge other pull request to master for same file.

**Comment by apc999** [comment]
@aaudiber is this change of public API break any compatibility? e.g., new Alluxio client app code will not compile with Alluxio 1.6 or earlier, is it ok?

**Comment by yupeng9** [comment]
@apc999 I feel it's fine because `AlluxioStatusException ` extends `IOException`. So the apps that catch `IOException` can also catch `AlluxioStatusException`

**Comment by aaudiber** [comment]
I think the change is fine. Users should be using the `FileSystem` interface, not going through `FileSystemMasterClient` directly. We annotate `FileSystem` as `@PublicApi`, but not `FileSystemMasterClient`. Even if they were using `FileSystemMasterClient`, their usage won't break unless they were trying to catch a subclass `IOException` that isn't a subclass of `AlluxioStatusException`.

**Pull request merged**
