### PR TITLE
[SMALLFIX] Check file equality by comparing URI

### PR DESCRIPTION
**Pull request by dbw9580**
Fixes alluxio/new-contributor-tasks#594.

### CODE REVIEW

**Comment by apc999** [comment]
@maobaolong  can you elaborate why we have this fix?
Is it because `files[0].getPath()` may return null?

**Comment by LuQQiu** [comment]
@maobaolong

**Comment by yyongycy** [comment]
so this change is pending due to the check error shown in above comment, is it?

**Comment by maobaolong** [comment]
because the authority of default uri could be different with the current one, and if the authority is null, it may be "null", so we don't care the authority but the path.

**Comment by apc999** [comment]
close as this PR for now as it is duplicated from https://github.com/Alluxio/alluxio/pull/13560

**Pull request closed without merging**
