### PR TITLE
Update checkConsistency to compare fingerprint

### PR DESCRIPTION
**Pull request by madanadit**
Compare fingerprint instead of just length: https://alluxio.atlassian.net/browse/ALLUXIO-3363

Replacement for #8588

### CODE REVIEW

**Comment by madanadit** [comment]
jenkins, test this please

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please.

**Comment by calvinjia** [comment]
@tahakashaf @madanadit Thank you for fixing this!

**Pull request merged**
