### PR TITLE
[DOCFIX] Update Documentation-Conventions

### PR DESCRIPTION
**Pull request by gpang**

### CODE REVIEW

**Comment by gpang** [comment]
@calvinjia

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by jiacheliu3** [comment]
One possible improvement maybe is to change the multiline in Terminology Table header row to one line by increasing the column width. 

`| Correct, preferred term |`

This cell will be wrapped into 3 lines.

However it's not well supported in markdown [stackoverflow discussion](https://stackoverflow.com/questions/36121672/set-table-column-width-via-markdown). We could do this by using HTML for this table but this arguably breaks the conciseness of this documentation page. @gpang What's your view on this?

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please.

**Pull request merged**
