### PR TITLE
[DOCFIX] Fix alluxio presto sandbox docs

### PR DESCRIPTION
**Pull request by Xenorith**

### CODE REVIEW

**Comment by Xenorith** [comment]
please help merge and cherry pick to 2.2 branch @ZacBlanco

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Comment by ZacBlanco** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please

**Comment by Xenorith** [comment]
@ZacBlanco can i borrow your powers again to cherry pick this to branch 2.1?

**Comment by ZacBlanco** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please

**Pull request merged**
