### PR TITLE
[DOCFIX] Remove rolling upgrade from docs

### PR DESCRIPTION
**Pull request by Xenorith**
the rolling upgrade feature is for limited experimental use currently with many limitations. we may bring back the docs in a future version when it is more widely applicable to various user scenarios.

### CODE REVIEW

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks!

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.10 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Pull request merged**
