### PR TITLE
[SMALLFIX] Increase heartbeat timeout to 1min

### PR DESCRIPTION
**Pull request by peisun1115**
When i drive Alluxio with many concurrent writers, 10 seconds become not enough.

### CODE REVIEW

**Comment by peisun1115** [comment]
@calvinjia

**Comment by calvinjia** [comment]
@peisun1115 thanks for the fix, is there any way to ensure the heartbeat has priority?

**Comment by peisun1115** [comment]
@calvinjia I think heartbeat in the current implementation has higher priority in a sense that it won't be blocked by other RPCs in the same connection.

We can ensure priority if we implement some flow control (or scheduling) on the RPCs.

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
