### PR TITLE
Add alias option for tieredstore levels

### PR DESCRIPTION
**Pull request by hamzabll5858**
Alluxio worker container generated exception when it wont find alias option in configuration. Currently null value is passed to alluxio worker container and it generated exception. I have added the alias value for levels in tieredstore.

### CODE REVIEW

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Comment by madanadit** [comment]
@hamzabll5858 Please sign the CLA, thx.

**Comment by hamzabll5858** [comment]
alluxio-bot, merge this please.

**Comment by jiacheliu3** [comment]
@madanadit Do you mind merging this one? Thanks!

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Pull request merged**
