### PR TITLE
Add logs for FileSystemContext life-cycle

### PR DESCRIPTION
**Pull request by ggezer**

### CODE REVIEW

**Comment by madanadit** [comment]
```
Tests in error: 
alluxio.server.ft.journal.MultiMasterJournalTest.testCheckpointReplay(alluxio.server.ft.journal.MultiMasterJournalTest)
  Run 1: MultiMasterJournalTest.before:53 » IO java.util.concurrent.TimeoutException: T...
  Run 2: MultiMasterJournalTest.testCheckpointReplay:64 » IO java.util.concurrent.Timeo...
```

**Comment by madanadit** [comment]
alluxio-bot, test this please.

**Comment by ggezer** [comment]
alluxio-bot, merge this please

**Comment by ggezer** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please

**Pull request merged**
