### PR TITLE
[ALLUXIO-1739] Use Alluxio Worker for DataServerHandler

### PR DESCRIPTION
**Pull request by calvinjia**
Since we've moved the dataserver to be at the Alluxio Worker level, we should pass the Alluxio worker instead of the block worker.

### CODE REVIEW

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by jsimsa** [comment]
LGTM

**Comment by gpang** [comment]
LGTM

**Pull request merged**
