### PR TITLE
[SMALLFIX] fixing encoding of strings in REST API endpoints

### PR DESCRIPTION
**Pull request by jsimsa**
This PR works around a limitation in the Jackson framework, which fails to properly encode String return values as JSON.

### CODE REVIEW

**Comment by calvinjia** [comment]
@jsimsa Thanks for the patch, is there a way to enforce the return values are encoded as JSON?

**Comment by jsimsa** [comment]
AFAIK, not programmatically (other than writing proper tests) ... the reason is that the Jackson framework has the last say in what gets sent over the wire

**Comment by uronce-cc** [comment]
LGTM

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
