### PR TITLE
Upgrade zookeeper from 3.5.5 to 3.5.8

### PR DESCRIPTION
**Pull request by bradyoo**
Note that hive has a dependency on zookeeper that is pinned to 3.4.6 at the moment

We are still waiting for hive to be java compatible and it will be dealt with then.

Otherwise, all the dependencies seems to be from alluxio itself making this minor upgrade.

### CODE REVIEW

**Comment by bradyoo** [comment]
https://github.com/apache/zookeeper/commit/4de5f012a56e26d72bcddf782995849d7a9e7cfd change from 3.5.5 to 3.5.6 was causing conflicts with netty-all dependency that we have. So this fixes that. Though if we are interested in bringing down our client jar size a little. This will be a low hanging fruit.. (10~15% savings)

**Comment by bradyoo** [comment]
For now, doing an upgrade to 3.5.8 because upgrading to 3.6.0+ runs into the following error

testNoParticipant(alluxio.master.ZkMasterInquireClientTest)  Time elapsed: 50.004 sec  <<< ERROR!
java.lang.IllegalStateException: Timed out waiting for watch removal
	at org.apache.curator.test.TestingZooKeeperMain.blockUntilStarted(TestingZooKeeperMain.java:146)
	at org.apache.curator.test.TestingZooKeeperServer.start(TestingZooKeeperServer.java:167)
	at org.apache.curator.test.TestingServer.<init>(TestingServer.java:117)
	at org.apache.curator.test.TestingServer.<init>(TestingServer.java:100)
	at org.apache.curator.test.TestingServer.<init>(TestingServer.java:87)
	at alluxio.master.ZkMasterInquireClientTest.before(ZkMasterInquireClientTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

I think this is happening because I need https://github.com/apache/curator/pull/334 (requires upgrade to curator).

**Comment by yuzhu** [comment]
> I think this is happening because I need [apache/curator#334](https://github.com/apache/curator/pull/334) (requires upgrade to curator).
Is this something we plan to do in the future? upgrading our curator dependency?

**Comment by bradyoo** [comment]
Yes. We absolutely will be upgrading curator later @yuzhu

**Comment by bradyoo** [comment]
Ping. @yuzhu

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
