### PR TITLE
Fix Unmount failure by Alluxio FUSE

### LINKED ISSUE #9461: Umount failed by Alluxio FUSE
**Alluxio Version:**
2.0

**Describe the bug**
Umount Alluxio FUSE mount point failed, while there is no other process occupy this mount point.
```
\# umount /mnt/alluxio-fuse/
umount: /mnt/alluxio-fuse: target is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))
```

**To Reproduce**
loop execution:
```
alluxio-fuse mount -o allow_other /mnt/alluxio-fuse/ /
touch /mnt/alluxio-fuse/mount-test/mount-test
umount /mnt/alluxio-fuse/
```

### PR DESCRIPTION
**Pull request by liuhongtong**
Fix #9461

If umount an Alluxio FUSE mount point,
fs.mount() returns without any exception.
but fs.umount() will conflict with the running umount command,
that results in "target is busy" error and umount command failing.

Signed-off-by: liuhongtong <hongtongliu@126.com>

### CODE REVIEW

**Comment by liuhongtong** [comment]
@apc999 I have added comment. PTAL.
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.536 sec <<< FAILURE! - in alluxio.master.AlluxioMasterProcessTest
startStopPrimary(alluxio.master.AlluxioMasterProcessTest)  Time elapsed: 1.948 sec  <<< FAILURE!
java.lang.AssertionError
	at alluxio.master.AlluxioMasterProcessTest.startStopTest(AlluxioMasterProcessTest.java:97)
	at alluxio.master.AlluxioMasterProcessTest.startStopPrimary(AlluxioMasterProcessTest.java:73)

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-1.8 please

**Pull request merged**
