### PR TITLE
Add getStatus RESTful API

### PR DESCRIPTION
**Pull request by JiamingMai**
Add getStatus RESTful API.

**Example:**
Get the specified directory/file information by the following request:
`curl -X GET http://localhost:28080/v1/info?path=/tpcds-data`

The response JSON looks like:
`[
  {
    "mType": "directory",
    "mName": "tpcds-data",
    "mPath": "/tpcds-data",
    "mUfsPath": "s3a://jiamingmai-test/tpcds-data",
    "mLastModificationTimeMs": 0,
    "mLength": 0,
    "mHumanReadableFileSize": "0B"
  }
]`

image

### CODE REVIEW

**Comment by LuQQiu** [comment]
@JiamingMai Thanks for adding the API call! Could you help support the full ufs path similar to listdir files RESTful API?
From Python perspective, we always provide the full ufs path as path parameter, thanks!

**Comment by JiamingMai** [comment]
> @JiamingMai Thanks for adding the API call! Could you help support the full ufs path similar to listdir files RESTful API? From Python perspective, we always provide the full ufs path as path parameter, thanks!

This API also supports full UFS path as path parameter.

**Review by LuQQiu — APPROVED** [review]
LGTM! Thanks for supporting the feature

**Comment by JiamingMai** [comment]
alluxio-bot, merge this please.

**Pull request merged**
