### PR TITLE
[ALLUXIO-1786] update function to isEmpty()

### PR DESCRIPTION
**Pull request by YunLi1988**

### CODE REVIEW

**Comment by gpang** [comment]
Thanks for this PR! It looks like your commits aren't linked to a valid Github account yet (see your commits at https://github.com/Alluxio/alluxio/pull/2874/commits) where your icon is gray. 
For us to properly credit your contributions, could you please set up your Github account by following the Github instructions here:

https://help.github.com/articles/setting-your-email-in-git/

**Comment by YunLi1988** [comment]
@gpang have updated my email address. PHAL!

**Comment by calvinjia** [comment]
LGTM

**Comment by apc999** [comment]
@YunLi1988 it seems from https://github.com/Alluxio/alluxio/pull/2874/commits , your commits in this PR are still not linked to your correct github account (you can see the gray cat icon). It will be great if you can try closing this PR and reopen a new PR once you have set up your email in git. If this sounds too much trouble, feel free to let us know and I will merge this PR (it looks great!) still. 

Thanks

**Comment by YunLi1988** [comment]
Hi Bin,

I have set up my email, but I am not sure how to close this PR and reopen
it. :P Can you please let me know how to do that?

Thanks,
Yun

**Comment by apc999** [comment]
@YunLi1988 , I can close this PR. And you can simply repeat your previous procedure to create an identical PR again.

**Comment by apc999** [comment]
you probably don't want to reopen, but simply submit a new PR.

**Comment by YunLi1988** [comment]
Hi Bin,

I have create a new PR. However it looks the submit is still not linked to
my git account. :P Can you have a look at one more time?

Thanks,
Yun

**Pull request closed without merging**
