### PR TITLE
[ALLUXIO-2663] Make the class 'ConutingRetryTest' final.

### PR DESCRIPTION
**Pull request by zhangweiwei0422**

### CODE REVIEW

**Comment by yupeng9** [comment]
@zhangweiwei0422 thanks for the contribution. Can you sign the CLA?.

**Comment by yupeng9** [comment]
@zhangweiwei0422 feel free to reopen this PR after you sign CLA

**Comment by zhangweiwei0422** [comment]
#6123

**Comment by zhangweiwei0422** [comment]
@yupeng9 Sorry, I did'nt see this until now. Will you plesase Open this PR?

**Pull request closed without merging**
