### PR TITLE
Use the s3a as property key name prefix for s3 compatible object stores

### LINKED ISSUE #8962: S3 compatible object stores should not use property names aws.*
**Is your feature request related to a problem? Please describe.**
when mounting an s3a compatible object store like ceph, we use a mount command similar to 

./bin/alluxio fs mount --option aws.accessKeyId=<CEPH_ACCESS_KEY_ID> --option aws.secretKey=<CEPH_SECRET_ACCESS_KEY>\
  --option alluxio.underfs.s3.endpoint=<HTTP_ENDPOINT> --option alluxio.underfs.s3.disable.dns.buckets=true \
  --option alluxio.underfs.s3a.inherit_acl=false /mnt/ceph s3a://<BUCKET>/<FOLDER>

This command refers to credentials as aws.accessKeyId and aws.secretKey even when not using aws. 

**Describe the solution you'd like**
We should create an alias for the property as alluxio.underfs.s3a.accessKeyId

**Describe alternatives you've considered**
-

**Urgency**
-

**Additional context**
-

### PR DESCRIPTION
**Pull request by qian0817**
### What changes are proposed in this pull request?

Fix #8962.

### Why are the changes needed?

See #8962.

### Does this PR introduce any user facing changes?

add property key `s3a.accessKeyId` and `s3a.secretKey`.

### CODE REVIEW

**Comment by HelloHorizon** [comment]
@apc999 I remembered that you make a change to allow the user to ignore the difference between s3:// and s3a:// schema when doing mount. Can you take a look at this pr?

**Comment by HelloHorizon** [comment]
@yyongycy can you take a look?

**Review by yyongycy — APPROVED** [review]
LGTM

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Pull request merged**
