### PR TITLE
Sort part files for uploading

### PR DESCRIPTION
**Pull request by Haoning-Sun**
### What changes are proposed in this pull request?

Merge the upload part files in the requested order.

### Why are the changes needed?

The checksum of the file uploaded by multipart is different from that of the original file.

### Does this PR introduce any user facing changes?

No.

### CODE REVIEW

**Comment by yyongycy** [comment]
Please @Jackson-Wang-7 help review

**Comment by yyongycy** [comment]
Please provide the test you had done. and paste the result here.

**Comment by Haoning-Sun** [comment]
@yyongycy I found the code for sorting the list in an earlier version, maybe this line was deleted by mistake when modifying. I re-added the original code.

**Comment by Jackson-Wang-7** [comment]
> @yyongycy I found the code for sorting the list in an earlier version, maybe this line was deleted by mistake when modifying. I re-added the original code.

I think so, the latest modification looks better

**Review by Jackson-Wang-7 — APPROVED** [review]

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Pull request merged**
