### PR TITLE
[DOCFIX] Remove redundant method names

### PR DESCRIPTION
**Pull request by LiuJiahao0001**
Fixes [Alluxio/new-contributor-tasks#641](https://github.com/Alluxio/new-contributor-tasks/issues/641)

### CODE REVIEW

**Review by dbw9580 — APPROVED** [review]
LGTM

**Comment by dbw9580** [comment]
Hi @LiuJiahao0001, thank you for your contribution! Can you please sign the CLA following the instructions above?

**Comment by LiuJiahao0001** [comment]
Hi @dbw9580 ，I have completed the operation according to relevant instructions. thank you

**Comment by dbw9580** [comment]
@jiacheliu3 please merge this

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
