### PR TITLE
Fix worker stream registration log msg

### PR DESCRIPTION
**Pull request by kevincai**
### What changes are proposed in this pull request?

Minor fix of log message

### Why are the changes needed?

Format string missing one position parameter.

### Does this PR introduce any user facing changes?

Nope

### CODE REVIEW

**Review by HelloHorizon — APPROVED** [review]

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by jiacheliu3** [comment]
Failed test is due to flakeness
```
Error: 0.577 [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 73.643 s <<< FAILURE! - in alluxio.client.fs.concurrent.ConcurrentFileInStreamIntegrationTest
Error: 0.587 [ERROR] alluxio.client.fs.concurrent.ConcurrentFileInStreamIntegrationTest.FileInStreamConcurrency  Time elapsed: 35.682 s  <<< FAILURE!
```

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
