### PR TITLE
[SMALLFIX] Improve java8 replace anonymous type with lambda

### PR DESCRIPTION
**Pull request by hiteshwadekar**
Fixing beginner issue for -> https://github.com/Alluxio/new-contributor-tasks/issues/395
Java8 improvement, replacing anonymous type with lambda.

Let me know if I missed anything, looking for suggestion, still trying to understand build, validate process.

### CODE REVIEW

**Comment by hiteshwadekar** [comment]
alluxio-bot

**Comment by hiteshwadekar** [comment]
alluxio-bot

**Comment by hiteshwadekar** [comment]
alluxio-bot

**Comment by calvinjia** [comment]
@hiteshwadekar Thanks for the contribution. Could you resolve the checkstyle problems (you can run this locally with `mvn checkstyle:checkstyle`)?

**Comment by hiteshwadekar** [comment]
@calvinjia Thanks for info. fixed indentation in PR, however, I tried with default eclipse auto indentation, but it didn't solve it, Any other way to auto-correct it?

**Comment by calvinjia** [comment]
@hiteshwadekar Did you try with our eclipse formatter settings? See: https://www.alluxio.org/docs/master/en/contributor/Code-Conventions.html#coding-style

**Comment by calvinjia** [comment]
alluxio-bot, check this please.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
@hiteshwadekar Thanks for improving the code quality!

**Comment by hiteshwadekar** [comment]
Thanks @calvinjia will pick some more

**Pull request merged**
