### PR TITLE
Remove deprecated docs

### PR DESCRIPTION
**Pull request by bf8086**
Yarn and Mesos deployment are no longer supported since 2.0.

### CODE REVIEW

**Comment by bf8086** [comment]
@madanadit @calvinjia PTAL.

**Comment by madanadit** [comment]
@bf8086 doesn't seem like yarn was marked for deprecation in the code even though the decision might have been made. do you mind adding the `@Deprecated` annotation to those classes?

**Comment by bf8086** [comment]
alluxio-bot, merge this please.

**Comment by bf8086** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please.

**Pull request merged**
