### PR TITLE
Remove web ufs

### PR DESCRIPTION
**Pull request by Jackson-Wang-7**
### What changes are proposed in this pull request?

Remove the code of web under filesystem.

### Why are the changes needed?

We will remove some unused UFSes, now is WebUnderFileSystem. Some UFSes are currently in a pending state (such as Kodo). If users continue to require them in the future, we can consider ongoing support; otherwise, they will be removed in the future, too.

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Review by yyongycy — APPROVED** [review]
LGTM

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks!

**Comment by Jackson-Wang-7** [comment]
alluxio-bot, merge this please

**Comment by Jackson-Wang-7** [comment]
remove the web ufs implementation, tracked in #18065

**Pull request merged**
