### PR TITLE
Remove Table module

### PR DESCRIPTION
**Pull request by apc999**
### What changes are proposed in this pull request?

Remove Table (Catalog service) module

### Why are the changes needed?

Depreciated in 2.9, will be removed in 300

### Does this PR introduce any user facing changes?

- catalog service removed
- transformation removed
- table command removed (already removed in 2.9)

### CODE REVIEW

**Review by beinan — APPROVED** [review]
lgtm, I will sync with end-users to figure out a workaround for the features removed.

**Comment by beinan** [comment]
alluxio-bot, merge this please.

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
