### PR TITLE
Shade protobuf to prevent dependency confliction

### PR DESCRIPTION
**Pull request by beinan**
### What changes are proposed in this pull request?

Shade protobuf

### Why are the changes needed?

Avoid dependency conflict

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Comment by beinan** [comment]
@JiamingMai could you help take a look and give it a shot, thanks a lot!

**Review by JiamingMai — APPROVED** [review]
LGTM. The alluxio client JAR can run successfully on Presto.

**Comment by beinan** [comment]
alluxio-bot, merge this please.

**Comment by jja725** [comment]
@JiamingMai could you help me understand this conflict? let's sync offline

**Pull request merged**
