### PR TITLE
Fix HDFSProxyUserValidationTaskTest

### PR DESCRIPTION
**Pull request by bradyoo**
Using Powermock makes it now such that you can no longer fetch the resource after Java 9 because (See https://stackoverflow.com/questions/54021754/why-does-the-getresource-method-return-null-in-jdk-11 UPDATE in the chosen answer)

### CODE REVIEW

**Comment by yuzhu** [comment]
alluxio-bot, test this please

**Comment by yuzhu** [comment]
alluxio-bot, test this with java 11 please

**Comment by yuzhu** [comment]
checkstyle?

**Comment by bradyoo** [comment]
Fixed checkstyle @yuzhu

**Comment by yuzhu** [comment]
alluxio-bot, test this with java 11 please

**Comment by yuzhu** [comment]
jenkins, test this with java 11 please

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
