### PR TITLE
Fix alluxio fuse atime unable to display problem

### PR DESCRIPTION
**Pull request by bzheng888**
### What changes are proposed in this pull request?
Fix alluxio fuse don't display atime problem
### Why are the changes needed?
When exec stat file command in alluxio fuse mount point, the result can't show atime.
### Does this PR introduce any user facing changes?
No

### CODE REVIEW

**Comment by LuQQiu** [comment]
@bzheng888 can you help create a github issue for this PR?

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks for supporting atime in getattr

**Comment by LuQQiu** [comment]
@bzheng888 can you help modify the AlluxioJniFuseFileSystemTest.getattr test to include the `atime` check?

**Review by maobaolong — APPROVED** [review]
@bzheng888 Thanks for this improvement. LGTM

**Review by apc999 — APPROVED** [review]

**Comment by maobaolong** [comment]
alluxio-bot, merge this please

**Comment by maobaolong** [comment]
@bzheng888 Sorry, please address the comment from @LuQQiu add a ut.

**Comment by maobaolong** [comment]
@bzheng888 Thanks for the ut, it looks good, the failed test seems a flaky test, ignore it for this PR.

```
Error: 3.459 [ERROR] alluxio.util.JvmPauseMonitorTest.testMockedInfoPause  Time elapsed: 0.719 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at alluxio.util.JvmPauseMonitorTest.testMockedInfoPause(JvmPauseMonitorTest.java:103)
```

**Comment by maobaolong** [comment]
alluxio-bot, merge this please

**Pull request merged**
