### PR TITLE
Add MemoryPageStoreOptions to the test case

### PR DESCRIPTION
**Pull request by XuanlinGuan**
### What changes are proposed in this pull request?
Add MemoryPageStoreOptions in data Collection

### Why are the changes needed?
If we want to test MemoryPageStoreOptions, we need to add this test case to data()

### Does this PR introduce any user facing changes?
No, I don't think so

### CODE REVIEW

**Review by dbw9580 — APPROVED** [review]

**Comment by HelloHorizon** [comment]
@XuanlinGuan @dbw9580 it seems this branch has more commits and reflects on https://github.com/Alluxio/alluxio/pull/16098. Do you mind cleaning the commit before merging the code?

**Comment by XuanlinGuan** [comment]
@HelloHorizon Thank you told me that. This branch is changed a bit messy by me. So I just want to keep [https://github.com/Alluxio/alluxio/pull/16098](url). Beacuse basically, they are the seem pr. Do I need to close this pr and clean commits in [https://github.com/Alluxio/alluxio/pull/16098](url)?
I am a new contributor and I so apologize do this messy work.

**Comment by HelloHorizon** [comment]
@XuanlinGuan feel free to clean the branch, and you can make a new pr with another branch for https://github.com/Alluxio/alluxio/pull/16098

**Comment by beinan** [comment]
alluxio-bot, merge this please.

**Pull request merged**
