### PR TITLE
[ALLUXIO-2158] Remove redundant initialization in LocalFirstPolicy.java

### PR DESCRIPTION
**Pull request by milton0825**
Remove redundant initialization in LocalFirstPolicy.java
private String mLocalHostName = null; can be simplified to private String mLocalHostName;

jira ticket: https://alluxio.atlassian.net/browse/ALLUXIO-2158

### CODE REVIEW

**Comment by aaudiber** [comment]
jenkins, ok to test

**Comment by jsimsa** [comment]
@milton0825 thank you for the PR ... once you sign the CLA, the PR is good to be merged

**Comment by jsimsa** [comment]
jenkins, test this please

**Comment by aaudiber** [comment]
LGTM, thanks for the improvement

**Pull request merged**
