### PR TITLE
[ALLUXIO-1803] Add alluxio-site.properties.template

### PR DESCRIPTION
**Pull request by rnirmal**
Sample alluxio properties template in conf/ to help easily
use and tune for the user

### CODE REVIEW

**Comment by rnirmal** [comment]
https://alluxio.atlassian.net/browse/ALLUXIO-1803

**Comment by haoyuan** [comment]
Jenkins, add to whitelist.

**Comment by yupeng9** [comment]
@rnirmal thanks for adding this template, which will greatly improve user experience. Could you also reference this template in the docs http://www.alluxio.org/documentation/en/Configuration-Settings.html and let the user know it?

**Comment by rnirmal** [comment]
@yupeng9 updated the documentation to show to use the template. I couldn't find out how to build the docs, but checked that the markdown looks good.

**Comment by yupeng9** [comment]
Thanks for updating the docs! To generate the docs, you can follow the instructions in docs/README.md
https://github.com/Alluxio/alluxio/tree/master/docs

**Comment by yupeng9** [comment]
LGTM

**Comment by apc999** [comment]
LGTM

**Pull request merged**
