### PR TITLE
Remove MigrateIntegrationTest and PersistIntegrationTest

### PR DESCRIPTION
**Pull request by jasondrogba**
### What changes are proposed in this pull request?

Remove MigrateIntegrationTest and PersistIntegrationTest.

### Why are the changes needed?

MigrateIntegrationTest and PersistIntegrationTest are related to the job service, which no longer exists in the Dora architecture. Therefore, MigrateIntegrationTest and PersistIntegrationTest can be removed.

### CODE REVIEW

**Comment by YichuanSun** [comment]
This PR is just recording the process of unit test fix. Please do not merge it until all the code is migrated to scheduler, or determine that all the code is no need to exist.

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks for the work!

**Comment by jiacheliu3** [comment]
fyi @jja725 PTAL thanks!

**Review by jja725 — APPROVED** [review]

**Comment by jja725** [comment]
It's good to be deleted

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
