### PR TITLE
Change port in test

### PR DESCRIPTION
**Pull request by jiacheliu3**
Seems there's a mysterious conflict in the port caused by this test, so I'm changing the ports this test uses in the hope that it does not conflict any more.

### CODE REVIEW

**Comment by jiacheliu3** [comment]
Oops one extra commit comes in accidentally, i will remove it after i test the test flakiness first

**Review by kaijchen — APPROVED** [review]
LGTM

**Comment by jiacheliu3** [comment]
@kaijchen thanks for looking at this. I noticed this test did not do `system.stop()` and I wonder if that can be the problem.

**Comment by kaijchen** [comment]
> I noticed this test did not do `system.stop()` and I wonder if that can be the problem.

Yes, followup: #16694. However, adding `system.stop()` doesn't solve the problem.

**Comment by jiacheliu3** [comment]
closed in favor of #16694

**Comment by kaijchen** [comment]
Hi @jiacheliu3, since this PR is fixing some flaky tests, maybe merge this first?

**Comment by jiacheliu3** [comment]
Reopened this PR as #16694 still needs some work. We will merge this one first and 16694 will take its time.

**Comment by LuQQiu** [comment]
Didn't see this PR before, just merge a fix from @tcrain https://github.com/Alluxio/alluxio/commit/b47fbda023be925e4c54c651ddf866e1de3b9e20

**Comment by kaijchen** [comment]
> Didn't see this PR before, just merge a fix from @tcrain [b47fbda](https://github.com/Alluxio/alluxio/commit/b47fbda023be925e4c54c651ddf866e1de3b9e20) about the same test

Great work, thanks for the fix.

**Comment by jiacheliu3** [comment]
> Didn't see this PR before, just merge a fix from @tcrain [b47fbda](https://github.com/Alluxio/alluxio/commit/b47fbda023be925e4c54c651ddf866e1de3b9e20) about the same test

That's much more graceful. Thanks for the fix!

**Pull request closed without merging**
