### PR TITLE
[DOCFIX] Update the Journal

### PR DESCRIPTION
**Pull request by zhipcui**
add UFS journal options configuration

### CODE REVIEW

**Comment by apc999** [comment]
@zhipcui thanks for the improvement. Have you signed the [CLA](https://cla.alluxio.org/)? If yes, I will manually remove the warning label.

**Comment by zhipcui** [comment]
I have signed the CLA. @apc999

**Comment by ZacBlanco** [comment]
alluxio-bot, check this please

**Comment by ZacBlanco** [comment]
@zhipcui if you've signed the CLA, then the label would have been automatically removed. Did you use the same email that is associated with your github account?

**Comment by zhipcui** [comment]
@ZacBlanco  I used the same email.

As the image below show，the CLA status is on completed status.
image

**Comment by ZacBlanco** [comment]
Thanks for the update

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
