### PR TITLE
Fix build path in shaded/client-hadoop3 pom

### PR DESCRIPTION
**Pull request by Xenorith**
need to fix the directory paths in cherry picked PR since it is under `dora/`

### CODE REVIEW

**Comment by Xenorith** [comment]
my bad for not catching this x.x

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks for the fix

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Pull request merged**
