### PR TITLE
[ALLUXIO-2159]Remove redundant initialization in NettyUnderFileSystemFileReader.java

### PR DESCRIPTION
**Pull request by apei830**
https://alluxio.atlassian.net/browse/ALLUXIO-2159

### CODE REVIEW

**Comment by RongGu** [comment]
LGTM.

**Comment by gpang** [comment]
ok to test

**Comment by jsimsa** [comment]
LGTM

**Comment by jsimsa** [comment]
@apei830 thank you for your PR, please do not forget to sign the CLA

**Pull request merged**
