### PR TITLE
[ALLUXIO-1921] Move logging to the correct scope

### PR DESCRIPTION
**Pull request by d9liang**
https://alluxio.atlassian.net/browse/ALLUXIO-1921

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
Thanks for the contribution, @d9liang !

**Comment by gpang** [comment]
LGTM

**Comment by jsimsa** [comment]
LGTM

**Pull request merged**
