### PR TITLE
[ALLUXIO-3171] JournalInputStream should be closed in JournalTool#main

### PR DESCRIPTION
**Pull request by tedyu**
https://alluxio.atlassian.net/browse/ALLUXIO-3171

Use try-with-resources construct

### CODE REVIEW

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
@tedyu once the CLA is signed, I can merge the PR

**Comment by tedyu** [comment]
I clicked on the link and tried to sign in with github.
However, I got rejected.

Any other way to sign CLA ?

**Comment by aaudiber** [comment]
Sorry, I'll look into what's going on there. For now, can you try [this link](http://cla.alluxio.org/) instead?

**Comment by aaudiber** [comment]
Awesome, thanks. Welcome to being an Alluxio contributor :)

**Pull request merged**
