### PR TITLE
[DOCFIX] Update tensorflow doc example

### PR DESCRIPTION
**Pull request by ssz1997**
Provide a new example in tensorflow documentation. 

MNIST dataset is another well-known image recognition dataset that classifies hand-writing digits. 

The python script is slightly modified from https://www.tensorflow.org/tutorials/quickstart/advanced.

The original second example uses `tf_cnn_benchmarsk.py`, which is more suitable for tensorflow1 whereas the new example is using tensorflow2, and is no longer under maintained. Therefore remove it.

### CODE REVIEW

**Comment by ssz1997** [comment]
@LuQQiu Please take a look. Thanks!

**Review by LuQQiu — APPROVED** [review]
LGTM, awesome!

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
@Xenorith cherry-pick?

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
