### PR TITLE
[DOCFIX] Add instruction for java 11

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Comment by yuzhu** [comment]
@calvinjia @LuQQiu PTAL

**Review by LuQQiu — APPROVED** [review]
LGTM! Thanks for adding docs for java 11

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
