### PR TITLE
[DOCFIX] Revise hdfs docs

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks!

**Comment by LuQQiu** [comment]
@yuzhu Please fix the PR title check, thanks!

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick to branch-2.4 please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
