### PR TITLE
Fix the issue to get a tag of a non-existed in OSS/COS

### PR DESCRIPTION
**Pull request by Jackson-Wang-7**
### What changes are proposed in this pull request?

Add exception handling for OSS and COS ufs in getting object tags and other apis.

### Why are the changes needed?
When handling exceptions, we need to identify exceptions that can be allowed, and other errors need to be converted to an Alluxio exception.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

### CODE REVIEW

**Review by elega — APPROVED** [review]
LGTM

**Comment by Jackson-Wang-7** [comment]
alluxio-bot, merge this please

**Comment by Jackson-Wang-7** [comment]
alluxio-bot, merge this please

**Comment by Jackson-Wang-7** [comment]
alluxio-bot, cherry-pick this to branch-3-1.1.x please

**Pull request merged**
