### PR TITLE
Fix enum fields of alluxio.wire.CommandType

### PR DESCRIPTION
**Pull request by ys270**
Fixes Alluxio/new-contributor-tasks#564
Enum fields of alluxio.wire.CommandType should be in Uppercase

### CODE REVIEW

**Comment by apc999** [comment]
@ys270 thanks for your contribution!
can you sign the CLA https://cla.alluxio.org/ ?
if you have already signed. let me know

**Comment by ys270** [comment]
There's one check going wrong but I can't find out why. There's a time out exception and I'm confused.

**Comment by apc999** [comment]
@ys270  can you update your PR and resolve the conflict? basically the file you modified `core/base/src/main/java/alluxio/wire/CommandType.java` has been moved to `core/common/src/main/java/alluxio/wire/CommandType.java`

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
