### PR TITLE
[DOCFIX] Fix typo in Running-AlluxioFuse-On-Docker.md

### PR DESCRIPTION
**Pull request by ferhui**

### CODE REVIEW

**Comment by maobaolong** [comment]
@ferhui Good catch, thank you for fixing this, LGTM.

**Review by gpang — APPROVED** [review]
@ferhui Thanks for the improvement!

LGTM

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Comment by ferhui** [comment]
@maobaolong @gpang Thanks for review!

**Pull request merged**
