### PR TITLE
Fix the client stressbench concurrency problem

### PR DESCRIPTION
**Pull request by bzheng888**
### What changes are proposed in this pull request?
Fix client stressbench concurrency problem.

### Why are the changes needed?
Reproduce:
Cluster:  
1 master and 2 workers

Command:
`bin/alluxio runClass alluxio.stress.cli.client.StressClientIOBench --operation Write --base alluxio:///stress-client-io-base --write-num-workers 2 --file-size 1m --threads 8`

Result: user_root.log
image

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

### CODE REVIEW

**Comment by Jackson-Wang-7** [comment]
@dbw9580 please take a look at the PR, thanks!

**Review by dbw9580 — CHANGES_REQUESTED** [review]
Thanks for reporting this! While synchronizing on the entire method surely works, I'm thinking if we can just synchronize over the part where `mWorkerInfoList` is not yet initialized? i.e.

```java
if (!mInitialized) {
  synchronized(this) {
    if (!mInitialized) {
      // initialize mWorkerInfoList
      mInitialized = true;
    }
  }
}
```
This will make less lock contentions after the list has been initialized.

**Review by dbw9580 — APPROVED** [review]
It seems `mIndex` is not updated atomically, either:

https://github.com/Alluxio/alluxio/blob/ce1352b592916235aa9c6c5112257dbed06f6ee0/stress/shell/src/main/java/alluxio/stress/cli/client/ClientIOWritePolicy.java#L91-L92

In this case, I guess we can only synchronize over the entire method body.

**Comment by bzheng888** [comment]
@dbw9580 Yes , the mIndex and mWorkerInfoList both need to be protected. 

> It seems `mIndex` is not updated atomically, either:
> 
> https://github.com/Alluxio/alluxio/blob/ce1352b592916235aa9c6c5112257dbed06f6ee0/stress/shell/src/main/java/alluxio/stress/cli/client/ClientIOWritePolicy.java#L91-L92
> 
> In this case, I guess we can only synchronize over the entire method body.

@dbw9580 Yes , the mIndex and mWorkerInfoList both need to be protected.

**Review by maobaolong — APPROVED** [review]
LGTM

**Comment by maobaolong** [comment]
alluxio-bot, merge this please

**Pull request merged**
