### PR TITLE
Improve check consistency with under storage behavior

### PR DESCRIPTION
**Pull request by yabola**
Each path in Alluxio will be compared with the underlying storage recursively. 
This PR aims to reduce unnecessary comparisons  with under storage path status (maybe an expansive operation) in nested directorys. 
E.g.
1. `/a/b/c` in Alluxio and UFS , then delete UFS directory `/a`, we can assert that `b`, `c` must be inconsistent with UFS. 
2. `/a/b/c` is only created in Alluxio, not on underlying storage , we can assert that  `b`, `c` must be inconsistent with UFS. 
3. .....
we can assert that the parent node is inconsistent, then the child nodes must be also inconsistent. 
remind : dir is considered consistent even if the dir's fingerprint was changed.

Existing test ：alluxio.client.fs.CheckConsistencyIntegrationTest

### CODE REVIEW

**Comment by yabola** [comment]
@jiacheliu3 please take a look~

**Comment by yabola** [comment]
alluxio-bot, check this please

**Comment by yabola** [comment]
alluxio-bot, check this please

**Comment by yabola** [comment]
@gpang @calvinjia please take a look,thx.

**Comment by yuzhu** [comment]
@yabola thanks for the change. one comment, looks like the only time we can have MINOR_INCONSISTENT is when we have files.  so perhaps we can say that if a dir is inconsistent we can assert the children is inconsistent?  so we avoid introducing the concept of MAJOR and MINOR inconsistency?

**Comment by yabola** [comment]
@yuzhu  I agree with you. If a dir is inconsistent, then we can assert the children is inconsistent. I had modified the code .But I want to confirm that dir is considered consistent even if the dir's fingerprint was changed.
Please review again, thx.

**Comment by calvinjia** [comment]
@yabola Thanks for the optimization!
@yuzhu raises a good point, I think in the case we shadow a directory, it is reasonable to state that the files underneath are also inconsistent, so I'm okay with this change. Though this should be a pretty rare case where consistency doesn't make that much sense in the first place.

**Review by yuzhu — APPROVED** [review]
LGTM, thanks

**Comment by yabola** [comment]
alluxio-bot, merge this please.

**Comment by yuzhu** [comment]
alluxio-bot, merge this please.

**Pull request merged**
