### PR TITLE
Port changes of [#12769] to branch-2.3

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
Ping? @yuzhu Note that tests passed.

**Review by yuzhu — APPROVED** [review]

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Comment by bradyoo** [comment]
This cherry-pick was built on top of another chery-pick. Since the other cherry-pick is merged. I rebased it up. Diff isn't any different (just smaller). Going to merge.

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Pull request merged**
