### PR TITLE
Remove the redundant DefaultBlockMaster#SuppressFBWarnings

### PR DESCRIPTION
**Pull request by jianghuazhu**
### What changes are proposed in this pull request?
In DefaultBlockMaster, there are some redundant SuppressFBWarnings. The purpose of this pr is to remove them.
Details: https://github.com/Alluxio/alluxio/issues/16660

### Does this PR introduce any user facing changes?
For user, there is no impact.

### CODE REVIEW

**Comment by jianghuazhu** [comment]
Some unit tests fail, such as:
DistributedCommandsStatsTest

It seems that it has little to do with the code I submitted.
Can you help review this pr, @jenoudet  @yuzhu @jja725 .
Thank you very much.

**Review by jenoudet — APPROVED** [review]
Thanks for the simplification! In the future, you can begin the PR description with any of [these words](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to automatically link issues and PRs together.

**Comment by jianghuazhu** [comment]
Thanks @jenoudet  for the tip. That's just what I need.

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
