### PR TITLE
[SMALLFIX] Remove extra s in alluxio-fuse script

### PR DESCRIPTION
**Pull request by bzheng888**
### What changes are proposed in this pull request?

Small fix

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

### CODE REVIEW

**Comment by ssz1997** [comment]
Which operating system are you using? 

I remember different systems have different syntax on the sleep command. Could you help double check whether it would work on the widely used systems? Some on top of head include macOS, CentOS, Ubuntu, Alpine.

**Comment by bzheng888** [comment]
@ssz1997  My os is macOS ARM arch, Is this result expected? 
image

**Comment by bzheng888** [comment]
@ssz1997 PTAL, If it is alright that only the widely used systems is currently supported. I'll close this pr, thanks!

**Comment by ssz1997** [comment]
@bzheng888 We currently don't know whether AlluxioFuse works with Apple ARM in terms of correctness and other aspects. Some user reported it's not usable at all. I'm closing this PR so we don't need to investigate on whether it will affect other systems. 

Thanks for bringing this up. Feel free to create an issue for this so we can keep this in mind and get back to it.

**Pull request closed without merging**
