### PR TITLE
Show errors for DistributedLoad/Cp/Mv job submission failures in console

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
➜  alluxio git:(master) ✗ bin/alluxio fs distributedLoad /test0
/test0/file011784.bin loading
Failed to start job with error: Failed to connect to JobMasterClient @ localhost:20001 after 8 attempts
/test0/file006613.bin loading
....

**Comment by bradyoo** [comment]
Job submission failures used to only go to the logs. It now goes to the console and the logs. @yuzhu: Should be easy to review.

**Review by yuzhu — APPROVED** [review]
LGTM, thanks!

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Pull request merged**
