### PR TITLE
Update scalability doc

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Comment by yuzhu** [comment]
@gpang @bradyoo

**Comment by bradyoo** [comment]
LGTM

**Comment by yuzhu** [comment]
merging because this is a doc change

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Pull request merged**
