### PR TITLE
Update DistributedLoad using cache request

### PR DESCRIPTION
**Pull request by jja725**
### What changes are proposed in this pull request?

Update DistributedLoad using cache request instead of read with passive cache.

### Why are the changes needed?

using read to cache block is not efficient and error proune. Use cache request directly.

### Does this PR introduce any user facing changes?
no

### CODE REVIEW

**Comment by maobaolong** [comment]
@jja725 As `CacheRequest` is a new come feature, I hope it would be stable, but maybe there are some bugs for several months in the future, so I suggest to keep an option to load data by original read back mode, once the cacherequest way fail, we can also using distributedload command. If we keep the option for previous read-back data mode, we can have more courage to upgrade to the new version or back porting this patch.

**Review by yuzhu — COMMENTED** [review]
@jja725 overall looks good. @maobaolong 's suggest is a valid one, but I am also interested in the performance aspect of this. Could you do some benchmarking using two versions and see how much it improves load performance?

**Comment by jja725** [comment]
> @jja725 overall looks good. @maobaolong 's suggest is a valid one, but I am also interested in the performance aspect of this. Could you do some benchmarking using two versions and see how much it improves load performance?

sure I would do the benchmarking and add a option for distributedLoad

**Comment by jja725** [comment]
@yuzhu @maobaolong add one option to support the old passive cache implementation

**Review by maobaolong — COMMENTED** [review]
It look perfect now. Do you have a change to test this in a container env? Since I test the Load command cannot work in the container env after `load` command updated to use direct cache way, luckily I have fixed that issue.

**Comment by yuzhu** [comment]
@jja725 could you update the documentation for distributedLoad to reflect the strategy choices?

**Comment by jja725** [comment]
> @jja725 could you update the documentation for distributedLoad to reflect the strategy choices?

@yuzhu added doc, and I set the default to not use direct cache. So probably we can merge this in and try to test it in container env later after docker hub have the newest version(hard to test feature branch). After confirmation with test docker env, we can switch the default to use direct cache.

**Comment by jja725** [comment]
@yuzhu @maobaolong tested in local docker env, it works fine. So I would set using direct cache as default then.

**Review by maobaolong — APPROVED** [review]
@jja725 Thanks for this contribution.

**Review by yuzhu — APPROVED** [review]

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
