### PR TITLE
[DOCFIX] Fix  deploy Alluxio on a Cluster with HA

### PR DESCRIPTION
**Pull request by Trevor-zhang**

### CODE REVIEW

**Comment by Trevor-zhang** [comment]
refer to  [Failed deploy Alluxio on a Cluster with HA](https://github.com/Alluxio/alluxio/issues/12125)

**Comment by Trevor-zhang** [comment]
refer to issue [Failed deploy Alluxio on a Cluster with HA](https://github.com/Alluxio/alluxio/issues/12125)

**Review by apc999 — APPROVED** [review]
thanks for the improvement! @Trevor-zhang

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.3 please

**Pull request merged**
