### PR TITLE
Upgrade swagger-maven-plugin from 3.1.1 to 3.1.7

### LINKED ISSUE #12407: Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.1
**Alluxio Version:**
master

**Describe the bug**

```bash
mvn clean  install -Dmaven.javadoc.skip=true -DskipTests -Dlicense.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true
...
...
[INFO] Alluxio Job Service 2.5.0-SNAPSHOT ................. SUCCESS [  0.017 s]
[INFO] Alluxio Job Service - Common Utilities 2.5.0-SNAPSHOT SUCCESS [  0.266 s]
[INFO] Alluxio Job Service - Client 2.5.0-SNAPSHOT ........ SUCCESS [  0.170 s]
[INFO] Alluxio Shell 2.5.0-SNAPSHOT ....................... SUCCESS [  0.645 s]
[INFO] Alluxio Core - Client - HDFS 2.5.0-SNAPSHOT ........ SUCCESS [  0.363 s]
[INFO] Alluxio Stress 2.5.0-SNAPSHOT ...................... SUCCESS [  0.030 s]
[INFO] Alluxio Stress - Common 2.5.0-SNAPSHOT ............. SUCCESS [  0.223 s]
[INFO] Alluxio Stress - Shell 2.5.0-SNAPSHOT .............. SUCCESS [  0.201 s]
[INFO] Alluxio Table - Shell 2.5.0-SNAPSHOT ............... SUCCESS [  0.133 s]
[INFO] Alluxio Assembly 2.5.0-SNAPSHOT .................... SUCCESS [  0.017 s]
[INFO] Alluxio Assembly - Client 2.5.0-SNAPSHOT ........... SUCCESS [  7.517 s]
[INFO] Alluxio Core - Server 2.5.0-SNAPSHOT ............... SUCCESS [  0.020 s]
[INFO] Alluxio Core - Server - Common Utilities 2.5.0-SNAPSHOT SUCCESS [  0.939 s]
[INFO] Alluxio Under File System 2.5.0-SNAPSHOT ........... SUCCESS [  0.017 s]
[INFO] Alluxio Under File System - Local FS 2.5.0-SNAPSHOT  SUCCESS [  0.143 s]
[INFO] Alluxio Core - Server - Master 2.5.0-SNAPSHOT ...... FAILURE [  0.988 s]
[INFO] Alluxio Core - Server - Proxy 2.5.0-SNAPSHOT ....... SKIPPED
[INFO] Alluxio Core - Server - Worker 2.5.0-SNAPSHOT ...... SKIPPED
[INFO] Alluxio Job Service - Server 2.5.0-SNAPSHOT ........ SKIPPED
[INFO] Alluxio Log Server 2.5.0-SNAPSHOT .................. SKIPPED
[INFO] Alluxio Table - Server 2.5.0-SNAPSHOT .............. SKIPPED
[INFO] Alluxio Table - Server - Common 2.5.0-SNAPSHOT ..... SKIPPED
[INFO] Alluxio Table - Server - Master 2.5.0-SNAPSHOT ..... SKIPPED
[INFO] Alluxio Assembly - Server 2.5.0-SNAPSHOT ........... SKIPPED
[INFO] Alluxio Integration 2.5.0-SNAPSHOT ................. SKIPPED
[INFO] Alluxio Integration - FUSE 2.5.0-SNAPSHOT .......... SKIPPED
[INFO] Alluxio Integration - Tools 2.5.0-SNAPSHOT ......... SKIPPED
[INFO] Alluxio Integration - Tools - HMS 2.5.0-SNAPSHOT ... SKIPPED
[INFO] Alluxio Integration - Validation Tools 2.5.0-SNAPSHOT SKIPPED
[INFO] Alluxio MiniCluster 2.5.0-SNAPSHOT ................. SKIPPED
[INFO] Alluxio Shaded Libraries 2.5.0-SNAPSHOT ............ SKIPPED
[INFO] Alluxio Shaded Libraries - Client 2.5.0-SNAPSHOT ... SKIPPED
[INFO] Alluxio Shaded Libraries - Hadoop 2.8.5-tq-0.1.0-SNAPSHOT SKIPPED
[INFO] Alluxio Shaded Libraries - Ozone 2.5.0-SNAPSHOT .... SKIPPED
[INFO] Alluxio Table - Server - UnderDB 2.5.0-SNAPSHOT .... SKIPPED
[INFO] Alluxio Table - Server - UnderDB - Hive 2.5.0-SNAPSHOT SKIPPED
[INFO] Alluxio Table - Server - UnderDB - Glue 2.5.0-SNAPSHOT SKIPPED
[INFO] Alluxio Tests 2.5.0-SNAPSHOT ....................... SKIPPED
[INFO] Alluxio Under File System - HDFS 2.5.0-SNAPSHOT .... SKIPPED
[INFO] Alluxio Under File System - Microsoft Azure DataLake 2.5.0-SNAPSHOT SKIPPED
[INFO] Alluxio Under File System - Tencent Cloud COS 2.5.0-SNAPSHOT SKIPPED
[INFO] Alluxio Under File System - GCS 2.5.0-SNAPSHOT ..... SKIPPED
[INFO] Alluxio Under File System - Qiniu Kodo 2.5.0-SNAPSHOT SKIPPED
[INFO] Alluxio Under File System - Aliyun OSS 2.5.0-SNAPSHOT SKIPPED
[INFO] Alluxio Under File System - S3 2.5.0-SNAPSHOT ...... SKIPPED
[INFO] Alluxio Under File System - Swift 2.5.0-SNAPSHOT ... SKIPPED
[INFO] Alluxio Under File System - Microsoft Azure Blob Storage 2.5.0-SNAPSHOT SKIPPED
[INFO] Alluxio Under File System - Web 2.5.0-SNAPSHOT ..... SKIPPED
[INFO] Alluxio Under File System - Apache Ozone 2.5.0-SNAPSHOT SKIPPED
[INFO] Alluxio UI 2.5.0-SNAPSHOT .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:09 min
[INFO] Finished at: 2020-10-28T12:56:12+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.1:generate (default) on project alluxio-core-server-master: Unable to parse configuration of mojo com.github.kongchen:swagger-maven-plugin:3.1.1:generate for
 parameter apiSources: Cannot set 'apiSources' in class com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo: io/swagger/models/Info: io.swagger.models.Info -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginConfigurationException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :alluxio-core-server-master
```

**To Reproduce**

Not sure it can be reproduced oh other build environments, but It can be reproduced on my environment

`mvn clean  install -Dmaven.javadoc.skip=true -DskipTests -Dlicense.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true`

**Expected behavior**

Success build alluxio

**Urgency**

Normal

**Additional context**

Maybe this is a bug of `swagger-maven-plugin 3.1.1`, after I upgrade the swagger-maven-plugin to 3.1.7, the problem has gone.

### PR DESCRIPTION
**Pull request by maobaolong**
Fix #12407

### CODE REVIEW

**Comment by yuzhu** [comment]
Aalluxio-bot, test this with Java 11 please

**Review by yuzhu — APPROVED** [review]

**Comment by yuzhu** [comment]
Might be specific to his environment. Cannot repro.

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
