### PR TITLE
Print web metrics servlet page as human-readable format

### PR DESCRIPTION
**Pull request by LuQQiu**
### What changes are proposed in this pull request?

Pretty print the metrics/json web servlet

### Why are the changes needed?

Easier for users to view all the metrics exposed by master/worker/fuse

### Does this PR introduce any user facing changes?

Yeah, for web UI  metrics/json/ page, it will show json string as well formatted human readable string instead of the natural json string

### CODE REVIEW

**Comment by yuzhu** [comment]
@LuQQiu could you attach a sample output? is the output still json? would my json browser plugin still be able to work with it?

**Comment by LuQQiu** [comment]
[metricsExample.log](https://github.com/Alluxio/alluxio/files/6971968/metricsExample.log)

**Review by yuzhu — APPROVED** [review]
LGTM, thanks

**Review by maobaolong — APPROVED** [review]
it LGTM, thanks for this improvement.

**Comment by LuQQiu** [comment]
thanks for reviewing!

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
