### PR TITLE
[DOCFIX] Update Running-HBase-on-Alluxio.md

### PR DESCRIPTION
**Pull request by infoplat**
25行，创建/base目录，应该为创建/hbase目录。英文版是这样的。

### CODE REVIEW

**Comment by infoplat** [comment]
alluxio-bot, check this please

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
add to whitelist

**Comment by ifcharming** [comment]
@infoplat  thank you for your contribution to Alluxio!

Seems like you have another PR going to `master` branch, for a same change.
Can you please close this one against `branch-1.3`?

**Pull request closed without merging**
