### PR TITLE
[SMALLFIX] Netty version upgrade

### PR DESCRIPTION
**Pull request by peisun1115**
Upgrade netty from 4.0 to 4.1

New features in 4.1:
http://netty.io/wiki/new-and-noteworthy-in-4.1.html
The ones that are very relevant to us:
1. Easier and more precise buffer leak tracking
2. PooledByteBufAllocator as the default allocator
3. Globally unique channel ID

### CODE REVIEW

**Comment by peisun1115** [comment]
@calvinjia

**Comment by calvinjia** [comment]
@peisun1115 I notice Netty does not guarantee backward compatibility between 4.1 and 4.0, will this change be backward compatible for us?

**Comment by peisun1115** [comment]
@calvinjia 

I am not aware of any backward compatibility issue yet. 

The 4.1 release note says
"""
Although we did our best to keep the backward compatibility from 4.0, 4.1 contains multiple additions which might not be fully backward-compatible with 4.0. Please make sure to recompile your application against the new version.

When you recompile your application, you might find some deprecation warnings. Please make sure to fix them all by using the suggested alternative, so that you have less trouble when upgrading to the next version.
"""

I didn't see any "deprecation warnings" when i recompile. And all tests passed. Let me know if you have any suggestions to further verify.

**Comment by peisun1115** [comment]
I've also tested the old client on the new server by running 
./bin/alluxio fs copyFromLocal /tmp/a /a (cache_through to excise the netty code)
./bin/alluxio fs cat /a

I also did ./bin/alluxio runTests

all worked

**Comment by calvinjia** [comment]
LGTM

**Comment by peisun1115** [comment]
@calvinjia can you merge this PR? thank you.

**Pull request merged**
