### PR TITLE
SECURITY: Adds an enforcer rule to exclude commons collections 3.2.1

### PR DESCRIPTION
**Pull request by pcj**
Adds a maven enforcer rule to exclude apache commons collections 3.2.1 from any transitive dependencies.

I read this blog post today by @cgruber http://www.geekinasuit.com/2016/03/apache-commons-collections-321.html and popped this rule into your pom.xml; it fails the build at HDFS.  Sorry I am not involved enough in your project to propose the fix, but I wanted to call it to your attention.

```
[INFO] Reactor Summary:
[INFO] 
[INFO] Alluxio Parent .................................... SUCCESS [  4.151 s]
[INFO] Alluxio Core ...................................... SUCCESS [  0.627 s]
[INFO] Alluxio Core - Common Utilities ................... SUCCESS [ 47.104 s]
[INFO] Alluxio Under File System ......................... SUCCESS [  0.482 s]
[INFO] Alluxio Under File System - Local FS .............. SUCCESS [  6.100 s]
[INFO] Alluxio Under File System - HDFS .................. FAILURE [  0.304 s]
[INFO] Alluxio Under File System - Gluster FS ............ SKIPPED
[INFO] Alluxio Under File System - Aliyun OSS ............ SKIPPED
[INFO] Alluxio Under File System - Swift ................. SKIPPED
[INFO] Alluxio Under File System - S3 .................... SKIPPED
[INFO] Alluxio Under File System - GCS ................... SKIPPED
[INFO] Alluxio Core - Client ............................. SKIPPED
[INFO] Alluxio Core - Server ............................. SKIPPED
[INFO] Alluxio Key Value ................................. SKIPPED
[INFO] Alluxio Key Value - Common Utilities .............. SKIPPED
[INFO] Alluxio Key Value - Client ........................ SKIPPED
[INFO] Alluxio Key Value - Server ........................ SKIPPED
[INFO] Alluxio Shell ..................................... SKIPPED
[INFO] Alluxio Examples .................................. SKIPPED
[INFO] Alluxio MiniCluster ............................... SKIPPED
[INFO] Alluxio Tests ..................................... SKIPPED
[INFO] Alluxio Integration ............................... SKIPPED
[INFO] Alluxio Assemblies ................................ SKIPPED
```

### CODE REVIEW

**Comment by apc999** [comment]
the article mentioned in the above link @pcj provided to explain the reason to remove this package:
https://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/#jenkins

**Comment by gpang** [comment]
ok to test

**Comment by ifcharming** [comment]
Jenkins, test this please

**Comment by ifcharming** [comment]
Hi @pcj , thanks for proposing this PR!
Can you please take a look at the build failure?

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4:enforce (enforce-versions) on project alluxio-underfs-hdfs: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :alluxio-underfs-hdfs
```

**Comment by pcj** [comment]
Hi @ifcharming.  This PR only included the enforcer rule to fail the build if a transitive dependency on collections 3.2.1 if found (it's working!).  I didn't go through all the dependencies and actually update them, but I'm happy to help with that.  

Build was failing at underfs/hdfs due to a dependency on an outdated hadoop-commons dependency. Changing  

```
-    <hadoop.version>2.2.0</hadoop.version>
+    <hadoop.version>2.7.2</hadoop.version>
```

...fixes that.  However, build still failing on underfs/glusterfs due to glusterfs outdated.  Sadly, that's the most recent published version.  So you have many users on this?  I opened https://github.com/gluster/glusterfs-hadoop/pull/135.  If that is merged and a new glusterfs pushed to mvn repository, could help resolve this PR.  Hope this helps.

**Comment by ifcharming** [comment]
Thank you @pcj for the detailed explanation. That makes a lot of sense.

This PR is not urgent. Totally fine to wait until the glusterfs change is merged. Just wanted to check the status of this PR :) Thanks again for this improvement!

**Pull request closed without merging**
