### PR TITLE
[SMALLFIX] Improve javadoc in ObjectUnderFileSystem

### PR DESCRIPTION
**Pull request by singer-bin**
### What changes are proposed in this pull request?
Change `add` into `adds` in code comments.

### Why are the changes needed?
fixs https://github.com/Alluxio/new-contributor-tasks/issues/619

### Does this PR introduce any user facing changes?
No.

### CODE REVIEW

**Comment by singer-bin** [comment]
@alluxio-bot @beinan java11 reported an error, nothing to do with my changes.

**Comment by singer-bin** [comment]
@alluxio-bot @beinan java11 reported an error, nothing to do with my changes.

**Comment by singer-bin** [comment]
@alluxio-bot @beinan java11 reported an error, nothing to do with my changes.

**Review by dbw9580 — APPROVED** [review]

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
