### PR TITLE
Clean up block client code

### PR DESCRIPTION
**Pull request by tcrain**
### What changes are proposed in this pull request?

Code cleanup including fix grammar, use optional instead of return null, require non null when setting variables in constructor, address IDE warnings

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Review by yuzhu — APPROVED** [review]
LGTM，thanks

**Comment by yuzhu** [comment]
could you fix the conflict please @tcrain

**Comment by HelloHorizon** [comment]
Hey @tcrain , do you mind fixing the conflict?

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Pull request merged**
