### PR TITLE
[ALLUXIO-1826] Remove error message constants in FileInStream

### PR DESCRIPTION
**Pull request by xxhuang**
Instead of having constants for log messages (BLOCK_ID_NOT_CACHED, BLOCK_ID_EXISTS_SO_NOT_CACHED) in the class, we can inline the String where it appears to be consistent with the rest of the codebase.

https://alluxio.atlassian.net/browse/ALLUXIO-1826

### CODE REVIEW

**Comment by xxhuang** [comment]
alluxio-bot, check this please

**Comment by xxhuang** [comment]
alluxio-bot, check this please

**Comment by xxhuang** [comment]
alluxio-bot, check this please

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
LGTM

**Pull request merged**
