### PR TITLE
[SMALLFIX] remove st_blksize from fuse du

### PR DESCRIPTION
**Pull request by LuQQiu**

### CODE REVIEW

**Comment by LuQQiu** [comment]
The other hdfs fuse examples I checked yesterday implements other fuse packages other than the one  we used. When I tested the results of fuse du on linux and mac, the results are wrong.

I check the libfuse code, they said `st_blksize` is ignored in `getattr` in https://github.com/libfuse/libfuse/blob/d4a7ba44b022e3b63fc215374d87ed9e930d9974/include/fuse.h#L302. Besides, according to http://man7.org/linux/man-pages/man2/stat.2.html,  `st_blocks` is the number of 512B blocks allocated.

When I change the block number to be
```
stat.st_blocks.set((int) Math.ceil((double) size / 512));
```

Both linux and mac fuse du command shows correct results.
PTAL, thanks!

**Comment by aaudiber** [comment]
Is there a way to test this end-to-end so that we can see what fuse will report to users?

**Comment by LuQQiu** [comment]
@aaudiber I test the fuse du in mac and linux.
The fuse mount point contains:
```
fileA(1GB)
folder/fileB(1GB)
```
I used the same dd commands to create all the files in fuse mount point in mac and linux.

The results are very different. 
with raw `du` 
mac shows du with block size = 512, linux shows du result with block size = 1024.
The `du` result is not controlled by libfuse, but control by the underlying system.

with `du -h`
mac shows the file size as 1GB, but linux shows the file size as 1.1GB.
They are not accurate.

It's hard to include `du` in integration test now. The results of `du` is some kind of random...

**Comment by aaudiber** [comment]
are they the same number of blocks with `du -k`? It's surprising that they would be incorrect. Our integration tests and most user run Linux, so we could use an `assume` in the test to only run it on Linux

**Comment by LuQQiu** [comment]
I will test `du -k` later and add linux `du` integration test. Thanks!

**Pull request merged**
