### PR TITLE
[ALLUXIO-1988]remove the extra  words

### PR DESCRIPTION
**Pull request by micrazy**
remove the extra "in" before "in parallel" in RecomputePlan Line 28:
https://alluxio.atlassian.net/browse/ALLUXIO-1988

### CODE REVIEW

**Comment by micrazy** [comment]
The javadoc of RecomputePlan in line 28 have an extra "in" before "in parallel".We need to remove it.

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
Thanks @micrazy for contributing to Alluxio!
This PR overall looks good to me.

Per Alluxio convention, can you please use the prefix `[ALLUXIO-1988]` in the PR title and add a brief title? Also can you put the standard JIRI URL in the PR description ? (https://alluxio.atlassian.net/browse/ALLUXIO-1988)

[DOCFIX] is only used for Alluxio documentation improvement.

**Comment by ifcharming** [comment]
LGTM, thanks for the improvement.

**Pull request merged**
