### PR TITLE
[DOCFIX] Improve docker file

### PR DESCRIPTION
**Pull request by LuQQiu**
Improve Docker file

### CODE REVIEW

**Review by ssz1997 — APPROVED** [review]
Thanks for updating the docker doc!

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by ssz1997** [comment]
@Xenorith Please help cherry pick this Doc fix. Thanks

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Pull request merged**
