### PR TITLE
[DOCFIX] Update the command in the example in Chinese doc

### PR DESCRIPTION
**Pull request by saltylin**

### CODE REVIEW

**Comment by ifcharming** [comment]
Thanks for the improvement!

Can you please also update the `docs/_includes/Running-Hadoop-MapReduce-on-Alluxio/compile-Alluxio-Hadoop.md` with `-DskipTest` ?

**Comment by saltylin** [comment]
@ifcharming Updated #2962

**Comment by ifcharming** [comment]
LGTM

**Comment by yupeng9** [comment]
LGTM

**Pull request merged**
