### PR TITLE
[WIP] [DOCFIX] add docs/cn/Clients-S3.md

### PR DESCRIPTION
**Pull request by whatbeg**
add docs/cn/Clients-S3.md, translate a part of it

### CODE REVIEW

**Comment by apc999** [comment]
@whatbeg is this working-in-progress ?

**Comment by yupeng9** [comment]
@whatbeg is this doc ready for review?

**Comment by whatbeg** [comment]
@yupeng9 no, I just translate a part of it, you can assign another developer to translate the full text of it. @apc999

**Comment by whatbeg** [comment]
@yupeng @apc999 ok, now I have free time, i will complete this translation. : )

**Comment by whatbeg** [comment]
OK, PR #6215 has finished the work, I'll close this PR later.

**Pull request closed without merging**
