### PR TITLE
Replace the FOLDER_SUFFIX from "_$folder$" to "/" in OSS UFS

### PR DESCRIPTION
**Pull request by Jackson-Wang-7**
### What changes are proposed in this pull request?
Replace the FOLDER_SUFFIX from "_$folder$" to "/" in OSS UFS

### Why are the changes needed?
We don't want to use '_$ Folder $" to represent the directory. We want to use a more general "/" instead to avoid some issues

### Does this PR introduce any user facing changes?
No

### CODE REVIEW

**Comment by Jackson-Wang-7** [comment]
@huanghua78 @yyongycy I have tested the basic operations with "/" in OSS. Deleting, listing, reading, and writing files are all normal.

**Comment by yyongycy** [comment]
Please do some preliminary tests.

**Review by yyongycy — APPROVED** [review]
LGTM

**Review by huanghua78 — APPROVED** [review]
LGTM

**Comment by Jackson-Wang-7** [comment]
alluxio-bot, merge this please

**Pull request merged**
