### PR TITLE
Add Job Definition Names to Job Stat command

### PR DESCRIPTION
**Pull request by bradyoo**
@calvinjia 

image

### CODE REVIEW

**Comment by bradyoo** [comment]
This will merge conflict with https://github.com/Alluxio/alluxio/pull/10144

So going to wait for the other one to merge.

**Comment by bradyoo** [comment]
jenkins, test this please

**Comment by calvinjia** [comment]
@bradyoo Could we add the job name to the job summary command as well?

**Comment by bradyoo** [comment]
Oh You want it in the Top 10 List too? Sure.

**Comment by bradyoo** [comment]
Addressed feedback

**Comment by bradyoo** [comment]
@calvinjia: Ping?

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by ZacBlanco** [comment]
@calvinjia should this be in 2.1?

**Comment by bradyoo** [comment]
I didn't think this was very important so I actually didn't document this in my CLI documentation change either.

**Comment by calvinjia** [comment]
@ZacBlanco Yeah

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please.

**Pull request merged**
