### PR TITLE
Fix Alluxio Tarball in Dockerfile to latest version

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
CC: @ZacBlanco 

Also, can someone add the v2.1.0 label as well?

**Comment by ZacBlanco** [comment]
Maybe not for this PR but, frankly I think we should just get rid of the URL in the dockerfile and force the user to specify a download. This is at least the 3rd time we (read, I) have missed an update to an arbitrary URL in our codebase

**Comment by bradyoo** [comment]
alluxio-bot, test this please.

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Comment by ZacBlanco** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please

**Pull request merged**
