### PR TITLE
Use static imports for standard test utilities in /alluxio/core/commo…

### PR DESCRIPTION
**Pull request by HelloHorizon**
…n/src/test/java/alluxio/util/executor/ControllableSchedulerTest.java

### CODE REVIEW

**Comment by HelloHorizon** [comment]
alluxio-bot, check this please

**Comment by HelloHorizon** [comment]
@yuzhu please take a look.

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
