### PR TITLE
[SMALLFIX] upgrade commons-lang's version to 2.6

### PR DESCRIPTION
**Pull request by peisun1115**
upgrade commons-lang's version to 2.6. We are compiling commons-lang to our client jars (with dependency). Spark uses 2.6 which has a function ClassUtils#isAssignable(a, b, c) that doesn't appear in 2.4

stack trace:
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.NoSuchMethodError: org.apache.commons.lang.ClassUtils.isAssignable([Ljava/lang/Class;[Ljava/lang/Class;Z)Z
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$makeCopy$1$$anonfun$7.apply(TreeNode.scala:393)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$makeCopy$1$$anonfun$7.apply(TreeNode.scala:384)
  at scala.collection.IndexedSeqOptimized$$anonfun$1.apply(IndexedSeqOptimized.scala:50)
  at scala.collection.IndexedSeqOptimized$$anonfun$1.apply(IndexedSeqOptimized.scala:50)
  at scala.collection.IndexedSeqOptimized$class.segmentLength(IndexedSeqOptimized.scala:195)
  at scala.collection.mutable.ArrayOps$ofRef.segmentLength(ArrayOps.scala:186)
  at scala.collection.GenSeqLike$class.prefixLength(GenSeqLike.scala:93)
  at scala.collection.mutable.ArrayOps$ofRef.prefixLength(ArrayOps.scala:186)
  at scala.collection.IndexedSeqOptimized$class.find(IndexedSeqOptimized.scala:50)
  at scala.collection.mutable.ArrayOps$ofRef.find(ArrayOps.scala:186)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$makeCopy$1.apply(TreeNode.scala:384)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$makeCopy$1.apply(TreeNode.scala:373)
  at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:49)
  at org.apache.spark.sql.catalyst.trees.TreeNode.makeCopy(TreeNode.scala:373)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:357)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:270)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:270)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:270)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:307)
  at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
  at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
  at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
  at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)

### CODE REVIEW

**Comment by peisun1115** [comment]
@calvinjia

**Comment by calvinjia** [comment]
What's the change between 2.4 and 2.6? Do you know if it will impact any code/dependencies we have?

**Comment by peisun1115** [comment]
@calvinjia 
http://commons.apache.org/proper/commons-lang/release-notes/RELEASE-NOTES-2.5.txt
http://commons.apache.org/proper/commons-lang/release-notes/RELEASE-NOTES-2.6.txt

* [        ] - ClassUtils - new isAssignable() methods with autoboxing is the one that is causing problem.

I don't know whether it will impact any code/dependencies we have... How do you usually test that?

**Comment by calvinjia** [comment]
@peisun1115 
It looks like all the changes are additions/backward compatible.

**Comment by jsimsa** [comment]
LGTM (modulo tests passing)

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
