### PR TITLE
[SMALLFIX] Do not override read type for copyToLocal/cp/cat fs commands

### PR DESCRIPTION
**Pull request by madanadit**

### CODE REVIEW

**Comment by calvinjia** [comment]
@madanadit Thanks for the improvement, should this also apply to other commands like `head`?

**Comment by madanadit** [comment]
@calvinjia `head` and `tail` are 2 commands I left out. I did so since these commands are mostly used only for testing / verification of an output. However, I don't feel strongly about this. I can apply the change to the 2 as well for consistency. what do you think?

**Comment by calvinjia** [comment]
Since we have async partial caching, the won't be much of a performance hit. Though I think ideally we would default all our CLI commands to `NO_CACHE` and only cache when the user explicitly specifies so.

**Comment by aaudiber** [comment]
I think the #1 goal here should be consistency. Otherwise users will be unpleasantly surprised when one command caches and the next doesn't. At first glance, `head` and `tail` seem like file reads, so it makes sense for caching behavior to follow `alluxio.user.file.readtype.default`.

If we think the common case for shell operations is to not want to cache, we need to split the default read type into on property for the shell and another property for everything else.

**Comment by madanadit** [comment]
@aaudiber @calvinjia

**Pull request merged**
