### PR TITLE
Fix logging error in ActiveSync

### PR DESCRIPTION
**Pull request by yuzhu**
Fix the counting of events for ActiveSync logging

### CODE REVIEW

**Comment by yuzhu** [comment]
@madanadit Thanks for catching this
@ZacBlanco FYI, this is going to 2.1.2

**Comment by ZacBlanco** [comment]
can you add a comment about what this fixes in the PR description?

**Comment by madanadit** [comment]
@bf8086 fyi

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
test failure not related to the change..

**Comment by madanadit** [comment]
```
Tests in error: 
alluxio.client.metrics.MetricsHeartbeatContextTest.testContextCounter(alluxio.client.metrics.MetricsHeartbeatContextTest)
  Run 1: MetricsHeartbeatContextTest.testContextCounter:110 » Runtime alluxio.exception...
  Run 2: MetricsHeartbeatContextTest.testContextCounter:110 » Runtime alluxio.exception...
```

**Comment by madanadit** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
`alluxio.client.metrics.MetricsHeartbeatContextTest
testContextCounter(alluxio.client.metrics.MetricsHeartbeatContextTest)  Time elapsed: 22.68 sec  <<< ERROR!
java.lang.RuntimeException: alluxio.exception.status.InternalException: Channel authentication failed with code:INTERNAL. ChannelKey: Channel{ClientType=MasterInquireClient, ClientHostname=3505bfe1bc30, ServerAddress=GrpcServerAddress{HostName=master2, SocketAddress=master2:19998}, ChannelId=c41dcae8-8a8b-483e-a9d4-440287aa1756}, AuthType: SIMPLE, Error: alluxio.exception.status.InternalException
	at alluxio.client.metrics.MetricsHeartbeatContextTest.testContextCounter(MetricsHeartbeatContextTest.java:110)
Caused by: alluxio.exception.status.InternalException: Channel authentication failed with code:INTERNAL. ChannelKey: Channel{ClientType=MasterInquireClient, ClientHostname=3505bfe1bc30, ServerAddress=GrpcServerAddress{HostName=master2, SocketAddress=master2:19998}, ChannelId=c41dcae8-8a8b-483e-a9d4-440287aa1756}, AuthType: SIMPLE, Error: alluxio.exception.status.InternalException
	at alluxio.client.metrics.MetricsHeartbeatContextTest.testContextCounter(MetricsHeartbeatContextTest.java:110)
Caused by: alluxio.exception.status.InternalException
	at alluxio.client.metrics.MetricsHeartbeatContextTest.testContextCounter(MetricsHeartbeatContextTest.java:110)
Caused by: java.lang.NullPointerException
	at alluxio.client.metrics.MetricsHeartbeatContextTest.testContextCounter(MetricsHeartbeatContextTest.java:110)
testContextCounter(alluxio.client.metrics.MetricsHeartbeatContextTest)  Time elapsed: 1.401 sec  <<< ERROR!
java.lang.RuntimeException: alluxio.exception.status.InternalException: Channel authentication failed with code:INTERNAL. ChannelKey: Channel{ClientType=MasterInquireClient, ClientHostname=3505bfe1bc30, ServerAddress=GrpcServerAddress{HostName=master2, SocketAddress=master2:19998}, ChannelId=46ec795c-4cae-40f6-9683-03f24a88f66f}, AuthType: SIMPLE, Error: alluxio.exception.status.InternalException
	at alluxio.client.metrics.MetricsHeartbeatContextTest.testContextCounter(MetricsHeartbeatContextTest.java:110)
Caused by: alluxio.exception.status.InternalException: Channel authentication failed with code:INTERNAL. ChannelKey: Channel{ClientType=MasterInquireClient, ClientHostname=3505bfe1bc30, ServerAddress=GrpcServerAddress{HostName=master2, SocketAddress=master2:19998}, ChannelId=46ec795c-4cae-40f6-9683-03f24a88f66f}, AuthType: SIMPLE, Error: alluxio.exception.status.InternalException
	at alluxio.client.metrics.MetricsHeartbeatContextTest.testContextCounter(MetricsHeartbeatContextTest.java:110)
Caused by: alluxio.exception.status.InternalException
	at alluxio.client.metrics.MetricsHeartbeatContextTest.testContextCounter(MetricsHeartbeatContextTest.java:110)
Caused by: java.lang.NullPointerException
	at alluxio.client.metrics.MetricsHeartbeatContextTest.testContextCounter(MetricsHeartbeatContextTest.java:110)`

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please

**Pull request merged**
