### PR TITLE
Fix unnecessary judgement

### PR DESCRIPTION
**Pull request by bzheng888**
### What changes are proposed in this pull request?
Remove an unnecessary judgement.

### Why are the changes needed?
The judgement is redundant, need to remove
### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

### CODE REVIEW

**Review by maobaolong — APPROVED** [review]
Good catch, 👍， @LuQQiu please take another look, thank you.

**Review by apc999 — APPROVED** [review]
thanks for the improvement

**Comment by maobaolong** [comment]
The failed is from jacoco with an error which is not related to this PR.

```
02:04:14.132 [INFO] ------------------------------------------------------------------------
Error: 4.150 [ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.5:report (default-cli) on project alluxio-integration-jnifuse-native: An error has occurred in JaCoCo report generation.: Error while creating report: malformed input around byte 2 -> [Help 1]
Error: 4.151 [ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.5:report (default-cli) on project alluxio-hub-transport: An error has occurred in JaCoCo report generation.: Error while creating report: malformed input around byte 2 -> [Help 1]
Error: 4.153 [ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.5:report (default-cli) on project alluxio-core-transport: An error has occurred in JaCoCo report generation.: Error while creating report: malformed input around byte 2 -> [Help 1]
```

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
