### PR TITLE
Stop only grpc server when a master lose primary

### LINKED ISSUE #13740: Not restart web server to improve leader-follower switching performance
**Is your feature request related to a problem? Please describe.**
When I set the following configuration
alluxio.master.embedded.journal.election.timeout=1s
alluxio.master.embedded.journal.heartbeat.interval=100ms
It takes about 20s to switch the leader. From the logs and I find that it takes about 15 s to start the jetty server.

**Describe the solution you'd like**
 is it possible not restart the web server when changing leader to improve the switching speed.

**Describe alternatives you've considered**

**Urgency**
Urgency.

**Additional context**

### LINKED ISSUE #13840: Non Leader master should also start web server
**Is your feature request related to a problem? Please describe.**

- When ha didn't work as expected, or the leader didn't transfer to a new master, there are no leader that time, so we want to the the stacks from web page.

- We want to scrap the metrics of non-leader masters by prometheus, to monitor the gc, heap, and some other metrics of it.

**Describe the solution you'd like**

Start the web server all the time, although it isn't leader.

**Describe alternatives you've considered**

Start the web server all the time, although it isn't leader.

**Urgency**
High

**Additional context**
No

### PR DESCRIPTION
**Pull request by qian0817**
### What changes are proposed in this pull request?

Only stop grpc server when a master lose primary. 

fix #13740 
fix #13840 

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. improve leader-follower switching performance
  2. can get metrics info although master is not leader.
 
### Does this PR introduce any user facing changes?

can use follower master address to use webui.

### CODE REVIEW

**Comment by maobaolong** [comment]
This seems similar to #13905 ?

**Comment by maobaolong** [comment]
> This seems similar to #13905 ?

>> Sorry for not noticing this PR before, so now what showld I do with my PR. Should i close it?

@jiacheliu3 @bzheng888 Do you have some suggestion or discussion?

**Comment by jiacheliu3** [comment]
@maobaolong @qian0817 So great minds think alike :)

#13905 will add a design doc open for discussion (not added yet), @qian0817 please join us there for the discussion on the feature design. @maobaolong This PR has a different view as #13905 , as it implemented a `RedirectFilter` for HTTP requests and forward it to the current primary. If eventually we want the behavior to be redirecting to the primary, a `RedirectFilter` like this PR is the way to go. You guys can discuss further in the design doc. @qian0817 pls keep an eye on the updates in #13905 

We can close this PR in favor of #13905 . Actually I'll close #13184 too for the same reason.

**Comment by apc999** [comment]
@jiacheliu3 @maobaolong  what's the decision? do we move forward on this PR?

**Comment by jiacheliu3** [comment]
Closed in favor of https://github.com/Alluxio/alluxio/pull/13905

**Pull request closed without merging**
