### PR TITLE
[ALLUXIO-2259]remove alluxio.Constants.DEFAULT_HOST_RESOLUTION_TIMEOUT_MS from Constants.java

### PR DESCRIPTION
**Pull request by Zhangcy0722**
https://alluxio.atlassian.net/browse/ALLUXIO-2259

### CODE REVIEW

**Comment by Zhangcy0722** [comment]
alluxio-bot, check this please' to re-run checks

**Comment by Zhangcy0722** [comment]
alluxio-bot, check this please

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
Jenkins, test this please

**Pull request merged**
