### PR TITLE
Lock mount table while reverse resolving

### PR DESCRIPTION
**Pull request by ggezer**
Reverse-resolving a path was not safe against concurrent updates to the mount table.

### CODE REVIEW

**Review by yuzhu — APPROVED** [review]
thanks for fixing this.

**Comment by ggezer** [comment]
alluxio-bot, merge this please

**Comment by ggezer** [comment]
@beinan fyi.

**Comment by madanadit** [comment]
@ggezer cherry-pick to 2.6?

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.6 please

**Pull request merged**
