### PR TITLE
Fix absent cache stats are always zero

### PR DESCRIPTION
**Pull request by dbw9580**
### What changes are proposed in this pull request?

Fix the absent cache stats which are always zero.

### Why are the changes needed?

From the doc on `Cache::stats()`:

> Returns a current **snapshot** of this cache's cumulative statistics, or a set of default values if the cache is not recording statistics. All statistics begin at zero and never decrease over the lifetime of the cache.
**Warning**: this cache may not be recording statistical data. For example, a cache created using CacheBuilder only does so if the CacheBuilder.recordStats method was called. If statistics are not being recorded, a CacheStats instance with zero for all values is returned.

This fix

1. enables stats collection on the cache
2. retrieves a new snapshot every time the gauge is polled, instead of the stale value captured by the lambda.

### Does this PR introduce any user facing changes?

Yes, the metrics are fixed.

### CODE REVIEW

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks for the catch!

**Review by yuzhu — APPROVED** [review]

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by dbw9580** [comment]
@Xenorith cherry-pick this to 2.8, please.

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Comment by jenoudet** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
