### PR TITLE
Fix logging to capture jobControlId

### PR DESCRIPTION
**Pull request by deepak-shivamurthy**
### What changes are proposed in this pull request?

https://github.com/Alluxio/new-contributor-tasks/issues/643
Fix logging to capture jobControlId 

### Why are the changes needed?

this will help in getting jobControlId in the logs, and will help in getting status information about the job

### Does this PR introduce any user facing changes?

its just log level changes

### CODE REVIEW

**Review by jja725 — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by jja725** [comment]
Please fix the style, you can get related information here https://docs.alluxio.io/os/user/edge/en/contributor/Code-Conventions.html

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Pull request merged**
