### PR TITLE
[SMALLFIX]Correct deleteUnrevisioned flag logic

### PR DESCRIPTION
**Pull request by maobaolong**

### CODE REVIEW

**Comment by aaudiber** [comment]
@maobaolong can you describe what you're using the script for?

The intention of the "deleteUnrevisioned" flag is to enable people to add new files and then generate tarballs which include them. If we don't run `git clean -fdX`, the project will contain ignored files that don't belong in a distribution. 

The name "deleteUnrevisioned" is misleading because even with `deleteUnrevisioned=false`, we still delete unrevisioned files if they are ignored by `.gitignore`. `deleteIgnoredOnly` might be a better name.

**Comment by maobaolong** [comment]
I just want use the tarball script to generate a `tar.gz` package but, the mvn command in this script is hard code, i want to separate build and package to two step, and do not use this script to execute build.

And  if the if branch and else branch are same, `if [[ "${delete_unrevisioned}" == true ]]; then` is useless. i want to use this `prepare_repo` function and don't want to delete the `**target`, because i don't execute build here.

**Comment by aaudiber** [comment]
One branch uses the `x` flag lowercase and the other uses `X` uppercase. The difference is that the uppercase version only deletes explicitly ignored files, so it makes sense when building a local change for testing purposes. The lowercase `x` deletes all untracked files, so it makes sense when trying to build a pristine version of the repository, e.g. for final release testing purposes.

**Comment by maobaolong** [comment]
@aaudiber I see, thank you for your clearly explanation.

**Pull request closed without merging**
