### PR TITLE
[DOCFIX] Fix POSIX API doc

### PR DESCRIPTION
**Pull request by LuQQiu**
Improve POSIX API doc

### CODE REVIEW

**Review by ssz1997 — APPROVED** [review]
LGTM

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
@Xenorith Please cherry-pick this to branch-2.8

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Pull request merged**
