### PR TITLE
Add config check for alluxio.master.ttl.checker.interval at start time

### PR DESCRIPTION
**Pull request by MEILIDEKCL**
### What changes are proposed in this pull request?
#17405
And this pr is from #17408

### Why are the changes needed?

add pre-check for alluxio.master.ttl.checker.interval, to avoid resources waste when starting alluxio.

### CODE REVIEW

**Review by maobaolong — CHANGES_REQUESTED** [review]
This looks you add a checker into a generic place, suggest to use` PropertyKey$Builder#setValueValidationFunction` to achieve your purpose.

**Comment by MEILIDEKCL** [comment]
> This looks you add a checker into a generic place, suggest to use` PropertyKey$Builder#setValueValidationFunction` to achieve your purpose.

Yeah, you mean I need add `setValueValidationFunction` on the `PropertyKey` of  `MASTER_TTL_CHECKER_INTERVAL_MS`. But  I just find one function `CHECK_FILE_EXISTS` in `PropertyKey.java`. So if I add one function to this file, will it cause an inconsistent code style? 
And, I think adding it into a generic place is more reasonable.
So, how about your idea? Thank you so much.

**Comment by MEILIDEKCL** [comment]
And, `PropertyKey$Builder#setValueValidationFunction` looks like for the validation of default value. But in this situation, we need to check the user conf rather than the default conf.

**Comment by MEILIDEKCL** [comment]
@jiacheliu3 Could you have a look? Thanks!

**Pull request closed without merging**
