### PR TITLE
[DOCFIX] Update overview diagram

### PR DESCRIPTION
**Pull request by Xenorith**
update the diagram in Overview landing page with relevant integrations and APIs

### CODE REVIEW

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.6 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to release-2.6.0 please

**Pull request merged**
