### PR TITLE
Update run_docker.sh with alluxio-maven:0.0.4

### PR DESCRIPTION
**Pull request by Xenorith**

### CODE REVIEW

**Comment by Xenorith** [comment]
jenkins, test this please

**Comment by Xenorith** [comment]
@ZacBlanco okay this is good to go. had to update the PR job config in jenkins to not force usage of 0.0.3, now it'll use whichever one is set in run_docker.sh so it'll keep using 0.0.3 before this commit

**Comment by ZacBlanco** [comment]
Thanks for the info

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Pull request merged**
