### PR TITLE
Fix Fuse remove dir not empty error code

### PR DESCRIPTION
**Pull request by LuQQiu**
### What changes are proposed in this pull request?

Remove directory return correct error code when failed to delete directory because directory not empty

### Why are the changes needed?

Pjdfstest
expect 0 mkdir ${n0} 0755
create_file ${type} ${n0}/${n1}
expect "EEXIST|ENOTEMPTY" rmdir ${n0}
### Does this PR introduce any user facing changes?
Clear error message

### CODE REVIEW

**Review by ssz1997 — COMMENTED** [review]
Does it make sense to make all `deletePath` behave the same as the new `rmInternal`?

**Comment by yyongycy** [comment]
So this is just to fix the return value, not actually logic?

**Comment by LuQQiu** [comment]
@ssz1997 @yyongycy yeah, just fixing the return code, no actual logic
emmm, our internal code is mainly throw exception when failed, but fuse at the outtest level wants to return error code. If changing deletePath to return error code, it conflicts our common convention of throwing exceptions

**Comment by LuQQiu** [comment]
@ssz1997 @yyongycy PTAL, thanks

**Review by yyongycy — APPROVED** [review]
lgtm

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
