### PR TITLE
Fix memory leak caused by OOM when parsing write request

### PR DESCRIPTION
**Pull request by qian0817**
### What changes are proposed in this pull request?

Fix memory leak caused by OOM when parsing write request.

### Why are the changes needed?
When the following OOM error occurs, we find that the direct memory here is not freed correctly.

screentshot

### Does this PR introduce any user facing changes?

No user facing changes.

### CODE REVIEW

**Comment by dbw9580** [comment]
Can you please describe why this can cause a leak, and why the proposed change can fix it?

**Comment by qian0817** [comment]
> Can you please describe why this can cause a leak, and why the proposed change can fix it?


The `CompositeByteBuf` class has the following code:
```java
public CompositeByteBuf addComponent(boolean increaseWriterIndex, int cIndex, ByteBuf buffer) {
    checkNotNull(buffer, "buffer");
    addComponent0(increaseWriterIndex, cIndex, buffer);
    consolidateIfNeeded();
    return this;
}
private void consolidateIfNeeded() {
    // Consolidate if the number of components will exceed the allowed maximum by the current
    // operation.
    int size = componentCount;
    if (size > maxNumComponents) {
        consolidate0(0, size);
    }
}
private void consolidate0(int cIndex, int numComponents) {
    if (numComponents <= 1) {
        return;
    }

    final int endCIndex = cIndex + numComponents;
    final int startOffset = cIndex != 0 ? components[cIndex].offset : 0;
    final int capacity = components[endCIndex - 1].endOffset - startOffset;
    final ByteBuf consolidated = allocBuffer(capacity);

    for (int i = cIndex; i < endCIndex; i ++) {
        components[i].transferTo(consolidated);
    }
    lastAccessed = null;
    removeCompRange(cIndex + 1, endCIndex);
    components[cIndex] = newComponent(consolidated, 0);
    if (cIndex != 0 || numComponents != componentCount) {
        updateComponentOffsets(cIndex);
    }
}
```
It will try to consolidate a part of the ByteBuf when the number of butebuf exceeds the componentCount value and involves the behavior of direct memory allocation in it. If an OOM occurs here, then the current logic cannot handle the newly allocated memory and it will not be released. This PR prevents the consolidation behavior during this process to avoid memory leaks.

**Comment by dbw9580** [comment]
Thanks for the explanation.

While I understand that this patch can avoid an OOM at this specific call site, the actual cause of the memory leak is not here. The worker is at the brink of OOM because somewhere else has been leaking memory, and this happens to be the victim that triggers the OOM.

The fix itself is very hacky and obscure (mostly due to this whole part of code is doing all kinds of hacky things to avoid copies between gRPC and internal buffers), and hard to maintain. I'll recommend trying other ongoing approaches to fix (or alleviate) the memory leaks, e.g. https://github.com/Alluxio/alluxio/pull/16461 a new NIO bytebuffer-backed memory pool, and see if it helps with the leak.

**Comment by jiacheliu3** [comment]
@qian0817 @dbw9580 can you pls update why this is closed? Thx

**Pull request closed without merging**
