### PR TITLE
[ALLUXIO-3015]update jets3t version from 0.8.1 to 0.9.4 to meet only signature v4 in cn-north-1 aws s3 region

### PR DESCRIPTION
**Pull request by neuwzm**
https://alluxio.atlassian.net/browse/ALLUXIO-3015
update jets3t to 0.9.4 fix the problem alluxio can not mount aws s3 region cn-north-1 in china  , because jets3t version 0.8.1 do not support signature V4, AWS other regions support both signature V2 & V4 while cn-north-1 is a new region which only support signature V4.

### CODE REVIEW

**Comment by neuwzm** [comment]
alluxio-bot, check this please

**Comment by neuwzm** [comment]
@alluxio-bot alluxio-bot, check this please

**Comment by neuwzm** [comment]
alluxio-bot, check this please

**Comment by neuwzm** [comment]
alluxio-bot, check this please

**Comment by madanadit** [comment]
Hi @neuwzm, we have moved the legacy s3n connector to a new repository (https://github.com/Alluxio/alluxio-extensions/tree/master/underfs/s3n). Branch-1.6 has documentation updates for the same:
- http://www.alluxio.org/docs/master/en/UFSExtensions.html
- http://www.alluxio.org/docs/master/en/DevelopingUFSExtensions.html

On another note, we recommend using the S3A connector (https://github.com/Alluxio/alluxio/tree/master/underfs/s3a) to connect to object stores supporting the S3 API.

**Comment by neuwzm** [comment]
alluxio-bot, check this please

**Comment by neuwzm** [comment]
@apc999 ok . I see  thx!  I will change it to the alluxio-extensions repository

**Comment by apc999** [comment]
thanks @neuwzm  I will close this PR then.

**Pull request closed without merging**
