### PR TITLE
[TACHYON-1153] Fix HdfsUnderFileSystem getSpace

### PR DESCRIPTION
**Pull request by vesense**
Fix HdfsUnderFileSystem.getSpace using FileSystem.getStatus() instead of Deprecated DistributedFileSystem.getDiskStatus

### CODE REVIEW

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
ok to test

**Comment by calvinjia** [comment]
@vesense Thanks for the patch, but I don't think this API is available in Hadoop 1.x? Will the user be able to compile against older versions of hadoop?

**Comment by apc999** [comment]
@vesense , should Tachyon raise Hadoop support to 2.x for 0.9-snapshot?

**Comment by vesense** [comment]
@calvinjia  @apc999 
Sorry I took so long to respond.  Yes, I think we should drop hadoop 1.x version for 0.9.0-SNAPSHOT, in order to better support new hadoop version.

**Comment by calvinjia** [comment]
@vesense I don't think its justified to drop support for hadoop 1.x for a minor improvement in the api used. Are there any significant advantages in using 2.x only apis?

**Comment by yupeng9** [comment]
@vesense I'm closing this, and let me know if you want to continue the work on it.

**Pull request closed without merging**
