### PR TITLE
Add metrics for cache hit/miss

### PR DESCRIPTION
**Pull request by calvinjia**
Adds 3 metrics
number of bytes read from local cache
number of bytes read from external store
number of bytes requested from external store (may be less than bytes read because we read full pages)

### CODE REVIEW

**Comment by calvinjia** [comment]
@apc999 Yeah we should add more metrics over time, I would prefer to merge this PR first so we can have an example of how metrics are added in code and consumed by users.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by LuQQiu** [comment]
@calvinjia  is number of bytes read from local cache + number of bytes read from external store = existing number of bytes read from alluxio

**Comment by calvinjia** [comment]
@LuQQiu It's not quite equivalent, since we read additional data.

Local Cache + External Requested = # User requested bytes (through read api)
Local Cache + External Read = true # of bytes read

**Pull request merged**
