### PR TITLE
Bump commons-compress from 1.16.1 to 1.19

### PR DESCRIPTION
**Pull request by bradyoo**
Bump to address vulnerability:
https://github.com/advisories/GHSA-53x6-4x5p-rrvv

### CODE REVIEW

**Comment by bradyoo** [comment]
alluxio-bot, test this please.

**Comment by bradyoo** [comment]
@gpang can you merge this for me?

**Comment by ZacBlanco** [comment]
don't merge yet - I'm working on cutting the branch and updating versions in master - I will ping back here when it can be merged

**Comment by ZacBlanco** [comment]
ok, good to merge

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
