### PR TITLE
Use block size to request cache space

### PR DESCRIPTION
**Pull request by apc999**

### CODE REVIEW

**Comment by apc999** [comment]
@calvinjia this PR changes the initial tmp block size on caching UFS blocks. I'm thinking that given the current default block size is much smaller (256MB->64MB), shall we actually just request the default block size on both creating new blocks in addition to caching blocks from UFS or remote workers?

**Comment by calvinjia** [comment]
@apc999 I think for new blocks, it should be `min(10 MB, blocksize)`. For making the default reservation equal to block size, I think that requires some more consideration.

**Comment by ZacBlanco** [comment]
@calvinjia @apc999 is this PR still on the table? If not, can we close it?

**Comment by apc999** [comment]
@calvinjia  I actually think this PR is still valid at least for UFS blocks (which we know the size in ahead). This can strictly reduce the overhead to pressure worker at least from UFS reads.

**Pull request closed without merging**
