### PR TITLE
Add NoSuchObjectException for no object found exception

### PR DESCRIPTION
**Pull request by HelloHorizon**
e.g. exception for getTable() (no such table), getDatabase() (no such database)

### CODE REVIEW

**Comment by HelloHorizon** [comment]
@yuzhu please check this

**Comment by HelloHorizon** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
@gpang for classes like additional exceptions, should we move these into the `experimental` module?

**Comment by apc999** [comment]
we typically don't add new exceptions. is this required?
If possible, we want to standardize on `AlluxioStatusException`

**Comment by apc999** [comment]
Suggest to return `alluxio.exception.status.NotFoundException`

**Comment by HelloHorizon** [comment]
@apc999 Good suggestion! I will try to reuse the alluxio.exception.status.NotFoundException.

**Pull request closed without merging**
