### PR TITLE
Remove deprecated FaultTolerantFileSystem or alluxio-ft://

### PR DESCRIPTION
**Pull request by apc999**
alluxio-ft:// has been removed functionality-wise a long time ago. 
now really remove the code since we are after 2.0

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
@apc999 Thanks for getting rid of this

**Pull request merged**
