### PR TITLE
[ALLUXIO-2143] Improve comment for NonUniqueFieldIndexIterator mIndexIterator

### PR DESCRIPTION
**Pull request by huzijian**
https://alluxio.atlassian.net/browse/ALLUXIO-2143
I just update the Iterator to iterator

### CODE REVIEW

**Comment by apc999** [comment]
"Commits associated with Github account: false
It looks like your commits on GitHub aren't linked to a valid Github account yet. Your commits are made with the email zijianhu@jianhus-macbook-pro.local, which is not associated with your Github account. For us to properly credit your contributions, could you please set up your Github account by following the Github instructions here?"

**Comment by apc999** [comment]
alluxio-bot, check this please

**Comment by apc999** [comment]
+1 LGTM
thanks for the contribution.

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Pull request merged**
