### PR TITLE
Simplify MigrateDefinition

### PR DESCRIPTION
**Pull request by bradyoo**
DistributedCp and DistributedMv now no longer needs the complicated folder to folder operation and now only handles file to file. Removing a bunch of code that does folder to folder work.

### CODE REVIEW

**Comment by bradyoo** [comment]
@gpang ping

**Comment by bradyoo** [comment]
Since gene seems busy, I'll give it to @yuzhu

**Review by yuzhu — APPROVED** [review]
LGTM

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Pull request merged**
