### PR TITLE
[SMALLFIX] Correct the property name in the helm charts

### PR DESCRIPTION
**Pull request by sighingnow**
### What changes are proposed in this pull request?

Fixes a typo in alluxio helm charts.

### Why are the changes needed?

The typo prevents us from passing custom mount options (e.g, `allow_other`) to alluxio's helm charts.

### Does this PR introduce any user facing changes?

None.

### CODE REVIEW

**Comment by sighingnow** [comment]
alluxio-bot, check this please

**Review by jiacheliu3 — APPROVED** [review]
Thanks for the fix! The change looks good.
Could you also update the version in https://github.com/Alluxio/alluxio/blob/566ecd260b7424d42a40dfcaf9349e8940d1fa2c/integration/kubernetes/helm-chart/alluxio/Chart.yaml#L15 and https://github.com/Alluxio/alluxio/blob/master/integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
Will merge once the versions are updated. Thx!

**Comment by sighingnow** [comment]
> Thanks for the fix! The change looks good. Could you also update the version in
> 
> https://github.com/Alluxio/alluxio/blob/566ecd260b7424d42a40dfcaf9349e8940d1fa2c/integration/kubernetes/helm-chart/alluxio/Chart.yaml#L15
> 
> and https://github.com/Alluxio/alluxio/blob/master/integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
> Will merge once the versions are updated. Thx!

Done.

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks for the fix! Will merge on tests passing.

**Comment by sighingnow** [comment]
The failed test case seems a network error and is not related to changes in this PR.

**Comment by jiacheliu3** [comment]
One failed test due to flakeness
```
Error: 1.650 [ERROR] Errors: 
Error: 1.650 [ERROR] alluxio.server.ft.journal.JournalBackupIntegrationTest.backupDelegationFailoverProtocol
Error: 1.650 [ERROR]   Run 1: JournalBackupIntegrationTest.backupDelegationFailoverProtocol:288->lambda$backupDelegationFailoverProtocol$1:290 » TestTimedOut
Error: 1.650 [ERROR]   Run 2: JournalBackupIntegrationTest.backupDelegationFailoverProtocol:314 expected:<0> but was:<1>
```

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by sighingnow** [comment]
> alluxio-bot, merge this please

Thank you @jiacheliu3 ~

**Pull request merged**
