### PR TITLE
Add the descriptions of JAVA_OPTS in alluxio-env.sh.template

### PR DESCRIPTION
**Pull request by swg-liuge**
### What changes are proposed in this pull request?

add the descriptions of ALLUXIO_JOB_MASTER_JAVA_OPTS and ALLUXIO_JOB_WORKER_JAVA_OPTS

### Why are the changes needed?

Better help others to configure the environment

### Does this PR introduce any user facing changes?

no

### CODE REVIEW

**Comment by flaming-archer** [comment]
LGTM

**Comment by swg-liuge** [comment]
@ggezer could you help to review this pr? thanks a lot.

**Review by apc999 — APPROVED** [review]

**Comment by swg-liuge** [comment]
@apc999  thanks a lot, but  the integration tests failed, could we rerun  it?😿 I think this failure has nothing to do with this pr 😿

**Review by yuzhu — APPROVED** [review]

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
@swg-liuge thanks for noting that one of the integration tests failed. next time it would be great if you could copy the unit test failure, then one of the maintainers can either ask you to look into the failure or quickly confirm that it is not introduced by your PR. hopefully these flakey integration tests will not be a long term issue because we are actively trying to resolve them, thanks for your patience

**Comment by yuzhu** [comment]
Run 1: FileOutStreamIntegrationTest.cancelWrite:248 expected:<0> but was:<3000> is a known failure

**Pull request merged**
