### PR TITLE
[ALLUXIO-2334] Mark class DefaultAsyncPersistHandler with keyword "final"

### PR DESCRIPTION
**Pull request by UniqueAndys**
https://alluxio.atlassian.net/browse/ALLUXIO-2334
Mark class DefaultAsyncPersistHandler with keyword "final"

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by aaudiber** [comment]
Jenkins, test this please

**Comment by aaudiber** [comment]
The test failure looks unrelated to this PR

**Pull request merged**
