### PR TITLE
Make configuration source of truth in AlluxioFuse

### PR DESCRIPTION
**Pull request by LuQQiu**
### What changes are proposed in this pull request?

Make configuration the source of truth.
CLI inputs will overwrite configuration.

### Why are the changes needed?

Ease the configuration and fuse options logics in AlluxioFuse.

### Does this PR introduce any user facing changes?

NA

### CODE REVIEW

**Comment by LuQQiu** [comment]
@ssz1997 i wanted to add three fuse configuration and find it's relatively complicated for moving options from AlluxioConfiguration to fuseOpts.

**Review by ssz1997 — COMMENTED** [review]
I think this makes sense. Please fix the tests though.

**Comment by LuQQiu** [comment]
@yyongycy can you help take a look, thanks!

**Review by yyongycy — APPROVED** [review]
LGTM

**Pull request merged**
