### PR TITLE
[DOCFIX] Add Unit-Testing.md of the Chinese version

### PR DESCRIPTION
**Pull request by JiangXiNJU**
https://alluxio.atlassian.net/browse/ALLUXIO-2243

### CODE REVIEW

**Comment by saltylin** [comment]
ok to test

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
@JiangXiNJU thank you for the translation! This PR looks great.

Can you please sign the [contribution license agreement](http://cla.alluxio.org/). It's all electronic and will take just minutes.

**Comment by JiangXiNJU** [comment]
@ifcharming I have tried to sign the contribution license agreement. But each time when I click "REVIEW DOCUMENT" in the received email, the following page shows up.
aa
The required address in this page seems to be only valid in US. But I am in China and then I get the error page below.
bb
How could I sign the agreement correctly?

**Comment by calvinjia** [comment]
@JiangXiNJU Could you try signing the CLA again? I think the issue you were seeing should be resolved.

**Comment by apc999** [comment]
LGTM

**Pull request merged**
