### PR TITLE
[ALLUXIO-2144] Update the class comments for IndexDefinition

### PR DESCRIPTION
**Pull request by rootsongjc**
https://alluxio.atlassian.net/browse/ALLUXIO-2144

### CODE REVIEW

**Comment by yupeng9** [comment]
jenkins, test this please

**Comment by yupeng9** [comment]
LGTM

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
Dear @rootsongjc,

It looks like your commits on GitHub aren't linked to a valid Github account yet. For us to properly credit your contributions, could you please set up your Github account by following the Github instructions [here](https://help.github.com/articles/setting-your-email-in-git)?

Thank you for your contribution to Alluxio!

**Comment by aaudiber** [comment]
Ping @rootsongjc

**Comment by calvinjia** [comment]
@rootsongjc any updates on this?

**Comment by aaudiber** [comment]
Closing due to inactivity

**Pull request closed without merging**
