### PR TITLE
[DOCFIX] Update Requirements.md

### PR DESCRIPTION
**Pull request by Xenorith**

### CODE REVIEW

**Comment by Xenorith** [comment]
@LuQQiu @apc999 there are fuse lib version requirements listed; can you double check that these are still accurate, since i've seen some FUSE related changes go in recently?

```
* FUSE installed
  * libfuse 2.9.3 or newer for Linux
  * osxfuse 3.7.1 or newer for MacOS
```

**Review by LuQQiu — APPROVED** [review]
Thanks for updating the doc! @Xenorith I will work on the POSIX API requirements, thanks for reminding me!

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please

**Pull request merged**
