### PR TITLE
Fix worker cannot be ssd only tier in docker issue

### LINKED ISSUE #13601: Cannot launch Alluxio-Worker in docker with SSD only config
**Alluxio Version:**
Alluxio 2.5.0-3

**Describe the bug**
Launch Alluxio docker with SSD only config failed
```
docker run -d --rm \
    --net=host \
    --name=alluxio-worker \
    -v /alluxio:/alluxio \
    -e ALLUXIO_JAVA_OPTS=" \
       -Dalluxio.worker.hostname=ip-172-31-42-134.ec2.internal \
       -Dalluxio.user.hostname=ip-172-31-42-134.ec2.internal \
       -Dalluxio.master.hostname=ip-172-31-47-167.ec2.internal \
       -Daws.accessKeyId=<> \
       -Daws.secretKey=<> \
       -Dalluxio.master.mount.table.root.ufs=s3://<>/ \
       -Dalluxio.master.journal.type=UFS \
       -Dalluxio.master.journal.folder=/alluxio/journal \
       -Dalluxio.worker.tieredstore.levels=1 \
       -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=SSD \
       -Dalluxio.worker.tieredstore.level0.alias=SSD \
       -Dalluxio.worker.tieredstore.level0.dirs.path=/alluxio/alluxio-ssd \
       -Dalluxio.worker.tieredstore.level0.dirs.quota=300GB" \
    -e ALLUXIO_WORKER_JAVA_OPTS=" \
       -Dalluxio.worker.tieredstore.levels=1 \
       -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=SSD \
       -Dalluxio.worker.tieredstore.level0.alias=SSD \
       -Dalluxio.worker.tieredstore.level0.dirs.path=/alluxio/alluxio-ssd \
       -Dalluxio.worker.tieredstore.level0.dirs.quota=300GB" \
    alluxio/alluxio:2.5.0-3 worker
```
When checking the alluxio configuration in the docker container, i saw the alluxio-env.sh contains
```
export ALLUXIO_RAM_FOLDER="/dev/shm"
export ALLUXIO_JAVA_OPTS="        -Dalluxio.worker.hostname=ip-172-31-42-134.ec2.internal        -Dalluxio.user.hostname=ip-172-31-42-134.ec2.internal        -Dalluxio.master.hostname=ip-172-31-47-167.ec2.internal        -Daws.accessKeyId=<>        -Daws.secretKey=<>        -Dalluxio.master.mount.table.root.ufs=s3://<>/        -Dalluxio.master.journal.type=UFS        -Dalluxio.master.journal.folder=/alluxio/journal        -Dalluxio.worker.tieredstore.levels=1        -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=SSD        -Dalluxio.worker.tieredstore.level0.alias=SSD        -Dalluxio.worker.tieredstore.level0.dirs.path=/alluxio/alluxio-ssd        -Dalluxio.worker.tieredstore.level0.dirs.quota=300GB"
```
When deploying alluxio worker via docker, we will use 
```
-e ALLUXIO_JAVA_OPTS="-Dalluxio.property.name=value"
```
According to https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Docker.html, 
Alluxio environment variables will be copied to conf/alluxio-env.sh when the image starts. 

In our [entrypoint.sh](https://github.com/Alluxio/alluxio/blob/master/integration/docker/entrypoint.sh), I saw the following logics
```
  # Only set ALLUXIO_RAM_FOLDER if tiered storage isn't explicitly configured  if [[ -z "${ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH}" ]]; then    # Docker will set this tmpfs up by default. Its size is configurable through the    # --shm-size argument to docker run    export ALLUXIO_RAM_FOLDER=${ALLUXIO_RAM_FOLDER:-/dev/shm}  fi

writeConf # which writes alluxio java opts to the alluxio-env.sh
```

should reverse the previous two logics
**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

### PR DESCRIPTION
**Pull request by LuQQiu**
### What changes were proposed in this pull request?
Fix #13601 
Set alluxio ram folder only if tier 0 is not MEM and tier 0 dir is not set explicitly

### Why are the changes needed?
To enable launching worker with SSD only storage through docker

### Does this PR introduce _any_ user-facing change?
No

### CODE REVIEW

**Review by apc999 — APPROVED** [review]

**Comment by LuQQiu** [comment]
@apc999 PTAL, validated and improved the shell code, thanks
@HelloHorizon FYI

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
@HelloHorizon can you help cherry-pick to branch-2.6?

**Comment by HelloHorizon** [comment]
alluxio-bot, cherry-pick this to branch-2.6 please

**Pull request merged**
