### PR TITLE
Add extra space for K8s env variables

### PR DESCRIPTION
**Pull request by jiacheliu3**
This fix ensures the env JAVA_OPTS defined in K8s ConfigMap all end with a space. 
This change fixes the error where properties are appended to the end of JAVA_OPTS and crush into the last property w/o whitespace.

Sample error: 
```
2019-10-29 00:28:01,972 ERROR ProcessUtils - Uncaught exception while running Alluxio worker @172.31.20.213:29999, stopping it and exiting. Exception "java.lang.RuntimeException: Configuration cannot evaluate value 0.7-Dalluxio.master.metastore.dir=/metastore as double for key alluxio.worker.tieredstore.level0.watermark.low.ratio", Root Cause "null"
java.lang.RuntimeException: Configuration cannot evaluate value 0.7-Dalluxio.master.metastore.dir=/metastore as double for key alluxio.worker.tieredstore.level0.watermark.low.ratio
```
where
`alluxio.worker.tieredstore.level0.watermark.low.ratio` is the last property in `ALLUXIO_WORKER_JAVA_OPTS` in `singleMaster-localJournal/alluxio-configmap.yaml`

This error is resolved by adding a space character to the end of `ALLUXIO_WORKER_JAVA_OPTS`.

### CODE REVIEW

**Comment by madanadit** [comment]
Alternatively, we can fix this in `libexec`. But to reduce the impact at this time, the K8s specific fix is fine.

**Comment by madanadit** [comment]
Created a bug for the `libexec` fix: https://github.com/Alluxio/alluxio/issues/10341

**Comment by madanadit** [comment]
@ZacBlanco Please merge and cherry-pick to branch-2.1 if this looks good to you.

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Comment by ZacBlanco** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please

**Pull request merged**
