### PR TITLE
[DOCFIX] Update sevaral doc pages of Chinese version

### PR DESCRIPTION
**Pull request by njuxiaoqian**

### CODE REVIEW

**Comment by ifcharming** [comment]
ok to test

**Comment by yupeng9** [comment]
LGTM. Thanks for the doc update. Could you also attach a screenshot?

**Comment by njuxiaoqian** [comment]
@yupeng9 Screenshots are below.

hadoop-1
spark-1
spark-2
zeppelin

**Comment by yupeng9** [comment]
Awesome. Thanks.

**Pull request merged**
