### PR TITLE
Port change [#17314] to branch-2.8

### PR DESCRIPTION
**Pull request by jiacheliu3**
Manually cherry pick https://github.com/Alluxio/alluxio/pull/17314

### What changes are proposed in this pull request?

1. Standby job masters register with the primary and report info like version.
2. A command to display all job masters in cluster.
3. Adds supporting code for the above.
4. All job workers report version to the primary job master.
5. Display in command all job worker versions too.

```
✗ bin/alluxio fsadmin report jobservice
Master Address   State    Start Time       Version                          Revision
localhost:20001  PRIMARY  20230425-110043  2.10.0-SNAPSHOT                  ac6a0616
localhost:20021  STANDBY  20230425-110130  2.10.0-SNAPSHOT                  ac6a0616
localhost:20011  STANDBY  20230425-110117  2.10.0-SNAPSHOT                  ac6a0616

Job Worker       Version                          Revision Task Pool Size Unfinished Tasks Active Tasks Load Avg
192.168.3.8      2.10.0-SNAPSHOT                  ac6a0616 10             0                0            9.01904296875, 11.87939453125, 9.30322265625

Status: CREATED   Count: 0
Status: CANCELED  Count: 0
Status: FAILED    Count: 90
Status: RUNNING   Count: 0
Status: COMPLETED Count: 0

10 Most Recently Modified Jobs:
...

10 Most Recently Failed Jobs:
...

10 Longest Running Jobs:
...
```

### Does this PR introduce any user facing changes?

The command output is improved

### CODE REVIEW

**Comment by jiacheliu3** [comment]
all tests passed except checkstyle

**Comment by jiacheliu3** [comment]
failed test is known flake and succeeded in the last run
```
Error: 0.507 [ERROR] alluxio.client.cli.fs.command.UnsetTtlTest  Time elapsed: 70.197 s  <<< ERROR!
java.lang.RuntimeException: Timed out waiting for process Alluxio job worker to start
	at alluxio.master.TestUtils.waitForReady(TestUtils.java:34)
	at alluxio.master.LocalAlluxioJobCluster.start(LocalAlluxioJobCluster.java:66)
	at alluxio.client.cli.fs.AbstractFileSystemShellTest.beforeClass(AbstractFileSystemShellTest.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at alluxio.testutils.LocalAlluxioClusterResource$1.evaluate(LocalAlluxioClusterResource.java:202)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

**Comment by jiacheliu3** [comment]
alluxio-bot, force-merge this please

**Review by Jackson-Wang-7 — APPROVED** [review]
lgtm for the back port change

**Pull request merged**
