### PR TITLE
[DOCFIX] Fix relative path url

### PR DESCRIPTION
**Pull request by tieujason330**
- jenkins DocPublish build caught an issue with a case-sensitive path
- @ns1123 FYI

### CODE REVIEW

**Comment by tieujason330** [comment]
@madanadit PTAL - change based off a recent commit (b075d21)

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Comment by madanadit** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please.

**Comment by madanadit** [comment]
@tieujason330 can you cherry-pick to branch-2.0 manually, there seems to be a conflict

**Comment by tieujason330** [comment]
@madanadit my mistake, this PR was to branch-2.0. I should've merged to master first

**Comment by madanadit** [comment]
alluxio-bot, cherry-pick this to master please.

**Pull request merged**
