### PR TITLE
[SMALLFIX] Fix typo in MetricsSystem

### PR DESCRIPTION
**Pull request by Haoning-Sun**
### What changes are proposed in this pull request?

Fix typo.

### CODE REVIEW

**Review by dbw9580 — APPROVED** [review]
thanks!

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Review by maobaolong — APPROVED** [review]
It LGTM.

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
