### PR TITLE
Add metrics sink to job master

### PR DESCRIPTION
**Pull request by ssyssy**
### What changes are proposed in this pull request?

Adding metrics sink to job master.

### Why are the changes needed?

Fix the issue that the job master is unable to sink metrics. 

### Does this PR introduce any user facing changes?

Yes, this change will enable users to sink metrics from the job master.

### CODE REVIEW

**Comment by ssyssy** [comment]
@jja725 Tested the csv sink, it works.

**Review by jja725 — APPROVED** [review]
LGTM

**Comment by elega** [comment]
@jiacheliu3 can you help merge it?

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
