### PR TITLE
[SMALLFIX]modified a RESTFul api 'getStatus' 

### PR DESCRIPTION
**Pull request by maobaolong**
The api can accept one of the argument `path` or `blockId`.

If you give the `blockId` argument, this api will give the fileInfo which contains this block.

### CODE REVIEW

**Comment by jsimsa** [comment]
two things:

- the API you modified is deprecated and should not be used
- the block ID should not be exposed to Alluxio clients

why do you need to expose the block ID?

**Comment by maobaolong** [comment]
@jsimsa  So if I want to get `FileInfo` by given `block id`, is there another better way?

**Comment by jsimsa** [comment]
@maobaolong why do you need to lookup `FileInfo` by block ID?

**Comment by maobaolong** [comment]
@jsimsa because when i find the block id in the log file, i don't know which block it stand for, and it relate which file, if i know these thing, it would help me to know what has happened, otherwise, just a id, no more information.

**Comment by jsimsa** [comment]
I think the problem is with the log message itself (it should provide the name of the file) ... block IDs are an internal implementation detail and should not be needed to understand what happened ... also blocks can be evicted which means that the lookup (at least the way you implemented it) might not always return the correct information

can you give tell me which log statements are you talking about so that I can get a better idea of how the logging can be improved? thanks

**Comment by maobaolong** [comment]
The following is the log content contain `block id`
```
# master.log
2017-03-07 14:36:13,532 WARN  logger.type (BlockMaster.java:processWorkerAddedBlocks) - Failed to register workerId: 2362210421694528212 to blockId: 213037088768

# worker.log
AlluxioTException(type:BLOCK_ALREADY_EXISTS, message:Temp blockId 690533433344 is not available, because it already exists, className:alluxio.exception.BlockAlreadyExistsException)
```

And this picture can help you more.

image

**Comment by jsimsa** [comment]
@maobaolong after discussing this with other Alluxio maintainers our conclusion is that:

- client-side logging should not be exposing block and file IDs and we will actively work on improving the log messages
- server-side logging of block level services is expected to use block ID, however the block IDs are considered an internal implementation detail and should not be mapped back to files paths ... any functionality that requires server-side block id information should be implemented in Alluxio

**Comment by maobaolong** [comment]
@jsimsa Thank for stare at this PR.
Ok, Shall we implements a way to let some people like me who want to know what files path a block id mapped back to? At least a way, otherwise, it really hard to guess what is the block id in some server-side log. If nobody know the block id means, why output it? Or we can implements it in alluxio debug mode. Is that a compromise

**Comment by jsimsa** [comment]
my point is that no one user should need to know which file does a block ID correspond to ... this information should only be needed for debugging ... changing the log level of server-side log messages that output block ids to "debug" makes more sense

**Comment by jsimsa** [comment]
@maobaolong I have created https://alluxio.atlassian.net/browse/ALLUXIO-2644 to track the sanitization of the log message ... if you do not mind, please close this PR ... best

**Comment by maobaolong** [comment]
@jsimsa okey, it doesn't metter, I know your point. in fact, i think we should have a developer mode of alluxio, in this mode, we can have dedeveloper apis and cli commands.

**Pull request closed without merging**
