### PR TITLE
[ALLUXIO-2040] Make the Mesos principal property optional

### PR DESCRIPTION
**Pull request by efeller**
https://alluxio.atlassian.net/browse/ALLUXIO-2040

### CODE REVIEW

**Comment by aaudiber** [comment]
Jenkins, ok to test

**Comment by jsimsa** [comment]
LGTM

**Comment by gpang** [comment]
Hi @efeller , thanks for submitting a pull request to Alluxio!

We found your commits on GitHub aren't linked to a valid Github account yet (see your commits at https://github.com/Alluxio/alluxio/pull/3605/commits). For us to properly credit your contributions, could you please set up your Github account by following the Github instructions here: https://help.github.com/articles/setting-your-email-in-git/

Thanks!

**Comment by efeller** [comment]
Hi @gpang, thanks, should be fixed. :-)

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
@efeller Thanks for the quick fix!

**Comment by gpang** [comment]
LGTM

**Pull request merged**
