### PR TITLE
[ALLUXIO-3301] change watermark.high.ratio default value to 0.95

### PR DESCRIPTION
**Pull request by ChangerYoung**
(https://alluxio.atlassian.net/browse/ALLUXIO-3301)

### CODE REVIEW

**Comment by gpang** [comment]
alluxio-bot, check this please

**Comment by ChangerYoung** [comment]
alluxio-bot, check this please

**Comment by gpang** [comment]
@ChangerYoung @aaudiber Is this supposed to go to branch-1.5, or master?

**Comment by aaudiber** [comment]
@gpang This is intentionally targeting branch-1.5

**Pull request merged**
