### PR TITLE
Fix worker swallow OOM

### PR DESCRIPTION
**Pull request by jja725**
### What changes are proposed in this pull request?

Throw Error when there's an Error so the worker could crash and let K8s restart the worker.

### Why are the changes needed?

Without this, Worker would still pretend to be functional if there's OOM.
### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
na

### CODE REVIEW

**Review by maobaolong — APPROVED** [review]
LGTM.

**Comment by yuzhu** [comment]
@jja725 did you verify that OOM exceptions will crash the worker in this case? I just want to make sure there is not a catch somewhere higher in the call stack that masks it. Also does this allow other non-fatal exceptions to crash the worker?

**Comment by jja725** [comment]
> @jja725 did you verify that OOM exceptions will crash the worker in this case? I just want to make sure there is not a catch somewhere higher in the call stack that masks it. Also does this allow other non-fatal exceptions to crash the worker?

From eyeball, there's no higher-level mask this throwable since BlockReadHandler is the highest level for GRPC server. If there's RuntimeException, then it would follow the previous behavior.

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by jja725** [comment]
alluxio-bot, cherry-pick this to branch-2.6 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.9 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.9 please

**Comment by maobaolong** [comment]
@jja725 Is it can exit worker if throw RuntimeException here? I guess it can just stop the current thread only?

**Comment by jja725** [comment]
@maobaolong if it's not a fatal error, it would just return an error response to the client and do nothing

**Comment by maobaolong** [comment]
@jja725 So the behaviour is not changed than before?  Curious about the affect after wrap to RuntimeException?

**Comment by qian0817** [comment]
@jja725 @yuzhu @maobaolong What is the difference in behaviour after the modification, in my view it is the same.

**Comment by jja725** [comment]
@qian0817 this change would be combined with https://github.com/Alluxio/alluxio/pull/16462/files

**Pull request merged**
