### PR TITLE
[ALLUXIO-2390] Add comment in SwiftUnderFileSystem.java:getContainerName  Dev rocketeer

### PR DESCRIPTION
**Pull request by rorovic**
https://alluxio.atlassian.net/browse/ALLUXIO-2390

This is my New Contributor pull request !

Before line 'return uri.getAuthority', add a comment "Authority contains the user, host and port portion of a URI"

### CODE REVIEW

**Comment by rorovic** [comment]
alluxio-bot, check this please

**Comment by rorovic** [comment]
alluxio-bot, check this please

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
@rorovic Thanks for the PR! Since this is pointing to a jira ticket, the PR title should have the prefix "[ALLUXIO-2390]" instead of "[SMALLFIX]".

**Comment by apc999** [comment]
LGTM

**Comment by rorovic** [comment]
thanks! it's owesome!

**Pull request merged**
