### PR TITLE
Convert grpc to alluxio exceptions in polling ping

### PR DESCRIPTION
**Pull request by aaudiber**
We retry `alluxio.exception.status.UnavailableException`, but not the gRPC `StatusRuntimeException` equivalent. This converts the gRPC exception to an `AlluxioStatusException` so that we can properly retry when the status is `Unavailable`

### CODE REVIEW

**Comment by bf8086** [comment]
I can see this becoming a popular type of issues. @ggezer Is it possible we provide some pattern to automatically convert the exception or make it harder to forget about the conversion?

**Comment by ggezer** [comment]
`StatusRuntimeException` should have been converted to `AlluxioStatusException` at the AbstractClient. 
@aaudiber, Do you have a stack-trace that shows otherwise?

**Comment by ggezer** [comment]
@aaudiber, I see the ::connect() call in AbstractClient::retryRpc is not under try-catch. Do you think catching all exceptions in the below catch block in ::connect() would make it work?
...
...
} catch (IOException e) {
        LOG.warn("Failed to connect ({}) with {} @ {}: {}", retryPolicy.getAttemptCount(),
            getServiceName(), mAddress, e.getMessage());
  }

**Comment by ggezer** [comment]
> I can see this becoming a popular type of issues. @ggezer Is it possible we provide some pattern to automatically convert the exception or make it harder to forget about the conversion?

@bf8086, @aaudiber suggested implementing an exception handling client that we can wrap over naked service stubs. Which could save us from future instances of such issues as long as everyone obeys and don't use a naked stub. 

Such work could be impactful so I'm fine letting this one go as it is, and we can open an issue to track that.

**Pull request merged**
