### PR TITLE
Fix casts to long

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
Failed tests: 
alluxio.client.cli.fs.command.PersistCommandTest.persistOnRenameDirectory(alluxio.client.cli.fs.command.PersistCommandTest)
  Run 1: PersistCommandTest.persistOnRenameDirectory:105->AbstractFileSystemShellTest.checkFilePersisted:306
  Run 2: PersistCommandTest.persistOnRenameDirectory:105->AbstractFileSystemShellTest.checkFilePersisted:306

**Comment by bradyoo** [comment]
alluxio-bot, test this please.

**Comment by bradyoo** [comment]
ping?

**Comment by bradyoo** [comment]
Can you merge this? @gpang

**Comment by bradyoo** [comment]
ping? @gpang

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
