### PR TITLE
Set the default to not clean the git repo

### PR DESCRIPTION
**Pull request by yuzhu**
This prevents users from accidentally deleting local changes

### CODE REVIEW

**Comment by yuzhu** [comment]
@Xenorith @tieujason330 PTAL

**Comment by Xenorith** [comment]
updated PR build from
`ALLUXIO_DOCKER_IMAGE=alluxio/alluxio-maven:0.0.3 ALLUXIO_DOCKER_NO_TTY=true ./dev/jenkins/run_docker.sh`
to 
`ALLUXIO_DOCKER_IMAGE=alluxio/alluxio-maven:0.0.3 ALLUXIO_DOCKER_NO_TTY=true ALLUXIO_GIT_CLEAN=true ./dev/jenkins/run_docker.sh`

**Comment by yuzhu** [comment]
@Xenorith i think you need to use `ALLUXIO_DOCKER_IMAGE=alluxio/alluxio-maven:0.0.3 ALLUXIO_DOCKER_NO_TTY=true ALLUXIO_DOCKER_GIT_CLEAN=true ./dev/jenkins/run_docker.sh`, the flag is `ALLUXIO_DOCKER_GIT_CLEAN`

**Comment by Xenorith** [comment]
re-updated >.< can't even copy strings correctly

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
