### PR TITLE
Fix hostname used for job worker

### PR DESCRIPTION
**Pull request by madanadit**

### CODE REVIEW

**Comment by madanadit** [comment]
jenkins, test this please.

**Comment by madanadit** [comment]
@ggezer PTAL

**Comment by apc999** [comment]
Should this go to branch 2.0 too?

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
is this PR the followup of https://github.com/Alluxio/alluxio/pull/9453? @madanadit

**Comment by madanadit** [comment]
Yes it is, thx

**Comment by madanadit** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please.

**Pull request merged**
