### PR TITLE
Display worker block count in worker webui

### PR DESCRIPTION
**Pull request by bzheng888**
### What changes are proposed in this pull request?

Display worker block count in webui overview.

### Why are the changes needed?
Let the user see this worker's block count more directly

### Does this PR introduce any user facing changes?
Worker web ui change, display the block count on overview page.

### CODE REVIEW

**Comment by bzheng888** [comment]
wecom-temp-1c7d7cc4fc3716a2564715066b302b17
The effect is shown in the figure.

**Review by maobaolong — APPROVED** [review]
Good catch. LGTM. Thanks for your contribution.

**Review by LuQQiu — APPROVED** [review]
LGTM

**Comment by LuQQiu** [comment]
@tieujason330 PTAL thanks

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
