### PR TITLE
[SMALLFIX] Do not set ufs address in bootstrap conf

### PR DESCRIPTION
**Pull request by calvinjia**
Under file system address should be set in site-properties in most cases.

### CODE REVIEW

**Comment by jsimsa** [comment]
this means that the user needs to create the properties file before they can successfully start alluxio (e.g. even in the standalone case which previously worked out of the box)

**Comment by apc999** [comment]
@jsimsa , the problem with bootstraping ufs in alluxio-env.sh is you still need to modify the value as it only specifies the scheme. And we try to consolidate these properties to be set only in properties files in the long run.

**Comment by jsimsa** [comment]
LGTM

**Comment by apc999** [comment]
in other words, we think bootstrapping is useful for setting master address, but less so for ufs address. So this PR still keeps the bootstrapping for master

**Comment by apc999** [comment]
LGTM

**Pull request merged**
