### PR TITLE
Replace runtime client module with shaded client

### PR DESCRIPTION
**Pull request by apc999**
Follow up of https://github.com/Alluxio/alluxio/pull/10004 to remove runtime client jar completely.

### CODE REVIEW

**Comment by apc999** [comment]
@LuQQiu I did basic tests locally,it can gerenate the client locally correctly.
Can you help make some tests?

**Comment by apc999** [comment]
@calvinjia , @LuQQiu , do you have preference of using a "new" module `alluxio-shaded-client` or re-use existing `alluxio-core-client-runtime` module for this purpose? I could see pros and cons for both approaches per my discussion with @ZacBlanco , tho I don't have a strong preference of each. Want to hear from you

**Comment by calvinjia** [comment]
@apc999 I have a slight preference for a new module because the contents will not only be the core client.

**Comment by LuQQiu** [comment]
I will prefer to put it under the `core/client/` instead of `shaded/` so that it's more obvious what content this jar contains. but since we already made a Presto PR, I think we don't have obvious problems to go by `shaded/client`.

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-1.8 please

**Pull request merged**
