### PR TITLE
[ALLUXIO-2668] Make PathUtilsTest final

### PR DESCRIPTION
**Pull request by lizy97**
[https://alluxio.atlassian.net/browse/ALLUXIO-2668](https://alluxio.atlassian.net/browse/ALLUXIO-2668)

### CODE REVIEW

**Comment by lizy97** [comment]
@alluxio-bot check this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
alluxio-bot, check this please

**Pull request merged**
