### PR TITLE
[ALLUXIO-1904] Changed creation of reader in RemoteBlockInStream

### PR DESCRIPTION
**Pull request by HorizonNet**
https://alluxio.atlassian.net/browse/ALLUXIO-1904
- Added method to RemoteBlockReader.Factory which only creates a new
  instance if none already exists
- Changed the RemoteBlockReader creation in
  RemoteBlockInStream#readFromRemote
- Added tests for RemoteBlockReader.Factory

### CODE REVIEW

**Comment by calvinjia** [comment]
@HorizonNet Thanks for the proposing a solution to this inefficiency. 
I'm not sure if this will work though since the `RemoteReader` object is not assumed to be thread safe (see `NettyRemoteBlockReader`).

**Comment by HorizonNet** [comment]
@calvinjia I'm not very familiar with threading in Java. Would marking `createIfNotExist` as `synchronized` solve the problem? Do you have any other ideas?

**Comment by calvinjia** [comment]
@HorizonNet 
A good state would be to have each `RemoteBlockInStream` own an instance of `RemoteReader`. The current proposal makes all `RemoteBlockInStreams` use the same `RemoteReader`.

**Comment by HorizonNet** [comment]
@calvinjia I think I have a solution for this according to your comment. I will close this PR to avoid a mess (and to avoid to interfere with [ALLUXIO-1587](https://alluxio.atlassian.net/browse/ALLUXIO-1587)) and open a new PR.

**Pull request closed without merging**
