### PR TITLE
Fix FUSE docs

### PR DESCRIPTION
**Pull request by LuQQiu**

### CODE REVIEW

**Comment by LuQQiu** [comment]
Target to see if the PR-BUILD is definitely failed
`alluxio.master.metastore.InodeStoreTest` keeps failing in local

**Comment by LuQQiu** [comment]
jenkins, test this please

**Comment by apc999** [comment]
@LuQQiu  target your PR to master branch first then cherry-pick to 2.0?

**Comment by LuQQiu** [comment]
This PR is used for testing if there is any branch-2.0 test failures which introduced by recent cherry-picking PRs

**Comment by LuQQiu** [comment]
alluxio.client.cli.JournalToolTest.dumpHeapCheckpointFromEmbeddedJournal(alluxio.client.cli.JournalToolTest)
  Run 1: JournalToolTest.dumpHeapCheckpointFromEmbeddedJournal:164->checkpointEmbeddedJournal:211->lambda$checkpointEmbeddedJournal$0:225 Runtime
  Run 2: JournalToolTest.dumpHeapCheckpointFromEmbeddedJournal:164->checkpointEmbeddedJournal:211->lambda$checkpointEmbeddedJournal$0:225 Runtime

**Pull request closed without merging**
