### PR TITLE
Register journal sequence number metric

### PR DESCRIPTION
**Pull request by codings-dan**
### What changes are proposed in this pull request?

We need the sequence number information of log to monitor the cluster status. The corresponding metrickey is provided in the source code, but it is not registered to the metric system.

Please outline the changes and how this PR fixes the issue.

Register the metric key related to the sequence number to the metric system

### Does this PR introduce any user facing changes?
No

### CODE REVIEW

**Review by ggezer — CHANGES_REQUESTED** [review]
@codings-dan Thanks for this fix. Could you please register for `UfsJournalSystem` as well?

**Comment by apc999** [comment]
ping @codings-dan

**Comment by codings-dan** [comment]
@apc999 @ggezer I have fixed,PTAL

**Review by ggezer — APPROVED** [review]

**Comment by ggezer** [comment]
alluxio-bot, merge this please

**Pull request merged**
