### PR TITLE
[SMALLFIX] Fix enum fields in alluxio.stress.master.Operation

### PR DESCRIPTION
**Pull request by yuexingri**
Fixes Alluxio/new-contributor-tasks#566

### CODE REVIEW

**Comment by apc999** [comment]
Thanks @yuexingri ! can you sign the CLA (https://cla.alluxio.org/)
In case it is already signed, please let me know

**Comment by yuexingri** [comment]
> Thanks @yuexingri ! can you sign the CLA (https://cla.alluxio.org/)
> In case it is already signed, please let me know

look likes l'll already signed.

**Comment by apc999** [comment]
@gpang  do you know if this will break anything, if we change enum fields?

**Comment by yuexingri** [comment]
> @gpang do you know if this will break anything, if we change enum fields?

Could you please speed up the review. I must complete this task by the 11th

**Comment by apc999** [comment]
> @apc999 Hrmmm, unfortunately, I think this will affect all callers of these stress tests. When the command names change, the invocation of the program will have to change to reflect the name change. I would be nice to not change it, since then we would have to change all invocations to use different versions of the command line options.

No worry. I have a approach to work around with compatibility and meanwhile respect Java code convention

**Comment by apc999** [comment]
@gpang  can you help take a look at why we got

```
Error: 9.218 [ERROR] alluxio.stress.StressMasterBenchIntegrationTest.createFileAndListAndRename  Time elapsed: 12.683 s  <<< ERROR!
java.lang.RuntimeException: 
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "operation" (class alluxio.stress.master.MasterBenchParameters), not marked as ignorable (13 known properties: "mStopCount", "mDuration", "mBasePath", "mCreateFileSize", "mTargetThroughput", "mTag", "mConf", "mBaseAlias", "mOperation", "mClients", "mThreads", "mFixedCount", "mWarmup"])
 at [Source: (String)"{
  "throughput" : 162.6331,
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402)
	at alluxio.util.JsonSerializable.fromJson(JsonSerializable.java:71)
	at alluxio.util.JsonSerializable.fromJson(JsonSerializable.java:82)
	at alluxio.stress.cli.report.GenerateReport.readJson(GenerateReport.java:153)
	at alluxio.stress.cli.report.GenerateReport.lambda$run$0(GenerateReport.java:86)
	... 24 more
```

**Comment by gpang** [comment]
I think it is having trouble ser/de the MasterBenchParameters instance? Maybe it thinks `operation` is a field, because there is a `getOperation()` method.

**Comment by apc999** [comment]
@gpang I found `com.beust.jcommander.IStringConverter` which we can convert jcommander args to a class on parsing

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
