### PR TITLE
Add slash to the end of the root mount ufs uri

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Comment by yuzhu** [comment]
@gpang @madanadit PTAL

**Review by madanadit — APPROVED** [review]

**Comment by Xenorith** [comment]
does this break backcompat in any way?

**Comment by yuzhu** [comment]
> does this break backcompat in any way?
It allows a superset of what worked before to be mounted.  Will monitor the tests as they are the only ones that rely on the error behavior

**Comment by gpang** [comment]
@yuzhu Is a unittest possible?

**Comment by yuzhu** [comment]
@gpang looked into unit test, since we use temp directories as ufs root for all of our tests.. we can't really construct a uri with just a scheme and port

**Comment by yuzhu** [comment]
@gpang are you ok with addressing the test for this later in a separate PR?

**Review by gpang — APPROVED** [review]
LGTM (after tests pass)

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
