### PR TITLE
Add option to disable dictionary encoding for ParquetWriter

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
alluxio-bot, check this please

**Comment by gpang** [comment]
flaky test?
```
Tests in error: 
alluxio.server.ft.journal.JournalBackupIntegrationTest.backupDelegationFailoverProtocol(alluxio.server.ft.journal.JournalBackupIntegrationTest)
  Run 1: JournalBackupIntegrationTest.backupDelegationFailoverProtocol:249 » TestTimedOut
  Run 2: JournalBackupIntegrationTest.backupDelegationFailoverProtocol:268 » FailedPrecondition
```

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
