### PR TITLE
[SMALLFIX] Use camelcase for bootstrapConf command, and keep bootstrap-conf still work

### PR DESCRIPTION
**Pull request by apc999**
Other commands are in camel case

### CODE REVIEW

**Comment by calvinjia** [comment]
Could you update the other instances of bootstrap-conf (ie. docs/comments)?

**Comment by ifcharming** [comment]
This change LGTM, but I guess you might also want to update all the documentation of bootstrap-conf?

**Comment by aaudiber** [comment]
@apc999 LGTM modulo updating other instances

**Comment by aaudiber** [comment]
@apc999, are there any updates on this?

**Comment by apc999** [comment]
@aaudiber updated. PTAL

**Comment by aaudiber** [comment]
LGTM

**Pull request merged**
