### PR TITLE
[DOCFIX] Add multipart-upload method

### PR DESCRIPTION
**Pull request by zhezhidashi**
### What changes are proposed in this pull request?

[DOCFIX] Add multipart-upload method

### Why are the changes needed?

1. Add multipart upload method in S3, OSS, COS and OBS.
2. Add configure COS and OBS with Alluxio.

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Review by JiamingMai — APPROVED** [review]
LGTM

**Comment by Xenorith** [comment]
@JiamingMai @zhezhidashi note that the cos ufs is an outdated one, the cosn one is added later and is supposed to have better performance? https://github.com/Alluxio/alluxio/issues/12581 should there be a multipart upload section for `COSN.md`?

also wondering if we should keep the older cos ufs and doc if it is true that cosn is preferred. i don't know much about the usage but just a thought

cc @ccmao1130

**Comment by zhezhidashi** [comment]
> 

[COS](https://cloud.tencent.com/product/cos): Object Storage (Cloud Object Storage, COS) is a distributed storage service launched by Tencent Cloud that has no directory hierarchy, no data format restrictions, can accommodate massive amounts of data, and supports HTTP/HTTPS protocol access.
[COSN](https://cloud.tencent.com/document/faq/436/36897)

So why saying it is outdated? It seems that COS product is currently maintained by Tencent teams. And is there any experimental data showing the cosn performs better than cos?

By the way, it seems that the code related to COSN is not written much, even the jar package of cosn is not imported: [Alluxio-COSN](https://github.com/Alluxio/alluxio/pull/12493/files#diff-fc0ff466cab86c7c24351a77a9f98b358cc7ad5522bbbd33cb4bea663d388329)

**Comment by Xenorith** [comment]
COS, the storage system, is supported by two different UFS integrations in Alluxio. I am wondering why we have two different implementations, so I checked that COS was [added in 2018](https://github.com/Alluxio/alluxio/pull/7380) and COSN was [added in 2020](https://github.com/Alluxio/alluxio/pull/12493) stating that COS has poor performance.

I do not have any additional context or information about them, but if a new person were to encounter them, it is confusing to explain which one to use. Since they integrate with the same storage system and assuming they are both useful, it would be best to explain which one to use under different situations.

**Comment by zhezhidashi** [comment]
@Xenorith 
[COS](https://cloud.tencent.com/product/cos) product is currently maintained by Tencent teams. It seems that [COSN](https://cloud.tencent.com/document/faq/436/36897) is just access COS through Hadoop API. I don't think and can't find any evidence that COSN can be faster or brings better stability. So the docs about COS and COSN may need to be revised.
By the way, I cannot find any information about COSN on Tencent Object Storage's official site. There is only COS on their official site.

COS, S3, OSS are common object storage system, that are developed and maintained by large Internet companies. They should all perform well.

I read alluxio's ufs code, and find that the implementation logic of COS is about identical to OSS, S3. So if the performance of object storage developed by Large Internet is not much different, the data transmission through alluxio should also be similar.

**Comment by Xenorith** [comment]
@zhezhidashi thanks for looking more into this! @ccmao1130 hopefully this is enough information for you to work with

**Pull request merged**
