### PR TITLE
[ALLUXIO-1669] Improve StreamOptionUtils

### PR DESCRIPTION
**Pull request by MichaelPhantom**
[ALLUXIO-1669](https://alluxio.atlassian.net/browse/ALLUXIO-1669)
Guys, refactored the motheds to return corrisponding static instance for each R/W option, please help review it, thank you.

### CODE REVIEW

**Comment by aaudiber** [comment]
I think this might be a problem since the the options are mutable, so if a caller modifies the options they get back from these utils methods, it will modify the stored constants and influence the next caller. @calvinjia does this ticket still make sense?

**Comment by MichaelPhantom** [comment]
Hi @aaudiber ,
As Jenkins test failed, while my local unit test passed(please find the detail in the end), so suspect this might be caused by the "modifiable constant" issue, would you please give me a hint about where does the modification happen in order to dive into it considering calvinjia has not responded to this PR yet, thanks a lot!
Best
Phantom

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running alluxio.client.IsolatedFileSystemIntegrationTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 24.965 sec

Results :

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0

**Comment by calvinjia** [comment]
@aaudiber 
Good point, I don't think the current strategy will be correct if we mutate the options.

@MichaelPhantom 
I think for this change to be applicable, we would need to make immutable versions of the options, but I'm not sure if that achieves the original goal of simplifying the code. What do you think @aaudiber ?

**Comment by aaudiber** [comment]
@MichaelPhantom Even if no caller was currently modifying the options, it would still be confusing for anyone who might try to modify them in the future. I think it makes more sense to remove StreamOptionUtils altogether and inline the option creations. It's easier to understand ` OpenFileOptions.defaults().setReadType(ReadType.CACHE_PROMOTE)` than `getOpenFileOptionsCache()`. Would you be interested in taking https://alluxio.atlassian.net/browse/ALLUXIO-2116?

**Comment by MichaelPhantom** [comment]
@aaudiber @calvinjia as discussed above, gonna work on [ALLUXIO-2116](https://alluxio.atlassian.net/browse/ALLUXIO-2116), thanks.

**Pull request closed without merging**
