### PR TITLE
Implement ByteBufferReadable for HdfsFileInputStream

### PR DESCRIPTION
**Pull request by gengxin**
hdfs c api prefer to use direct read when opening hdfs file. [Code](https://github.com/apache/hadoop/blob/branch-2.7/hadoop-hdfs-project/hadoop-hdfs/src/main/native/libhdfs/hdfs.c#L1009)

However, Alluxio's HdfsDataInputStream don't implement interface ByteBufferReadable, so a lot of exception logs are seen when applications (like apache Impala) use hdfs c api to open hdfs files.

Exceptions logs are like below:

> UnsupportedOperationException: Byte-buffer read unsupported by input stream

This pull request fix this by implement ByteBufferReadable. In our tests,  it also benefits impala performance (probably because less exception handling and logs).

### CODE REVIEW

**Comment by apc999** [comment]
Thanks @gengxin for the improvement.  Do you know if this API is available in HDFS Client API since which version? I vaguely recall the reason not having this method is to make Alluxio client (and under storage) compile with  Hadoop 1.x, which is no more a constraint since 2.0. But might be good to double check.

**Comment by gpang** [comment]
@gengxin Can we target this to `master` branch first, and then cherry-pick to other release branches?

**Comment by gengxin** [comment]
> Do you know if this API is available in HDFS Client API since which version?

@apc999 Thanks for the reminding. ByteBufferReadable interface is supported from hadoop [2.0.2-alpha](https://issues.apache.org/jira/browse/HADOOP-8135), so this change will not build on hadoop 1.x version. I also tried to build this change on master branch for the following hadoop versions, all succeeded:

**Apache**
-Phadoop-2 -Dhadoop.version=2.2.0
-Phadoop-3 -Dhadoop.version=3.0.0

**Cloudera**
-Phadoop-2 -Dhadoop.version=2.0.0-cdh4.7.0

**Hortonworks**
-Phadoop-2 -Dhadoop.version=2.1.0.2.0.5.0-67

> which is no more a constraint since 2.0.

Seems [alluxio 2.0 still support hadoop 1.x](https://docs.alluxio.io/os/user/stable/en/contributor/Building-Alluxio-From-Source.html#hadoop-distribution-support), could I submit this change to master branch?

**Comment by gengxin** [comment]
> @gengxin Can we target this to `master` branch first, and then cherry-pick to other release branches?

Sure, I will do it after the compatibility issue with hadoop 1.x is fixed. :)

**Comment by apc999** [comment]
@gengxin thanks for the update. if I merge your PR now, it will break the build for Alluxio with Hadoop-1 profile. @calvinjia , is it time to split multiple hadoop modules now for hadoop 1, hadoop 2 and hadoop 3 on client side? I can see multiple benefits actually by having multiple versions

**Comment by jiacheliu3** [comment]
@apc999 Came across this PR, do we still want to work on this?

**Comment by apc999** [comment]
> @apc999 Came across this PR, do we still want to work on this?
@jiacheliu3 
already implemented  in #13406 . I will close this PR as this is duplicated.

**Pull request closed without merging**
