### PR TITLE
Update Web UI npm-shrinkwraps

### PR DESCRIPTION
**Pull request by tieujason330**

### CODE REVIEW

**Comment by tieujason330** [comment]
@calvinjia PTAL, thanks!

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
@tieujason330 Thanks for updating! Is there a way we can ensure it stays up to date?

**Comment by tieujason330** [comment]
@calvinjia This was probably my fault, i must've tried shrinkwrapping before I undid some package changes.. It should be more stable from now on.

**Pull request merged**
