### PR TITLE
[ALLUXIO-3148] PrometheusMetricsServlet

### PR DESCRIPTION
**Pull request by hmalphettes**
https://alluxio.atlassian.net/browse/ALLUXIO-3148

This pull request adds a new Metrics servlet that formats the codahale metrics as [prometheus](https://prometheus.io/) metrics.

This contribution is entirely my own, done on my personal time and machine although it will be very useful during my office hours should it be merged.

Thanks for your attention!

### CODE REVIEW

**Comment by hmalphettes** [comment]
I added a second commit to start the `PrometheusMetricsServlet` just like the `MetricsServlet` is started.
I was not sure what would be the best way to turn off this new feature just looking at the `MetricsServlet`.
Hence I assumed everyone wants this new endpoint.

alluxio-prometheus-metrics

**Comment by apc999** [comment]
@calvinjia  do we have license requirement?

**Comment by calvinjia** [comment]
@hmalphettes Thanks for the contribution! Could you verify these new dependencies have licenses compatible with Apache 2.0? I think they are all Apache 2.0, but would like to double check.

**Comment by hmalphettes** [comment]
Sure - everything in prometheus is ASL-2.0.

We are adding directly or indirectly the following dependencies:
https://github.com/prometheus/client_java/blob/master/simpleclient/pom.xml
https://github.com/prometheus/client_java/blob/master/simpleclient_common/pom.xml
https://github.com/prometheus/client_java/blob/master/simpleclient_dropwizard/pom.xml
https://github.com/prometheus/client_java/blob/master/simpleclient_servlet/pom.xml

And then io.dropwizard.metrics/metrics-core/3.1.2 which is maintained by Coda Hale and is also ASL-2.0: https://mvnrepository.com/artifact/io.dropwizard.metrics/metrics-core/3.1.2

We are ignoring the servlet dependency as it is not distributed from here.

**Comment by calvinjia** [comment]
@hmalphettes Thanks for verifying!

**Comment by hmalphettes** [comment]
Great! Let's contribute a grafana dashboard eventually.
Thanks to all!

**Pull request merged**
