### PR TITLE
Add alluxio core client runtime shaded jar

### PR DESCRIPTION
**Pull request by LuQQiu**
Modify the Alluxio core client runtime module to publish alluxio core client runtime jar with dependencies when releasing Alluxio.

Fix https://github.com/Alluxio/alluxio/issues/9988

### CODE REVIEW

**Comment by LuQQiu** [comment]
@apc999 @calvinjia @ZacBlanco  PTAL, thanks!

**Comment by LuQQiu** [comment]
Now the differences between new alluxio client jar and the original one is that:
(1) Nearly all components are relocated, even those un-relocated before
com/google, org/apache/yetus, org/codehaus,  org/checkerframework/
(2) logging classes are removed from the shaded uber jar
org/apache/log4j,  alluxio/core/client/runtime/org/apache/commons/logging/
some of the classes within org/slf4j
(3) Remove the auto-generated LICENSE, NOTICE files and copy the LICENSE/NOTICE file under Alluxio home directory.

**Comment by LuQQiu** [comment]
@apc999 @apc999 PTAL, thanks!
The changes are tested successfully with presto integration by @ZacBlanco and me.

**Comment by calvinjia** [comment]
@LuQQiu Awesome! Have you verified if you can deploy this artifact through the maven deploy (and maven release) plugins? There are sometimes limitations on no src or no javadoc modules.

**Comment by apc999** [comment]
Question: in this way (re-using artifact `alluxio-core-client-runtime`), are we bound to create a new patch release? Or are we still able to over the existing artifact https://mvnrepository.com/artifact/org.alluxio/alluxio-core-client-runtime on 2.0.1 ?

**Comment by apc999** [comment]
talked to @LuQQiu , on hold merging the PR for now

**Comment by LuQQiu** [comment]
@apc999 @calvinjia Tested with the changes, the last change is to avoid the following error:
```
 Error creating shaded jar: duplicate entry: META-INF/services/alluxio.shaded.client.com.fasterxml.core.ObjectCodec



[INFO] +- org.alluxio:alluxio-core-client-fs:jar:2.0.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.7:compile


[INFO] +- org.alluxio:alluxio-core-client-hdfs:jar:2.0.1:compile
[INFO] |  +- com.google.guava:guava:jar:27.0.1-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.17:compile
[INFO] |  +- org.alluxio:alluxio-core-base:jar:2.0.1:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.7:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.7:compile
```

Removed jackson-core and jackson-annotations packages from `alluxio-core-base` since they are already the dependencies of `jackson-databind`

**Comment by apc999** [comment]
@LuQQiu is this ready to merger?

**Comment by LuQQiu** [comment]
Hold on, sorry that I find the previous error doesn't fixed completely

**Comment by LuQQiu** [comment]
Ready to merge after the PR-BUILD finished

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by ZacBlanco** [comment]
alluxio-bot, cherry-pick this into meta-service please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-1.8 please

**Pull request merged**
