### PR TITLE
[DOCFIX] Fix some typos in doc

### PR DESCRIPTION
**Pull request by jianghuazhu**
### What changes are proposed in this pull request?
Some wrong descriptions were found in Journal.md and User-CLI.md, the purpose of this pr is to fix them.
Details: https://github.com/Alluxio/alluxio/issues/16612

### Why are the changes needed?
Yes, some wrong descriptions were found here.

### Does this PR introduce any user facing changes?
After fixing them, it will be more convenient for users to use.

### CODE REVIEW

**Comment by jianghuazhu** [comment]
Can you help review this pr, @tcrain  @jiacheliu3 .
Thank you very much.

**Comment by jianghuazhu** [comment]
Can you help review this pr, @HelloHorizon   @jenoudet .
Thank you very much.

**Review by jenoudet — COMMENTED** [review]
The english part looks good! Can't speak to the Chinese part however.

**Comment by jianghuazhu** [comment]
Many thanks to @jenoudet  for the review.

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
