### PR TITLE
[ALLUXIO-2364]Change the type of the argument Inode

### PR DESCRIPTION
**Pull request by gjhkael**
https://alluxio.atlassian.net/browse/ALLUXIO-2364

### CODE REVIEW

**Comment by gjhkael** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
ok to test

**Comment by aaudiber** [comment]
Jenkins, add to whitelist

**Comment by aaudiber** [comment]
The change looks good to me, thanks for the improvement! Do you mind signing the CLA?

**Comment by gjhkael** [comment]
I signed it!

**Comment by gjhkael** [comment]
How to sign the CLA before a pull request?

**Comment by gjhkael** [comment]
I signed it!

**Comment by aaudiber** [comment]
Did you get an email with a form and fill it out?

**Comment by gjhkael** [comment]
yes, I fill the all information.

**Comment by aaudiber** [comment]
hm, I don't see the filled out form, did you get a confirmation email?

**Comment by gjhkael** [comment]
No, I have not get the comfirmation email, and I see  the Status of the form is Sent.

**Comment by aaudiber** [comment]
maybe try using a gmail email?

**Comment by gjhkael** [comment]
ok, I finish it.

**Comment by aaudiber** [comment]
Thanks!

**Pull request merged**
