### PR TITLE
Increase timeout in MultiMasterLocalAlluxioCluster

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
@yuzhu

**Comment by bradyoo** [comment]
Note that amplab jenkins failed on some flaky test and you can see that the actual github-actions check passed

**Comment by bradyoo** [comment]
@yuzhu

**Review by bf8086 — APPROVED** [review]
Thanks for fixing it!

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
