### PR TITLE
[SMALLFIX] Do not close channel synchronously

### PR DESCRIPTION
**Pull request by peisun1115**

### CODE REVIEW

**Comment by calvinjia** [comment]
@peisun1115 is the goal to not wait for any Netty calls?

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
@calvinjia at least for `NettyPacketWriter.java`, without this fix, if worker throws exception on client-side packet writer close, client will hang forever.

**Comment by calvinjia** [comment]
Got it, we may want to do this everywhere to prevent similar problems.

**Comment by peisun1115** [comment]
@calvinjia i've searched sync() in Alluxio codebase and these are the only instances relevant.

**Pull request merged**
