### PR TITLE
Merge master-2.x commits 2023/04/01~2023/04/30 into main

### PR DESCRIPTION
**Pull request by jiacheliu3**
Merge missing commits from master-2.x to main. The commits in 2023/04/01~2023/04/30 from https://github.com/Alluxio/alluxio/compare/main...master-2.x will be included by this PR.

**Exceptions**
https://github.com/Alluxio/alluxio/commit/4435584bf15a370fe0a0fbf9350bc45b6fd922b3 was skipped because it has been manually cherry-picked to main by https://github.com/Alluxio/alluxio/commit/f64314c124ef2ee99a19eef8869b8d84b84afd59

https://github.com/Alluxio/alluxio/commit/9a4e154e7293667572fec25c63136462fb58a345 and https://github.com/Alluxio/alluxio/commit/fd19fb60cadf2d941f5b36d11f128563e511d50d are in a wrong order (ported in the end)

[new checkpointing for embedded journal](https://github.com/Alluxio/alluxio/commit/8cbcbcd6d3f3451f2bfeb326efadfd1372c9351e) is not in, need manual work

[rockdb thread safety fix](https://github.com/Alluxio/alluxio/commit/9f152c554b737b7014a3c8ac1555d0a2d1e2e936) is not in, need manual work

https://github.com/Alluxio/alluxio/commit/bf60aefc247f57708fd39dce1c440515712a54c1 depends on the commit above

[fsadmin report proxy command](https://github.com/Alluxio/alluxio/commit/dbac084c1e1d89c1e9253da036746e2df9e1ef14) is not in, need manual work

[fsadmin report jobservice show job master/worker versions](https://github.com/Alluxio/alluxio/commit/8da59539201cff376c33256846bd565d976a148e) is not in, need manual work

https://github.com/Alluxio/alluxio/commit/32f923e8a303301705eeb8bd4e5c8ee3b361875c is not included because it has been manually cherry-picked by https://github.com/Alluxio/alluxio/pull/17361

[graceful decommission worker](https://github.com/Alluxio/alluxio/commit/141ee0e567a4c6c60907f85ea66b828704bd761d) is not in, need manual work

[fsadmin report capacity command show worker version](https://github.com/Alluxio/alluxio/commit/26257e6f35c57d937f6f5bdee831facc2fcf7e1a) is not in, need manual work

### CODE REVIEW

**Review by Xenorith — APPROVED** [review]

**Review by huanghua78 — APPROVED** [review]
Looks good.

**Review by lucyge2022 — APPROVED** [review]
s3 part looks good to me.

**Review by lucyge2022 — APPROVED** [review]
s3 part looks good to me.

**Review by dbw9580 — APPROVED** [review]
client and worker related changes LGTM

**Review by Jackson-Wang-7 — APPROVED** [review]
lgtm

**Comment by jiacheliu3** [comment]
alluxio-bot, sync-merge this please

**Pull request merged**
