### PR TITLE
 [ALLUXIO-2163] Add a debug message in SwiftUnderFileSystem.java::getModificationTimeMs

### PR DESCRIPTION
**Pull request by HongweiQin**
https://alluxio.atlassian.net/browse/ALLUXIO-2163
It's a hot Summer, right?

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by apc999** [comment]
@HongweiQin thanks for the patch. would you mind to edit the title to be a bit more informative?

thanks

**Comment by HongweiQin** [comment]
@apc999 Sure!

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
