### PR TITLE
Refactor out entry.getKey()

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by gpang** [comment]
@bradyoo can you provide in the description why this could be an issue?

**Comment by bradyoo** [comment]
There isn't actually an issue in the code. This is just SonarQube yelling about it.

**Comment by bradyoo** [comment]
Tests in error: 
alluxio.client.fs.FreeAndDeleteIntegrationTest.deleteDir(alluxio.client.fs.FreeAndDeleteIntegrationTest)
  Run 1: FreeAndDeleteIntegrationTest.deleteDir:146 » TestTimedOut test timed out after...
  Run 2: FreeAndDeleteIntegrationTest.deleteDir:146 » TestTimedOut test timed out after..

**Comment by bradyoo** [comment]
alluxio-bot, test this please.

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Comment by ZacBlanco** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please

**Pull request merged**
