### PR TITLE
[DOCFIX] Rename k8s doc

### PR DESCRIPTION
**Pull request by ssz1997**
Rename the dropdown name of kubernetes doc.

### CODE REVIEW

**Review by Xenorith — APPROVED** [review]

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.9 please

**Comment by ssz1997** [comment]
@Xenorith For some reason 2.9.0 documentation didn't pick up this change. The edge doc did pick up though. Any concerns?

**Comment by Xenorith** [comment]
> @Xenorith For some reason 2.9.0 documentation didn't pick up this change. The edge doc did pick up though. Any concerns in terms of alluxio-bot?

ah i see what's wrong, should be fixed on next update

**Pull request merged**
