### PR TITLE
[SMALLFIX]Fix Workers Web ui error

### PR DESCRIPTION
**Pull request by codings-dan**
### What changes are proposed in this pull request?
Fix Workers Web ui shows error

### Why are the changes needed?
Now the worker web hearder shows error

### Does this PR introduce any user facing changes?
Yes

### CODE REVIEW

**Review by maobaolong — COMMENTED** [review]
Good catch, it LGTM, thanks for this bugfix, look forward to merge this PR.

**Review by maobaolong — APPROVED** [review]
Good catch, it LGTM, thanks for this bugfix, look forward to merge this PR.

**Comment by maobaolong** [comment]
@tieujason330 Would you please take another look?

**Comment by tieujason330** [comment]
that header change was added in this PR - https://github.com/Alluxio/alluxio/pull/14296. does it no longer apply?

**Comment by codings-dan** [comment]
@tieujason330 Yean, the last change introduced a loop, which would cause the header to display abnormally and multiple Node Names to appear. This change fix the problem.

**Comment by codings-dan** [comment]
The ci test error has nothing to do whith this code change
```
Error: 3.012 [ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 65.679 s <<< FAILURE! - in alluxio.client.fs.concurrent.ConcurrentFileInStreamIntegrationTest
Error: 3.019 [ERROR] alluxio.client.fs.concurrent.ConcurrentFileInStreamIntegrationTest.FileInStreamConcurrency  Time elapsed: 32.211 s  <<< FAILURE!
java.lang.AssertionError: Failed with exception(s) [java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block wo`rker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}, java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=b2219688a578, SocketAddress=b2219688a578/172.17.0.2:36539}]`
```

**Comment by maobaolong** [comment]
@codings-dan Would you like to attach a screenshot here?

**Comment by codings-dan** [comment]
@maobaolong Sure, now the web ui is like this:
企业微信20220124-142919

**Comment by maobaolong** [comment]
@codings-dan Sorry for the confusing, would you like to attach a screenshot to shown the issue before fixed.

**Comment by codings-dan** [comment]
@maobaolong Now the web ui header may show many "node name", see below

**Comment by tieujason330** [comment]
@codings-dan thanks for clearing that up, i understand the issue now. although your change fixes the bug, it also no longer shows `Node Name (Container Host)` in a K8s env vs `Node Name` in a bare-metal env like https://github.com/Alluxio/alluxio/pull/14296 intended. Your change will always show `Node Name (Container Host)`, which may be unclear if it's not K8s. Can you update your changes to still handle this?

**Comment by codings-dan** [comment]
@tieujason330 I'd love to help fix it, but I'm not very familiar with the front-end tech stack, so it may not be possible for the time being, can you help fix it, thanks

**Comment by jiacheliu3** [comment]
@tieujason330 Talked to the contributor today in our community sync and he's not too familiar with the change you suggested. Would you be able to add a commit to this PR or take over this? Thx!

**Comment by tieujason330** [comment]
@jiacheliu3 let's close this and i'll create a new PR w/ a fix

**Pull request closed without merging**
