### PR TITLE
Capitalize enum fields

### PR DESCRIPTION
**Pull request by jenoudet**
Tackled the following new contributor tasks:
Fix https://github.com/Alluxio/new-contributor-tasks/issues/568
Fix https://github.com/Alluxio/new-contributor-tasks/issues/565

### CODE REVIEW

**Comment by yuzhu** [comment]
@jenoudet 
Thanks for the fixes. 
Normally we have the commit message start with an action verb. 
For example, this one could be "Fix formatting to follow the code style convention". 

Otherwise the changes LGTM.

**Comment by yuzhu** [comment]
looks like you also need to modify `alluxio.stress.StressClientIOBenchIntegrationTest.readIO`

**Comment by yuzhu** [comment]
```Error: 7.464 [ERROR] Errors: 
Error: 7.465 [ERROR] alluxio.stress.StressClientIOBenchIntegrationTest.readIO
Error: 7.465 [ERROR]   Run 1: StressClientIOBenchIntegrationTest.readIO:40 » Parameter Invalid value for --o...
Error: 7.466 [ERROR]   Run 2: StressClientIOBenchIntegrationTest.readIO:40 » Parameter Invalid value for --o...
03:19:37.470 [INFO] 
03:19:37.470 [INFO] 
Error: 7.471 [ERROR] Tests run: 44, Failures: 0, Errors: 1, Skipped: 1```

**Comment by yuzhu** [comment]
```java.lang.AssertionError: report must contain graph name: READ_ARRAY-NOT_RANDOM
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at alluxio.stress.AbstractStressBenchIntegrationTest.generateAndVerifyReport(AbstractStressBenchIntegrationTest.java:70)
	at alluxio.stress.StressClientIOBenchIntegrationTest.readIO(StressClientIOBenchIntegrationTest.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at alluxio.testutils.LocalAlluxioClusterResource$ResetRule$1.evaluate(LocalAlluxioClusterResource.java:291)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

Error: 4.042 [ERROR] alluxio.stress.StressClientIOBenchIntegrationTest.readIO  Time elapsed: 16.73 s  <<< FAILURE!
java.lang.AssertionError: report must contain graph name: READ_ARRAY-NOT_RANDOM
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at alluxio.stress.AbstractStressBenchIntegrationTest.generateAndVerifyReport(AbstractStressBenchIntegrationTest.java:70)
	at alluxio.stress.StressClientIOBenchIntegrationTest.readIO(StressClientIOBenchIntegrationTest.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at alluxio.testutils.LocalAlluxioClusterResource$ResetRule$1.evaluate(LocalAlluxioClusterResource.java:291)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by apc999** [comment]
Thanks for your contribution @jenoudet 
Mind reverting your change to https://github.com/Alluxio/new-contributor-tasks/issues/567?
Trivial change by renaming the enum fields will break backward compatibility.
In practice, we also prefer creating one pull request for one issue to make each code change as incremental as possible. So in cases like this, I can proceed by merging your other two fixes :)

**Comment by yuzhu** [comment]
@apc999 could you take another look please? the remaining enum changes are internal enums, and we should be ok here.

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
