### PR TITLE
[DOCFIX] Fix file name to capital

### PR DESCRIPTION
**Pull request by Limuzhou**
Fixed file name typo.

### CODE REVIEW

**Review by HelloHorizon — APPROVED** [review]
@Limuzhou Thanks for the improvement!

**Comment by Limuzhou** [comment]
alluxio-bot, merge this please

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Comment by HelloHorizon** [comment]
alluxio-bot, cherry-pick this to branch-2.6 please

**Pull request merged**
