### PR TITLE
Call builder correctly for gRPC channel message size

### PR DESCRIPTION
**Pull request by ggezer**

### CODE REVIEW

**Comment by ggezer** [comment]
@ZacBlanco I'd need to carve out fake RPCs for testing the props. I'm open to making such extensive testing later.

**Comment by ZacBlanco** [comment]
Yeah I just took a look. It's unfortunate that after calling `setMaxInboundMessageSize` on the netty channel that there isn't a way to check, other than actually sending a message.

We can put it of until later.

**Comment by ggezer** [comment]
alluxio-bot, merge this please

**Comment by ggezer** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please

**Comment by ggezer** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please

**Pull request merged**
