### PR TITLE
ALLUXIO-100

### PR DESCRIPTION
**Pull request by MrGaoxx**
Rename ConcurrentFileSystemMasterCreateTest.java to ConcurrentCreateIntegrationTest.java

### CODE REVIEW

**Comment by MrGaoxx** [comment]
alluxio-bot, check this please

**Comment by MrGaoxx** [comment]
alluxio-bot,check this please

**Comment by aaudiber** [comment]
@MrGaoxx Which JIRA ticket is this referencing? Alluxio-100 looks unrelated: https://alluxio.atlassian.net/browse/ALLUXIO-100

**Comment by yupeng9** [comment]
Closing this PR due to being inactive for a while, feel free to reopen it if you have updates.

**Pull request closed without merging**
