### PR TITLE
Support customized environment variables for helm chart

### PR DESCRIPTION
**Pull request by cheyang**

### CODE REVIEW

**Comment by jiacheliu3** [comment]
I will handle the related doc page change.

**Comment by cheyang** [comment]
> env:
>     # Extra environment variables for the master pod
>     # Example:
>     # JAVA_HOME: /opt/java

done

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Comment by jiacheliu3** [comment]
@madanadit Do you think this should be cherry-picked into 2.3 branch? We are cherry-picking https://github.com/Alluxio/alluxio/pull/11786 with version 0.6.8, so I assume this 0.6.7 should be there too.

**Comment by madanadit** [comment]
Yep, both

**Comment by jiacheliu3** [comment]
alluxio-bot, cherry-pick this to branch-2.3 please.

**Comment by jiacheliu3** [comment]
alluxio-bot, cherry-pick this to branch-2.3 please.

**Pull request merged**
