### PR TITLE
[SMALL-FIX] fix java 8 compilation

### PR DESCRIPTION
**Pull request by siyangy**

### CODE REVIEW

**Comment by yupeng9** [comment]
Thanks for the improvement. Could you describe what's the error like with Java 8 and why this fixes the issue?

**Comment by siyangy** [comment]
I got something like this when changing java.version in pom.xml to 1.8:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:testCompile (default-testCompile) on project tachyon-core-client-internal: Compilation failure: Compilation failure:
[ERROR] /Users/siyangy/Developer/tachyon/core/client-internal/src/test/java/tachyon/client/block/TachyonBlockStoreTest.java:[131,11] reference to assertEquals is ambiguous

**Comment by yupeng9** [comment]
Gotcha. Thanks.

**Comment by yupeng9** [comment]
LGTM

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by yupeng9** [comment]
LGTM.

**Pull request merged**
