### PR TITLE
Close ServerSocket properly in MasterProcess.configureAddress

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
@ZacBlanco Can you merge this for me when the build succeeds?

**Comment by ZacBlanco** [comment]
+1

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Comment by ZacBlanco** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please

**Pull request merged**
