### PR TITLE
Set up initFromBackup correctly

### PR DESCRIPTION
**Pull request by apc999**
Fixes https://github.com/Alluxio/alluxio/issues/9969 by addressing the regression  in PR #9808

### CODE REVIEW

**Comment by ns1123** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
@ZacBlanco I have no context on this feature and what should be tested. This PR is purely to revert some change I made accidentally in #9808 which cleans up the use of UnderFileSystem factory methods but try to use UfsManager more

**Comment by ZacBlanco** [comment]
I know this is reverting a previous change, but it broke the functionality described in #9969 

If we're reverting the change we should be adding a test to ensure it doesn't happen again

**Comment by ZacBlanco** [comment]
Closing this as I've opened a continuation of this PR in #10046

**Pull request closed without merging**
