### PR TITLE
  [ALLUXIO-2130]  Ends a comment with period

### PR DESCRIPTION
**Pull request by mf1633012**
https://alluxio.atlassian.net/browse/ALLUXIO-2130

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by aaudiber** [comment]
Jenkins, test this please

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by apc999** [comment]
alluxio-bot, check this please

**Comment by apc999** [comment]
Found an extra space in the title , removed

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Pull request merged**
