### PR TITLE
Bump ratis version to 2.5.1

### PR DESCRIPTION
**Pull request by kaijchen**
### What changes are proposed in this pull request?

Bump ratis version to 2.5.1 and fix API changes.

### Why are the changes needed?

Ratis 2.5.1 is released and brings several improvements and bug fixes.

### Does this PR introduce any user facing changes?

No.

### CODE REVIEW

**Comment by JiamingMai** [comment]
There are failing tests. Could you take a look to fix them?

**Comment by kaijchen** [comment]
> There are failing tests. Could you take a look to fix them?

Thanks for reminding, the failed test is using reflection to access some internal API.
I guess that's the reason why it's failing. I will look into it later.

**Comment by kaijchen** [comment]
> There are failing tests. Could you take a look to fix them?

I can reproduce the failure, but I'm not sure about the cause.

After `mFollowerJournalSystem.suspend(null);` is called, will the follower stop appending log entries?
Or it just suspends applying log entries to statemachine while keep persisting them?

**Comment by kaijchen** [comment]
```
Error: 2.177 [ERROR] alluxio.master.journal.raft.RaftJournalTest.gainPrimacyAfterSuspend  Time elapsed: 39.12 s  <<< ERROR!
java.util.concurrent.TimeoutException: Timed out waiting for follower becomes leader options: WaitForOptions{interval=20, timeout=30000} last value: false
	at alluxio.util.CommonUtils.waitForResult(CommonUtils.java:383)
	at alluxio.util.CommonUtils.waitFor(CommonUtils.java:341)
	at alluxio.master.journal.raft.RaftJournalTest.promoteFollower(RaftJournalTest.java:405)
	at alluxio.master.journal.raft.RaftJournalTest.gainPrimacyAfterSuspend(RaftJournalTest.java:351)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

Error: 2.180 [ERROR] alluxio.master.journal.raft.RaftJournalTest.gainPrimacyAfterSuspend  Time elapsed: 39.209 s  <<< ERROR!
java.util.concurrent.TimeoutException: Timed out waiting for follower becomes leader options: WaitForOptions{interval=20, timeout=30000} last value: false
	at alluxio.util.CommonUtils.waitForResult(CommonUtils.java:383)
	at alluxio.util.CommonUtils.waitFor(CommonUtils.java:341)
	at alluxio.master.journal.raft.RaftJournalTest.promoteFollower(RaftJournalTest.java:405)
	at alluxio.master.journal.raft.RaftJournalTest.gainPrimacyAfterSuspend(RaftJournalTest.java:351)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jiacheliu3** [comment]
> ```
> Error: 2.177 [ERROR] alluxio.master.journal.raft.RaftJournalTest.gainPrimacyAfterSuspend  Time elapsed: 39.12 s  <<< ERROR!
> java.util.concurrent.TimeoutException: Timed out waiting for follower becomes leader options: WaitForOptions{interval=20, timeout=30000} last value: false
> 	at alluxio.util.CommonUtils.waitForResult(CommonUtils.java:383)
> 	at alluxio.util.CommonUtils.waitFor(CommonUtils.java:341)
> 	at alluxio.master.journal.raft.RaftJournalTest.promoteFollower(RaftJournalTest.java:405)
> 	at alluxio.master.journal.raft.RaftJournalTest.gainPrimacyAfterSuspend(RaftJournalTest.java:351)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
> 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
> 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
> 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> Error: 2.180 [ERROR] alluxio.master.journal.raft.RaftJournalTest.gainPrimacyAfterSuspend  Time elapsed: 39.209 s  <<< ERROR!
> java.util.concurrent.TimeoutException: Timed out waiting for follower becomes leader options: WaitForOptions{interval=20, timeout=30000} last value: false
> 	at alluxio.util.CommonUtils.waitForResult(CommonUtils.java:383)
> 	at alluxio.util.CommonUtils.waitFor(CommonUtils.java:341)
> 	at alluxio.master.journal.raft.RaftJournalTest.promoteFollower(RaftJournalTest.java:405)
> 	at alluxio.master.journal.raft.RaftJournalTest.gainPrimacyAfterSuspend(RaftJournalTest.java:351)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
> 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
> 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
> 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.lang.Thread.run(Thread.java:748)
> ```

@jenoudet Kaijie reports this UT fails after bumping up to 2.5.1, could you take a look? Thanks!

**Comment by jenoudet** [comment]
Took a look but could not find the root cause.

**Comment by jenoudet** [comment]
Hello @kaijchen, I have fixed the problem, please take a look at [this commit](https://github.com/Alluxio/alluxio/pull/17571/commits/00b8889d801215f2cb42647692f839e22e3d165a) and you can incorporate it into this PR. Thanks!

**Comment by kaijchen** [comment]
> Hello @kaijchen, I have fixed the problem, please take a look at [this commit](https://github.com/Alluxio/alluxio/pull/17571/commits/00b8889d801215f2cb42647692f839e22e3d165a) and you can incorporate it into this PR. Thanks!

Thanks @jenoudet for fixing the test.
I noticed #17571 is for main (dora), and this PR is for master-2.x.
I've updated mine to include the fix.

**Review by jenoudet — APPROVED** [review]

**Comment by jenoudet** [comment]
alluxio-bot, merge this please

**Pull request merged**
