### PR TITLE
[ALLUXIO-1918]: Change name testEquals to equalsTest

### PR DESCRIPTION
**Pull request by brennonyork**
Changed all tests in the form on `testEquals` to `equalsTest`. In the one case where there is a test against the `CommonTestUtils` titled `testEqualsTest` I figured that:
1. since it ends with `Test` it conforms to the Alluxio naming conventions
2. it is accurately testing a function (not a test) called `testEquals` 

[ALLUXIO-1918 here](https://alluxio.atlassian.net/browse/ALLUXIO-1918)

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, add to whitelist

**Comment by apc999** [comment]
OK to test

**Comment by gpang** [comment]
Thanks @brennonyork ! Could you also add a link back to the jira ticket in the PR description?

**Comment by gpang** [comment]
LGTM

**Comment by aaudiber** [comment]
LGTM, thanks for fixing this!

**Comment by brennonyork** [comment]
@gpang done!

**Pull request merged**
