### PR TITLE
[ALLUXIO-2325] Remove unused method getInode in InodeTree

### PR DESCRIPTION
**Pull request by jxr1124**
https://alluxio.atlassian.net/browse/ALLUXIO-2325
Removed unused method getInode() and member variable mInode in InodeTree, and adjust related method TraversalResult().
modified by dg1533502

### CODE REVIEW

**Comment by jxr1124** [comment]
[DOCFIX] remove unused method getInode in InodeTree

**Comment by jxr1124** [comment]
[ALLUXIO-2325] remove unused method getInode in InodeTree

**Comment by jxr1124** [comment]
alluxio-bot, check this please

**Comment by jxr1124** [comment]
alluxio-bot, check this please

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by aaudiber** [comment]
@jxr1124 FindBugs is now complaining about an unused field
```
[INFO] Unread field: alluxio.master.file.meta.InodeTree$TraversalResult.mInode 
[alluxio.master.file.meta.InodeTree$TraversalResult] At InodeTree.java:[line 1109]
```
I think we need to this field as well

**Pull request merged**
