### PR TITLE
[SMALLFIX] Docs update: skip tests in compiling alluxio for hadoop

### PR DESCRIPTION
**Pull request by yupeng9**

### CODE REVIEW

**Comment by ifcharming** [comment]
LGTM

Do we also want to update the context
`mvn install -Dhadoop.version=2.7.1` in `Running-Hadoop-MapReduce-on-Alluxio.md` ?

**Comment by yupeng9** [comment]
I think it can be any version?

**Comment by ifcharming** [comment]
May I was not clear -- I mean in page `Running-Hadoop-MapReduce-on-Alluxio.md`, not `_includes/Running-Hadoop-MapReduce-on-Alluxio/compile-Alluxio-Hadoop.md`.

There is some context `mvn install -Dhadoop.version=2.7.1` , shall we also add `-DskipTests` for that?

**Comment by yupeng9** [comment]
oh gotcha. Good point.

**Pull request merged**
