### PR TITLE
Add an option to avoid OutOfDirectMemoryError for AlluxioFuse

### PR DESCRIPTION
**Pull request by secfree**
### What changes are proposed in this pull request?

Add an option to avoid OutOfDirectMemoryError for AlluxioFuse.

### Why are the changes needed?

Fix https://github.com/Alluxio/alluxio/issues/16094

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Comment by yyongycy** [comment]
Do you have any hard evidence this option fixes the issue? How did you tested/verified that?

**Comment by secfree** [comment]
> Do you have any hard evidence this option fixes the issue? How did you tested/verified that?

I did the test the following way
1. alluxio-fuse mount with/without the property `-Dio.netty.noPreferDirect=true`, keep all other parameters consistent
2. Use the same number of processes to read an alluxio-fuse mount path

The result is
- There are a lot of OutOfDirectMemoryError without `-Dio.netty.noPreferDirect=true`
- There is no OutOfDirectMemoryError with `-Dio.netty.noPreferDirect=true`

I was able to reproduce it repeatedly.

As alluxio-fuse is using netty, and netty manages the direct memory pool by itself. With `-Dio.netty.noPreferDirect=true`, it does not use direct memory and uses heap memory, which is managed by GC, which releases memory faster.

**Comment by yyongycy** [comment]
> > Do you have any hard evidence this option fixes the issue? How did you tested/verified that?
> 
> I did the test the following way
> 
> 1. alluxio-fuse mount with/without the property `-Dio.netty.noPreferDirect=true`, keep all other parameters consistent
> 2. Use the same number of processes to read an alluxio-fuse mount path
> 
> The result is
> 
> * There are a lot of OutOfDirectMemoryError without `-Dio.netty.noPreferDirect=true`
> * There is no OutOfDirectMemoryError with `-Dio.netty.noPreferDirect=true`
> 
> I was able to reproduce it repeatedly.
> 
> As alluxio-fuse is using netty, and netty manages the direct memory pool by itself. With `-Dio.netty.noPreferDirect=true`, it does not use direct memory and uses heap memory, which is managed by GC, and GC releases memory faster.

Any side effect? and other options? Wondering in what situation it is triggered?

**Comment by secfree** [comment]
> Any side effect? and other options?
The side effect is, without using direct memory, `Zero Copy` is disabled. The data needs to be copied once more between `user space` and `kernel space`.

> Wondering in what situation it is triggered?
Background of my base: the platform needs to do alluxio-fuse mount for each user's job in its pod, as different jobs have different parallel, so it is difficult to set a fixed proper value for MaxDirectMemorySize.

**Pull request closed without merging**
