### PR TITLE
Remove loadMetadataCommand

### PR DESCRIPTION
**Pull request by yyongycy**
### What changes are proposed in this pull request?

Remove loadMetadataCommand.

### Why are the changes needed?

Remove loadMetadataCommand.
It is not used in new arch.

### Does this PR introduce any user facing changes?

NA

### CODE REVIEW

**Review by Xenorith — COMMENTED** [review]
i already merged my golang change; could you also remove them as part of this PR?
https://github.com/Alluxio/alluxio/pull/18016

**Comment by yyongycy** [comment]
> i already merged my golang change; could you also remove them as part of this PR? #18016

Sure, will do that once I get confirmation from @elega

**Review by elega — APPROVED** [review]

**Comment by yyongycy** [comment]
@jja725 Please help double confirm, the load is required.

**Review by jja725 — APPROVED** [review]

**Comment by Xenorith** [comment]
going to force merge since this is a known issue (and the test suite only runs 3 tests) rather than wasting a cycle to rebase

**Comment by Xenorith** [comment]
alluxio-bot, force-merge this please

**Pull request merged**
