### PR TITLE
[DOCFIX] [ALLUXIO-2009] Update "System Configuration" to "Configuration"

### PR DESCRIPTION
**Pull request by EMOBO**
https://alluxio.atlassian.net/browse/ALLUXIO-2009
Update "System Configuration" to "Configuration" in docs/cn/Web-Interface.md to be consistent with the Web UI navigation bar

### CODE REVIEW

**Comment by ifcharming** [comment]
ok to test

**Comment by apc999** [comment]
Thanks for submitting a patch to Alluxio!

We found your commits on GitHub aren't linking to a valid Github account yet. ( See https://github.com/Alluxio/alluxio/pull/3480/commits where your icon is gray)
For us to properly credit your contributions, would you spend a minute or two to set up your Github account by (1) following the Github instructions here, (2) closing this PR, and (3) creating another PR?
Thank you again for your contribution!

**Comment by RongGu** [comment]
Thanks for proposing this @EMOBO . This issue has already been resolved in our current version. I think we can close this PR now. @apc999

**Comment by apc999** [comment]
@RongGu I have merged this PR any way :) thanks for the followup

**Pull request merged**
