### PR TITLE
Fix path for URIStatus from UFSStatus

### PR DESCRIPTION
**Pull request by huanghua78**
### What changes are proposed in this pull request?

Construct correct path for URIStatus from UFSStatus.

### Why are the changes needed?

When user issues listStatus(path), the returned result from UFS is relative path from the requested path.
We need to concat the result path after the requested path.

### Does this PR introduce any user facing changes?

N/A

### CODE REVIEW

**Comment by huanghua78** [comment]
alluxio-bot, check this please

**Comment by huanghua78** [comment]
Combined changes from #17262 from @JiamingMai

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks!

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
