### PR TITLE
[ALLUXIO-3275] Fix NPE while running concurrentListFiles

### PR DESCRIPTION
**Pull request by yuzhu**
https://alluxio.atlassian.net/browse/ALLUXIO-3275

The NPE happens when there are concurrent createFile and listFile happening, and the createFile happen to finish between two `getChildren` calls.

### CODE REVIEW

**Comment by yuzhu** [comment]
@aaudiber @gpang fixed the concurrentListFile test, PTAL.

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by aaudiber** [comment]
@yuzhu could this affect the 1.8.0 release? Unless this was introduced since the release, we should file a jira ticket in case someone runs into this

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
I also agree with @aaudiber . We should create a Jira ticket for this PR.

**Comment by yuzhu** [comment]
@aaudiber @gpang Jira ticket created. https://alluxio.atlassian.net/browse/ALLUXIO-3275

**Comment by gpang** [comment]
@yuzhu please cherry-pick this to branch-1.8.

**Pull request merged**
