### PR TITLE
Add filter to copy jobs

### PR DESCRIPTION
**Pull request by ssyssy**
### What changes are proposed in this pull request?

Add filter to copy jobs.

### Why are the changes needed?

To add copy job to policy engine.

### Does this PR introduce any user facing changes?

na

### CODE REVIEW

**Comment by ssyssy** [comment]
Tested on the EE side.
./bin/alluxio fs policy status test
Policy test:

Since server started:
	Jobs Scheduled: 1
	Jobs Running: 0
	Jobs Succeeded: 1
	Jobs Failed: 0

Most Recent Job Progress Report: 	Settings:	check-content: false
	Job State: SUCCEEDED
	Files Processed: 1
	Bytes Copied: 826.38MB out of 826.38MB
	Throughput: 1621.09KB/s
	Files failure rate: 0.00%
	Files Failed: 0

**Comment by ssyssy** [comment]
@jja725 ping for review.

**Review by jja725 — APPROVED** [review]
LGTM

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Pull request merged**
