### PR TITLE
Improve search for finding worker without block

### LINKED ISSUE #16405: Improve the search of worker without block in alluxio.job.plan.load.LoadDefinition
**Summary**
In code, at line no.: https://github.com/Alluxio/alluxio/blob/branch-2.8/job/server/src/main/java/alluxio/job/plan/load/LoadDefinition.java#L169
collects the block locations as list which later at line no. https://github.com/Alluxio/alluxio/blob/branch-2.8/job/server/src/main/java/alluxio/job/plan/load/LoadDefinition.java#L174 being used to check block workers are contained in the list or not.
Typically, list takes O(N) time to search, it would be better to use Set which takes O(1) time on average if there is no hash collision.

### PR DESCRIPTION
**Pull request by vimalKeshu**
### What changes are proposed in this pull request?
Resolve #16405 
It replaces the list with set for finding worker without block function which is being called in for loop.

### Why are the changes needed?
It improves the search time from O(N) to O(1).

### Does this PR introduce any user facing changes?
No

### CODE REVIEW

**Review by jja725 — APPROVED** [review]
LGTM, thanks for the improvement!

**Review by maobaolong — APPROVED** [review]
LGTM

**Comment by shivamurthydeepak** [comment]
@jja725 Could you please help in merging this PR as we dont have access. Thank you!

**Comment by vimalKeshu** [comment]
Thank you @jja725 and @maobaolong for reviewing the PR. 
@jja725 It seems I don't have permission to merge this PR. Can you please help me to merge it. Thank you again.

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Pull request merged**
