### PR TITLE
Remove Ufs Extension

### PR DESCRIPTION
**Pull request by apc999**
### What changes are proposed in this pull request?

Remove entry point of ufs extension

### CODE REVIEW

**Comment by LuQQiu** [comment]
@apc999 PTAL, thanks!

**Comment by LuQQiu** [comment]
@apc999 PTAL, thanks

**Comment by Xenorith** [comment]
can/should the corresponding property key be hidden?
```
  public static final PropertyKey EXTENSIONS_DIR =
      stringBuilder(Name.EXTENSIONS_DIR)
          .setDefaultValue(format("${%s}/extensions", Name.HOME))
          .setDescription("The directory containing Alluxio extensions.")
          .setConsistencyCheckLevel(ConsistencyCheckLevel.WARN)
          .setScope(Scope.SERVER)
          .build();
```

**Comment by LuQQiu** [comment]
@Xenorith PTAL, thanks!

**Review by Xenorith — APPROVED** [review]

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Pull request merged**
