### PR TITLE
Cancel sync job in middle of ufs calls if client cancelled

### PR DESCRIPTION
**Pull request by bradyoo**
The previous version slowed down the sync because the number of prefetch threads were much smaller than the number of rpc threads that were performing a sync in many cases.

### CODE REVIEW

**Comment by yuzhu** [comment]
@bradyoo is the only difference from the prev version the change in default thread count?

**Comment by bradyoo** [comment]
@yuzhu That is correct though I can't figure out why the test is failing so I'm reverting that bit back for a moment to see if the tests succeed.

**Comment by bradyoo** [comment]
had to reduce the number for the tests to pass. I think the way the test is passing right now (and the way it not have been passing before may not be the way we think it is... The test is too timing based to debug properly.)

**Comment by yuzhu** [comment]
which test was it?

**Comment by bradyoo** [comment]
repeatedDirectorySync and repeatedChildrenSync

**Comment by yuzhu** [comment]
LGTM

**Review by yuzhu — APPROVED** [review]

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Pull request merged**
