### PR TITLE
Fix RaftClient closed error

### LINKED ISSUE #16164: Failed to manually switch the master
**Alluxio Version:**
master

**Describe the bug**
Failed to switch master using fsadmin command.

**To Reproduce**

Start three alluxio masters, and then select a standby master to switch to the primary master.

```
bin/alluxio fsadmin journal quorum elect -address alluxio-host2:19200
```

The log is as follows:
```
INFO  RaftJournalSystem - Transferring leadership to master with address <alluxio-host2:19200> and with RaftPeerId <alluxio-host2_19200>
INFO  RaftJournalSystem - Transferring leadership initiated
ERROR RaftJournalSystem - caught an error when executing transfer: client-948C0C68FF19 is already CLOSED
```

**Expected behavior**
Switch the master normally.

**Urgency**
Urgent. 

**Are you planning to fix it**
Yes. 

**Additional context**
Problems caused by using ratis-2.3.0.

### PR DESCRIPTION
**Pull request by Haoning-Sun**
### What changes are proposed in this pull request?

Use a new client in the thread to avoid closing the client when the method ends.

### Why are the changes needed?
Fix #16164.

### Does this PR introduce any user facing changes?
No.

### CODE REVIEW

**Review by jenoudet — APPROVED** [review]
Great catch, thanks for the fix!

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Comment by jenoudet** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Comment by HelloHorizon** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Pull request merged**
