### PR TITLE
Add cosn and ozone to generate-tarball

### PR DESCRIPTION
**Pull request by lwllvyb**

### CODE REVIEW

**Comment by lwllvyb** [comment]
alluxio-bot, check this please

**Comment by maobaolong** [comment]
@apc999 Looks like the failing tests are unrelated?

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
@lwllvyb  can you sign the CLA (https://cla.alluxio.org/) ? if you have already signed it and the label is still here, let me know and I will remove it manually.

**Comment by lwllvyb** [comment]
> @lwllvyb can you sign the CLA (https://cla.alluxio.org/) ? if you have already signed it and the label is still here, let me know and I will remove it manually.

I have already signed it.

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
