### PR TITLE
[SMALLFIX] Update file docs/cn/Accessing-Alluxio-from-Zeppelin.md

### PR DESCRIPTION
**Pull request by jixiaozhong**

### CODE REVIEW

**Comment by jixiaozhong** [comment]
alluxio-bot, check this please

**Comment by jixiaozhong** [comment]
alluxio-bot, check this please

**Comment by jixiaozhong** [comment]
alluxio-bot, check this please

**Comment by LuQQiu** [comment]
@jixiaozhong Please fix the conflicting files. At your local branch, you can use 
`git pull upstream master` to pull the latest master branch changes to your local branch.
After you solve the merge conflicts, you can use `git add/commit/push origin` commands you did before to push changes to this PR. Thanks!

**Comment by jixiaozhong** [comment]
alluxio-bot, check this please

**Pull request merged**
