### PR TITLE
Use correct audit log configuration in proxy

### PR DESCRIPTION
**Pull request by Haoning-Sun**
### What changes are proposed in this pull request?

The v1 and v2 versions of proxy use uniform judgment conditions.

### CODE REVIEW

**Review by Xenorith — COMMENTED** [review]
could you also fix the same problem in https://github.com/Alluxio/alluxio/blob/master-2.x/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java#L1521

**Comment by Xenorith** [comment]
also suggest updating the PR title to be `Use correct audit log configuration in proxy`. thanks

**Comment by Haoning-Sun** [comment]
> could you also fix the same problem in https://github.com/Alluxio/alluxio/blob/master-2.x/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java#L1521

Done.

**Review by Xenorith — APPROVED** [review]

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Pull request merged**
