### PR TITLE
[DOCFIX] Fix doc links and anchor tags

### PR DESCRIPTION
**Pull request by Xenorith**

### CODE REVIEW

**Comment by ZacBlanco** [comment]
I did a pass with my link checker and it came back with the following errors:


```
- ./_site/en/contributor/Code-Conventions.html
  *  External link https://www.slf4j.org/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL peer certificate or SSH remote key was not OK
- ./_site/en/deploy/Running-Alluxio-On-Kubernetes.html
  *  linking to ../operation/Journal.html#ufs-journal-configuration}}, but ufs-journal-configuration}} does not exist (line 904)
     <a href="../operation/Journal.html#ufs-journal-configuration%7D%7D">UFS Journal</a>
  *  linking to ../ufs/S3.html#root-mount-point}}, but root-mount-point}} does not exist (line 893)
     <a href="../ufs/S3.html#root-mount-point%7D%7D">mount S3</a>
- ./_site/en/operation/Configuration.html
  *  linking to internal hash #specify-cluster-wide-defaults that does not exist (line 1021)
     <a href="#specify-cluster-wide-defaults">Cluster default values</a>
```

You can ignore the first one because it's due to an out-of-date cert

**Comment by ZacBlanco** [comment]
since these are all doc changes, I'm going to merge it before the build passes

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please

**Pull request merged**
