### PR TITLE
Change JNI-Fuse to default alluxio POSIX API implementation

### PR DESCRIPTION
**Pull request by LuQQiu**
Use JNI-Fuse as default Alluxio POSIX API implementation

### CODE REVIEW

**Review by apc999 — APPROVED** [review]

**Comment by LuQQiu** [comment]
Error: 0.785 [ERROR] Errors: 
Error: 0.786 [ERROR] alluxio.server.ft.journal.MultiMasterJournalTest.testTtl(alluxio.server.ft.journal.MultiMasterJournalTest)
Error: 0.786 [ERROR]   Run 1: MultiMasterJournalTest.before:53 » IO java.util.concurrent.TimeoutException: T...
Error: 0.787 [ERROR]   Run 2: MultiMasterJournalTest.before:53 » IO java.util.concurrent.TimeoutException: T...

**Comment by apc999** [comment]
failing tests are unrelated.

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please

**Pull request merged**
