### PR TITLE
Documentation layouts changes to match with Alluxio.com Theme

### PR DESCRIPTION
**Pull request by aunglinn**
Layouts and styling changes for documentations to match with Alluxio.com web theme.

### CODE REVIEW

**Comment by uronce-cc** [comment]
Could we ignore the `.sass-cache` directory in .gitignore? Or this hidden directory is needed?

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
It doesn't look like your github account is correctly set up with your email. Could you please set up your account with the directions here: https://help.github.com/articles/setting-your-email-in-git/

Thanks!

**Comment by aunglinn** [comment]
@gpang I've changed my email address. Is there any problem? 
@uronce-cc  Should I close this one and make a new pull request with .sass_cache/ ignored ?

**Comment by uronce-cc** [comment]
@aunglinn The .sass_cache directory still exists.

**Comment by aunglinn** [comment]
I'm going to create a new pull request. Thanks @uronce-cc .

**Pull request closed without merging**
