### PR TITLE
Avoid exception when audit log is used with NOSASL authentication

### PR DESCRIPTION
**Pull request by bf8086**
Cherry-picked for `branch-2.0`

Fixes Alluxio/alluxio#9294
Fixes Alluxio/alluxio#9295

Update audit logic to be more flexible when acquiring user information.

pr-link: Alluxio/alluxio#9645
change-id: cid-838211044d298fb42335b77f1c9c509fd42d185e

### CODE REVIEW

**Comment by bf8086** [comment]
@gpang PTAL.

**Comment by bf8086** [comment]
Jenkins, test this please.

**Comment by bf8086** [comment]
Jenkins, test this please.

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
