### PR TITLE
[ALLUXIO-2125] Change s3 to S3 in S3AUnderFileSystem

### PR DESCRIPTION
**Pull request by shijcnju**
https://alluxio.atlassian.net/browse/ALLUXIO-2125
In the class S3AUnderFileSystem.java, there are references to "s3" and "S3", change them to all use "S3"

### CODE REVIEW

**Comment by shijcnju** [comment]
alluxio-bot, check this please

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by aaudiber** [comment]
@shijcnju It looks like the file has been changed to use Windows line endings - could you change it back to unix line endings?

**Comment by shijcnju** [comment]
@aaudiber I have changed it back to unix line endings.

**Comment by aaudiber** [comment]
Thanks for fixing, looks good to me

**Pull request merged**
