### PR TITLE
[ALLUXIO-2702]Specify null variable in DataFileChannel.java precondition check

### PR DESCRIPTION
**Pull request by lijunyou**
https://alluxio.atlassian.net/browse/ALLUXIO-2702

### CODE REVIEW

**Comment by lijunyou** [comment]
alluxio-bot, check this please

**Comment by lijunyou** [comment]
alluxio-bot, check this please

**Comment by apc999** [comment]
@lijunyou could you sign [the contribution license agreement](http://cla.alluxio.org/)?

**Comment by lijunyou** [comment]
sure,i have done this 8 days ago

**Comment by lijunyou** [comment]
alluxio-bot, check this please

**Pull request merged**
