### PR TITLE
Add api counts graph for client-io stress test

### PR DESCRIPTION
**Pull request by HelloHorizon**

### CODE REVIEW

**Comment by HelloHorizon** [comment]
jenkins, test it please

**Comment by HelloHorizon** [comment]
jenkins, test this please

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please.

**Comment by HelloHorizon** [comment]
@gpang Can you help to merge this in?

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
