### PR TITLE
Upgrade Apache Ratis from 2.3.0 to 2.4.0

### PR DESCRIPTION
**Pull request by kaijchen**
### What changes are proposed in this pull request?

1. Upgrade Apache Ratis to 2.4.0.
2. Fix issues caused by API change.  (Please double check the `RaftStorage.StartupOption` I used) 

Verified with CI: https://github.com/kaijchen/alluxio/pull/1/checks

### Why are the changes needed?

Apache Ratis has released 2.4.0 in Oct 18th and includes some bug fixes.
https://ratis.apache.org/post/2.4.0.html

Do note Apache Ratis 2.4.1 release is under discussion,
but we can just bump the dependency version when it's released.
https://lists.apache.org/thread/9yw80p20ds533wwn7jfcg1f76q56zogh

### Does this PR introduce any user facing changes?

No.

### CODE REVIEW

**Review by maobaolong — APPROVED** [review]
It LGTM, welcome ratis 2.4.0

**Comment by maobaolong** [comment]
@jiacheliu3 Would you like to take another look?

**Comment by kaijchen** [comment]
Thanks @maobaolong for the review.

PS: I have re-signed the CLA by editing the PDF. I don't know if it's the correct way.
(The old CLA expired probably due to email / username change).

**Review by codings-dan — APPROVED** [review]
@kaijchen Thanks a lot for working on this! the change looks good, +1  @jiacheliu3 Could you help review this pull request? Thanks!

**Comment by maobaolong** [comment]
@kaijchen You can add the old email to your github account, hope this can works, otherwise, your can print the CLA pdf -> sign it -> take picture -> email to [cla@alluxio.org](mailto:cla@alluxio.org)

**Comment by kaijchen** [comment]
> @kaijchen You can add the old email to your github account, hope this can works, otherwise, your can print the CLA pdf -> sign it -> take picture -> email to [cla@alluxio.org](mailto:cla@alluxio.org)

My old email is still present in my github account. Maybe I should just resign the CLA.

**Comment by maobaolong** [comment]
@jiacheliu3 Hope this can help branch 2.9

**Review by jenoudet — APPROVED** [review]

**Review by jiacheliu3 — APPROVED** [review]
LGTM although the frequent changes in Ratis API really concerns me. Let's merge this first and wait out for a few days and see if everything is really working as expected.

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by kaijchen** [comment]
Thanks @maobaolong @codings-dan @jenoudet and @jiacheliu3 for the review.

**Pull request merged**
