### PR TITLE
Update depencencies in POM files in client module

### LINKED ISSUE #9403: NoSuchMethodError when use filesystem api
**Alluxio Version:**
Alluxio-2.0

**Describe the bug**

when we use this filesytem api to access alluxio cluster
```
  val conf: InstancedConfiguration = new InstancedConfiguration(ConfigurationUtils.defaults())
  System.out.println(masterAddress.getHost() + ' ' + masterAddress.getPort())
  conf.set(PropertyKey.MASTER_HOSTNAME, masterAddress.getHost())
  conf.set(PropertyKey.MASTER_RPC_PORT, Integer.toString(masterAddress.getPort()))
  val fs = FileSystem.Factory.create(conf)
```
we will meet exception below:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Hex.encodeHexString([B)Ljava/lang/String;
	at alluxio.conf.Hash.compute(Hash.java:59)
	at alluxio.conf.Hash.get(Hash.java:73)
	at alluxio.conf.AlluxioProperties.hash(AlluxioProperties.java:271)
	at alluxio.conf.InstancedConfiguration.hash(InstancedConfiguration.java:421)
	at alluxio.ClientContext.<init>(ClientContext.java:99)
	at alluxio.ClientContext.create(ClientContext.java:61)
	at alluxio.client.file.FileSystemContext.create(FileSystemContext.java:166)
	at alluxio.client.file.FileSystemContext.create(FileSystemContext.java:155)
	at alluxio.client.file.FileSystem$Factory.create(FileSystem.java:117)
	at AlluxioUtil.<init>(AlluxioUtil.scala:22)
```
this is because in maven repo dependencies:

alluxio-core-client-fs:2.0.0 -->  alluxio-core-common:2.0.0 --> commons.httpclient:3.1 --> 
commons-codec:1.2

while in commons-codec:1.2,  Hex do not have  encodeHexString function.
in alluxio source code , we find that commons-codec's version is 1.10  in pom.xml

### PR DESCRIPTION
**Pull request by apc999**
- Add direct dependencies in modules in client, to prevent transitive dependencies introduce jar hell on conflict. I run `mvn dependency:analyze` to collect "Undeclared but used" dependencies 
- Fix #9403

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
@apc999 I still see warnings for some modules. Is the idea that we will just clean up the external dependencies? Because those dependencies will rely on the internal modules, won't it be a problem when it fetches transitive dependencies?

**Comment by apc999** [comment]
@calvinjia do you see warnings on internal or external modules? I expected to fix all those warnings on internal modules (`alluxio-*`). Some other warnings on any of the deps [here](https://github.com/apc999/alluxio/blob/9fe4f90c1d23b922515644bd4cdcbb32277db658/pom.xml#L772) can be ignored as they are considered as common deps in this repo and added automatically to all modules

**Comment by apc999** [comment]
ping @calvinjia

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please.

**Pull request merged**
