### PR TITLE
Remove extra colon in java classpath for FUSE

### LINKED ISSUE #15451: FUSE java process hangs on class loader.
**Alluxio Version:**
2.7.3

**Describe the bug**
FUSE process goes into deadlock when mounting a sub-directory named "_alluxio_" in _current directory_. The process then becomes zombie process when killed.

**To Reproduce**
```sh
# assume a Alluxio cluster is ready.
alias afuse='/opt/alluxio-2.7.3/integration/fuse/bin/alluxio-fuse'
alias afs='/opt/alluxio-2.7.3/alluxio fs'
cd ~
mkdir ./alluxio
afs mkdir /fuse-data
afuse mount ./alluxio /fuse-data
ls # <-- this command never returns, and won't break on Ctrl+C.
```

**Expected behavior**
FUSE process to not hang.

**Details**

`jstack` output of the hanging FUSE process:

<details>
  <summary>Click to expand.</summary>

```sh
Full thread dump OpenJDK 64-Bit Server VM (25.322-b06 mixed mode):

"Attach Listener" #45 daemon prio=9 os_prio=0 tid=0x00007fc670001000 nid=0xc565 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Thread-7" #44 daemon prio=5 os_prio=0 tid=0x00007fc628001000 nid=0xb7d8 waiting for monitor entry [0x00007fc675aba000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:398)
	- waiting to lock <0x00000000f1740e80> (a java.lang.Object)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at alluxio.jnifuse.AbstractFuseFileSystem.getattrCallback(AbstractFuseFileSystem.java:189)

"Thread-6" #41 daemon prio=5 os_prio=0 tid=0x0000556a80b53800 nid=0xb6f6 waiting for monitor entry [0x00007fc690a8c000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:398)
	- waiting to lock <0x00000000f1740e80> (a java.lang.Object)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at alluxio.jnifuse.AbstractFuseFileSystem.getattrCallback(AbstractFuseFileSystem.java:189)

"Thread-5" #29 daemon prio=5 os_prio=0 tid=0x00007fc638022800 nid=0xb6d7 waiting for monitor entry [0x00007fc69128d000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:398)
	- waiting to lock <0x00000000f1740e80> (a java.lang.Object)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at alluxio.jnifuse.AbstractFuseFileSystem.getattrCallback(AbstractFuseFileSystem.java:189)

"Thread-4" #28 daemon prio=5 os_prio=0 tid=0x00007fc618022000 nid=0xb6d5 runnable [0x00007fc691a8d000]
   java.lang.Thread.State: RUNNABLE
	at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
	at java.io.File.exists(File.java:830)
	at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java:1391)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:250)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	- locked <0x00000000f1740e80> (a java.lang.Object)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at alluxio.jnifuse.AbstractFuseFileSystem.getattrCallback(AbstractFuseFileSystem.java:189)

"config-hash-master-heartbeat-0" #15 daemon prio=5 os_prio=0 tid=0x00007fc6b037a000 nid=0xb6ac runnable [0x00007fc693bfa000]
   java.lang.Thread.State: RUNNABLE
	at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
	at java.io.File.exists(File.java:830)
	at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java:1391)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:250)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	- locked <0x00000000f2814430> (a java.lang.Object)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at alluxio.client.meta.RetryHandlingMetaMasterConfigClient.getConfigHash(RetryHandlingMetaMasterConfigClient.java:89)
	at alluxio.client.file.ConfigHashSync.heartbeat(ConfigHashSync.java:81)
	- locked <0x00000000c0101eb8> (a alluxio.client.file.ConfigHashSync)
	at alluxio.client.file.FileSystemContextReinitializer.lambda$new$0(FileSystemContextReinitializer.java:69)
	at alluxio.client.file.FileSystemContextReinitializer$$Lambda$87/101478235.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

"BlockMasterClientPoolGcThreads-0" #14 daemon prio=5 os_prio=0 tid=0x00007fc6b0375800 nid=0xb6a6 waiting on condition [0x00007fc693cfd000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c00a67c0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

"FileSystemMasterClientPoolGcThreads-0" #13 daemon prio=5 os_prio=0 tid=0x00007fc6b0373800 nid=0xb6a5 waiting on condition [0x00007fc693dfe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c00a7000> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

"metrics-master-heartbeat-0" #12 daemon prio=5 os_prio=0 tid=0x00007fc6b036f000 nid=0xb69f runnable [0x00007fc6981c3000]
   java.lang.Thread.State: RUNNABLE
	at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
	at java.io.File.exists(File.java:830)
	at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java:1391)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:250)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	- locked <0x00000000f1b28bc0> (a java.lang.Object)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at alluxio.client.metrics.ClientMasterSync.heartbeat(ClientMasterSync.java:75)
	- locked <0x00000000c00a7c38> (a alluxio.client.metrics.ClientMasterSync)
	at alluxio.client.metrics.MetricsHeartbeatContext$$Lambda$83/485041780.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

"Service Thread" #8 daemon prio=9 os_prio=0 tid=0x00007fc6b0137800 nid=0xb657 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007fc6b0124800 nid=0xb656 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007fc6b0122800 nid=0xb655 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007fc6b0120000 nid=0xb654 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007fc6b0119800 nid=0xb653 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007fc6b00e5800 nid=0xb652 in Object.wait() [0x00007fc69938f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000c00d0c10> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x00000000c00d0c10> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007fc6b00e1000 nid=0xb651 in Object.wait() [0x00007fc699490000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000c00d0e40> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000000c00d0e40> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=0 tid=0x00007fc6b004c000 nid=0xb64b runnable [0x00007fc6b7e4a000]
   java.lang.Thread.State: RUNNABLE
	at alluxio.jnifuse.LibFuse.fuse_main_real(Native Method)
	at alluxio.jnifuse.AbstractFuseFileSystem.execMount(AbstractFuseFileSystem.java:112)
	at alluxio.jnifuse.AbstractFuseFileSystem.mount(AbstractFuseFileSystem.java:92)
	at alluxio.fuse.AlluxioFuse.launchFuse(AlluxioFuse.java:172)
	at alluxio.fuse.AlluxioFuse.main(AlluxioFuse.java:136)

"VM Thread" os_prio=0 tid=0x00007fc6b00d7000 nid=0xb650 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007fc6b005f000 nid=0xb64c runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007fc6b0061000 nid=0xb64d runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007fc6b0062800 nid=0xb64e runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007fc6b0064800 nid=0xb64f runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007fc6b013c800 nid=0xb658 waiting on condition 

JNI global references: 507
```

</details>

In thread dump above, we can notice that some threads are stucking at java class loader, as hightlighted below.

**Urgency**
not urgent.

**Are you planning to fix it**
Pull request #15452 .

**Similar problems**
try Googling for "_UnixFileSystem.getBooleanAttributes0_", which may relate to a Java issue.

### PR DESCRIPTION
**Pull request by cangyin**
Please backport to v2.7.3

close #15451

### CODE REVIEW

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks for fixing the issue

**Comment by LuQQiu** [comment]
@cangyin Thanks for fixing the issue, can you help [sign a contribution license agreement](https://cla.alluxio.org/), otherwise we are not able to merge the PR.

Do you know why the extra colon will cause the class loader issue you linked?

**Comment by cangyin** [comment]
@LuQQiu The extra colon will be splited as an empty string, which may be considered as current directory in Java, I think.

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Comment by cangyin** [comment]
I didn't received any email for signing the Contribution License Agreement.

**Comment by HelloHorizon** [comment]
@cangyin can you try to click the above [sign a contribution license agreement](https://cla.alluxio.org/) link to sign the agreement?

**Comment by cangyin** [comment]
@HelloHorizon I did, and tried re-submitting a few times, for Tencent QQ email and Gmail, but no emails were received.

**Comment by cangyin** [comment]
You can just close the PR, and introduce the change in future commits. It's fine.

**Comment by HelloHorizon** [comment]
@Xenorith can you help here?

**Comment by Xenorith** [comment]
i see a single event triggered at 2022-04-26T04:23:16 UTC for the gmail address but something seems wrong with the response from docusign that we integrate with. unfortunately i do not have any additional information; my suggestion would be to try again in 24 hours

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Pull request merged**
