### PR TITLE
Reorganize doc categories

### PR DESCRIPTION
**Pull request by Xenorith**
Problems:
- Need chinese translation of new categories in _config.yml
- Can `Use Cases` page be removed? It was not listed in the overview category
- Can `Metrics` page be removed? It was not listed in the operation category
- 3 API pages (FS, S3 and POSIX APIs) were kept even though the entire API category was not listed in the new layout. Confirm that they should still remain the same?

Change list:
- Overview
  - Move top level pages into overview/
  - Renamed Overview.md to Introduction.md
  - Renamed Architecture-DataFlow.md to Architecture.md
- Core services
  - Moved and renamed corresponding pages into new directory named `core-services/`
  - Moved pages under Structured Data into here
- Install Alluxio
  - Renamed from Deploying Alluxio, with directory name `install/`
  - Removed page on vagrant
  - Added page priorities for listing in desired order
- Alluxio in the Cloud
  - Moved AWS EMR and Dataproc pages into new directory named `cloud/`
- Compute Integrations
  - Renamed from Data applications, with directory name `compute/`
- Storage integrations
  - Renamed from Ufs, with directory name `storage/`
- Operations
  - Moved pages from basic and advanced into `operations/` directory
  - Renamed Command-Line-Interface.md to User-CLI.md
  - Added page priorities for listing in desired order
- Fixed links for all the renames and moves

### CODE REVIEW

**Comment by ZacBlanco** [comment]
Why is the metrics page being removed? I don't understand

**Comment by apc999** [comment]
- Please keep Metrics in Operations
- Please keep Use Cases in Overview
- Keep 3 API pages
I will translate the `_config.yml`

**Comment by Xenorith** [comment]
do the chinese pages need to be reorganized in the same way?

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
