### PR TITLE
Enable both file and table semantics to share distLoad code

### PR DESCRIPTION
**Pull request by JySongWithZhangCe**
### What changes are proposed in this pull request?

Repackaging distributed load code into DistributedLoadUtils to enable file semantics and structured data semantics to share distributed load code.

### Why are the changes needed?
https://github.com/Alluxio/alluxio/issues/13287

### Does this PR introduce any user facing changes?
Nope.

### CODE REVIEW

**Comment by JySongWithZhangCe** [comment]
alluxio-bot, check this please

**Review by rongrong — APPROVED** [review]
Do we have tests to make sure the commands work the same way as before after the refactor?

**Comment by JySongWithZhangCe** [comment]
> Do we have tests to make sure the commands work the same way as before after the refactor?

1. Cmd out put looks like this:
image

**Comment by beinan** [comment]
alluxio-bot, merge this please.

**Pull request merged**
