### PR TITLE
[WIP] Attempt to deflake MultiMasterJournalTest and similar tests

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
Here, I'm not looking for not only the test to pass but for tests like MultiMasterJournalTest to not go to the second try.

**Comment by yuzhu** [comment]
@gpang did some work on getting unique ports for multi master tests, you might want to talk to him

**Comment by bradyoo** [comment]
Thanks. I'll take a look at https://github.com/Alluxio/alluxio/pull/9894/files. I just wanted to trigger some CIs to look at what the results are like and plan to close this PR.

**Comment by gpang** [comment]
My old PR is not the correct final solution, so there is no need to base anything off of that.

**Pull request closed without merging**
