### PR TITLE
Fix file owner and group out of sync in activeSync

### PR DESCRIPTION
**Pull request by fuchaohong**
activeSync:  Fixes file owner&group out of sync

### CODE REVIEW

**Comment by gpang** [comment]
@fuchaohong Hi Thanks for this contribution! I think your branch is in an incorrect state. It contains other commits other than your own, so it is causing conflicts.

**Comment by fuchaohong** [comment]
> @fuchaohong Hi Thanks for this contribution! I think your branch is in an incorrect state. It contains other commits other than your own, so it is causing conflicts.

@gpang Hi Thanks for your adivce! The base branch is wrong, now changed.

**Comment by fuchaohong** [comment]
@gpang Hi Would you please help me answer. I find the reasons for unsuccessful check is building, but i used the same command to build successfully. https://github.com/Alluxio/alluxio/pull/13051/checks?check_run_id=2094216645

**Comment by yuzhu** [comment]
@fuchaohong thanks for your fix. Our normal process is that  we fix any bugs in the master branch and then maintainers will cherry-pick to the needed release branches. So for this fix, could you please target the master branch instead? 

Thanks.

**Comment by fuchaohong** [comment]
> @fuchaohong thanks for your fix. Our normal process is that we fix any bugs in the master branch and then maintainers will cherry-pick to the needed release branches. So for this fix, could you please target the master branch instead?
> 
> Thanks.

@yuzhu  Thanks for your advice. I will try again base the master branch.

**Pull request closed without merging**
