### PR TITLE
Revert "Reuse refcount=0 lock in the LockPool"

### PR DESCRIPTION
**Pull request by yuzhu**
This reverts commit 9a35c1aeeda9b61cffeb563ad8acd3efcfac9624.

### CODE REVIEW

**Comment by apc999** [comment]
@yuzhu  can you leave some message on why we revert this PR, for the information of @maobaolong

**Comment by yuzhu** [comment]
@maobaolong this PR introduced some instability in our testing, with a single thread end up holding many locks and eventually locking up the master. We are investigating the root cause of it, but bisection has pointed to this PR.

**Comment by HelloHorizon** [comment]
code coverage error:
`Error: Codecov failed with the following error: The process '/usr/bin/bash' failed with exit code 1`

**Review by HelloHorizon — APPROVED** [review]
LGTM

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Comment by HelloHorizon** [comment]
alluxio-bot, cherry-pick this to branch-2.6 please

**Comment by maobaolong** [comment]
@yuzhu Thank you for revert the PR related, could you please offer some reproduce steps or show me some more details, I will have a code level check now besides.

**Pull request merged**
