### PR TITLE
[SMALLFIX] increase the heartbeat timeout

### PR DESCRIPTION
**Pull request by peisun1115**
I have seen this in the log:
timed out after 36903ms without a heartbeat
timed out after 29539ms without a heartbeat
timed out after 17920ms without a heartbeat
timed out after 13112ms without a heartbeat

This caused lots of blocks as "LOST":
http://ec2-54-149-189-171.us-west-2.compute.amazonaws.com:19999/browse?path=%2FCREATE_FILE_MUST_CACHE_1.1.0_C30%2F0%2F0%2F0&offset=0&limit=20

I think we need to improve the way to do the heartbeat. It takes too long to copy the block information when the worker has lots of blocks.

### CODE REVIEW

**Comment by ifcharming** [comment]
You might also want to update the documentation for the default value change.

**Comment by peisun1115** [comment]
@ifcharming  Fixed

**Comment by apc999** [comment]
LGTM

**Comment by ifcharming** [comment]
LGTM

**Pull request merged**
