### PR TITLE
[SMALLFIX] Fix jobId format in JobDoesNotExistException

### LINKED ISSUE #15032: change JobDoesNotExistException log: turn jobid to number format
**Alluxio Version:**
alluxio 2.8.0

**Describe the bug**
log as follows:
```
2022-02-15 02:24:07,818 WARN  job.JobMasterClientServiceHandler (RpcUtils.java:callAndReturn) - Exit (Error): getJobStatus: request=jobId: 1641894092546 , Error=alluxio.exception.JobDoesNotExistException: The job of id 1,641,894,092,546 does not exist
```

**Expected behavior**
the log turn from  【The job of id 1,641,894,092,546 does not exist】  to 【The job of id 1641894092546 does not exist】

### PR DESCRIPTION
**Pull request by lilyzhoupeijie**
change jobId to number format
Fixes #15032

### CODE REVIEW

**Review by maobaolong — APPROVED** [review]
LGTM. Thanks for your contribution!

**Comment by lilyzhoupeijie** [comment]
No effect on modules: (alluxio.server.ft.journal.raft.**,alluxio.server.ft.journal.ufs.**) ,can we pass this check?

**Review by jja725 — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Pull request merged**
