### PR TITLE
[SMALLFIX] Adjust alluxio binary and comments to match user cli docs

### PR DESCRIPTION
**Pull request by ZhuTopher**
Small changes to the Alluxio binary and related components' comments which were forgotten in PR #12980 
- Note that no implementation is changing for the alluxio binary, just the usage comment

### CODE REVIEW

**Comment by gpang** [comment]
@ZhuTopher Thanks! For the PR title, the `[DOCFIX]` should be removed. We use that prefix when all the changes are in docs, like the *.md files. Since this PR is changing java files and non .md files, that prefix can be removed.

**Comment by gpang** [comment]
There were some checkstyle errors.
```
/usr/src/alluxio/shell/src/main/java/alluxio/cli/TestRunner.java:58: error: Line is longer than 100 characters (found 120).
/usr/src/alluxio/shell/src/main/java/alluxio/cli/TestRunner.java:62: error: Line is longer than 100 characters (found 141).
```

**Comment by ZhuTopher** [comment]
@gpang Addressed the checkstyle errors

**Comment by ZhuTopher** [comment]
From the failed Java 8 Integration Tests console output:
```
Warning: 973 [WARNING] npm WARN @octokit/plugin-request-log@1.0.3 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.
Error: 5.979 [ERROR]
...
18:01:39.943 [INFO] --- copy-rename-maven-plugin:1.0:copy (copy-and-rename-file) @ alluxio-table-server-underdb ---
Error: 9.945 [ERROR] sourceFile /usr/src/alluxio/table/server/underdb/target/alluxio-table-server-underdb-2.6.0-SNAPSHOT-jar-with-dependencies.jar does not exist
...
Error: 7.526 [ERROR] Failures: 
Error: 7.526 [ERROR] alluxio.client.fs.io.FileOutStreamIntegrationTest.cancelWrite[1]
Error: 7.527 [ERROR]   Run 1: FileOutStreamIntegrationTest.cancelWrite:247 expected:<0> but was:<3000>
Error: 7.527 [ERROR]   Run 2: FileOutStreamIntegrationTest.cancelWrite:247 expected:<0> but was:<2000>
18:25:17.532 [INFO] 
Error: 7.532 [ERROR] Errors: 
Error: 7.532 [ERROR] alluxio.client.fs.io.FileInStreamIntegrationTest.readTest1
Error: 7.532 [ERROR]   Run 1: FileInStreamIntegrationTest.readTest1:126 » TestTimedOut test timed out after ...
Error: 7.533 [ERROR]   Run 2: FileInStreamIntegrationTest.readTest1:126 » TestTimedOut test timed out after ...
18:25:17.534 [INFO] 
18:25:17.535 [INFO] 
Error: 7.535 [ERROR] Tests run: 146, Failures: 1, Errors: 1, Skipped: 4
```

Any idea why those would be occurring? I don't see how the changes in this PR would have caused those errors.

**Comment by LuQQiu** [comment]
Sounds like flaky errors, when you see those errors, you can click the details button of that failed tests and click the rerun button
i triggered those failed tests

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks for fixing the cli docs

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
