### PR TITLE
[ALLUXIO-1703] improve thrift configuration and documentation

### PR DESCRIPTION
**Pull request by pfxuan**
Adjust default min threads used for handling thrift RPC requests; improve en/cn documentation for configuration settings.

### CODE REVIEW

**Comment by yupeng9** [comment]
LGTM. Thanks for the update.

**Comment by pfxuan** [comment]
Any further comments and suggestions for this PR?

**Comment by chengqiangboy** [comment]
I change my alluxio-env.sh  according to the PR, but there is no help in my situation.I use the alluxio as spark's off_heap.
`16/03/22 22:36:06 ERROR type: java.net.SocketTimeoutException: Read timed out
alluxio.org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
        at alluxio.org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:129)
        at alluxio.org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at alluxio.org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129)
        at alluxio.org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
        at alluxio.org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at alluxio.org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
        at alluxio.org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
        at alluxio.org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
        at alluxio.org.apache.thrift.protocol.TProtocolDecorator.readMessageBegin(TProtocolDecorator.java:135)
        at alluxio.org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
        at alluxio.thrift.BlockWorkerClientService$Client.recv_cacheBlock(BlockWorkerClientService.java:255)
        at alluxio.thrift.BlockWorkerClientService$Client.cacheBlock(BlockWorkerClientService.java:241)
        at alluxio.client.block.BlockWorkerClient$3.call(BlockWorkerClient.java:142)
        at alluxio.client.block.BlockWorkerClient$3.call(BlockWorkerClient.java:139)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:322)
        at alluxio.client.block.BlockWorkerClient.cacheBlock(BlockWorkerClient.java:139)
        at alluxio.client.block.LocalBlockOutStream.close(LocalBlockOutStream.java:96)
        at alluxio.client.file.FileOutStream.close(FileOutStream.java:159)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
        at com.esotericsoftware.kryo.io.Output.close(Output.java:168)
        at org.apache.spark.serializer.KryoSerializationStream.close(KryoSerializer.scala:208)
        at org.apache.spark.storage.BlockManager.dataSerializeStream(BlockManager.scala:1196)
        at org.apache.spark.storage.AlluxioBlockManager.putValues(AlluxioBlockManager.scala:127)
        at org.apache.spark.storage.ExternalBlockStore.putIntoExternalBlockStore(ExternalBlockStore.scala:79)
        at org.apache.spark.storage.ExternalBlockStore.putIterator(ExternalBlockStore.scala:67)
        at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:798)
        at org.apache.spark.storage.BlockManager.putIterator(BlockManager.scala:645)
        at org.apache.spark.streaming.receiver.BlockManagerBasedBlockHandler.storeBlock(ReceivedBlockHandler.scala:77)
        at org.apache.spark.streaming.receiver.ReceiverSupervisorImpl.pushAndReportBlock(ReceiverSupervisorImpl.scala:157)
        at org.apache.spark.streaming.receiver.ReceiverSupervisorImpl.pushArrayBuffer(ReceiverSupervisorImpl.scala:128)
        at org.apache.spark.streaming.receiver.ReceiverSupervisorImpl$$anon$3.onPushBlock(ReceiverSupervisorImpl.scala:109)
        at org.apache.spark.streaming.receiver.BlockGenerator.pushBlock(BlockGenerator.scala:296)
`

**Comment by chengqiangboy** [comment]
Thank you very much.

**Pull request merged**
