### PR TITLE
Handle interruptions on various heart beats

### PR DESCRIPTION
**Pull request by ggezer**
Fixes https://github.com/Alluxio/alluxio/issues/9658

### CODE REVIEW

**Comment by ggezer** [comment]
@gpang Recreated to target to master.

**Comment by gpang** [comment]
@ggezer I have noticed that `ReplicationChecker` also runs into issues. Does that have to be handled too?

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
@ggezer Could you cherry-pick this to the appropriate branches

**Pull request merged**
