### PR TITLE
[DOCFIX] Update Chinese HDFS Docs

### PR DESCRIPTION
**Pull request by thanosaw**

### CODE REVIEW

**Comment by LuQQiu** [comment]
jenkins, test this please

**Comment by thanosaw** [comment]
> 53: relative link did not match expected pattern "[命令行界面]({{ '/en/operation/User-CLI.html'| relativize_url}})"
> 
> add space after the html' to match the pattern required

Couldn't find the associated hyperlink

**Comment by LuQQiu** [comment]
> > 53: relative link did not match expected pattern "[命令行界面]({{ '/en/operation/User-CLI.html'| relativize_url}})"
> > add space after the html' to match the pattern required
> 
> Couldn't find the associated hyperlink

Probably from previous merged PR. No worries!

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
