### PR TITLE
Do not wait for web ui to be ready to be ready in tests

### PR DESCRIPTION
**Pull request by bradyoo**
I believe this is going to be greatly increase the stability of the unit tests.

### CODE REVIEW

**Comment by bradyoo** [comment]
@calvinjia What do you think about dropping Webserver serving requirement from waitForReady for Master processes?

**Review by totongcute — APPROVED** [review]

**Review by calvinjia — COMMENTED** [review]
@bradyoo If its a source of test instability, I would prefer checking for the test flag and deciding whether or not to wait for the web server. For production deployments we should ensure the webserver is running.

**Comment by bradyoo** [comment]
Changed to only be the case for tests based on @calvinjia's suggestion

**Review by gpang — COMMENTED** [review]
Thanks! Does this also work for webui or rest tests?

**Review by calvinjia — APPROVED** [review]

**Comment by bradyoo** [comment]
if the webui or rest tests didn't work. The tests for the ci wouldn't be passing.

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Pull request merged**
