### PR TITLE
[ALLUXIO-1924] Fix typo in javadoc of alluxio.master.file.FileSystemMaster#getFileInfoInternal

### PR DESCRIPTION
**Pull request by lettergram**
https://alluxio.atlassian.net/browse/ALLUXIO-1924

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, add to whitelist

**Comment by apc999** [comment]
ok to test

**Comment by jsimsa** [comment]
LGTM

**Comment by apc999** [comment]
LGTM

**Comment by apc999** [comment]
LGTM

**Pull request merged**
