### PR TITLE
Add synchronized to the builder

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Comment by yuzhu** [comment]
This might have caused the NPE during the sync process seen by the community.

**Comment by yuzhu** [comment]
alluxio-bot, test this please

**Comment by yuzhu** [comment]
@HelloHorizon PTAL

**Comment by gpang** [comment]
@yuzhu 
Why does this cause an NPE? I don't think the `synchronized` is necessary, because in that part of the method, there is only 1 thread accessing that builder.

**Comment by yuzhu** [comment]
@gpang this is not the cause of the NPE. closing it now.

**Pull request closed without merging**
