### PR TITLE
Log when it is a file

### PR DESCRIPTION
**Pull request by HelloHorizon**
### What changes were proposed in this pull request?
restore #13558

### CODE REVIEW

**Comment by HelloHorizon** [comment]
@yuzhu FYI

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Comment by HelloHorizon** [comment]
alluxio-bot, cherry-pick this to branch-2.6 please

**Review by yuzhu — COMMENTED** [review]
LGTM

**Pull request merged**
