### PR TITLE
Use boolean instead of String as default value type

### PR DESCRIPTION
**Pull request by bzheng888**
### What changes are proposed in this pull request?
Fix some code style.

### Why are the changes needed?
Code style

### Does this PR introduce any user facing changes?
No

### CODE REVIEW

**Review by maobaolong — APPROVED** [review]
LGTM， thanks for your contribution

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks

**Comment by LuQQiu** [comment]
Error: 1.296 [ERROR] Errors: 
Error: 1.296 [ERROR] alluxio.client.hadoop.FileSystemUriIntegrationTest.multiMasterUriTest
Error: 1.297 [ERROR]   Run 1: FileSystemUriIntegrationTest.multiMasterUriTest:76->testConnection:90 » Timeout
Error: 1.297 [ERROR]   Run 2: FileSystemUriIntegrationTest.multiMasterUriTest:76->testConnection:90 » Timeout

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
