### PR TITLE
[ALLUXIO-1776] Add unit tests for IdUtils

### PR DESCRIPTION
**Pull request by breakdawn**
Add two unit tests for IdUtils. 
mvn test passed.

### CODE REVIEW

**Comment by breakdawn** [comment]
@apc999 This is reopened for #2856 , anything i can follow up?

**Comment by gpang** [comment]
ok to test

**Comment by apc999** [comment]
@breakdawn Thanks for submitting the PR again!

It seems your commits are still not linked to your account yet: see the question mark next on page https://github.com/Alluxio/alluxio/pull/2868/commits/32dd5ded14dbfcc442fc6ef89019cb52e334e3ce
I think you haven't added your email in commit to your account. You could click the question mark to get more instructions.

Let's give one more try. In case there is still some issue, I will merge your PR anyway --- it looks good to me :)

**Comment by breakdawn** [comment]
After configure the email, i can't find the question mark anymore. I'll try to reopen it.

**Pull request closed without merging**
