### PR TITLE
[DOCFIX] Upgrade docker integration example to 1.7.0

### PR DESCRIPTION
**Pull request by bajohns**
Now that 1.7.0 is our the Dockerfile can be updated to get the latest release.

### CODE REVIEW

**Comment by bajohns** [comment]
alluxio-bot, check this please

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
@bajohns The test failure isn't related to this PR

**Comment by bajohns** [comment]
Thanks @calvinjia

**Pull request merged**
