### PR TITLE
[Alluxio-1938] Add unit tests for URIStatus

### PR DESCRIPTION
**Pull request by xgong**
Alluxio-1938. Add unit tests for URIStatus

### CODE REVIEW

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by haoyuan** [comment]
Jenkins, add to whitelist.

**Comment by aaudiber** [comment]
Hi @xgong, it looks like the commit with the tests was reverted, was that intentional?

**Comment by xgong** [comment]
@aaudiber 
Sorry about this. Looks like that I totally messed up my repository.

I have created a new pull request https://github.com/Alluxio/alluxio/pull/3190 for this issue.

Will close this one.

**Comment by xgong** [comment]
This pull request is no longer valid because I messed up my local repository.
Created a new pull request https://github.com/Alluxio/alluxio/pull/3190 for the same ticket.

**Pull request closed without merging**
