### PR TITLE
Downgrade swagger-maven-plugin from 3.1.7 back to 3.1.1

### PR DESCRIPTION
**Pull request by bradyoo**
This broke job and worker REST API docs

### CODE REVIEW

**Review by ZacBlanco — APPROVED** [review]
Have you investigated why they don't work? And can you provide a description of what is broken? Also, this is just for the workers - and not for the masters, right?

**Comment by bradyoo** [comment]
I don't really know why they don't work but the rest doc pages look like this. https://docs.alluxio.io/os/restdoc/edge/proxy/index.html

The proxy and job ones are broken so I doubt it has much to do with workers vs masters.

**Comment by bradyoo** [comment]
Also, can you merge it for me?

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Pull request merged**
