### PR TITLE
Fix FormatUtils.getSizeFromBytes method should supports EB

### PR DESCRIPTION
**Pull request by flaming-archer**
### What changes are proposed in this pull request?

add EB in FormatUtils.getSizeFromBytes.

### Why are the changes needed?
While ufs is very very large, it can display as xxxxEB.

### CODE REVIEW

**Comment by flaming-archer** [comment]
> 

alluxio-bot, check this please

**Comment by flaming-archer** [comment]
> alluxio-bot, check this please

alluxio-bot, check this please

**Comment by flaming-archer** [comment]
> Automated checks report:
> 
> * Commits associated with Github account: PASS
> * PR title follows the conventions: FAIL
>   
>   * The title of the PR does not pass all the checks. Please fix the following issues:
>     
>     * Title must not end with punctuation
>     * First word of title ("FormatUtils.getSizeFromBytes") is not an imperative verb. Please use one of the [valid words](https://raw.githubusercontent.com/Alluxio/alluxio/master/docs/resources/pr/pr_title_words.md)
> 
> Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.

alluxio-bot, check this please

**Comment by flaming-archer** [comment]
@yuzhu @LuQQiu @Xenorith @apc999 Pls help to review.

**Comment by flaming-archer** [comment]
@jenoudet hello, could you please help to review.

**Comment by yuzhu** [comment]
@flaming-archer  hi, we are in the middle of new year/christmas break, so lots of us are on vacation. we will be back the first week of jan. thanks for your contribution.

**Comment by flaming-archer** [comment]
> @flaming-archer hi, we are in the middle of new year/christmas break, so lots of us are on vacation. we will be back the first week of jan. thanks for your contribution.
Ok, have a good vacation ~

**Comment by flaming-archer** [comment]
> 

Ok, have a good vacation ~

**Review by jenoudet — COMMENTED** [review]
Would it be possible to collapse these simple changes into 1 commit? This PR currently has 18 commits, which seems unnecessarily complicated for such a small change.

**Comment by flaming-archer** [comment]
> Would it be possible to collapse these simple changes into 1 commit? This PR currently has 18 commits, which seems unnecessarily complicated for such a small change.

I try some ways but failed, so i make another pr https://github.com/Alluxio/alluxio/pull/14784. Pls help to review.

**Comment by flaming-archer** [comment]
see https://github.com/Alluxio/alluxio/pull/14784

**Pull request closed without merging**
