### PR TITLE
Skip tests with a warning when the config files are not readable

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Comment by yuzhu** [comment]
@LuQQiu i made some changes to change FAILED TO SKIPPED when the config files are not there. That happens a lot in clusters with default settings, the setting gets ignored by hadoop but gets a failed result from validation tool.

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks for the improvement!

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
