### PR TITLE
Add doc about Presto SDK for Dora

### PR DESCRIPTION
**Pull request by JiamingMai**
Add doc about Presto SDK for Dora

### CODE REVIEW

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks for adding the doc!

**Comment by maobaolong** [comment]
@JiamingMai Is this document related to how to use Presto access Dora LocalCache or Dora Cluster?

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
@maobaolong the usage of Presto SDK with dora should be similar to before Presto + Alluxio system cache but with the following two diff:
- Require dora configurations (the same configuration as launching the dora cluster)
- new presto SDK supports full UFS URL and supports clientside ufs fallback

**Pull request merged**
