### PR TITLE
[ALLUXIO-2609] Deprecate Throwables.propagate with RuntimeException in RetryHandlingBlockWorkerClient.java

### PR DESCRIPTION
**Pull request by pilyfer**
https://alluxio.atlassian.net/browse/ALLUXIO-2609

### CODE REVIEW

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
add to whitelist

**Comment by calvinjia** [comment]
alluxio-bot, check this please

**Comment by calvinjia** [comment]
@pilyfer Thanks for improving the code base health!

**Pull request merged**
