### PR TITLE
[ALLUXIO-2326] Fix javadoc in AlluxioShell

### PR DESCRIPTION
**Pull request by Wangxiz**
[https://alluxio.atlassian.net/browse/ALLUXIO-2326]()
Update the javadoc for #printUsage from

*         Method which prints the method to use all the commands.
to
*         Prints usage for all shell commands.

### CODE REVIEW

**Comment by Wangxiz** [comment]
alluxio-bot, check this please

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
add to whitelist

**Comment by apc999** [comment]
Jenkins, test this please

**Pull request merged**
