### PR TITLE
[SMALLFIX] Clean up in the test module

### PR DESCRIPTION
**Pull request by HorizonNet**
Minor fixes in the **test** module.

*LineageMasterIntegrationTest*: Introduced automatic resource management in try statement.
*RPCMessageIntegrationTest*: Introduced automatic resource management in try statement.
*BlockWorkerClientAuthenticationIntegrationTest*: Introduced automatic resource management in try statement.
*MasterClientAuthenticationIntegrationTest*: Introduced automatic resource management in try statement and added documentation.
*AbstractAlluxioShellTest*: Converted if-else-statements into switch statements.

### CODE REVIEW

**Comment by aaudiber** [comment]
LGTM, thanks for the cleanups!

**Comment by aaudiber** [comment]
@HorizonNet ready to merge after merge conflicts are resolved

**Comment by HorizonNet** [comment]
@aaudiber Thanks for the comment. I merged the latest changes into this one.

**Comment by aaudiber** [comment]
LGTM

**Pull request merged**
