### PR TITLE
Update proto codes

### PR DESCRIPTION
**Pull request by LuQQiu**
This PR runs `mvn ... -Pgenerate` directly on the master branch.

### CODE REVIEW

**Comment by yuzhu** [comment]
wasn't there some talk of removing these auto generated files from the repo?

**Comment by LuQQiu** [comment]
I am not sure about those talks, but at least there isn't some PR targetting removing them

**Comment by yuzhu** [comment]
See #10754

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
