### PR TITLE
Support true owner and group by Alluxio FUSE with allow_other options

### LINKED ISSUE #9552: Can't distinguish creator of file by Alluxio FUSE with allow_other options
**Alluxio Version:**
2.0

**Describe the bug**
When mount Alluxio FUSE by user alluxio, if another user creates a file or directory in the mount point, the owner of the file or directory will be the user alluxio. I can't distinguish who is the true owner.

**To Reproduce**
mount Alluxio FUSE by user alluxio
```
alluxio $ alluxio-fuse mount -o allow_other /mnt/alluxio-fuse/ /
```
mkdir by user hahaha
```
hahaha $ cd /mnt/alluxio-fuse
hahaha $ mkdir hahaha
hahaha $ ls -l -d hahaha
drwxr-xr-x 1 alluxio alluxio 0 Jul 24 15:09 hahaha
```

### PR DESCRIPTION
**Pull request by LuQQiu**
fixes #9552
Cherry-picking changes from #9622 

If allow_other fuse option is given, the file/dir created by other users should show its actual creator instead of showing the user who mounted the fuse filesystem.
In this PR, create file and create directory will show real owner and group.

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by gpang** [comment]
@LuQQiu Did you use the cherry-pick command? The original commit message is not showing.

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Comment by LuQQiu** [comment]
@gpang I didn't use cherry-pick, I manually make the same modifications as the original PR (which targets 1.8 and does not merge yet)

**Pull request merged**
