### PR TITLE
 [ALLUXIO-2278] correct 'meta data' to 'metadata'

### PR DESCRIPTION
**Pull request by btlcmr0702**
Accoding the requirement of ALLUXIO-2278 on JIRA , i just fix the javadoc in EvictorTestUtils.java .I correct the word 'meta data' to word 'metadata' 
The link of JIPA ticket is https://alluxio.atlassian.net/browse/ALLUXIO-2278

### CODE REVIEW

**Comment by btlcmr0702** [comment]
alluxio-bot, check this please

**Comment by btlcmr0702** [comment]
alluxio-bot, check this please

**Comment by btlcmr0702** [comment]
alluxio-bot, check this please

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Pull request merged**
