### PR TITLE
Add buildx support for build-docker.sh

### PR DESCRIPTION
**Pull request by JySongWithZhangCe**
### What changes are proposed in this pull request?
Fix https://github.com/Alluxio/alluxio/issues/16821

Developers can execute cross compare with `build-docker.sh`
etc.
`./build-docker.sh buildx linux/arm64`

### Why are the changes needed?
Nope.

### Does this PR introduce any user facing changes?
Nope, just for developers.

### CODE REVIEW

**Comment by JySongWithZhangCe** [comment]
@beinan Would you like to take a look~Thanks♪(･ω･)ﾉ

**Review by Xenorith — COMMENTED** [review]
in case others are using the same script, can we preserve backwards compatibility by setting the most common default value for `build_mode` and `platform`, such that if the script was called as before (ex. `dev/scripts/build-docker.sh path/to/tarball`) it will still operate as before?

**Comment by JySongWithZhangCe** [comment]
> in case others are using the same script, can we preserve backwards compatibility by setting the most common default value for `build_mode` and `platform`, such that if the script was called as before (ex. `dev/scripts/build-docker.sh path/to/tarball`) it will still operate as before?

Makes sense, I'll modify it

**Comment by JySongWithZhangCe** [comment]
> in case others are using the same script, can we preserve backwards compatibility by setting the most common default value for `build_mode` and `platform`, such that if the script was called as before (ex. `dev/scripts/build-docker.sh path/to/tarball`) it will still operate as before?



> in case others are using the same script, can we preserve backwards compatibility by setting the most common default value for `build_mode` and `platform`, such that if the script was called as before (ex. `dev/scripts/build-docker.sh path/to/tarball`) it will still operate as before?

Before this PR, build-docker.sh does not support setting parameters, so there is no backward compatibility issue on parameters. After the second commit is modified, it will be consistent with the previous image tag without specifying buildx.

**Review by Xenorith — APPROVED** [review]

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Pull request merged**
