### PR TITLE
[MERGE] merge facl branch into master

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Comment by yuzhu** [comment]
@calvinjia @gpang  PTAL at this one instead of  #7619

**Comment by calvinjia** [comment]
@yuzhu Were there any new conflicts which needed to be resolved?

**Comment by yuzhu** [comment]
@calvinjia nope

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Pull request merged**
