### PR TITLE
Let distributed load files to specify job worker

### PR DESCRIPTION
**Pull request by maobaolong**
With this PR, we can use distributedLoad shell like this.

```bash
bin/alluxio fs distributedLoad --hosts LOCALITY_ID:rackA  /testdir
```

So, job master can dispatch the task to the job worker which belong to the rackA.

### CODE REVIEW

**Comment by maobaolong** [comment]
@apc999 Can you please take a look at this PR, thank you.

**Comment by apc999** [comment]
@maobaolong  before we proceed with detailed review, I have a high level question:
1. is it possible to leverage https://docs.alluxio.io/os/user/stable/en/operation/Tiered-Locality.html for your purpose, without introducing new concept?
1. since this is a new feature to add, moving forward, we want a design doc similar to the doc attached here: https://github.com/Alluxio/alluxio/issues/13260 . I will tag corresponding owner to review the design doc. in this case it is @ggezer

**Comment by maobaolong** [comment]
@apc999 After a quick overview the document of Tirered-Locality, and a discussion with the original feature requester, I guess maybe `Tiered-Locality` cannot satisfy the request.

I have a simple [design doc ](https://docs.google.com/document/d/13t_c9-MhLuv9iLui6AZZpPM8sVhvrhlZqEf4IeRKy40/edit?usp=sharing)for this feature, please take a look.

**Comment by maobaolong** [comment]
@apc999 Have a discussion offline with Bin again, using `Tiered-Locality Identify` to filter job workers as selected task executors. PTAL.

**Comment by apc999** [comment]
@maobaolong 

`bin/alluxio fs distributedLoad --hosts LOCALITY_ID:rackA  /testdir` looks confusing to me

How about supporting the following:

```
// already supported
bin/alluxio fs distributedLoad --hosts host1,host2  /testdir
bin/alluxio fs distributedLoad --host-file /host/file  /testdir
// to support
bin/alluxio fs distributedLoad --locality id1,id2  /testdir
bin/alluxio fs distributedLoad --locality-file /locality/file  /testdir

```

**Comment by maobaolong** [comment]
@apc999 Thank you for the suggestion, I push a new commit to address your suggestion, PTAL.

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
