### PR TITLE
Move shaded module from a top module to a submodule inside underfs

### PR DESCRIPTION
**Pull request by apc999**
and rename the module to be consistent with other modules

### CODE REVIEW

**Comment by apc999** [comment]
@calvinjia Agree. But having it as a top level module seems an overkill from codebase organization perspective. How about having a `dep` or `shaded` top level module and move this module inside as  `hadoop`? I would imagine in the future, we may need to add more shaded module?

**Comment by calvinjia** [comment]
@apc999 Yeah I think having another top level module for `shaded` would be good. The modules inside should just be shaded libraries and have no Alluxio dependencies.

**Comment by apc999** [comment]
@calvinjia @yuzhu  PTAL

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
alluxio-bot, merge this please

**Pull request merged**
