### PR TITLE
Fix Flaky JobMasterIntegrationTest

### PR DESCRIPTION
**Pull request by bradyoo**
JobMaster has no guarantee that the jobs will be started in order. Route around this by actually waiting for the job to start running.

### CODE REVIEW

**Comment by ZacBlanco** [comment]
Why are we just ignoring it?

**Comment by bradyoo** [comment]
I'm ignoring it for now to prevent this from blocking other people's work
while dealing with distributedLoad issues because this code is not
currently being directly used for anything.

**Comment by bradyoo** [comment]
@ZacBlanco I ended up fixing the test instead.

**Comment by bradyoo** [comment]
Attempt 2

**Comment by bradyoo** [comment]
jenkins, test this please.

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Pull request merged**
