### PR TITLE
[SMALLFIX] Avoid hardcoding write type to touch command

### PR DESCRIPTION
**Pull request by apc999**

### CODE REVIEW

**Comment by apc999** [comment]
alluxio-bot, check this please

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
LGTM
@jsimsa @uronce-cc could one of you take a look?

**Comment by jsimsa** [comment]
Jenkins, test this please

**Comment by jsimsa** [comment]
LGTM

**Comment by apc999** [comment]
Jenkins, test this please

**Pull request merged**
