### PR TITLE
[ALLUXIO-2343] Improve error handling in DefaultAlluxioWorker#createThriftServerSocket

### PR DESCRIPTION
**Pull request by Harry95**
https://alluxio.atlassian.net/browse/ALLUXIO-2343
Remove the log statement

### CODE REVIEW

**Comment by aaudiber** [comment]
ok to test

**Comment by aaudiber** [comment]
Jenkins, add to whitelist

**Comment by Harry95** [comment]
alluxio-bot, check this please

**Comment by Harry95** [comment]
funny

**Comment by apc999** [comment]
LGTM

**Pull request merged**
