### PR TITLE
Support export jvm metric

### LINKED ISSUE #13726: Add jvm metrics to alluxio metrics system
**Is your feature request related to a problem? Please describe.**

Alluxio can export the basic jvm merics, something like gc count, gc pause time, full gc count, full gc pause time, memory usage, thread count(runnable, blocked, time_blocked, xxx).

**Describe the solution you'd like**

Something like this https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/metrics2/source/JvmMetrics.java

**Describe alternatives you've considered**

Add a JvmMetric class to maintain the jvm related metrics.

**Urgency**

Normal

**Additional context**

No

### PR DESCRIPTION
**Pull request by maobaolong**
Fix #13726

### What changes are proposed in this pull request?

Export JVM related metrics

### Why are the changes needed?

Add ClassLoadingGaugeSet and CachedThreadStatesGaugeSet to Alluxio MetricRegistry.

### Does this PR introduce any user facing changes?

Add more metrics.

### CODE REVIEW

**Comment by apc999** [comment]
@LuQQiu  do you remember what other JVM metrics we are collecting?

**Comment by LuQQiu** [comment]
```
  "gauges": {
    "G1-Old-Generation.count": {
      "value": 0
    },
    "G1-Old-Generation.time": {
      "value": 0
    },
    "G1-Young-Generation.count": {
      "value": 4
    },
    "G1-Young-Generation.time": {
      "value": 18
    },
    "heap.committed": {
      "value": 268435456
    },
    "heap.init": {
      "value": 268435456
    },
    "heap.max": {
      "value": 4294967296
    },
    "heap.usage": {
      "value": 0.04063761234283447
    },
    "heap.used": {
      "value": 174537216
    },
    "name": {
      "value": "76874@MacBook-Pro.local"
    },
    "non-heap.committed": {
      "value": 73252864
    },
    "non-heap.init": {
      "value": 7667712
    },
    "non-heap.max": {
      "value": -1
    },
    "non-heap.usage": {
      "value": -68897128
    },
    "non-heap.used": {
      "value": 68897288
    },
    "pools.CodeHeap-'non-nmethods'.committed": {
      "value": 2555904
    },
    "pools.CodeHeap-'non-nmethods'.init": {
      "value": 2555904
    },
    "pools.CodeHeap-'non-nmethods'.max": {
      "value": 5836800
    },
    "pools.CodeHeap-'non-nmethods'.usage": {
      "value": 0.21945175438596493
    },
    "pools.CodeHeap-'non-nmethods'.used": {
      "value": 1280896
    },
    "pools.CodeHeap-'non-profiled-nmethods'.committed": {
      "value": 2555904
    },
    "pools.CodeHeap-'non-profiled-nmethods'.init": {
      "value": 2555904
    },
    "pools.CodeHeap-'non-profiled-nmethods'.max": {
      "value": 122912768
    },
    "pools.CodeHeap-'non-profiled-nmethods'.usage": {
      "value": 0.015047029125566515
    },
    "pools.CodeHeap-'non-profiled-nmethods'.used": {
      "value": 1849472
    },
    "pools.CodeHeap-'profiled-nmethods'.committed": {
      "value": 10551296
    },
    "pools.CodeHeap-'profiled-nmethods'.init": {
      "value": 2555904
    },
    "pools.CodeHeap-'profiled-nmethods'.max": {
      "value": 122908672
    },
    "pools.CodeHeap-'profiled-nmethods'.usage": {
      "value": 0.078383793781451
    },
    "pools.CodeHeap-'profiled-nmethods'.used": {
      "value": 9634048
    },
    "pools.Compressed-Class-Space.committed": {
      "value": 6160384
    },
    "pools.Compressed-Class-Space.init": {
      "value": 0
    },
    "pools.Compressed-Class-Space.max": {
      "value": 1073741824
    },
    "pools.Compressed-Class-Space.usage": {
      "value": 0.005347438156604767
    },
    "pools.Compressed-Class-Space.used": {
      "value": 5741768
    },
    "pools.G1-Eden-Space.committed": {
      "value": 160432128
    },
    "pools.G1-Eden-Space.init": {
      "value": 27262976
    },
    "pools.G1-Eden-Space.max": {
      "value": -1
    },
    "pools.G1-Eden-Space.usage": {
      "value": 0.738562091503268
    },
    "pools.G1-Eden-Space.used": {
      "value": 118489088
    },
    "pools.G1-Eden-Space.used-after-gc": {
      "value": 0
    },
    "pools.G1-Old-Gen.committed": {
      "value": 99614720
    },
    "pools.G1-Old-Gen.init": {
      "value": 241172480
    },
    "pools.G1-Old-Gen.max": {
      "value": 4294967296
    },
    "pools.G1-Old-Gen.usage": {
      "value": 0.011096596717834473
    },
    "pools.G1-Old-Gen.used": {
      "value": 47659520
    },
    "pools.G1-Old-Gen.used-after-gc": {
      "value": 0
    },
    "pools.G1-Survivor-Space.committed": {
      "value": 8388608
    },
    "pools.G1-Survivor-Space.init": {
      "value": 0
    },
    "pools.G1-Survivor-Space.max": {
      "value": -1
    },
    "pools.G1-Survivor-Space.usage": {
      "value": 1
    },
    "pools.G1-Survivor-Space.used": {
      "value": 8388608
    },
    "pools.G1-Survivor-Space.used-after-gc": {
      "value": 8388608
    },
    "pools.Metaspace.committed": {
      "value": 51691520
    },
    "pools.Metaspace.init": {
      "value": 0
    },
    "pools.Metaspace.max": {
      "value": -1
    },
    "pools.Metaspace.usage": {
      "value": 0.9748888792591125
    },
    "pools.Metaspace.used": {
      "value": 50393488
    },
    "total.committed": {
      "value": 341950464
    },
    "total.init": {
      "value": 276103168
    },
    "total.max": {
      "value": 4294967295
    },
    "total.used": {
      "value": 243445616
    },
    "uptime": {
      "value": 194521
    },
    "vendor": {
      "value": "AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.8+10 (11)"
    }
```

**Comment by LuQQiu** [comment]
@maobaolong  what exact metrics will be added? how can we use your newly added metrics to get more information on the jvm?
the added metrics is light or relatively heavy?

**Comment by maobaolong** [comment]
@LuQQiu  The following metrics are new added. 

```json
"loaded": {
"value": 9980
},
"unloaded": {
"value": 23
},
"new.count": {
"value": 0
},
"blocked.count": {
"value": 0
},
"runnable.count": {
"value": 16
},
"terminated.count": {
"value": 0
},
"timed_waiting.count": {
"value": 33
},
"count": {
"value": 58
},
"daemon.count": {
"value": 39
},
"deadlock.count": {
"value": 0
},
"deadlocks": {
"value": []
},
```

We can use these information to measure thread status, healthy status.

These added metrics are light, we get these metrics from MXBean, for thread state related metrics, we cache the result for 5 seconds.

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks for adding the metrics!

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
@maobaolong @LuQQiu  is there any documentation we need to update based on this change?

**Comment by apc999** [comment]
Hey @maobaolong Those JVM metrics are really useful, can you add some docs for the added JVM metrics or even giving more information for the existing jvm metrics so that other users can know how to use them! Appreciate your help

https://docs.alluxio.io/os/user/stable/en/reference/Metrics-List.html#jvm-attributes

**Review by yuzhu — APPROVED** [review]
LGTM, thanks

**Review by LuQQiu — APPROVED** [review]
LGTM! Thanks for adding the jvm metrics docs! This docs are pretty helpful

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
