### PR TITLE
Fix NPE in server address

### PR DESCRIPTION
**Pull request by bf8086**
Fixed an NPE in `GrpcServerAddress` when the address is passed in unresolved.

### CODE REVIEW

**Comment by bf8086** [comment]
@ggezer PTAL.

**Comment by ggezer** [comment]
Thanks for fixing this.
Do we always create InetSocketAddress with a host name? 
There could be problems with Kerberos if there are places where we only specify the port and assume local address. (If Kerberos principals are configured to match reverse lookup name of hosts)

**Comment by bf8086** [comment]
> Thanks for fixing this.
> Do we always create InetSocketAddress with a host name?
> There could be problems with Kerberos if there are places where we only specify the port and assume local address. (If Kerberos principals are configured to match reverse lookup name of hosts)

From Javadoc `InetSocketAddress.getHostName` will return the original host name if given, or in the case of an ip address, a reverse lookup will be used to acquire the hostname.

**Comment by bf8086** [comment]
Jenkins, test this please.

**Comment by ggezer** [comment]
So the earlier behavior is that we take the reverse lookup name even if hostname was provided. Now always using the given hostname may have effects on certificate resolution. We may want to run some tests with this before checking in.

**Comment by ggezer** [comment]
LGTM.

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
