### PR TITLE
Fix checkstyle

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Comment by yuzhu** [comment]
@gpang looks like my last PR had some pom error.. surprised jenkins did not catch this.. PTAL

**Comment by yuzhu** [comment]
@HelloHorizon FYI

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
