### PR TITLE
[ALLUXIO-2070] Define class FileInStreamIntegrationTest as final

### PR DESCRIPTION
**Pull request by xiao-chen**
https://alluxio.atlassian.net/browse/ALLUXIO-2070

### CODE REVIEW

**Comment by RongGu** [comment]
LGTM.

**Comment by uronce-cc** [comment]
LGTM

**Comment by xiao-chen** [comment]
Ran the test locally, passed.
Also searched for usage in current code base, not being used elsewhere.

**Comment by xiao-chen** [comment]
Thanks everyone. :)

**Pull request merged**
