### PR TITLE
[ALLUXIO-2857] Rename file ChmodCommandTest.java to ChmodCommandIntegrationTest.java

### PR DESCRIPTION
**Pull request by XiangruL**
https://alluxio.atlassian.net/browse/ALLUXIO-2857

### CODE REVIEW

**Comment by XiangruL** [comment]
to re-run checks

**Comment by XiangruL** [comment]
to re-run checks

**Comment by XiangruL** [comment]
to re-run checks

**Comment by XiangruL** [comment]
alluxio-bot, check this please

**Comment by XiangruL** [comment]
alluxio-bot, check this please

**Comment by XiangruL** [comment]
alluxio-bot, check this please

**Comment by XiangruL** [comment]
alluxio-bot, check this please

**Comment by XiangruL** [comment]
alluxio-bot, check this please

**Comment by XiangruL** [comment]
alluxio-bot, check this please

**Comment by XiangruL** [comment]
alluxio-bot, check this please

**Comment by XiangruL** [comment]
alluxio-bot, check this please

**Comment by apc999** [comment]
Jenkins, test this please

**Pull request merged**
