### PR TITLE
[SMALLFIX] Use static imports for standard test utilities

### PR DESCRIPTION
**Pull request by qinglanDeku**
Change

import org.junit.Assert;

to

import static org.junit.Assert.assertTrue;

AND

Update all

Assert.{{ method }}*

to

{{ method }}*

For example

update

Assert.assertTrue(mGraph.getRoots().isEmpty());

to

assertTrue(mGraph.getRoots().isEmpty());

### CODE REVIEW

**Comment by qinglanDeku** [comment]
alluxio-bot, check this please

**Comment by qinglanDeku** [comment]
Jenkins, test this please.

**Comment by newnius** [comment]
alluxio-bot, check this please.

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
