### PR TITLE
Fix the bug that PagedDoraWorker is created twice

### PR DESCRIPTION
**Pull request by JiamingMai**
Fix the bug that PagedDoraWorker is created twice.

### CODE REVIEW

**Review by dbw9580 — APPROVED** [review]
LGTM

**Review by huanghua78 — APPROVED** [review]
Looks good

**Comment by huanghua78** [comment]
@LuQQiu Please help review and merge this.

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
