### PR TITLE
[SMALLFIX] reducing the default max size of the block worker Thrift client pool

### PR DESCRIPTION
**Pull request by jsimsa**
This changes prevents a highly concurrent Alluxio client from depleting the Alluxio worker connection pool.

### CODE REVIEW

**Comment by calvinjia** [comment]
@jsimsa Could you add something to the documentation of this value to describe what the best practices are?

**Comment by apc999** [comment]
LGTM

**Comment by jsimsa** [comment]
@calvinjia done

**Comment by apc999** [comment]
LGTM

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
LGTM

**Comment by calvinjia** [comment]
@jsimsa Could you also update the `alluxio-site` defaults file?

**Comment by jsimsa** [comment]
@calvinjia done

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
