### PR TITLE
Remove the countCommand

### PR DESCRIPTION
**Pull request by yyongycy**
### What changes are proposed in this pull request?

Remove the countCommand

### Why are the changes needed?

Remove the countCommand.

### Does this PR introduce any user facing changes?
NA

### CODE REVIEW

**Review by yuzhu — COMMENTED** [review]
I did not know we had this.. but this could be useful as a utility and it is not in the critical path of the code. @apc999 what do you think?

**Comment by yyongycy** [comment]
> I did not know we had this.. but this could be useful as a utility and it is not in the critical path of the code. @apc999 what do you think?

It is not easy to count without the master like metadata. Most likely in object store, no such command.

**Comment by qian0817** [comment]
> > I did not know we had this.. but this could be useful as a utility and it is not in the critical path of the code. @apc999 what do you think?
> 
> It is not easy to count without the master like metadata. Most likely in object store, no such command.

We do not support the "ls -R" command under the dora architecture?

**Review by Jackson-Wang-7 — APPROVED** [review]
LGTM for removing the count comment cuz we don't support them now.

**Comment by yyongycy** [comment]
> > > I did not know we had this.. but this could be useful as a utility and it is not in the critical path of the code. @apc999 what do you think?
> > 
> > 
> > It is not easy to count without the master like metadata. Most likely in object store, no such command.
> 
> We do not support the "ls -R" command under the dora architecture?

this is not related to "ls -R"

**Comment by yyongycy** [comment]
alluxio-bot, merge this pleaes

**Comment by dbw9580** [comment]
From docs: 
> count works recursively and accounts for any nested directories and files.

> this is not related to "ls -R"

`count` is essentially `ls -R` with cosmetics applied. My stance is that with or without `count`, an admin can always do `ls -R` and count the number of files and directories with shell commands. Therefore, it is a matter of usability and UX, not a matter of performance or system stability.

**Comment by yyongycy** [comment]
> From docs:
> 
> > count works recursively and accounts for any nested directories and files.
> 
> > this is not related to "ls -R"
> 
> `count` is essentially `ls -R` with cosmetics applied. My stance is that with or without `count`, an admin can always do `ls -R` and count the number of files and directories with shell commands. Therefore, it is a matter of usability and UX, not a matter of performance or system stability.

From the user point of view, count is a single command, it can't show the cost of this command, that is a little misleading. While "ls -R" will indicate the cost more explicit.

**Review by yuzhu — APPROVED** [review]

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Pull request merged**
