### PR TITLE
[SMALLFIX] Fix a grammar mistake

### PR DESCRIPTION
**Pull request by harris233**
### What changes are proposed in this pull request?
Fixes https://github.com/Alluxio/new-contributor-tasks/issues/626
change "It must be able serialize" to "It must be able to serialize"

### Why are the changes needed?
Fix a grammar mistake

### Does this PR introduce any user facing changes?
No

### CODE REVIEW

**Review by HelloHorizon — APPROVED** [review]
LGTM

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Comment by HelloHorizon** [comment]
@harris233 can you fill the Contribution license agreement?

**Comment by harris233** [comment]
> @harris233 can you fill the Contribution license agreement and fix the style check?

ok

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Pull request merged**
