### PR TITLE
Remove test that hasn't ran for 2 years

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
@yuzhu

**Comment by yuzhu** [comment]
why remove it now? maybe we can resurrect it when we find the time?

**Comment by bradyoo** [comment]
the problem is the way the tests are getting split up when using github-actions doesn't follow slow-tests and since slow-tests has only one entry that hasn't been touched for 2 years, I have decided to remove it.

**Comment by bradyoo** [comment]
There is no way for this test to have any reasonable runtime. This test was slow since the test was instated and never ran ever.

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
