### PR TITLE
Fix to support mount fuse do not report error on macosx

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes are proposed in this pull request?

Fix  mount fuse do not report error on macosx

### CODE REVIEW

**Comment by ssz1997** [comment]
@maobaolong  What is your macosx version? And why the sleep command stops fuse from reporting error?

**Comment by maobaolong** [comment]
@ssz1997 Thanks for your reply.

image

```
➜  ~ sleep 1
➜  ~ sleep 2s
usage: sleep seconds
```

**Comment by jiacheliu3** [comment]
@ssz1997 Could you take a look? Thanks！

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks!

**Review by ssz1997 — APPROVED** [review]

**Review by LuQQiu — APPROVED** [review]

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
@maobaolong do you think this is applicable to the `main` branch? I see the `alluxio-fuse` command looks quite different now. Thanks!

**Pull request merged**
