### PR TITLE
[DOCFIX] Update FS and S3 API documentation

### PR DESCRIPTION
**Pull request by ZacBlanco**
### What changes are proposed in this pull request?

documentation updates and improvements for the FS-API and S3-API pages

### Why are the changes needed?

Many recent updates to the S3 API since the last release

### Does this PR introduce any user facing changes?

no

### CODE REVIEW

**Review by HelloHorizon — APPROVED** [review]
LGTM

**Comment by HelloHorizon** [comment]
@Xenorith can you cherry-pick this pr?

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
