### PR TITLE
[ALLUXIO-2998] avoid unnecessary ufs rename during create

### PR DESCRIPTION
**Pull request by gpang**
https://alluxio.atlassian.net/browse/ALLUXIO-2998

### CODE REVIEW

**Comment by gpang** [comment]
@calvinjia

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
@calvinjia That is an interesting point. Technically, it would be still be possible to use, be we are choosing to default to not care about it for the UFS files. This is because the main UFSes we have already provide strong enough guarantees on concurrent writes. However, if we have a new UFS which has weaker guarantees, this could be useful again.

**Comment by calvinjia** [comment]
Makes sense, thanks

**Pull request merged**
