### PR TITLE
Replace deprecated Matchers to ArgumentMatchers

### PR DESCRIPTION
**Pull request by xichen01**
### What changes are proposed in this pull request?

`org.mockito.Matchers` is deprecated in org.mockito 3.4. This class will likely be removed in version 4.0 It's recommended to change it to `org.mockito.ArgumentMatchers`.

### Why are the changes needed?

Replace deprecated org.mockito.Matchers to org.mockito.ArgumentMatchers

### Does this PR introduce any user facing changes?
no

### CODE REVIEW

**Review by maobaolong — CHANGES_REQUESTED** [review]
@xichen01 Thank you for this contribution. Could you care about the style issue?

**Comment by HelloHorizon** [comment]
reference https://www.javadoc.io/doc/org.mockito/mockito-core/3.4.0/org/mockito/Matchers.html

**Review by HelloHorizon — APPROVED** [review]
Thanks for the improvements @xichen01 ! LGTM

**Review by maobaolong — APPROVED** [review]
Thanks for the contribution.

**Comment by HelloHorizon** [comment]
alluxio-bot, mere this please

**Pull request merged**
