### PR TITLE
Use virtual functions instead of AmazonS3 for temp token refresh

### PR DESCRIPTION
**Pull request by yyongycy**
Use virtual functions instead of AmazonS3 for temp token refresh.

### CODE REVIEW

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks!

**Comment by LuQQiu** [comment]
@yyongycy Fix the codestyle so that i can merge it?

**Comment by yyongycy** [comment]
> @yyongycy Fix the codestyle so that i can merge it?

fixed, please help merge

**Comment by yyongycy** [comment]
This failure looks like the code coverage reporting, not related to the code change.

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
