### PR TITLE
[ALLUXIO-1588] Add test coverage for WorkerClientHeartbeatExecutor

### PR DESCRIPTION
**Pull request by alexnaspo**
added test coverage described in ALLUXIO-1588

### CODE REVIEW

**Comment by yupeng9** [comment]
ok to test

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by aaudiber** [comment]
Jenkins, test this please.

**Comment by yupeng9** [comment]
LGTM. Thanks for adding the test coverage!

**Pull request merged**
