### PR TITLE
[ALLUXIO-2202] change some info/error log to debug as it takes lots of time

### PR DESCRIPTION
**Pull request by peisun1115**

### CODE REVIEW

**Comment by peisun1115** [comment]
@calvinjia

**Comment by gpang** [comment]
@peisun1115 Thanks! Do you have a general idea of how this affects performance?

**Comment by apc999** [comment]
LGTM. In general, we should avoid logging on critical path of individual operations, unless it is one-time

**Comment by calvinjia** [comment]
LGTM, I'm also curious how much of a performance hit this is.

**Comment by peisun1115** [comment]
@apc999 @calvinjia @gpang 

I am going to close this PR for now and reopen it later after more evaluation along with my other PRs.

**Pull request closed without merging**
