### PR TITLE
Improve /fix/upgrade CSI template

### PR DESCRIPTION
**Pull request by ssz1997**
1. The versions of csi node driver registrar and csi provisioner are old and not supported any more. Bump them up to a newer version. 
2. Fix a typo in the controller-rbac template.
3. Improve static pvc so it won't look for any existing storageClass.

### CODE REVIEW

**Comment by ssz1997** [comment]
@Binyang2014 Please take a look at this as well. Thanks!

**Review by LuQQiu — APPROVED** [review]
LGTM， thanks

**Review by Binyang2014 — APPROVED** [review]
LGTM

**Comment by LuQQiu** [comment]
Thanks @Binyang2014 for reviewing it

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
