### PR TITLE
Update PropertyKey.java

### PR DESCRIPTION
**Pull request by DamonFool**
Update the description of MASTER_TTL_CHECKER_INTERVAL_MS

### What changes are proposed in this pull request?

Only property description for MASTER_TTL_CHECKER_INTERVAL_MS is changed.

### Why are the changes needed?

To make the description to be clearer.

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Review by maobaolong — APPROVED** [review]
It LGTM, Thanks for your contribution!

**Comment by maobaolong** [comment]
rerun the failed test.

**Comment by maobaolong** [comment]
@dbw9580 Would you like to take a look at this PR?

**Review by dbw9580 — APPROVED** [review]

**Comment by DamonFool** [comment]
Thanks @maobaolong and @dbw9580 for your review.

**Comment by maobaolong** [comment]
alluxio-bot, merge this please

**Pull request merged**
