### PR TITLE
[ALLUXIO-2162] Add a debug message in SwiftUnderFileSystem.java::getBlockSizeByte

### PR DESCRIPTION
**Pull request by cry2133**
https://alluxio.atlassian.net/browse/ALLUXIO-2162

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by apc999** [comment]
LGTM

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
