### PR TITLE
Change ResultRequired to SummaryOnly

### PR DESCRIPTION
**Pull request by apc999**

### CODE REVIEW

**Review by yuzhu — APPROVED** [review]

**Comment by gpang** [comment]
@apc999 Is this misleading? I think we just send back an empty list, not a summary of the listing. I would assume for a summary we would send back maybe the # of paths, etc, but the client will just get back an empty list.

**Comment by yuzhu** [comment]
does `loadMetadataOnly` work better? Seems like that is the only purpose of this flag right?

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by JySongWithZhangCe** [comment]
Thx!

**Pull request merged**
