### PR TITLE
Remove TableMaster dependency on FileSystemMaster

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes are proposed in this pull request?

The TableMaster does not have anything that needs to depend on the FileSystemMaster, therefore remove the depdency definition

### Does this PR introduce any user facing changes?

No.

### CODE REVIEW

**Comment by jiacheliu3** [comment]
@HelloHorizon I'm not super familiar with TableMaster but based on what I see from the code this is fine. WDYT? Why did TableMaster depend on FileSystemMaster originally?

**Comment by HelloHorizon** [comment]
@maobaolong do you mind adding more context to the description?

**Comment by LuQQiu** [comment]
@maobaolong can you create a github issue with information about why you want this change? thanks!

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks for the improvement!

**Comment by jiacheliu3** [comment]
I quickly checked with @HelloHorizon and there's no objection, let's merge this. Thanks to all participations!

**Comment by maobaolong** [comment]
@LuQQiu I create an issue https://github.com/Alluxio/alluxio/issues/16706 here.

@jiacheliu3 Thanks for the kindly review.

**Pull request merged**
