### PR TITLE
Expose JobService.cancel(jobId) to cli

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
@calvinjia

**Comment by calvinjia** [comment]
@bradyoo Thanks for adding this feature, could you add documentation in the User CLI section?

**Comment by bradyoo** [comment]
@calvinjia: Updated user cli.

**Comment by bradyoo** [comment]
alluxio.master.transport.GrpcMessagingTransportTest.testServerClosed(alluxio.master.transport.GrpcMessagingTransportTest)
  Run 1: GrpcMessagingTransportTest.testServerClosed:157
  Run 2: GrpcMessagingTransportTest.testServerClosed:157

**Comment by bradyoo** [comment]
alluxio-bot, test this please.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Pull request merged**
