### PR TITLE
Make validation tool general

### PR DESCRIPTION
**Pull request by LuQQiu**
Previously validation tool is hardcoded for hms validation tool. Since it may also be used for other tools, this PR makes the ValidationToolRegistry and Factory more generalize.

### CODE REVIEW

**Comment by madanadit** [comment]
```
Tests in error: 
alluxio.server.ft.journal.TriggeredCheckpointTest.ufsJournal(alluxio.server.ft.journal.TriggeredCheckpointTest)
  Run 1: TriggeredCheckpointTest.ufsJournal:63->validateCheckpointInClusterRestart:124 » Timeout
  Run 2: TriggeredCheckpointTest.ufsJournal:63->validateCheckpointInClusterRestart:124 » Timeout
```

**Comment by LuQQiu** [comment]
Tests in error: 
alluxio.server.ft.journal.TriggeredCheckpointTest.ufsJournal(alluxio.server.ft.journal.TriggeredCheckpointTest)
  Run 1: TriggeredCheckpointTest.ufsJournal:63->validateCheckpointInClusterRestart:124 » Timeout
  Run 2: TriggeredCheckpointTest.ufsJournal:63->validateCheckpointInClusterRestart:124 » Timeout

**Comment by madanadit** [comment]
alluxio-bot, test this please.

**Comment by LuQQiu** [comment]
Jenkins, test this please

**Comment by madanadit** [comment]
alluxio-bot, test this please.

**Comment by LuQQiu** [comment]
00:05:47.915 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install (default-install) on project alluxio-core-common: Failed to install metadata org.alluxio:alluxio-core-common:2.3.0-SNAPSHOT/maven-metadata.xml: Could not parse metadata /home/jenkins/.m2/repository/org/alluxio/alluxio-core-common/2.3.0-SNAPSHOT/maven-metadata-local.xml: in epilog non whitespace content is not allowed but got a (position: END_TAG seen ...</metadata>\na... @21:2)  -> [Help 1]

**Comment by LuQQiu** [comment]
Jenkins, test this please

**Comment by LuQQiu** [comment]
Failed tests: 
alluxio.client.file.MetadataCachingBaseFileSystemTest.openFile(alluxio.client.file.MetadataCachingBaseFileSystemTest)
  Run 1: MetadataCachingBaseFileSystemTest.openFile:121->verifyGetStatusThroughRPC:134 
fileSystemMasterClient.getStatus(
    /dir/file,
    <any>

**Comment by LuQQiu** [comment]
Tests in error: 
alluxio.server.ft.journal.TriggeredCheckpointTest.ufsJournal(alluxio.server.ft.journal.TriggeredCheckpointTest)
  Run 1: TriggeredCheckpointTest.ufsJournal:63->validateCheckpointInClusterRestart:124 » Timeout
  Run 2: TriggeredCheckpointTest.ufsJournal:63->validateCheckpointInClusterRestart:124 » Timeout

**Comment by LuQQiu** [comment]
Failures look unrelated. Merge this PR to not block following changes

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
