### PR TITLE
Leave hive fields as unset instead of empty string when the field is null

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Comment by yuzhu** [comment]
@gpang This was discovered during prestosql tests.  When the catalog server sets it to empty string, the fact that the field was null is lost and the connector can not recover that information. 

Doing it this way allows the connector to differentiate between a null field and an empty field.

**Comment by gpang** [comment]
@yuzhu does this have to be cherry-picked to `branch-2.1`?

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick to branch-2.1 please

**Comment by yuzhu** [comment]
> @yuzhu does this have to be cherry-picked to `branch-2.1`?

yes, and done

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please

**Pull request merged**
