### PR TITLE
Update MetricKey.java

### PR DESCRIPTION
**Pull request by xpbob**
use builder replace MetricKey

### What changes are proposed in this pull request?

Remove the redundant MetricKey to simplify code.

### Why are the changes needed?

create metrics in a uniform way

### Does this PR introduce any user facing changes?

no

### CODE REVIEW

**Comment by maobaolong** [comment]
@xpbob Thanks for remove the redundant `MetricKey`, this looks clear more. It LGTM.

**Review by maobaolong — APPROVED** [review]

**Review by dbw9580 — APPROVED** [review]

**Comment by maobaolong** [comment]
alluxio-bot, merge this please.

**Comment by HelloHorizon** [comment]
@xpbob we need the CLA signed before we merge the code, do you mind to send me your email address to me(shouwei@alluxio.com) thus I can send you the CLA? FYI @maobaolong

**Comment by xpbob** [comment]
@HelloHorizon  Thanks, I sent the email

**Pull request merged**
