### PR TITLE
Remove the LeaderCommand.java and LeaderCommandIntegrationTest.java f…

### PR DESCRIPTION
**Pull request by kuszz**
#13512

### CODE REVIEW

**Comment by LuQQiu** [comment]
Same backward compatibility issue, instead of removing a shell command directly, can you deprecated this command and mention that this command will be removed in Alluxio 3.0. There should be some examples in the code base about how to deprecate a command that is no longer needed. and point users using this command to new commands.

**Comment by kuszz** [comment]
> Same backward compatibility issue, instead of removing a shell command directly, can you deprecated this command and mention that this command will be removed in Alluxio 3.0. There should be some examples in the code base about how to deprecate a command that is no longer needed. and point users using this command to new commands.

Thanks, I will reference examples and modify the code

**Comment by apc999** [comment]
same [comment](https://github.com/Alluxio/alluxio/issues/13512#issuecomment-854153335) as @LuQQiu

**Review by apc999 — CHANGES_REQUESTED** [review]
Deprecate the command rather than removing it directly

**Comment by apc999** [comment]
close this PR for now. You can update the code offline and re-open it once you are done

**Pull request closed without merging**
