### PR TITLE
[SMALLFIX] Fix a bug in BlockMasterClientPool.

### PR DESCRIPTION
**Pull request by jsimsa**

### CODE REVIEW

**Comment by jsimsa** [comment]
@calvinjia done, PTAL

**Comment by calvinjia** [comment]
@jsimsa I'm not sure if the logic here is still valid. It looks like we wanted to use a queue which would collect clients as they they were returned to the pool and close them (probably with some timeout), otherwise `mClientList` could just be a set. Is it safe/valid to immediately close clients when the pool is closed? These clients could still be in use.

**Comment by jsimsa** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
As discussed offline the guarantees are enforced by the caller (ie. they need to wait for the clients to complete) or not necessary (because we want to abort all clients).

**Pull request merged**
