### PR TITLE
Bump alluxio-maven image to 0.0.8

### PR DESCRIPTION
**Pull request by ssz1997**
Apply the changes introduced in #15876 and #15881. Update the corresponding image version

### CODE REVIEW

**Review by Xenorith — APPROVED** [review]
code changes look good but... all the fuse tests are unhappy :/

**Comment by ssz1997** [comment]
@Xenorith I think we can merge this

**Comment by Xenorith** [comment]
did you rerun all the tests with the updated image? don't want to accidentally merge based on an outdated test result

**Comment by ssz1997** [comment]
Oops I didn't. Running it now

**Comment by Xenorith** [comment]
looks like they all passed with latest, thanks for rerun

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Pull request merged**
