### PR TITLE
[SMALLFIX]Use static imports for standard test utilities

### PR DESCRIPTION
**Pull request by ZikangZhou**
Change

import org.junit.Assert;
to

import static org.junit.Assert.assertEquals;
AND

Update all

Assert.{{ method }}*
to

{{ method }}*

### CODE REVIEW

**Comment by ZikangZhou** [comment]
> alluxio-bot, check this please

**Comment by ZikangZhou** [comment]
> Automated checks report:
> 
> * Commits associated with Github account: PASS
> * PR title follows the conventions: FAIL
>   
>   * The title of the PR does not pass all the checks. Please fix the following issues:
>     
>     * Title is too long (82 characters). Must be at most 72 characters.
> 
> Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.

alluxio-bot, check this please

**Comment by newnius** [comment]
alluxio-bot, check this please.

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
