### PR TITLE
Update ozone from 1.0.0 to 1.1.0

### PR DESCRIPTION
**Pull request by captainzmc**
### What changes are proposed in this pull request?

Ozone 1.1.0 has been released for a long time and 1.1.0 is more stable than 1.0.0. We can update the ozone version.

### CODE REVIEW

**Comment by captainzmc** [comment]
@maobaolong Please take a look at this PR.

**Comment by maobaolong** [comment]
@captainzmc Would you like to show some change list which have to upgrade the alluxio-side ozone version?

**Comment by captainzmc** [comment]
> @captainzmc Would you like to show some change list which have to upgrade the alluxio-side ozone version?

@maobaolong Ozone 1.1.0 in addition to fix some 1.0 bugs, It also add some future. I think the third one about performance are helpful, because alluxio currently uses OFS/O3FS to access ozone.

1、Volume/Bucket Quota Support
2、Security related enhancements
3、ofs/o3fs performance improvements with Teragen and Spark
4、Recon improvements

**Comment by maobaolong** [comment]
@captainzmc I'm glad that Ozone 1.1.0 have such great features, please list some features or bugfix about client side.

**Comment by apc999** [comment]
@maobaolong any comments ? are you good with this PR?

**Comment by maobaolong** [comment]
@apc999 I'm fine for merge this PR.

**Review by maobaolong — APPROVED** [review]

**Comment by captainzmc** [comment]
> @captainzmc I'm glad that Ozone 1.1.0 have such great features, please list some features or bugfix about client side.
Sorry for the late reply. Yes, there are some optimizations and bug fixes for the 1.1 client. For example, enable trash, optimize delete and rename, and fix o3FS list bugs. These all need to be modified on the client side.
image

**Comment by maobaolong** [comment]
@captainzmc Thanks for your information, @apc999 would you please merge this PR?

**Comment by maobaolong** [comment]
ping @apc999

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
