### PR TITLE
Update Helm version in doc

### PR DESCRIPTION
**Pull request by jiacheliu3**
This is a one-liner fix for Helm version in doc, in complement of [#10384 ]

Ref: https://github.com/Alluxio/alluxio/pull/10396

### CODE REVIEW

**Comment by jiacheliu3** [comment]
This should go into master then can be cherry-picked into 2.1 w/o manual work.

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
@madanadit Up to you whether we want 0.5.2 to be in 2.1, or maybe patched versions of 2.1.

**Comment by madanadit** [comment]
@jiacheliu3 I've created an issue to track this for the next patch release (https://github.com/Alluxio/alluxio/issues/10422). Unfortunately, updating the doc version before we release a new docker image is tricky for now.

**Pull request merged**
