### PR TITLE
Fix some incorrect comments in BlockHeartbeatReporter

### PR DESCRIPTION
**Pull request by jianghuazhu**
### What changes are proposed in this pull request?
In BlockHeartbeatReporter, there are some incorrect comments. The purpose of this pr is to fix them.

### Why are the changes needed?
Fix them will make the document look cleaner.

### Does this PR introduce any user facing changes?
For user, there is no impact.

### CODE REVIEW

**Comment by jianghuazhu** [comment]
There are some compilation errors that don't seem to be relevant to the code I submitted.
@dbw9580 @jenoudet , can you help review this pr? Thank you very much.

**Review by dbw9580 — APPROVED** [review]
LGTM, thanks for fixing the docs!

**Comment by jianghuazhu** [comment]
Thanks @dbw9580 .

**Comment by LuQQiu** [comment]
Java 8 Unit Tests / modules: (alluxio.client.**,alluxio.master.**) (pull_request) Test timeout because of "alluxio.client.file.cache.LocalCacheManagerTest"
https://github.com/Alluxio/alluxio/actions/runs/3820485207/jobs/6523540407

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
