### PR TITLE
Fix getActiveWorkers() in Scheduler

### PR DESCRIPTION
**Pull request by YichuanSun**
### What changes are proposed in this pull request?

When I call the Scheduler.getActiveWorkers(), it returns wrong result. This PR calls updateWorkers() when calls  getActiveWorkers(). Please review its correctness. 

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

### CODE REVIEW

**Comment by YichuanSun** [comment]
Could you please take a look when you have time? @lucyge2022 Thanks!

**Comment by lucyge2022** [comment]
why do we need to do this? who's using Scheduler.getActiveWorkers() and needs to get the most accurate up-to-date result ?

**Comment by YichuanSun** [comment]
> why do we need to do this? who's using Scheduler.getActiveWorkers() and needs to get the most accurate up-to-date result ?

OK, I have read the related code, this fix is no need. Thanks Lucy!

**Comment by YichuanSun** [comment]
abandon this fix.

**Pull request closed without merging**
