### PR TITLE
[ALLUXIO-2563] Improving Logger Names

### PR DESCRIPTION
**Pull request by calvinjia**
https://alluxio.atlassian.net/browse/ALLUXIO-2563

Previously our logger names were broken, defaulting to a hardcoded string. Instead of using the user defined logger category (before it was broken), we now use the class name in order to better filter the logs and remove the need for expensive log4j patterns.

Previous log message:
`2017-02-17 20:06:48,830 WARN  type (LocalUnderFileSystem.java:setOwner) - In order for Alluxio to set local files with the correct user and groups, Alluxio should be the local file system superusers.`

New log message:
`2017-02-17 20:07:40,012 WARN  LocalUnderFileSystem - In order for Alluxio to set local files with the correct user and groups, Alluxio should be the local file system superusers.`

### CODE REVIEW

**Comment by ifcharming** [comment]
LGTM

Thank you for improving the logging convention!

**Comment by yupeng9** [comment]
@calvinjia comparing the before and after, we lose the method name? In your example: `LocalUnderFileSystem.java:setOwner` -> `LocalUnderFileSystem.java`

**Comment by calvinjia** [comment]
@yupeng9 We lose the method name which is considered to be a costly piece of info to log. If the user is okay with taking a performance hit, they can always re enable it by changing the log4j properties.

**Comment by yupeng9** [comment]
Why is there a perf hit, and how much is it?

**Pull request merged**
