### PR TITLE
Fix worker cannot report worker cluster aggregated metrics issue

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes are proposed in this pull request?

Worker cannot report worker related cluster aggregated metrics

### Why are the changes needed?

With this fix, worker can report both client and worker related cluster aggregated metrics to master side.

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Comment by LuQQiu** [comment]
@yuzhu baolong saw a case that
in the worker process
- the client reportMetrics first and can the  initShouldReportMetrics(Client) and set the `sReported=true`
```
  private static synchronized List<alluxio.grpc.Metric> reportMetrics(InstanceType instanceType) {
    if (!sReported) {
      initShouldReportMetrics(instanceType);
      sReported = true;
    }
```
- then the worker itself reportMetrics, but `sReported==false` so worker metrics is not reported.

As a quick workaround, we can init both, but it doesn't sound a clean way of fixing the metricsSystem
@yuzhu what's your opinion

**Comment by maobaolong** [comment]
@LuQQiu Addressed your comment, thanks for pointing it out.

**Comment by maobaolong** [comment]
@yuzhu Maybe a make `reported` as a set can involve a middle state, worker could report to master the metrics not include the worker or client related metric in a short time while one of the reported set is true and another is false.

**Comment by LuQQiu** [comment]
Let's do what @yuzhu suggested,
replicated reported from a boolean to a normal set<instance type> check that whether that instance type is inited.
Since it's inside synchronized method, it's safe

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks for fixing it!

**Comment by LuQQiu** [comment]
Error: 6.299 [ERROR] Errors: 
Error: 6.299 [ERROR] alluxio.client.hadoop.FileSystemUriIntegrationTest.multiMasterUriTest
Error: 6.300 [ERROR]   Run 1: FileSystemUriIntegrationTest.multiMasterUriTest:76->testConnection:90 » Timeout
Error: 6.301 [ERROR]   Run 2: FileSystemUriIntegrationTest.multiMasterUriTest:76->testConnection:90 » Timeout
03:56:26.302 [INFO] 
Warning: 302 [WARNING] Flakes: 
Warning: 302 [WARNING] alluxio.client.rest.S3ClientRestApiTest.listAllMyBuckets
Error: 6.302 [ERROR]   Run 1: S3ClientRestApiTest.listAllMyBuckets:147 s3/ expected:<...e>2021-11-02T03:56:0[7]</CreationDate><Name...> but was:<...e>2021-11-02T03:56:0[6]</CreationDate><Name...>
03:56:26.302 [INFO]   Run 2: PASS


Error: 9.177 [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 82.368 s <<< FAILURE! - in alluxio.client.fs.concurrent.ConcurrentFileInStreamIntegrationTest
Error: 9.196 [ERROR] alluxio.client.fs.concurrent.ConcurrentFileInStreamIntegrationTest.FileInStreamConcurrency  Time elapsed: 37.554 s  <<< FAILURE!
java.lang.AssertionError: Failed with exception(s) [java.lang.RuntimeException: java.io.IOException: Failed to connect to remote block worker: 


Error: 2.211 [ERROR] Tests run: 8, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 34.09 s <<< FAILURE! - in alluxio.client.fs.FileSystemMasterRestartIntegrationTest
Error: 2.233 [ERROR] alluxio.client.fs.FileSystemMasterRestartIntegrationTest.unavailableUfsRecursiveCreate  Time elapsed: 4.106 s  <<< ERROR!
alluxio.exception.AccessControlException: The client user is not authorized so as to be null in server
	at alluxio.security.authentication.AuthenticatedClientUser.getClientUser(AuthenticatedClientUser.java:123)
	at alluxio.master.file.DefaultPermissionChecker.checkPermission(DefaultPermissionChecker.java:101)
	at alluxio.master.file.DefaultFileSystemMaster.listStatus(DefaultFileSystemMaster.java:1044)
	at alluxio.master.file.DefaultFileSystemMaster.listStatus(DefaultFileSystemMaster.java:1109)
	at alluxio.client.fs.FileSystemMasterRestartIntegrationTest.unavailableUfsRecursiveCreate(FileSystemMasterRestartIntegrationTest.java:304)

**Comment by LuQQiu** [comment]
The most important error is FileSystemMasterRestartIntegrationTest, the other looks flaky

this test all failed in another PR
https://github.com/Alluxio/alluxio/runs/4075815657?check_suite_focus=true

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
@Xenorith Please cherry-pick to branch-2.7, thanks!

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
