### PR TITLE
Remove file from UfsAbsentPathCache after persisting

### LINKED ISSUE #16621: "ls" a newly created file causes the file deleted from Alluxio
**Alluxio Version:**
2.7.1

**Describe the bug**
"ls" a newly created file causes the file deleted from Alluxio.

**To Reproduce**

```
$ ./bin/alluxio fs /test/
-rw-rw-rw-  alluxio  alluxio   12353   PERSISTED 12-05-2022 13:50:33:667 100% /test/file.01
-rw-rw-rw-  alluxio  alluxio   12353   PERSISTED 12-05-2022 13:52:44:480 100% /test/file.02

$ ./bin/alluxio fs copyFromLocal test_file /test/file.03
Copied file:///... to /test/file.03

// It needs to "ls" the file directly here. If "ls" the directory, the issue will not occur.
$ ./bin/alluxio fs /test/file.03
Path "/test/file.03" does not exist.

$ ./bin/alluxio fs /test/
-rw-rw-rw-  alluxio  alluxio   12353   PERSISTED 12-05-2022 13:50:33:667 100% /test/file.01
-rw-rw-rw-  alluxio  alluxio   12353   PERSISTED 12-05-2022 13:52:44:480 100% /test/file.02
```

**Expected behavior**
The file should exist in Alluxio.

**Urgency**
Urgent.

**Are you planning to fix it**
Yes

### PR DESCRIPTION
**Pull request by secfree**
### What changes are proposed in this pull request?

Remove the file from UfsAbsentPathCache after async persisting.

### Why are the changes needed?

To fix #16621

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Review by yyongycy — APPROVED** [review]
LGTM

**Comment by yyongycy** [comment]
@tcrain  Please help double check

**Comment by tcrain** [comment]
Looks good, thanks.

**Review by tcrain — APPROVED** [review]

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Pull request merged**
