### PR TITLE
[ALLUXIO-3066]: Clean up Embedded Channel tests

### PR DESCRIPTION
**Pull request by gurmeetb**
https://alluxio.atlassian.net/browse/ALLUXIO-3066

### CODE REVIEW

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by gurmeetb** [comment]
@calvinjia Thanks for running the tests again. This is weird, this time different test cases failed. And if we try running these tests locally in Debug mode, they pass.

**Comment by calvinjia** [comment]
@gurmeetb I suspect there is some kind of race condition which can lead to some kind of deadlock or starvation (since the tests are timing out). Debug mode with breakpoints may cause the timing to be affected.

**Comment by gurmeetb** [comment]
@calvinjia Yes, I also think so. An alternative would be to go with CountDownLatch since two threads may be affecting. I will test locally once and then push if it fixes the issue. Will keep posted soon.

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
@gurmeetb Thanks for improving the code and removing the extraneous logic!

**Pull request merged**
