### PR TITLE
[TACHYON-1316] Import TachyonFileSystem.TachyonFileSystemFactory and …

### PR DESCRIPTION
**Pull request by elonazoulay**
…call TachyonFileSystemFactory.get()

### CODE REVIEW

**Comment by calvinjia** [comment]
Jenkins, add to whitelist.

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
This patch looks good to me.
Thanks for improving the code readability!

+1 LGTM

**Comment by aaudiber** [comment]
Should this PR be going to tachyon-master instead of branch-0.8?

**Comment by calvinjia** [comment]
@elonazoulay could you reopen this one to the master branch? I think only bug fixes and doc fixes are going into branch-0.8 now.

**Comment by uronce-cc** [comment]
@elonazoulay Hey, any update on this? Thanks.

**Comment by haoyuan** [comment]
Hi @elonazoulay . Thanks for the PR. Is there any update on this?

**Comment by yupeng9** [comment]
Closing this because the project has renamed and this patch no longer applies.

**Pull request closed without merging**
