### PR TITLE
Fix the master service order

### PR DESCRIPTION
**Pull request by yyongycy**
### What changes are proposed in this pull request?

Fix the master service order

### Why are the changes needed?
Fix the master service order

### Does this PR introduce any user facing changes?

NA

### CODE REVIEW

**Comment by yyongycy** [comment]
@Xenorith

**Review by jenoudet — APPROVED** [review]

**Comment by maobaolong** [comment]
@yyongycy Is there another way to keep the order? Something like implement the `public Set<Class<? extends Server>> getDependencies()`

**Comment by yyongycy** [comment]
> @yyongycy Is there another way to keep the order? Something like implement the `public Set<Class<? extends Server>> getDependencies()`

This is just purely the order in the file, not actually the dependency

**Comment by yyongycy** [comment]
alluxio-bot, merge this please!

**Pull request merged**
