### PR TITLE
[SMALLFIX] add hive checker pom exclusion (#7726)

### PR DESCRIPTION
**Pull request by LuQQiu**

### CODE REVIEW

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by LuQQiu** [comment]
Jenkins, test this please

**Comment by LuQQiu** [comment]
The tests keep failing on FileSystemMasterIntegrationTest,
but this test runs successfully on my local computer.

**Comment by LuQQiu** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
That test is known to fail. (fixed in different PR)

**Pull request merged**
