### PR TITLE
Change journal tool test to use must cache instead of async

### PR DESCRIPTION
**Pull request by calvinjia**
When using async through there can be timing related issues with the persist step

### CODE REVIEW

**Comment by ggezer** [comment]
Does this help with flakiness? If so, how?

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
@ggezer I think it should help with the JournalToolTest. When that test fails it is usually do to a timing issue caused by the large number of async persists going on in the system.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Pull request merged**
