### PR TITLE
Change the order that we reset state

### PR DESCRIPTION
**Pull request by yuzhu**
@ggezer

### CODE REVIEW

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
@ggezer addressed comment, PTAL. thanks.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-1.8 please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-1.8 please.

**Pull request merged**
