### PR TITLE
[SMALLFIX] Replace unnecessarily verbose NewArrayList<byteBuffer> with new Array…

### PR DESCRIPTION
**Pull request by xhad1234**
[SMALLFIX] Trivial replacement in project width…List<>

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
LGTM

**Comment by apc999** [comment]
@xhad1234 thanks for the patch

this file `keyvalue/common/src/main/java/alluxio/thrift/KeyValueWorkerClientService.java` is auto-generated by thrift. typically we don't modify this kind of files. Could you remove it from your PR?

Thanks

**Comment by jsimsa** [comment]
@xhad1234 thank you for the PR, please address @apc999's comment ... otherwise this LGTM

**Comment by xhad1234** [comment]
Hi, Jiri and Bin,

I've removed the modify of KeyValueWorkerClientService.java and push. But I
could find the previous PR, should I make a new PR for that? Thx

Lei Qi   /  祁 磊
Master of Computational Data Science
School of Computer Science
Carnegie Mellon University

**Comment by xhad1234** [comment]
Forgive me, I found the PD. Done

Lei Qi   /  祁 磊
Master of Computational Data Science
School of Computer Science
Carnegie Mellon University

**Comment by apc999** [comment]
LGTM

**Pull request merged**
