### PR TITLE
[DOCFIX] Improve Async cache docs

### PR DESCRIPTION
**Pull request by yuzhu**
Improve user documentation on async caching

### CODE REVIEW

**Comment by jja725** [comment]
FYI: after merging the load command updates, those metrics @yuzhu  mentioned in the updates are replaced by the following metrics. 
Worker.CacheRequests: "Total number of cache requests received by this worker"

Worker.CacheRequestsAsync: "Total number of async cache requests received by this worker"

Worker.CacheRequestsSync: "Total number of sync cache requests received by this worker")

Worker.CacheSucceededBlocks: "Total number of cache succeeded blocks in this worker")

**Comment by yuzhu** [comment]
@jja725 is there a way for the user to monitor how many AsyncCache requests were submitted vs succeeded like before? seems like we lost that if we just have `Worker.CacheSucceededBlocks` ?

**Comment by jja725** [comment]
> @jja725 is there a way for the user to monitor how many AsyncCache requests were submitted vs succeeded like before? seems like we lost that if we just have `Worker.CacheSucceededBlocks` ?

yeah during the review, we think it's not that valuable to track the sync/async success number and just total number and a single ratio metric to see the separation between the two should be good. If you think individual metrics provide useful information we can add that back easily I think.

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
