### PR TITLE
[DOCFIX] Update Unified-Namespace.md

### PR DESCRIPTION
**Pull request by apc999**
### What changes are proposed in this pull request?

Fix a typo in sync doc

### CODE REVIEW

**Review by Limuzhou — APPROVED** [review]

**Comment by Limuzhou** [comment]
alluxio-bot, merge this please

**Review by HelloHorizon — APPROVED** [review]

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to release-2.6.2 please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.6 please

**Pull request merged**
