### PR TITLE
Fix Fuse write then read or overwrite workloads

### PR DESCRIPTION
**Pull request by LuQQiu**
Address https://github.com/Alluxio/alluxio/issues/15933

### What changes are proposed in this pull request?

Fix the Fuse write then read or overwrite race conditions.

### Why are the changes needed?

Support write then read or write then overwrite workloads

### Does this PR introduce any user facing changes?

NA

### CODE REVIEW

**Comment by LuQQiu** [comment]
@ssz1997 FYI

**Review by ssz1997 — APPROVED** [review]
LGTM. Is this still in Draft?

**Comment by LuQQiu** [comment]
Error: 4.044 [ERROR] Failures: 
Error: 4.044 [ERROR] alluxio.util.JvmPauseMonitorTest.testMockedInfoPause
Error: 4.044 [ERROR]   Run 1: JvmPauseMonitorTest.testMockedInfoPause:106
Error: 4.045 [ERROR]   Run 2: JvmPauseMonitorTest.testMockedInfoPause:103
00:17:14.046 [INFO] 
00:17:14.046 [INFO] 
Error: 4.047 [ERROR] Tests run: 714, Failures: 1, Errors: 0, Skipped: 6

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
