### PR TITLE
Unify journal related fsadmin commands

### PR DESCRIPTION
**Pull request by ggezer**
Fixes https://github.com/Alluxio/alluxio/issues/9542

### CODE REVIEW

**Comment by ggezer** [comment]
@calvinjia PTAL. Thanks!

**Comment by calvinjia** [comment]
@ggezer Do we need to update the documentation for the journal commands?

**Comment by ggezer** [comment]
@calvinjia Right. Doc for `checkpoint` will need to change. We don't have a doc for `quorum` yet, so it'll need to be included.

**Comment by calvinjia** [comment]
@ggezer Do you plan to update the docs in this PR or a separate one?

**Comment by ggezer** [comment]
@calvinjia I'll have a separate doc PR to cover journal related changes.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Pull request merged**
