### PR TITLE
[ALLUXIO-3293] Fix retry policy being invalid when reading local block from a crashed local worker

### PR DESCRIPTION
**Pull request by snodawn**
https://alluxio.atlassian.net/browse/ALLUXIO-3293

### CODE REVIEW

**Comment by snodawn** [comment]
alluxio-bot, check this please

**Comment by snodawn** [comment]
alluxio-bot, check this please

**Comment by snodawn** [comment]
alluxio-bot, check this please

**Comment by apc999** [comment]
I feel the retry logic should stay in `FileInStream` and make `BlockInStream` simpler (try or fail). The reason is `FileInStream` already keeps the retry logic and data structures, so it is easier to reason. @snodawn @aaudiber  ? e.g., in `FileInStream.positionedReadInternal`, we can move `mBlockStore.getInStream` into the `try` block and exception will be handled by `handleRetryableException` and retry continues.

**Comment by apc999** [comment]
@snodawn can you also remove the CLA missing label of this PR by [signing a contribution license agreement](https://cla.alluxio.org). It's all electronic and will take just minutes?

**Comment by aaudiber** [comment]
+1 for keeping the retry logic in `FileInStream`. If `BlockInStream.create` fails, we can throw a new error containing the failed worker name, then `FileInStream` can add the worker to the list of failed workers and do the retry.

**Comment by snodawn** [comment]
@apc999 @aaudiber , so we can move `mBlockStore.getInStream` and `updateStream` in `FileInStream` to try block, and add CreateStreamFailedException bringing the failed worker address when failed.  If there is no problem, i will add the test code later.

**Comment by apc999** [comment]
@snodawn @aaudiber  I thought a bit more on this patch and realized that it can be actually more complicated than I expected previously.  If we only `retry` in `FileInStream`, we have no way to get the failed worker address on creating the `BlockInStream`. I think that is why initially @snodawn put the retry and update the failed workers in `BlockInStream`.

I am playing with some fix locally to see if there is a good (clean I mean) workaround and will let you know

**Comment by snodawn** [comment]
@apc999 yes.  One way is to retry in `BlockInStream`, but it may make `BlockInStream` seem to be a little complex. Another way is add the failed worker info in a new exception as I do in my new commit, which will need to modify more than one files. Of cause, I think the second way may be more standard.

**Comment by apc999** [comment]
@snodawn @aaudiber , how about the following fix? 
Essentially, this fix aims to achieve:
- Update `failedWorkers` when `BlockInStream.create` throws exception 
- Still keep the retry in `FileInStream` class
- Make sure `updateStream()` and `mBlockStore.getInStream()` are within the try-catch so retry can proceed.


```diff
diff --git a/core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java b/core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java
index 9b9ce55175..971cf1fd4b 100644
--- a/core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java
+++ b/core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java
@@ -44,6 +44,7 @@ import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
 import java.io.IOException;
+import java.net.ConnectException;
 import java.util.Collections;
 import java.util.List;
 import java.util.Map;
@@ -212,7 +213,12 @@ public final class AlluxioBlockStore {
     if (dataSource == null) {
       throw new UnavailableException(ExceptionMessage.NO_WORKER_AVAILABLE.getMessage());
     }
-    return BlockInStream.create(mContext, info, dataSource, dataSourceType, options);
+    try {
+      return BlockInStream.create(mContext, info, dataSource, dataSourceType, options);
+    } catch (ConnectException e) {
+      failedWorkers.put(dataSource, System.currentTimeMillis());
+      throw e;
+    }
   }
 
   private Set<WorkerNetAddress> handleFailedWorkers(Set<WorkerNetAddress> workers,
diff --git a/core/client/fs/src/main/java/alluxio/client/file/FileInStream.java b/core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
index b3560c65a1..db528a35bd 100644
--- a/core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
+++ b/core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
@@ -113,8 +113,8 @@ public class FileInStream extends InputStream implements BoundedStream, Position
     CountingRetry retry = new CountingRetry(MAX_WORKERS_TO_RETRY);
     IOException lastException = null;
     while (retry.attempt()) {
-      updateStream();
       try {
+        updateStream();
         int result = mBlockInStream.read();
         if (result != -1) {
           mPosition++;
@@ -122,7 +122,9 @@ public class FileInStream extends InputStream implements BoundedStream, Position
         return result;
       } catch (UnavailableException | DeadlineExceededException | ConnectException e) {
         lastException = e;
-        handleRetryableException(mBlockInStream, e);
+        if (mBlockInStream != null) {
+          handleRetryableException(mBlockInStream, e);
+        }
         mBlockInStream = null;
       }
     }
@@ -151,8 +153,8 @@ public class FileInStream extends InputStream implements BoundedStream, Position
     CountingRetry retry = new CountingRetry(MAX_WORKERS_TO_RETRY);
     IOException lastException = null;
     while (bytesLeft > 0 && mPosition != mLength && retry.attempt()) {
-      updateStream();
       try {
+        updateStream();
         int bytesRead = mBlockInStream.read(b, currentOffset, bytesLeft);
         if (bytesRead > 0) {
           bytesLeft -= bytesRead;
@@ -163,7 +165,9 @@ public class FileInStream extends InputStream implements BoundedStream, Position
         lastException = null;
       } catch (UnavailableException | ConnectException | DeadlineExceededException e) {
         lastException = e;
-        handleRetryableException(mBlockInStream, e);
+        if (mBlockInStream != null) {
+          handleRetryableException(mBlockInStream, e);
+        }
         mBlockInStream = null;
       }
     }
@@ -214,8 +218,9 @@ public class FileInStream extends InputStream implements BoundedStream, Position
         break;
       }
       long blockId = mStatus.getBlockIds().get(Math.toIntExact(pos / mBlockSize));
-      BlockInStream stream = mBlockStore.getInStream(blockId, mOptions, mFailedWorkers);
+      BlockInStream stream = null;
       try {
+        stream = mBlockStore.getInStream(blockId, mOptions, mFailedWorkers);
         long offset = pos % mBlockSize;
         int bytesRead =
             stream.positionedRead(offset, b, off, (int) Math.min(mBlockSize - offset, len));
@@ -227,7 +232,9 @@ public class FileInStream extends InputStream implements BoundedStream, Position
         lastException = null;
       } catch (UnavailableException | DeadlineExceededException | ConnectException e) {
         lastException = e;
-        handleRetryableException(stream, e);
+        if (stream != null) {
+          handleRetryableException(stream, e);
+        }
         stream = null;
       } finally {
         closeBlockInStream(stream);
```

**Comment by snodawn** [comment]
@apc999, agree.  But moving `mBlockInStream = null` and `stream = null` to `if` block would be better?

**Comment by aaudiber** [comment]
looks good. Also make sure to update the javadoc for `getInStream` to indicate that in case of failure it will update the passed-in `failedWorkers` map

**Comment by apc999** [comment]
@snodawn if my proposed fix works for you, can you update this PR (also plugin Andrew's comments)?

**Comment by snodawn** [comment]
@apc999 ok.  I will also add the test code later. And please check again, thanks.

**Comment by apc999** [comment]
@snodawn that is fine. have you pushed your change here?

**Comment by snodawn** [comment]
@apc999 @aaudiber
I'm sorry to miss closing this PR, and try hard to re-open it, but no effect. So I create a new one in https://github.com/Alluxio/alluxio/pull/7828. And the new codes are pushed there.

**Pull request closed without merging**
