### PR TITLE
[DOCFIX] Add links to alluxio-presto-sandbox guide

### PR DESCRIPTION
**Pull request by Xenorith**
update getting started and overview with link to website post @haoyuan @ZacBlanco

### CODE REVIEW

**Comment by Xenorith** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Comment by haoyuan** [comment]
Great!

**Pull request merged**
