### PR TITLE
[SMALLFIX]Use static imports for standard test utilities

### PR DESCRIPTION
**Pull request by MirageLyu**
Use static imports for standard test utilities in /alluxio/core/common/src/test/java/alluxio/master/block/BlockIdTest.java
Change
import org.junit.Assert;
to
import static org.junit.Assert.assertEquals;
AND
Update all
Assert.{{ method }}*
to
{{ method }}*

### CODE REVIEW

**Comment by MirageLyu** [comment]
alluxio-bot, check this please

**Comment by MirageLyu** [comment]
Jenkins, test this please.

**Comment by newnius** [comment]
LGTM

**Comment by aaudiber** [comment]
alluxio-bot, merge this please

**Pull request merged**
