### PR TITLE
[ALLUXIO-2313]Improve javadoc for DynamicResourcePool (member variables)

### PR DESCRIPTION
**Pull request by NJUJYB**
https://alluxio.atlassian.net/browse/ALLUXIO-2313
Add descriptions for member variables and fix comments in DynamicResourcePool.java

### CODE REVIEW

**Comment by NJUJYB** [comment]
alluxio-bot, check this please

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by NJUJYB** [comment]
Thank you. I am so sorry and I misunderstand the meaning. Is that OK for my new commit?

**Comment by NJUJYB** [comment]
alluxio-bot, check this please

**Pull request merged**
