### PR TITLE
Add jobStatus metrics

### LINKED ISSUE #13894: Add metrics for Job service master to monitor the size of each status of job
**Is your feature request related to a problem? Please describe.**

Sometime, job master didn't works as expected, sometime it even didn't work at all, so add some metrics to measure how busy job master is.

**Describe the solution you'd like**

Add a batch of metrics for job service master to monitor the size of each status of job

**Describe alternatives you've considered**

Add some metricKey, and return the size of each status of job

**Urgency**

High

**Additional context**

If we cannot measure it, we cannot maintain it.

### PR DESCRIPTION
**Pull request by kuszz**
### What changes are proposed in this pull request?

Add metrics for Job service master to monitor the size of each status of job

### Why are the changes needed?

Please clarify why the changes are needed. For instance,

Sometime, job master didn't works as expected, sometime it even didn't work at all, so add some metrics to measure how busy job master is.

### Does this PR introduce any user facing changes?

Users can get job status metrics in webui

fix #13894

### CODE REVIEW

**Comment by maobaolong** [comment]
@kuszz Thanks for this useful feature! Have you done any test? If you have, please add the report to the description of this PR.

**Review by yuzhu — CHANGES_REQUESTED** [review]
@kuszz
you need to also instrument `PlanInfo` class

**Comment by kuszz** [comment]
> @kuszz
> you need to also instrument `PlanInfo` class

@yuzhu Now metrics.inc/dec has been in PlanInfo's constructor and setStatus func, should I add in other location?

**Comment by apc999** [comment]
@yuzhu  any input?

**Comment by yuzhu** [comment]
@kuszz could you write some unit test for this?

**Comment by yuzhu** [comment]
@kuszz  any update on this?

**Comment by yuzhu** [comment]
@kuszz  pinging one more time?

**Comment by kuszz** [comment]
> @kuszz pinging one more time?

Oh sorry I've busy with other things lately, I will add test code on Monday after test

**Comment by yuzhu** [comment]
```
Error: 8.472 [ERROR] Failures: 
Error: 8.472 [ERROR] alluxio.master.job.JobMasterTest.cancel
Error: 8.473 [ERROR]   Run 1: JobMasterTest.cancel:210 expected:<1> but was:<0>
Error: 8.473 [ERROR]   Run 2: JobMasterTest.cancel:210 expected:<1> but was:<0>
12:32:48.473 [INFO] 
Error: 8.474 [ERROR] alluxio.master.job.JobMasterTest.run
Error: 8.474 [ERROR]   Run 1: JobMasterTest.run:139 expected:<100> but was:<0>
Error: 8.474 [ERROR]   Run 2: JobMasterTest.run:139 expected:<100> but was:<0>
12:32:48.475 [INFO] 
Error: 8.475 [ERROR] Errors: 
Error: 8.475 [ERROR] alluxio.master.job.JobMasterTest.runNestedNonExistingJobConfig
Error: 8.475 [ERROR]   Run 1: JobMasterTest.runNestedNonExistingJobConfig:115 » IllegalArgument Master.JobCo...
Error: 8.478 [ERROR]   Run 2: JobMasterTest.runNestedNonExistingJobConfig:113 expected:<2> but was:<1>
```

**Comment by yuzhu** [comment]
@kuszz PTAL test errors

**Comment by yuzhu** [comment]
@kuszz ping? I think we are really close on this PR, just a couple of test failures to fix. I think these metrics are going to be very useful to the community.

**Comment by yuzhu** [comment]
@kuszz do you have some time to wrap this up in the coming days? there are some test failures.

**Pull request closed without merging**
