### PR TITLE
Update protolock plugin

### PR DESCRIPTION
**Pull request by yuzhu**
### What changes are proposed in this pull request?

Protolock prevents incompatible protobuf changes such as removing a field from a proto , but we are not using it correctly so far. 

https://github.com/salesforce/proto-backwards-compat-maven-plugin

### Why are the changes needed?
Better backwards compatibility

### CODE REVIEW

**Comment by yuzhu** [comment]
@ggezer  PTAL

**Review by apc999 — APPROVED** [review]
did you check it work locally?

**Comment by yuzhu** [comment]
yes, it would produce this error message 
```
ERROR] Failed to execute goal com.salesforce.servicelibs:proto-backwards-compatibility:1.0.7:backwards-compatibility-check (default) on project alluxio-core-transport: Backwards compatibility check failed! You can override this by specifying allowBreakingChanges=true -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :alluxio-core-transport
```

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
