### PR TITLE
Add mask in logging request

### PR DESCRIPTION
**Pull request by yyongycy**
Framework code for masking read/write request's potential credential.

### CODE REVIEW

**Review by jiacheliu3 — APPROVED** [review]
LGTM

**Comment by yyongycy** [comment]
alluxio-bot, merge this please!

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
