### PR TITLE
[ALLUXIO-2152] Improve exception handling in CommandLineJob

### PR DESCRIPTION
**Pull request by zhuansunxt**
https://alluxio.atlassian.net/browse/ALLUXIO-2152

### CODE REVIEW

**Comment by aaudiber** [comment]
ok to test

**Comment by aaudiber** [comment]
LGTM, thanks for the improvement @zhuansunxt!

**Comment by zhuansunxt** [comment]
Thanks Andrew for the review!

**Comment by ifcharming** [comment]
LGTM

**Pull request merged**
