### PR TITLE
[DOCFIX] Update Hive.md

### LINKED ISSUE #14085: Missing "Move a Partitioned Table"  in Chinese Docs
**Page**
https://docs.alluxio.io/os/user/stable/cn/compute/Hive.html

**Summary**
The method of moving the partition table path to Alluxio is missing in the Chinese document

### PR DESCRIPTION
**Pull request by Stevenchooo**
Fix #14085 

There is no guidance on how to move the Hive partitioned table in the Chinese document.
So I added related content.

### CODE REVIEW

**Comment by Stevenchooo** [comment]
Modify PR-TITLE

**Comment by Stevenchooo** [comment]
alluxio-bot, check this please

**Comment by Stevenchooo** [comment]
alluxio-bot, check this please

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
