### PR TITLE
Remove getTableObjectReq from hms tool

### PR DESCRIPTION
**Pull request by LuQQiu**
get_table_req and get_table_objects_by_name_req are not supported by some older version hms client. Remove this test case

### CODE REVIEW

**Comment by LuQQiu** [comment]
Tests in error: 
alluxio.client.fs.FileOutStreamAsyncWriteIntegrationTest.asyncWritePersistWithNoAutoPersist(alluxio.client.fs.FileOutStreamAsyncWriteIntegrationTest)
  Run 1: FileOutStreamAsyncWriteIntegrationTest.asyncWritePersistWithNoAutoPersist » Runtime
  Run 2: FileOutStreamAsyncWriteIntegrationTest.asyncWritePersistWithNoAutoPersist » Runtime

**Comment by LuQQiu** [comment]
Jenkins, test this please

**Comment by madanadit** [comment]
```
Tests in error: 
alluxio.server.ft.journal.JournalBackupIntegrationTest.backupRestoreEmbedded(alluxio.server.ft.journal.JournalBackupIntegrationTest)
  Run 1: JournalBackupIntegrationTest.after:85 » TestTimedOut test timed out after 6000...
  Run 2: JournalBackupIntegrationTest.backupRestoreEmbedded:138->backupRestoreTest:398 » FileAlreadyExists
```

**Comment by madanadit** [comment]
alluxio-bot, test this please.

**Comment by madanadit** [comment]
```
Tests in error: 
alluxio.client.cli.JournalToolTest.dumpHeapCheckpointFromEmbeddedJournal(alluxio.client.cli.JournalToolTest)
  Run 1: JournalToolTest.dumpHeapCheckpointFromEmbeddedJournal:165->checkpointEmbeddedJournal:206 » Alluxio
  Run 2: JournalToolTest.dumpHeapCheckpointFromEmbeddedJournal:173->findCheckpointDir:260 Unexpected checkpoint list: [] expected:<1> but was:<0>
```

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Pull request merged**
