### PR TITLE
[SMALLFIX] Remove unused logging setting

### PR DESCRIPTION
**Pull request by apc999**

### CODE REVIEW

**Comment by jsimsa** [comment]
LGTM

**Comment by jsimsa** [comment]
could you run `grep -R ACCESS_LOGGER *` in the root and remove all other instances of these environment variables? thanks

**Comment by apc999** [comment]
@jsimsa thanks for the suggestion. Another unused constant related to this has been removed.

**Comment by jsimsa** [comment]
there is one more in bin/alluxio-start.sh

**Comment by jsimsa** [comment]
thanks!

**Comment by apc999** [comment]
@jsimsa  PTAL. thanks.

**Comment by jsimsa** [comment]
LGTM

**Pull request merged**
