### PR TITLE
[ALLUXIO-1989]Remove useless parentheses in LeaderInquireClient#getMasterAddress

### PR DESCRIPTION
**Pull request by killxin**
[ALLUXIO-1989]Remove useless parentheses in LeaderInquireClient#getMasterAddress
https://alluxio.atlassian.net/browse/ALLUXIO-1989

### CODE REVIEW

**Comment by ifcharming** [comment]
Thanks @killxin for contributing to Alluxio!
This PR overall looks good to me.

Per Alluxio convention, can you please use your current PR description as the PR title? And add the JIRA ticket URL in the PR description ? (https://alluxio.atlassian.net/browse/ALLUXIO-1989)

**Comment by ifcharming** [comment]
ok to test

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by ifcharming** [comment]
LGTM, thanks for the improvement!

**Pull request merged**
