### PR TITLE
[SMALLFIX] Use static imports for standard test in IdUtilsTest

### PR DESCRIPTION
**Pull request by tieujason330**
Task: https://github.com/Alluxio/new-contributor-tasks/issues/546

### CODE REVIEW

**Comment by tieujason330** [comment]
Jenkins, please test this

**Comment by tieujason330** [comment]
jenkins, test this please

**Comment by cheng-chang** [comment]
LGTM

**Comment by cheng-chang** [comment]
alluxio-bot, merge this please

**Pull request merged**
