### PR TITLE
Fix FUSE umount logic under Linux

### PR DESCRIPTION
**Pull request by ddadaal**
### What changes are proposed in this pull request?

Fix FUSE umount logic under Linux by falling back to `umount` if `fusermount` returns non-zero code.

Tested under Debian 11 using libfuse2 and libfuse3. CI tests umount logic on alpine:3.10.2. Need more tests on other distros.

### Why are the changes needed?

Previously under Linux, alluxio-fuse uses `fusermount` to umount FUSE mountpoint, and if the call to `fusermount` process throws exception, use `umount` to umount instead. 

However, in some distros (like Debian 11), `fusermount` requires root privileges to umount, and **returns code 1** (not throwing exception) if not. The error message of running `fusermount -u` without root is `fusermount: failed to open /etc/mtab: No such file or directory`. But in Debian 11, `umount` can run without root privilege.

The requirement of root privileges differs in different distros. In the table, `Yes` means root is required to run a command on a distro. Tests on more distros are required.

| Distro | `fusermount -u` | `umount` |
| -- | -- | -- |
| Debian 11 | Yes | No |
| alpine:3.10.2 (docker image) | No | Yes |
| CentOS 7.9.2009 | No | Yes |

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Review by yyongycy — APPROVED** [review]
LGTM

**Comment by LuQQiu** [comment]
@Nizifan @maobaolong @kevincai This PR may help reduce the Fuse mount point failed to umount and left in the kubernetes cluster issue, PTAL

**Review by LuQQiu — APPROVED** [review]
LGTM! Thanks for fixing the umount issue!

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
