### PR TITLE
Fix typo at AbstractFileSystem

### PR DESCRIPTION
**Pull request by singer-bin**
Fixes [Alluxio/new-contributor-tasks/issues#621](https://github.com/Alluxio/new-contributor-tasks/issues/621)
at 
 [alluxio/core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java](https://github.com/singer-bin/alluxio/blob/fbae051d7f2c25df83a298c1d33490a095d015f5/core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java#L723)

### CODE REVIEW

**Comment by maobaolong** [comment]
@singer-bin Thanks for the contribution, please sign the CLA first, thank you.

**Review by beinan — APPROVED** [review]
lgtm

**Review by beinan — CHANGES_REQUESTED** [review]
@singer-bin could you please sign the CLA? then we are able to merge your commit, thanks a lot!

**Comment by singer-bin** [comment]
@maobaolong @beinan Thanks for reviewing the PR, the cla has been signed!

**Review by beinan — APPROVED** [review]
lgtm

**Comment by beinan** [comment]
alluxio-bot, merge this please.

**Pull request merged**
