### PR TITLE
Fix build warning for using keySet()

### PR DESCRIPTION
**Pull request by shangxinli**
### What changes are proposed in this pull request?

Please outline the changes and how this PR fixes the issue.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

### CODE REVIEW

**Comment by Jackson-Wang-7** [comment]
can you tell us more detail about why we need to do that?  or attach the warning content?

**Comment by Jackson-Wang-7** [comment]
LGTM, thanks!

**Review by Jackson-Wang-7 — APPROVED** [review]
LGTM

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Comment by HelloHorizon** [comment]
@shangxinli Hey Xinln, do you mind to sign the Alluxio Contributor License Agreement
 thus we can merge you code? I have sent you the Alluxio Contributor License Agreement.

**Pull request merged**
