### PR TITLE
Change some metastore cache metrics from gauge to counter

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
@LuQQiu I noticed this somewhat obvious improvement when I was testing out some metastore metrics and potential new improvements. Do you think I should be cherry-picking this?

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks for improving!

**Comment by bradyoo** [comment]
LGTM, alluxio-bot, merge this please.

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Comment by LuQQiu** [comment]
@bradyoo Does this PR need to be cherry-picked to branch-2.5

**Comment by bradyoo** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please.

**Comment by bradyoo** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please.

**Pull request merged**
