### PR TITLE
Remove dead code in FileUtils

### PR DESCRIPTION
**Pull request by Haoning-Sun**
### What changes are proposed in this pull request?

Remove useless codes.

### CODE REVIEW

**Comment by yyongycy** [comment]
@dbw9580  please help review

**Review by dbw9580 — APPROVED** [review]
LGTM. Usage of this utility function has been merged into `alluxio.underfs.local.LocalUnderFileSystem#listStatus` https://github.com/Alluxio/alluxio/blob/8f74e6584b6d2d71be3a3737057808b6f77c44ae/underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java#L296-L298

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Pull request merged**
