### PR TITLE
[ALLUXIO-1762] Refactor FileSystemMaster to better organize security related parts

### PR DESCRIPTION
**Pull request by apc999**
https://alluxio.atlassian.net/browse/ALLUXIO-1762

### CODE REVIEW

**Comment by jsimsa** [comment]
please resolve merge conflicts

**Comment by jsimsa** [comment]
otherwise, this looks good to me, thanks for the cleanup!

**Comment by uronce-cc** [comment]
LGTM ++

**Comment by yupeng9** [comment]
LGTM. Thanks for the improvement!

**Comment by ifcharming** [comment]
LGTM, thanks for the improvement!

**Pull request merged**
