### PR TITLE
Add metric Master.RpcQueueLength description

### PR DESCRIPTION
**Pull request by ssz1997**
Add some indication of the metric master rpc queue length

### CODE REVIEW

**Comment by ssz1997** [comment]
@ggezer Please take a look. Thanks!

**Review by ggezer — APPROVED** [review]
thanks!

**Comment by ggezer** [comment]
alluxio-bot, merge this please

**Comment by ssz1997** [comment]
@Xenorith Please help cherry pick this. Thanks!

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
