### PR TITLE
[ALLUXIO-1600] Improve javadoc in webapp

### PR DESCRIPTION
**Pull request by riversand963**
Hello!
I just provided a tentative fix for Alluxio-1600. Please let me know if it works.

Thanks
Yanqin

### CODE REVIEW

**Comment by riversand963** [comment]
alluxio-bot, check this please.

**Comment by riversand963** [comment]
alluxio-bot, check this please.

**Comment by riversand963** [comment]
alluxio-bot, check this please.
https://tachyon.atlassian.net/browse/ALLUXIO-1600
Add description for possible IOException that can be thrown from WebInterfaceBrowseLogsServlet's methods, including displayLocalFile and doGet.

**Comment by ifcharming** [comment]
Hi @riversand963 , thank you very much for contributing to Alluxio!
The change itself looks great and Jenkins is happy.

You probably want to use our latest Alluxio [JIRA](https://alluxio.atlassian.net/) instead of the deprecated Tachyon [JIRA](https://tachyon.atlassian.net/). Note that https://alluxio.atlassian.net/browse/ALLUXIO-1600 is closed, can you close this PR and open another one for a separate new contributor task?

Thanks, and looking forward to your contribution to Alluxio!

**Comment by riversand963** [comment]
Hi Chaomin,


Sure, already done.


Thanks

Yanqin

________________________________

**Pull request closed without merging**
