### PR TITLE
Enable mount specific dir in Alluxio in helm chart

### PR DESCRIPTION
**Pull request by ssz1997**
Previously using helm chart we can only mount the whole Alluxio storage. Now by specifying `FUSE_ALLUXIO_PATH` in the helm chart, we are able to mount one specific directory in Alluxio, both for standalone Fuse and workerFuse.

### CODE REVIEW

**Comment by ssz1997** [comment]
@LuQQiu Please take a look. Thanks!

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
