### PR TITLE
Update metrics and property keys

### PR DESCRIPTION
**Pull request by LuQQiu**
Update the metrics and property keys in Alluxio docs.

### CODE REVIEW

**Comment by LuQQiu** [comment]
@Xenorith i create this PR targetting branch-2.7 to prevent any deviation between branch-2.7 and master

**Comment by Xenorith** [comment]
you will also create the corresponding one for master branch too? otherwise may cause merge conflicts if cherry picking code that changes lines next to these changes

**Comment by LuQQiu** [comment]
https://github.com/Alluxio/alluxio/pull/14392 the master side PR

**Comment by Xenorith** [comment]
maybe need to regenerate since people seem to be updating lots of descriptions for metrics?

**Comment by LuQQiu** [comment]
after nearly all PRs are merged, i can redo this one

**Review by apc999 — APPROVED** [review]

**Pull request closed without merging**
