### PR TITLE
[SMALLFIX] implement CephFS UFS

### PR DESCRIPTION
**Pull request by runsisi**
this is a patch implements `CephFS` UFS, for early reviews.

Ceph version - latest stable release `Luminous 12.2.1`
tested on Linux dist. - `Ubuntu xenial` and `CentOS 7.3`

Since Ceph did not provide a native Java client, we need to install its Java binding for both building and running.

**preparing**
- preparing build environmen for `Ubuntu xenial`
add apt repository for Ceph and install CephFS java binding:
~$ `sudo vi /etc/apt/sources.list.d/ceph.list`
...
deb http://us.ceph.com/debian-luminous/ xenial main
~$ `sudo apt update`
~$ `sudo apt install libcephfs-java`
install maven dependency to local:
~$ `mvn install:install-file -Dfile=/usr/share/java/libcephfs-12.2.1.jar -DgroupId=com.ceph -DartifactId=libcephfs -Dpackaging=jar -Dversion=12.2.1`

- preparing build environmen for `CentOS 7.x`
add yum repository for Ceph and install CephFS java binding:
~$ `sudo vi /etc/yum.repos.d/ceph.repo`
[ceph]
...
baseurl = http://us.ceph.com/rpm-luminous/el7/x86_64/
~$ `sudo yum updateinfo`
~$ `sudo yum install cephfs-java libcephfs_jni-devel`
install maven dependency to local (the stock maven is a little old, may need to install rh-maven35 from sclo first, then `source /opt/rh/rh-maven35/enable` to use maven 3.5.*):
~$ `mvn install:install-file -Dfile=/usr/share/java/libcephfs.jar -DgroupId=com.ceph -DartifactId=libcephfs -Dpackaging=jar -Dversion=12.2.1`

**building**

~$ `mvn install -DskipTests`

**testing**

_NOTE_: before testing, we must have set up a running Ceph cluster, those `alluxio.underfs.cephfs.*` options are Ceph configuration options.

- Ceph cluster w/o CephX authentication
~$ `mvn test -pl underfs/cephfs -DtestCephFSBaseDir=cephfs:///alluxio_test -Dalluxio.underfs.cephfs.mon.host=10.118.202.195`

- Ceph cluster w/ CephX authentication
~$ `mvn test -pl underfs/cephfs -DtestCephFSBaseDir=cephfs:///alluxio_test -Dalluxio.underfs.cephfs.auth.id=admin -Dalluxio.underfs.cephfs.auth.key=AQD+ZxJatkFdOhAAfYRePpTJFoZDRUbx7I9c9A== -Dalluxio.underfs.cephfs.mon.host=10.118.202.195`

Signed-off-by: luo.runbing <luo.runbing@zte.com.cn>

### CODE REVIEW

**Comment by madanadit** [comment]
HI @runsisi!. Thanks for working on this PR. I had a few high-level questions.

1. An alternate approach to use CephFS w/ Alluxio (no code changes) is to mount ceph fs with the kernel driver (http://docs.ceph.com/docs/master/cephfs/kernel/) on each node and then use the LocalUnderFilesystem  under storage module. Can you help me understand the performance advantages of this PR over that approach?. Also, it will be nice to see a performance comparison of the two approaches using Ceph FS (w/ both small and large files).

2. Given that Ceph exposes many interfaces built on top of librados, my sense is that a librados UFS will give us highest raw performance (compared against cephfs, radosgw). Are there reasons other than performance that you are considering w/ this connected?. For example, if interoperating b/w different existing applications using Ceph FS, it makes sense to use the said interface via Alluxio as well.

Thanks!

**Comment by scienceluo** [comment]
Hi @madanadit ! @runsisi is out for business trip, here is our plan:
1. CephFS  VS  CephFS with Alluxio (**In progress**)
2. librados with Alluxio Test

Recently we are busy in another urgent thing, so maybe we will continue this test a few days later, if we have some progress, we will let you know ASAP.

Thanks for your reply.

**Comment by yupeng9** [comment]
@scienceluo thanks for letting us know. Is there any update on this PR?

**Comment by scienceluo** [comment]
@yupeng9 No good news about this pr : ( 

@runsisi I suggest you to close this pr for now, and when you have time to do this, then reopen it.

**Pull request closed without merging**
