### PR TITLE
Refactor for extension

### PR DESCRIPTION
**Pull request by yyongycy**
refactor for extension

### CODE REVIEW

**Comment by maobaolong** [comment]
@yyongycy Would you please give some more context for this refactor? What extension you attempt to?

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks!

**Comment by LuQQiu** [comment]
Error: 1.197 [ERROR] alluxio.client.hadoop.FileSystemUriIntegrationTest.multiMasterUriTest
Error: 1.198 [ERROR]   Run 1: FileSystemUriIntegrationTest.multiMasterUriTest:76->testConnection:90 » Timeout
Error: 1.198 [ERROR]   Run 2: FileSystemUriIntegrationTest.multiMasterUriTest:76->testConnection:90 » Timeout

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
