### PR TITLE
Release workerInfoList when a job completes

### PR DESCRIPTION
**Pull request by yuzhu**
### What changes are proposed in this pull request?

Release a chunk of memory when the job finishes 

### Why are the changes needed?

To help alleviate #13907 

### Does this PR introduce any user facing changes?
No

### CODE REVIEW

**Review by maobaolong — APPROVED** [review]
It's LGTM, thanks for fix this issue.

**Comment by maobaolong** [comment]
Error: 3.401 [ERROR] High: Inconsistent synchronization of alluxio.master.job.plan.PlanCoordinator.mWorkersInfoList; locked 75% of time [alluxio.master.job.plan.PlanCoordinator, alluxio.master.job.plan.PlanCoordinator, alluxio.master.job.plan.PlanCoordinator, alluxio.master.job.plan.PlanCoordinator] Unsynchronized access at PlanCoordinator.java:[line 174]Synchronized access at PlanCoordinator.java:[line 204]Synchronized access at PlanCoordinator.java:[line 158]Synchronized access at PlanCoordinator.java:[line 118] IS2_INCONSISTENT_SYNC

@yuzhu please take a look at the findbugs issue

**Review by apc999 — APPROVED** [review]
Add a UT?

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
