### PR TITLE
Update embedded journal metric descriptions

### PR DESCRIPTION
**Pull request by ZacBlanco**
### What changes are proposed in this pull request?

Update some vague metric descriptions 

### Why are the changes needed?

Descriptions should be clearer to users to enhance understanding

### CODE REVIEW

**Comment by ZacBlanco** [comment]
I verified the metrics using a local cluster with the following docker-compose file:

```
version: "3"

services:
  master1:
    image: alluxio/alluxio:latest
    environment:
      ALLUXIO_MASTER_JAVA_OPTS: " -Dalluxio.master.hostname=master1 -Dalluxio.master.journal.type=EMBEDDED -Dalluxio.master.embedded.journal.addresses=master1:19200,master2:19200 -Dalluxio.master.journal.checkpoint.period.entries=1000 "
    command: "master-only"
  master2:
    image: alluxio/alluxio:latest
    environment: 
      ALLUXIO_MASTER_JAVA_OPTS: " -Dalluxio.master.hostname=master2 -Dalluxio.master.journal.type=EMBEDDED -Dalluxio.master.embedded.journal.addresses=master1:19200,master2:19200 -Dalluxio.master.journal.checkpoint.period.entries=1000 "
    command: "master-only"

```

**Comment by ZacBlanco** [comment]
ping @ggezer

**Review by ggezer — APPROVED** [review]

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Comment by HelloHorizon** [comment]
alluxio-bot, cherry-pick this to branch-2.6 please

**Pull request merged**
