### PR TITLE
[TACHYON-1272] [WIP] Have a more convenient logger

### PR DESCRIPTION
**Pull request by ShaoshanLiu**
implement a common logger to be shared by all classes, this way we avoid each class creating its own instance of logger.

This is WIP, will modify each usage of logger once this gets in.

### CODE REVIEW

**Comment by ShaoshanLiu** [comment]
@calvinjia Hey Calvin, would this be something that you had in mind? a common class that implements the logger?

**Comment by calvinjia** [comment]
@ShaoshanLiu I think this is better than what we currently have, but I'm not sure how performant this will be (since its all through the same logger). Also if there is any issue with the class name. The best way would be if we could have something like a scala trait which provides the boilerplate for the logger.

**Comment by ShaoshanLiu** [comment]
@calvinjia thanks Calvin, the original intention for this change is to reduce memory usage? or to reduce the amount of code?  If it were to reduce memory usage, then we could use a centralized logger, but like you said there could be problems.  If it were to reduce the amount of code, and if we implemented this like a trait, then pretty much every class needs to extend this base class?  Let me know what you think.

thanks,

Shaoshan

**Comment by calvinjia** [comment]
@ShaoshanLiu 
The motivation for this ticket was to improve code maintainability but without a serious cost to performance. Like you said, going with the trait-like implementation is difficult because all classes would need to extend that class (and Java only allows single inheritance), but perhaps there are tricky ways to get what we want?

**Comment by ShaoshanLiu** [comment]
@calvinjia  do you think http://www.tinylog.org/ would work in this case?

**Comment by ShaoshanLiu** [comment]
@calvinjia seems that it is already in maven, http://mvnrepository.com/artifact/org.tinylog, so I think it could be a viable solution.  Benchmark looks good too: http://www.tinylog.org/benchmark

please let me know if this works for you, 

thanks,

Shaoshan

**Comment by calvinjia** [comment]
@ShaoshanLiu 
I'm not sure if its worth to include a new dependency for this ticket which is mostly a nice to have. Are there other projects using this library? 

If there isn't a straightforward way, it may be fine to continue with the current model as it isn't causing any issues.

**Comment by yupeng9** [comment]
@ShaoshanLiu are you still working on this PR. If not, could you close it?

**Comment by yupeng9** [comment]
@ShaoshanLiu I'm closing this PR because the codebase has changed significantly since Nov. Let me know when you plan to push a new one.

**Pull request closed without merging**
