### PR TITLE
Fix fuse shell logging

### PR DESCRIPTION
**Pull request by LuQQiu**
### What changes are proposed in this pull request?

Fix the logging of fuse shell

### Why are the changes needed?

Otherwise the first layer of the exception information will not be shown to users and users won't know the actual failure.

### Does this PR introduce any user facing changes?
Improve fuse shell logging

### CODE REVIEW

**Comment by LuQQiu** [comment]
@Xenorith For Alluxio 2.8, FYI

**Review by ssz1997 — APPROVED** [review]
LGTM

**Comment by LuQQiu** [comment]
Error: 9.874 [ERROR] alluxio.client.cli.job.DistributedCommandsStatsTest.testAsyncPersistCancelStats  Time elapsed: 90.171 s  <<< ERROR!
java.util.concurrent.TimeoutException: Timed out waiting for job 1649811838798 to be one of status [CANCELED] options: WaitForOptions{interval=20, timeout=45000} last value: false

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
@Xenorith Please help cherry-pick to 2.8 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Pull request merged**
