### PR TITLE
[DOCFIX] Update the GCS docs

### PR DESCRIPTION
**Pull request by gpang**

### CODE REVIEW

**Comment by gpang** [comment]
@calvinjia

**Comment by gpang** [comment]
Currently, I tried to update to follow the S3 one, since S3 and GCS are so similar.

**Comment by calvinjia** [comment]
@gpang Did you look at the current documentation? I have an update to the S3 docs to change the style which has not yet been merged: https://github.com/Alluxio/alluxio/pull/8433

**Comment by gpang** [comment]
hrmmm, I did not. I looked at whatever was in the code...

**Comment by gpang** [comment]
@calvinjia I updated the headings to follow the new S3 structure

**Pull request merged**
