### PR TITLE
[ALLUXIO-2286]Fix javadoc in MountTableTest

### PR DESCRIPTION
**Pull request by maqiufang**
https://alluxio.atlassian.net/browse/ALLUXIO-2286
I fixed a javadoc named MountTableTest.java.I updated "an URI" to "a RUI".

### CODE REVIEW

**Comment by jsimsa** [comment]
Jenkins, ok to test

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by aaudiber** [comment]
Jenkins seems to be having a rough day...

**Comment by aaudiber** [comment]
Jenkins, test this please

**Pull request merged**
