### PR TITLE
Add ListingCache metrics

### PR DESCRIPTION
**Pull request by bradyoo**
There are 2 changes here:

1. Make it more specific that load times are loads that happened as a result of a cache miss.
2. Add Listing Cache statistics.

### CODE REVIEW

**Comment by bradyoo** [comment]
@calvinjia The biggest question for this is whether or not I should weigh these metrics against the weight which is used in the ListingCache. I decided against it for simplicity and user understandability sakes but not sure if this is a good idea.

**Comment by bradyoo** [comment]
@calvinjia

**Review by calvinjia — APPROVED** [review]
I think tracking weight is not necessary for recording the cache stats. We may want to introduce a metric to track the size (sum of weights) of the cache though.

**Comment by bradyoo** [comment]
isn't that what MASTER_LISTING_CACHE_SIZE is?

**Comment by calvinjia** [comment]
Yup, looks like we already have it.

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Comment by LuQQiu** [comment]
@bradyoo Does this PR needs to be cherry-picked to branch-2.5?

**Comment by bradyoo** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please.

**Comment by bradyoo** [comment]
need to cherry-pick https://github.com/Alluxio/alluxio/pull/12988 first. so going to wait for that to happen and merge.

**Comment by bradyoo** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please.

**Comment by bradyoo** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please.

**Pull request merged**
