### PR TITLE
Support changing to the user which is not in dockerfile

### PR DESCRIPTION
**Pull request by cheyang**

### CODE REVIEW

**Review by apc999 — APPROVED** [review]

**Review by jiacheliu3 — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.3 please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.3-fuse please

**Pull request merged**
