### PR TITLE
[ALLUXIO-2362] Parameterized raw type declaration of Inode in LockedInodePath class

### PR DESCRIPTION
**Pull request by wcallag3**
https://alluxio.atlassian.net/browse/ALLUXIO-2362

### CODE REVIEW

**Comment by wcallag3** [comment]
alluxio-bot, check this please

**Comment by calvinjia** [comment]
Jenkins, add to whitelist.

**Comment by calvinjia** [comment]
Jenkins, ok to test.

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
