### PR TITLE
modify  [ALLUXIO­2803]

### PR DESCRIPTION
**Pull request by kangzhaoliangbizdata**
The preconditions check in LineageMasterClientServiceHandler(LineageMaster lineageMaster) can be chained to save a statement:
mLineageMaster = Preconditions.checkNotNull(lineageMaster);

### CODE REVIEW

**Comment by aaudiber** [comment]
Hey @kangzhaoliangbizdata, do you mind signing the CLA? You can sign it here: http://cla.alluxio.org/

**Comment by yupeng9** [comment]
@kangzhaoliangbizdata can you sign the CLA?

**Comment by apc999** [comment]
@kangzhaoliangbizdata  could you sign [the contribution license agreement](http://cla.alluxio.org/)?

**Comment by yupeng9** [comment]
@kangzhaoliangbizdata feel free to reopen this PR after you sign the CLA.

**Pull request closed without merging**
