### PR TITLE
[SMALLFIX] Add newline to helm-chart CHANGELOG.md

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Review by yuzhu — APPROVED** [review]

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Comment by jiacheliu3** [comment]
alluxio-bot, cherry-pick this to branch-2.3 please

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
Hi @Xenorith Do you know what happens here?

**Comment by Xenorith** [comment]
this PR was merged 21 days ago? cannot merge a merged PR

**Comment by jiacheliu3** [comment]
sorry i should be merging the cherry pick pr..

**Pull request merged**
