### PR TITLE
Enable v2 s3 proxy by default

### PR DESCRIPTION
**Pull request by lucyge2022**
### What changes are proposed in this pull request?

Enable v2 s3 proxy by default.

### Does this PR introduce any user facing changes?

s3 api will go thru v2 proxy service now.

### CODE REVIEW

**Review by Jackson-Wang-7 — APPROVED** [review]
lgtm, we need to take the first step

**Review by yuzhu — APPROVED** [review]

**Comment by Jackson-Wang-7** [comment]
@lucyge2022 Another point I lost is we may need to also enable V2 proxy in unit tests.

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Comment by lucyge2022** [comment]
> Could you please have a look at #17022? @lucyge2022

will do

**Pull request merged**
