### PR TITLE
Remove the distributedCp/Mv commands

### PR DESCRIPTION
**Pull request by yyongycy**
### What changes are proposed in this pull request?

Remove the distributedCp/Mv commands

### Why are the changes needed?

Remove the distributedCp/Mv commands.

### Does this PR introduce any user facing changes?
NA

### CODE REVIEW

**Review by dbw9580 — APPROVED** [review]

**Comment by dbw9580** [comment]
Also need to remove the entry points in the Alluxio shell

**Comment by yyongycy** [comment]
> Also need to remove the entry points in the Alluxio shell

It is loaded from 
  "fs")
    CLASS="alluxio.cli.fs.FileSystemShell"
    CLASSPATH=${ALLUXIO_CLIENT_CLASSPATH}
    runJavaClass "$@"

Reflect mechanism:

> 
>   public static Map<String, Command> loadCommands(String pkgName, Class[] classArgs,
>       Object[] objectArgs) {
>     Map<String, Command> commandsMap = new HashMap<>();
>     Reflections reflections = new Reflections(Command.class.getPackage().getName());
>     for (Class<? extends Command> cls : reflections.getSubTypesOf(Command.class)) {
>       // Add commands from <pkgName>.command.*
>       if (cls.getPackage().getName().equals(pkgName + ".command")
>           && !Modifier.isAbstract(cls.getModifiers())) {
>         // Only instantiate a concrete class
>         Command cmd = CommonUtils.createNewClassInstance(cls, classArgs, objectArgs);
>         commandsMap.put(cmd.getCommandName(), cmd);
>       }
>     }
>     return commandsMap;
>   }
>

**Review by jja725 — APPROVED** [review]
Thanks

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Pull request merged**
