### PR TITLE
[ALLUXIO-2037] Mark alluxio.Sessions class final

### PR DESCRIPTION
**Pull request by yhua**
Fix the issue: https://alluxio.atlassian.net/browse/ALLUXIO-2037. I have tested with : mvn test  &&  mvn checkstyle:checkstyle && mvn checkstyle:checkstyle

### CODE REVIEW

**Comment by aaudiber** [comment]
Jenkins, ok to test

**Comment by aaudiber** [comment]
Thanks for the PR @yhua!

Could you update your PR title to follow the format `[ALLUXIO-####] Change Description` and include a link to the corresponding JIRA ticket as the first line of the PR message?

The code change looks good to me.

**Comment by yhua** [comment]
Thank you guys, The change is done

**Comment by apc999** [comment]
LGTM, thanks for the patch!

**Pull request merged**
