### PR TITLE
Replace pre-sized array

### PR DESCRIPTION
**Pull request by Haoning-Sun**
### What changes are proposed in this pull request?

Replace pre-sized array.

### Why are the changes needed?
pre-sized array is not recommended in HotSpot based JVMs.

https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_new_reflective_array

### CODE REVIEW

**Comment by yyongycy** [comment]
not understand the relation between presize array and reflect.

**Comment by yyongycy** [comment]
@dbw9580 please take a look

**Review by dbw9580 — APPROVED** [review]
LGTM. The trick is more about eliminating zero initialization of arrays, not reflective construction, tho.

ref: https://www.baeldung.com/java-collection-toarray-methods

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Comment by yyongycy** [comment]
@Haoning-Sun  please check why the test fails all the time.

**Comment by Haoning-Sun** [comment]
@yyongycy I rebased it and all tests passed.

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Pull request merged**
