### PR TITLE
[ALLUXIO-2287]Update "an URI" to "a URI"

### PR DESCRIPTION
**Pull request by njunth**
https://alluxio.atlassian.net/browse/ALLUXIO-2287
Update "an URI" to "a URI" 
Fix javadoc in AlluxioURITest.java

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
@njunth Thanks! Could you please sign the CLA?

**Comment by ifcharming** [comment]
LGTM, thank you for contributing to Alluxio!

**Pull request merged**
