### PR TITLE
Remove unused DefaultBlockWorker#UFS_BLOCK_OPEN_TIMEOUT_MS

### PR DESCRIPTION
**Pull request by jianghuazhu**
### What changes are proposed in this pull request?
In DefaultBlockWorker, there are some constants that are not used. The purpose of this pr is to fix them.
Details: https://github.com/Alluxio/alluxio/issues/16652

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?
For the user, there is no impact.

### CODE REVIEW

**Comment by jianghuazhu** [comment]
Can you help review this pr,  @rongrong  @yuzhu @jja725 .
Thank you very much.

**Review by jja725 — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by jianghuazhu** [comment]
Thanks @jja725 .

**Comment by jianghuazhu** [comment]
Closes #16652

**Comment by jianghuazhu** [comment]
Hi @jja725 , this pr has existed for several days, could you please help to combine it into the master branch?
Thank you very much.

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
