### PR TITLE
[DOCFIX] Add dora doc structure

### PR DESCRIPTION
**Pull request by LuQQiu**
Add the doc structure

### CODE REVIEW

**Comment by LuQQiu** [comment]
alluxio-bot, recheck this please

**Comment by maobaolong** [comment]
@LuQQiu It seems work in progress?

**Comment by maobaolong** [comment]
@bzheng888 Please keep an eye on this PR 👁

**Comment by LuQQiu** [comment]
@maobaolong will have quick iterations on doc updates, and feel free to give us feedback on what docs are helpful for you

**Review by huanghua78 — APPROVED** [review]
Looks good.

**Review by dbw9580 — APPROVED** [review]
LGTM, thanks for putting the docs together!

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by maobaolong** [comment]
@LuQQiu Thanks for this useful document, it can certainly help us to getting closer to Dora.

It would be better if the presto with dora document can be completed, then we can run some big data workload test follow the instruments.

**Comment by JiamingMai** [comment]
> @LuQQiu Thanks for this useful document, it can certainly help us to getting closer to Dora.
> 
> It would be better if the presto with dora document can be completed, then we can run some big data workload test follow the instruments.

I will complete it later.

**Comment by ssz1997** [comment]
@LuQQiu I'm here to complain about the PR title. I was looking for the deployment instruction, and I know if it exists it must be somewhere inside the dora branch. I checked all the commits in the dora branch, and I saw the title of this PR is "add dora doc structure", which made me incorrectly thought "this doc change only has structure but not content", so I missed it :( And the description provide no extra information :(

**Pull request merged**
