### PR TITLE
Add eventual consistency support to createFile when creating ufs blocks

### PR DESCRIPTION
**Pull request by LuQQiu**
When creating ufs blocks, Alluxio knows from its metadata that the file does not exist and should retry creating files. Change from create to createNonexistingFile here to add eventual consistency support.

### CODE REVIEW

**Comment by LuQQiu** [comment]
@madanadit I look again all the places that use `create` instead of `createNonExistingFile`, this is the only place that within alluxio namespace control. May help to solve the create file failure. PTAL, thanks

**Comment by madanadit** [comment]
jenkins, test this please.

**Comment by madanadit** [comment]
jenkins, test this please.

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Pull request merged**
