### PR TITLE
[ALLUXIO-2029] Use StringBuilder instead of StringBuffer to avoid unnecessary synchronization

### PR DESCRIPTION
**Pull request by madanadit**
https://alluxio.atlassian.net/browse/ALLUXIO-2029

### CODE REVIEW

**Comment by aaudiber** [comment]
ok to test

**Comment by ifcharming** [comment]
add to whitelist

**Comment by aaudiber** [comment]
LGTM

**Comment by ifcharming** [comment]
LGTM, thanks for the improvement!

**Comment by madanadit** [comment]
Thanks Andrew!

**Pull request merged**
