### PR TITLE
[ALLUXIO-3040] Shade runtime client jar: no profiles are required

### PR DESCRIPTION
**Pull request by apc999**
https://alluxio.atlassian.net/browse/ALLUXIO-3040

Tested with Hadoop and Spark

### CODE REVIEW

**Comment by calvinjia** [comment]
@apc999 Have you done any validation for the shaded jar? I'm not sure if the logger will still work correctly after shading.

**Comment by apc999** [comment]
@calvinjia removed log4j and tested with Spark

**Comment by calvinjia** [comment]
@apc999 Do you want to modify the script and docs in this PR?

**Comment by apc999** [comment]
@calvinjia will do it in a separate PR

**Pull request merged**
