### PR TITLE
Set the physical ip for alluxio-fuse

### LINKED ISSUE #9623: alluxio.user.file.passive.cache.enabled=true not work
**Alluxio Version:**
What version of Alluxio are you using?

tag v2.0.0

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

### PR DESCRIPTION
**Pull request by zrss**
fix #9623

### CODE REVIEW

**Comment by apc999** [comment]
thanks for your contribution @zrss  ! @madanadit can help you review and merge the change (if all good). Meanwhile, can you sign the CLA https://cla.alluxio.org/ ? Let me know if you already done so and I could remove the check label

**Comment by zrss** [comment]
@apc999 , done, and the status is `Sent` ...

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Comment by madanadit** [comment]
alluxio-bot, cherry-pick this to master please.

**Pull request merged**
