### PR TITLE
[ALLUXIO-1973] Revert jets3t version to 0.8.1 for S3 UFS due to a performance regression.

### PR DESCRIPTION
**Pull request by ifcharming**
https://alluxio.atlassian.net/browse/ALLUXIO-1973

This PR:
- Reverts https://github.com/Alluxio/alluxio/pull/3043
- Reverts https://github.com/Alluxio/alluxio/pull/3314
- Downgrades jets3t dependency version to 0.8.1.
Those two features will be added back once jets3t 0.9.5 is released with fixes.

Tested with both S3 and GCS locally.
`./bin/alluxio runTests` passed.

Integration tests results with -Ps3Test:
```
Running alluxio.underfs.UnderStorageSystemInterfaceIntegrationTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 91.582 sec
Running alluxio.client.RemoteBlockInStreamIntegrationTest
Tests run: 32, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 476.201 sec
Running alluxio.client.keyvalue.KeyValuePartitionIntegrationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.723 sec
Running alluxio.client.keyvalue.KeyValueSystemIntegrationTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 177.341 sec
Running alluxio.client.BufferedBlockInStreamIntegrationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 58.332 sec
Running alluxio.client.ReadOnlyMountIntegrationTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 89.726 sec
Running alluxio.client.FileOutStreamAsyncWriteIntegrationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.739 sec
Running alluxio.client.LocalBlockInStreamIntegrationTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 27.552 sec
Running alluxio.client.concurrent.FileInStreamConcurrencyIntegrationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.401 sec
Running alluxio.client.FileInStreamIntegrationTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 100.074 sec
Running alluxio.client.FreeAndDeleteIntegrationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 sec
Running alluxio.client.FileOutStreamIntegrationTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 165.845 sec
Running alluxio.client.FileSystemUtilsIntegrationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 31.463 sec
Running alluxio.client.FileSystemIntegrationTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 111.025 sec
Running alluxio.shell.AlluxioShellUtilsTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.009 sec
Running alluxio.shell.command.CopyToLocalCommandTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 86.837 sec
Running alluxio.shell.command.LocationCommandTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.908 sec
Running alluxio.shell.command.SetTtlCommandTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.026 sec
Running alluxio.shell.command.CountCommandTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.182 sec
Running alluxio.shell.command.FreeCommandTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec
Running alluxio.shell.command.ChgrpCommandTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.837 sec
Running alluxio.shell.command.CopyFromLocalCommandTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 169.7 sec
Running alluxio.shell.command.RmrCommandTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 23.049 sec
Running alluxio.shell.command.RmCommandTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.778 sec
Running alluxio.shell.command.LoadCommandTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.258 sec
Running alluxio.shell.command.TouchCommandTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.067 sec
Running alluxio.shell.command.MkdirCommandTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 41.053 sec
....
```

Partial integration tests results with -PgcsTest:
```
Running alluxio.client.BufferedBlockInStreamIntegrationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.395 sec
Running alluxio.client.concurrent.FileInStreamConcurrencyIntegrationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.006 sec
Running alluxio.client.FileInStreamIntegrationTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.767 sec
Running alluxio.client.FileOutStreamAsyncWriteIntegrationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 31.807 sec
```

### CODE REVIEW

**Comment by ifcharming** [comment]
@calvinjia @apc999

**Comment by apc999** [comment]
LGTM

**Comment by ifcharming** [comment]
More GCS integration test results:

`cd tests; mvn test -PgcsTest`
```
Running alluxio.client.BufferedBlockInStreamIntegrationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.395 sec
Running alluxio.client.concurrent.FileInStreamConcurrencyIntegrationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.006 sec
Running alluxio.client.FileInStreamIntegrationTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.767 sec
Running alluxio.client.FileOutStreamAsyncWriteIntegrationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 31.807 sec
Running alluxio.client.FileOutStreamIntegrationTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 88.073 sec
Running alluxio.client.FileSystemIntegrationTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 184.347 sec
Running alluxio.client.FileSystemUtilsIntegrationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 40.017 sec
Running alluxio.client.FreeAndDeleteIntegrationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec
Running alluxio.client.IsolatedFileSystemIntegrationTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 103.048 sec
Running alluxio.client.keyvalue.KeyValuePartitionIntegrationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.663 sec
Running alluxio.client.keyvalue.KeyValueSystemIntegrationTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.439 sec
Running alluxio.client.LocalBlockInStreamIntegrationTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.272 sec
Running alluxio.client.ReadOnlyMountIntegrationTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 138.115 sec
Running alluxio.client.RemoteBlockInStreamIntegrationTest
1Tests run: 32, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 477.875 sec
Running alluxio.collections.IndexedSetConcurrencyTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.604 sec
Running alluxio.hadoop.FileSystemAclIntegrationTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.884 sec
Running alluxio.hadoop.FileSystemBlockLocationIntegrationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.315 sec
Running alluxio.hadoop.FileSystemRenameIntegrationTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 15.567 sec
Running alluxio.hadoop.FileSystemStatisticsTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.534 sec
Running alluxio.hadoop.fs.DFSIOIntegrationTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 29.135 sec
Running alluxio.hadoop.HdfsFileInputStreamIntegrationTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.507 sec
Running alluxio.master.lineage.LineageMasterIntegrationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 91.719 sec
Running alluxio.master.MasterFaultToleranceIntegrationTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 119.544 sec
Running alluxio.master.PinIntegrationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 32.299 sec
Running alluxio.master.ServiceSocketBindIntegrationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 60.123 sec
Running alluxio.network.protocol.RPCMessageIntegrationTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.177 sec
Running alluxio.security.BlockWorkerClientAuthenticationIntegrationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 55.918 sec
Running alluxio.security.ClusterInitializationTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 73.364 sec
Running alluxio.security.MasterClientAuthenticationIntegrationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 61.575 sec
Running alluxio.shell.AlluxioShellUtilsTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 88.368 sec
Running alluxio.shell.command.CatCommandTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 60.978 sec
Running alluxio.shell.command.ChgrpCommandTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 31.131 sec
Running alluxio.shell.command.ChmodCommandTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 30.2 sec
Running alluxio.shell.command.ChownCommandTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 30.729 sec
...
```

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
