### PR TITLE
Add additional metrics for client cache

### PR DESCRIPTION
**Pull request by calvinjia**
Adds page eviction rate, cache hit rate, space utilization, and error counts.

### CODE REVIEW

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please.

**Pull request merged**
