### PR TITLE
[ALLUXIO-2429]Fix hadoop client FileStatus 5th argument to modificationTime

### PR DESCRIPTION
**Pull request by TeddyBear1314**
https://alluxio.atlassian.net/browse/ALLUXIO-2429

### CODE REVIEW

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
@TeddyBear1314 Thanks for catching this bug, could you add a unit test for it?

**Comment by TeddyBear1314** [comment]
@calvinjia ok，I'll add the unit test! Thanks for the comment!

**Comment by TeddyBear1314** [comment]
@apc999 Thanks for the comment! I have changed my ut code.

**Comment by apc999** [comment]
LGTM

**Pull request merged**
