### PR TITLE
Fix double checked locking in S3 uploader

### PR DESCRIPTION
**Pull request by xichen01**
### What changes are proposed in this pull request?
fixed double checked locking

### Why are the changes needed?
missing `volatile`

about Double Check
https://codeql.github.com/codeql-query-help/java/java-unsafe-double-checked-locking/

### Does this PR introduce any user facing changes?
NO

### CODE REVIEW

**Review by HelloHorizon — APPROVED** [review]
Good catch and LGTM.

**Comment by HelloHorizon** [comment]
@apc999 I guess you also want to take a look if we want to add volatile to ensure the order.

**Review by maobaolong — COMMENTED** [review]
Is volatile expensive? AFAIK, sCleanerCleanMethod is called in high frequency

**Comment by xichen01** [comment]
It's not ThreadSafe without volatile, In extreme cases, the singleton pattern may return a null object.

**Review by maobaolong — APPROVED** [review]
LGTM

**Comment by jiacheliu3** [comment]
@HelloHorizon   @beinan Actually static init is almost always better than double-checked lazy init. Do you think we can init these fields at init time?

**Review by elega — APPROVED** [review]

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
