### PR TITLE
Add UseContainerSupport flag to default value.yaml of k8s helm chart

### LINKED ISSUE #17021: Wrong cpu core num returned from k8s env
In kubernetes env, deploy a pod with cpu core limit, lets say limit 30.

```
public class A {
  public static void main(String[] args) {
    System.out.println("Max core : " + Runtime.getRuntime().availableProcessors());
  }
}
```

```
# cat /proc/cpuinfo | grep processor | wc -l
30
# java A
Max core : 192
```

--------------

The above test is from Tencent (TKE) kubernetes, the  `192` is the node cpu processor number, but `cpuinfo` return the right value of pod cpu limit `30`

```
java -version
openjdk version "1.8.0_272"
```

@ssz1997 did the same test in aws kubernetes, return the opposite result.

### PR DESCRIPTION
**Pull request by maobaolong**
Fix #17021

### CODE REVIEW

**Comment by maobaolong** [comment]
@ssz1997 Thanks for the offline discussion about the related issue, this PR add the necessary jvm flag `UseContainerSupport` to the values.yaml of kubernetes helm chart. Would you like to take a look at this PR？Thanks.

**Comment by ssz1997** [comment]
@maobaolong How about we make the global one enabeld by default, so there's no need to add it to each individual component?

**Comment by maobaolong** [comment]
image
@ssz1997 Thanks for your advice, PTAL.

**Comment by ssz1997** [comment]
@maobaolong I modified your PR to use the existing global jvmOptions. Do you think this is better?

**Comment by maobaolong** [comment]
@ssz1997 It is better, thanks for your help.

**Review by ssz1997 — APPROVED** [review]

**Comment by ssz1997** [comment]
@maobaolong Could you help merge? I think you have the permission to do `alluxio-bot, merge this please`.

**Pull request merged**
