### PR TITLE
 [SMALLFIX] Update JOSS version number

### PR DESCRIPTION
**Pull request by gilv**
JOSS version is updated to 0.9.10

### CODE REVIEW

**Comment by apc999** [comment]
@gilv thanks for the PR, could you state the reason why we want to upgrade the dependency version? Typically, if there is no bug or serious performance issues, it is probably rare to change the dependency.

**Comment by gilv** [comment]
@apc999 There is no particular reason. Various bugs were  fixed in this version and i thought it would be good to have an updated version here. Not sure i understand why it's so rare to upgrade version of dependency, but we can keep the old one, if you prefer

**Comment by gpang** [comment]
I'm not sure but I think @rayzhang123 had some issues with jboss bugs? Maybe the newer versions will help.

**Comment by rlzhang** [comment]
Looks like the JOSS 0.9.10 don't have the fix I am looking for. I met the same problem which posted here: https://github.com/javaswift/joss/issues/77

**Comment by gilv** [comment]
@apc999 @rlzhang Is this listing issue is something you saw in Alluxio? Because according to the bug, it's not the way i perform listing in Alluxio. I also use JOSS in other projects and never saw issues with listing directories.

**Comment by gilv** [comment]
@apc999 @rlzhang But it's good to upgrade JOSS in any case.

**Comment by calvinjia** [comment]
Seems like the changes between 0.9.8 and 0.9.10 are mainly JOSS internal without dependency updates, so it should be safe to upgrade. However it seems like they are no longer publishing release notes (http://joss.javaswift.org/release-notes.html)?

LGTM

**Comment by gilv** [comment]
@calvinjia All is JOSS internal. There are various pending bug fixes to JOSS, some merged and JOSS 0.9.10 was born. I just feel, in case of JOSS, it's better to have most updated code.

**Comment by apc999** [comment]
LGTM

**Pull request merged**
