### PR TITLE
[DOCFIX] Add newline to StressBench.md

### PR DESCRIPTION
**Pull request by dbw9580**
Add newline to stress bench doc

### CODE REVIEW

**Review by yyongycy — APPROVED** [review]
LGTM

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by ssz1997** [comment]
@Xenorith Please help cherry pick this to branch-2.8, thanks

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Pull request merged**
