### PR TITLE
Remove legacy mesos scheduler

### PR DESCRIPTION
**Pull request by madanadit**

### CODE REVIEW

**Comment by madanadit** [comment]
@Xenorith fyi removing `-Pmesos`

**Comment by Xenorith** [comment]
thanks for the heads up. what would happen after this PR merges and `-Pmesos` is still set? do you know if the command will fail or will the flag be ignored?

**Comment by bradyoo** [comment]
LGTM

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Comment by Xenorith** [comment]
@madanadit not sure if this is related, but there's a `runMesosTest` option in `bin/alluxio` and associated docs in User-CLI.md

**Comment by madanadit** [comment]
@Xenorith that is related, i need to remove that as well

**Pull request merged**
