### PR TITLE
[SMALLFIX] fix NPE in worker servlet

### PR DESCRIPTION
**Pull request by siyangy**
listFiles call could return null when the dir doesn't exist.

### CODE REVIEW

**Comment by siyangy** [comment]
Jenkins, test this please

**Comment by yupeng9** [comment]
Thanks for the fix! Could you add a unit test for it?

**Comment by siyangy** [comment]
Is there an existing unit test for this servlet?

**Comment by yupeng9** [comment]
It'll be great if you can carry over the test from this PR: https://github.com/amplab/tachyon/pull/1779

**Comment by siyangy** [comment]
If there's not any web related test, I'd rather do that separately, fixing that PR itself is a non-trivial task, and that's only the first step to be able to write test for each servlet.

**Comment by yupeng9** [comment]
Cool. That makes sense to me. Thanks.

**Comment by yupeng9** [comment]
LGTM

**Comment by yupeng9** [comment]
@calvinjia can you also take a look?

**Comment by yupeng9** [comment]
Jenkins, test this please

**Pull request merged**
