### PR TITLE
Support Job master audit log

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes are proposed in this pull request?

Support job master print the user access audit log to a log file just like file system master audit log

### Why are the changes needed?

We want to record each job submitter and access user information.

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Comment by maobaolong** [comment]
@yuzhu Please take a look at this feature, believe this can helps forks! 😄

**Comment by LuQQiu** [comment]
@yuzhu PTAL, thanks

**Comment by yuzhu** [comment]
@maobaolong Please take a look at the conflict.  the rest looks good. Thanks for this PR!

**Comment by maobaolong** [comment]
@yuzhu Thanks for your review, resolved the conflict.

**Review by yuzhu — APPROVED** [review]

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
