### PR TITLE
[#8483] Change default journal type to EMBEDDED

### PR DESCRIPTION
**Pull request by LuQQiu**
#8483

### CODE REVIEW

**Comment by LuQQiu** [comment]
@calvinjia Now I did not change the configuration of tests (do not change tests from using UFS journal to Embedded Journal) because it is a bigger change and may make our PR build much slower. Do you think we should change as many tests as possible to use embedded journal?

**Comment by LuQQiu** [comment]
jenkins, test this please

**Comment by LuQQiu** [comment]
@aaudiber PTAL, I haven't change the tests to use embedded journal now, do we need to change some of the tests to test embedded journal in later PRs? Thanks

**Comment by calvinjia** [comment]
@LuQQiu Ideally we could switch between using UFSJournal and EmbeddedJournal for integration tests based on a profile/flag

**Comment by LuQQiu** [comment]
@calvinjia Yeah, it will be better to support switching between UFS Journal and Embedded journal. I will create a github issue for this and see if it has high priority.

**Pull request merged**
