### PR TITLE
[SMALLFIX] Add a script to restart master or worker or others

### PR DESCRIPTION
**Pull request by maobaolong**
During my test Alluxio this days, I executed many times `alluxio-stop.sh master`,`alluxio-start.sh master`, so let us have a restart script.

### CODE REVIEW

**Comment by apc999** [comment]
@maobaolong 
function to restart workers is available in `alluxio-start.sh` see

```
 ./alluxio-start.sh 
1
Error: no ACTION specified
Usage: alluxio-start.sh [-hNw] ACTION [MOPT] [-f]
Where ACTION is one of:
  all [MOPT]         	Start all masters, proxies, and workers.
  local [MOPT]       	Start all processes locally.
  master             	Start the master on this node.
  masters            	Start masters on master nodes.
  proxy              	Start the proxy on this node.
  proxies            	Start proxies on master and worker nodes.
  safe               	Script will run continuously and start the master if it's not running.
  worker [MOPT]      	Start a worker on this node.
  workers [MOPT]     	Start workers on worker nodes.
  restart_worker     	Restart a failed worker on this node.
  restart_workers    	Restart any failed workers on worker nodes.
```
you may think to add restart master(s) in here

**Comment by maobaolong** [comment]
@apc999  I see, but the restart workers here can not stop workers first. just start.

**Comment by apc999** [comment]
@maobaolong how about this:

1. add `restart_master` and `restart_masters` to `bin/alluxio-start.sh`
2. add `-f`, when `-f` is specified, we restart servers regardless if the JVM is already running or not.

We are typically open to enhance the current script, but conservative to add new script files into dir `bin/`. In shell, we want to minimize the interface :)

**Comment by maobaolong** [comment]
```
Usage: alluxio-start.sh [-hNw] ACTION [MOPT] [-f]
Where ACTION is one of:
  all [MOPT]         	Start all masters, proxies, and workers.
  local [MOPT]       	Start all processes locally.
  master             	Start the master on this node.
  masters            	Start masters on master nodes.
  proxy              	Start the proxy on this node.
  proxies            	Start proxies on master and worker nodes.
  safe               	Script will run continuously and start the master if it's not running.
  worker [MOPT]      	Start a worker on this node.
  workers [MOPT]     	Start workers on worker nodes.
  restart_worker [-f]    	Restart a failed worker on this node.
  restart_workers [-f]   	Restart any failed workers on worker nodes.
  restart all [-f]                Restart any failed node on its node.
  restart proxy [-f]          Restart a failed proxy on this node
  restart proxies [-f]       Restart any failed proxies on proxy nodes.
  restart local [-f]            Restart all failed processes locally

```

**Comment by aaudiber** [comment]
I agree with @maobaolong that the `restart_*` class of functions are really confusing. In almost any other system `restart` would mean "shut down and then start up", not "start up if not currently running". "start up if not currently running" is usually covered by `start`.

Adding `-f` preserves previous functionality, but continues in a confusing direction. I'd prefer to change the `restart_*` commands to be normal shutdown/startup restart commands. We can decide separately whether it's worth also having `restart_failed_*` commands for restarting failed services. I don't see much value in those commands tbh.

**Comment by yupeng9** [comment]
+1 to "shut down and then start up".

**Comment by maobaolong** [comment]
@apc999 @aaudiber @yupeng9 , we can use a command like `alluxio-daemon.sh <start|stop|restart|startiffailed> <masterworker|proxy|masters|workers|proxies>`,  to combine those command, indeed, it will change the user interface. what direction shall we choose?

**Comment by apc999** [comment]
@maobaolong I am cool with your proposal of introducing `alluxio-daemon.sh`. I think this is a cleaner approach and eventually we could have less script files in `bin/`. If @aaudiber and @yupeng9 don't want to have it, I am good with @aaudiber 's suggestion too.

**Comment by maobaolong** [comment]
@apc999 Thank you for your apply. So Shall I add a new script `alluxio-daemon.sh` in the `bin` folder, and implements the logic? Or simply to change the old restart command logic?

**Comment by aaudiber** [comment]
what do you think of moving `start/stop/restart` to the `bin/alluxio` command?

**Comment by apc999** [comment]
@aaudiber  
I am cool with moving `start/stop/restart` to the `bin/alluxio` command. I think it is kinda neat from users' perspective that `bin/alluxio` becomes the single point of entry point for a lot of functions.  My only concern is it will make `bin/alluxio` script harder to maintain as it is already providing quite a few functions (from users e.g. `fs` to developers e.g. `thriftGen`, `protoGen`).

Alternatively, how about having a `bin/alluxio-admin` script to host admin-related functions? E.g. have `start|stop|restart`, as well as `format`, `copyDir` and etc. And we could also have `bin/alluxio-dev` to provide developer oriented functions (optional)

**Comment by apc999** [comment]
sorry for clicking the close button by mistake -_-|||

**Comment by yupeng9** [comment]
@apc999  I feel `alluxio-daemon.sh` is more descriptive and consistent with other projects (e.g. hadoop-daemon and spark-daemon). So it's easier for users to understand and adopt.

**Comment by aaudiber** [comment]
In hadoop you use `hadoop-daemon.sh` to manually start individual processes on individual nodes, then they have a `start-dfs.sh` and `start-yarn.sh` for bringing up an entire cluster. If we have `alluxio-daemon.sh` it should be similar, where it only brings up a single instance of either master or worker.

I think eventually we should clean up `bin/alluxio` by moving developer tools elsewhere (maybe `dev/`), leaving space for `start|stop|restart`. `bin/alluxio-admin` would also work for me.

**Comment by yupeng9** [comment]
I think it's better organization of the commands if we can use args but not different scripts to specify single instance or entire cluster. 

Thinking it twice, I suggest we use `bin/alluxio` as the only script, and use the second option to as the category of the commands.

Such as
```
alluxio fs ...
alluxio admin [start/stop/restart]
alluxio dev [thriftGen/protoGen/...]
``` 
Thus, we can also manage the scripts better by grouping the commands per category in its own script file, and sourcing it the main `bin/alluxio` script.

**Comment by apc999** [comment]
@maobaolong is the proposal above good for you? if yes, do you want to take it or create a JIRA waiting other folks taking this task?

**Comment by maobaolong** [comment]
@yupeng9 This is really a better way to keep  only 1 entry for user, user can get help messages and sub command list from help flag.

@apc999 Thank you for remind me.  i will create a new JIRA and close this PR,  anyone can take it.

**Comment by maobaolong** [comment]
This is a jira i just create `https://alluxio.atlassian.net/browse/ALLUXIO-2986`

**Pull request closed without merging**
