### PR TITLE
Enable tiered category hierarchy/dropdowns for docs

### PR DESCRIPTION
**Pull request by Zijian-Zhu**
I create a directory named `overview-example-level-1-dir` under `docs/en` to make an example of this tiered docs.

The following screenshot is the example of the actually docs and directory under `docs/en/overview-example-level-1-dir`
image
As you can see `overview.md` and `Getting-Started.md` are level 1 docs. `Architecture.md` and `FAQ.md` are level 2 docs.
`JobService.md` is level 3 docs and `Use-Cases.md` is level 4 docs.

The following screenshot is example of content in the new Yaml file.
image
All the sub-directories need to be listed in the `subitems` with their `title` which does not need to be the same as their directory name and their `buttonTitle` which is the `title` without white space since white space will bug in the HTML.
All the docs located in each directory need to be listed in the `subfiles` with docs `title` and `url` which is the path of the doc after jekyll bulid (this path always the same of the path of the files except the file type is `.html` not `.md`

The following screenshot is the output of the example.
WX20230525-175144@2x
This is the full expansion of the example list. The blue string is the URL of the corresponding docs. And the button is collapse type and use the `buttonTitle` as name

### CODE REVIEW

**Comment by LuQQiu** [comment]
@Zijian-Zhu Thanks for the docs structure!
The levels looks good!

Some small suggestion about the format style:
Ideally directory and docs on the same level have the same visual effect, or slightly different visual effect
for example, `level-2-dir` matches the `Overview` and `getting started` style, or could have a different color indicating it's a folder instead of a doc.

**Comment by Zijian-Zhu** [comment]
The updated style of the list will look like following:
image

**Review by Xenorith — COMMENTED** [review]
with the example files in the PR, i would mark as `[WIP]` in PR title and/or create a draft PR, so we know it is not intended to be merged

**Review by LuQQiu — COMMENTED** [review]
The new docs structure is awesome! Thanks for adding it!
We can do the merge to main branch after english docs are relatively stable so that less work to modify the _config.yml (hopefully most of the docs are removed)

**Review by Xenorith — APPROVED** [review]

**Comment by Xenorith** [comment]
need to fix the doc check. it used to ensure the categories on each page is an existing category listed in the config yml, but now that mechanism is removed, so we could also remove the check.

in a future PR, we should add back a similar check to ensure that config yml file list and the list of all doc md files are exactly the same.

**Pull request closed without merging**
