### PR TITLE
Improve collectInfo command help message

### PR DESCRIPTION
**Pull request by jiacheliu3**

### CODE REVIEW

**Comment by jiacheliu3** [comment]
@bf8086 Do you mind merging this? Thanks!

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by jiacheliu3** [comment]
@bf8086 Do you mind merging this and cherry-pick to 2.3 please? Thanks!

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Comment by gpang** [comment]
alluxio-bot, cherry-pick this to branch-2.3 please

**Comment by jiacheliu3** [comment]
alluxio-bot, cherry-pick this to branch-2.3 please

**Pull request merged**
