### PR TITLE
Avoid logging log info from ratis

### PR DESCRIPTION
**Pull request by HelloHorizon**
There are a large number of logs from Ratis with info level. Change the log level to WARN to avoid it.

### CODE REVIEW

**Review by bf8086 — APPROVED** [review]
LGTM.

**Review by gpang — APPROVED** [review]
LGTM

**Comment by bf8086** [comment]
alluxio-bot, merge this please.

**Comment by bf8086** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please.

**Pull request merged**
