### PR TITLE
Implement fuse statfs unit test

### PR DESCRIPTION
**Pull request by LuQQiu**
Implement the unit test for fuse statfs method

### CODE REVIEW

**Comment by LuQQiu** [comment]
@liuhongtong @apc999 PTAL, thanks!

**Comment by liuhongtong** [comment]
@LuQQiu LGTM

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Pull request merged**
