### PR TITLE
Remove redundant blank in PropertyKey

### PR DESCRIPTION
**Pull request by waterlx**
A format change, no logic involved.

### CODE REVIEW

**Comment by maobaolong** [comment]
@waterlx LGTM, please sign the contribution license agreement

**Comment by maobaolong** [comment]
@waterlx Thank for your contribution, @apc999 Could you please take a look?

**Review by maobaolong — APPROVED** [review]

**Comment by waterlx** [comment]
Thank you @maobaolong and @apc999 for taking care of this change.

**Review by gpang — APPROVED** [review]
LGTM

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
