### PR TITLE
Mark job as failure if there's failed files

### PR DESCRIPTION
**Pull request by jja725**
### What changes are proposed in this pull request?

Mark job as failure if there's failed files instead of mark job as succeeded

### Why are the changes needed?
Resolve confusion progress report

### Does this PR introduce any user facing changes?

na

### CODE REVIEW

**Review by ssyssy — COMMENTED** [review]
lgtm

**Review by ssyssy — APPROVED** [review]

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Pull request merged**
