### PR TITLE
Fix ufs journal dumper input directory

### PR DESCRIPTION
**Pull request by LuQQiu**
The journal dumper is broken when running against non-local UFS journal like HDFS.
The inputDir was new File(HDFSUri).getAbsolutePath() which is invalid.

### CODE REVIEW

**Comment by LuQQiu** [comment]
@bf8086 PTAL the fix for ufs journal dumper, thanks

**Review by bf8086 — COMMENTED** [review]
Thanks for the improvement! Overall looks good to me. Do you mind adding a unit test for journal location with authorities?

**Review by bf8086 — APPROVED** [review]
LGTM.

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
