### PR TITLE
Fix NPE in TaskExecutorManager.notifyTaskFailure

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
alluxio.concurrent.CountingLatchTest.unblockMultipleInc(alluxio.concurrent.CountingLatchTest)
  Run 1: CountingLatchTest.unblockMultipleInc:139
  Run 2: CountingLatchTest.unblockMultipleInc:139


jenkins, test this please.

**Comment by bradyoo** [comment]
jenkins, test this please.

**Comment by bradyoo** [comment]
alluxio.server.ft.journal.MultiMasterJournalTest.testTtl(alluxio.server.ft.journal.MultiMasterJournalTest)

**Comment by bradyoo** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please

**Pull request merged**
