### PR TITLE
Use Concurrent Mark Sweep garbage collector for master by default

### PR DESCRIPTION
**Pull request by bf8086**
Cherry-picked `38cc5b5` to `branch-1.8`.

Use Concurrent Mark Sweep garbage collector for master by default  …
It is crucial to minimize full garbage collection pause in Alluxio
master which could cause various issues including master fail over. This
change switch to use Concurrent Mark Sweep garbage collector by default
so it is less likely to enter a long full GC pause on master.

pr-link: #9706
change-id: cid-0365adf8eb3705c6548502154367de2dc1ad0cf7

### CODE REVIEW

**Comment by wyykwan** [comment]
jenkins, test this please

**Comment by gpang** [comment]
alluxio-bot, check this please

**Comment by gpang** [comment]
alluxio-bot, check this please

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Pull request merged**
