### PR TITLE
[ALLUXIO-2275]replaced 'channel' with 'channels' at '//be newly created channel' in NettyChannelPool.java

### PR DESCRIPTION
**Pull request by guolingbing**
https://alluxio.atlassian.net/browse/ALLUXIO-2275
replaced 'channel with 'channels' at '//be newly created channel' in NettyChannelPool.java

### CODE REVIEW

**Comment by guolingbing** [comment]
@alluxio-bot alluxio-bot, check this please

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by aaudiber** [comment]
@guolingbing Once you sign the CLA and we'll be good to merge

**Comment by aaudiber** [comment]
@guolingbing Thanks for the improvement!

**Pull request merged**
