### PR TITLE
[ALLUXIO-1797]browse-body.jsp extra code removed

### PR DESCRIPTION
**Pull request by sakurasnows**
[ALLUXIO-1797] browse-body.jsp extra code removed

### CODE REVIEW

**Comment by maobaolong** [comment]
@sakurasnows Thank you for your contribution. You can replace your  PR title  to `[ALLUXIO-1797]browse-body.jsp extra code removed`

**Comment by gpang** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
@sakurasnows can you run the commands recommended by alluxio-bot?

**Comment by aaudiber** [comment]
@sakurasnows Closing due to inactivity, feel free to re-open if you have time to address the comments

**Pull request closed without merging**
