### PR TITLE
[SMALLFIX] Deflake FileSystemAclIntegrationTest

### PR DESCRIPTION
**Pull request by ifcharming**
User `CreateOptions ` and `MkdirsOptions` to make the UFS operation atomic. Otherwise, the metadata might be loaded (with default `rwxr-xr-x`) before it's chmod'ed.

### CODE REVIEW

**Comment by ifcharming** [comment]
@jsimsa @madanadit

**Comment by jsimsa** [comment]
thanks, can we put this into branch-1.4?

**Comment by ifcharming** [comment]
@jsimsa  this is a change only affecting tests, do we want to include in 1.4 ?

**Comment by ifcharming** [comment]
see #4503

**Pull request closed without merging**
