### PR TITLE
[DOCFIX] Rename gRPC -ThreadActivelyCount to -ThreadActiveCount

### PR DESCRIPTION
**Pull request by ZhuTopher**
See file diffs

### CODE REVIEW

**Comment by LuQQiu** [comment]
@ZhuTopher we use auto command bin/alluxio docGen to update the configuration and metrics in the Alluxio docs. This PR may be conflicted with https://github.com/Alluxio/alluxio/pull/14392

**Comment by LuQQiu** [comment]
@ZhuTopher can you help remove the metrics key updates but maintain the changes in docs/en/reference/Metrics-List.md

**Comment by LuQQiu** [comment]
@xichen01  @maobaolong we updated some metric key name here to be more syntax correct, since the metric keys are added recently. If you have any monitoring system already depends on it, please see if it's easy to modify the names

**Review by LuQQiu — APPROVED** [review]
LGTM, up to you whether we want to modify the metric name as well

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
@Xenorith cherry-pick?

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
