### PR TITLE
[SMALLFIX] Java 8 migration: replace anonymous type with lambda in alluxio.web.UIFileInfo#PATH_STRING_COMPARE

### PR DESCRIPTION
**Pull request by MoxinC**

### CODE REVIEW

**Comment by MoxinC** [comment]
Jenkins, test this please

**Comment by MoxinC** [comment]
Jenkins, test this please

**Comment by MoxinC** [comment]
Jenkins, test this please

**Comment by MoxinC** [comment]
Jenkins, test this please

**Comment by MoxinC** [comment]
Jenkins, test this please

**Comment by MoxinC** [comment]
Jenkins, test this please

**Comment by MoxinC** [comment]
Jenkins, test this please

**Comment by MoxinC** [comment]
MoxinC wants to merge into Alluxio:master from MoxinC:smallfix

**Comment by MoxinC** [comment]
MoxinC wants to merge into Alluxio:master from MoxinC:smallfix

**Comment by MoxinC** [comment]
@apc999

**Comment by newnius** [comment]
@apc999 PTAL, thanks

**Comment by newnius** [comment]
LGTM

**Pull request merged**
