### PR TITLE
Fix log file with 0 byte offset from end

### LINKED ISSUE #9482: Displaying file with 0 byte offset from the end in the UI creates a blank page
**Alluxio Version:**
2.0.0

**Describe the bug**
Displaying file with 0 byte offset from the end in the UI creates a blank page. This seems to only happen with the logs page (possibly only if the UFS is local).

**To Reproduce**
Open a log file. 
Check the display relative from to end from start. 
Press Go

**Expected behavior**
A page with an empty data box but still has the other controls.

### PR DESCRIPTION
**Pull request by tieujason330**
- Fixes #9482 
- shouldn't use truthy/falsy values for this check - `data.fileData = ''` is still valid for a real file

### CODE REVIEW

**Comment by tieujason330** [comment]
@calvinjia PTAL, thanks

**Comment by calvinjia** [comment]
jenkins, test this please.

**Comment by calvinjia** [comment]
@tieujason330 In the commit message, please use `Fixes #...` as opposed to `change for`. This will automatically close the issue after the PR is merged.

**Comment by tieujason330** [comment]
@calvinjia - good to know about the commit message, updated it. I agree with reusing the logic, didn't want to do it as part of the fix

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Pull request merged**
