### PR TITLE
[ALLUXIO-1792] Improve javadoc in IndexedSet#removeFromIndices

### PR DESCRIPTION
**Pull request by peisun1986**
https://alluxio.atlassian.net/browse/ALLUXIO-1792

We are missing a newline before the @param section of IndexedSet#removeFromIndices

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
LGTM

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by uronce-cc** [comment]
LGTM

**Comment by yupeng9** [comment]
LGTM. @peisun1986 could you sign the licensing agreement?

**Comment by gpang** [comment]
Jenkins, test this please

**Pull request merged**
