### PR TITLE
Fix packaging distributed load code into DistributedLoadUtils

### LINKED ISSUE #13287: Packaging distributed load code into DistributedLoadUtils
**Describe the solution you'd like**
Packaging distributed load code into DistributedLoadUtils, so that both distributed load on filesystem and table are able to use the same code.

### PR DESCRIPTION
**Pull request by JySongWithZhangCe**
Fix #13287

### CODE REVIEW

**Comment by JySongWithZhangCe** [comment]
alluxio-bot, test this please

**Comment by JySongWithZhangCe** [comment]
alluxio-bot, test this please

**Comment by bradyoo** [comment]
I'll rerun the tests but the test here doesn't look like a flake (though I don't understand why it's happening yet)

**Comment by JySongWithZhangCe** [comment]
alluxio-bot, test this please

**Comment by JySongWithZhangCe** [comment]
@jiacheliu3 Could you give me some suggestions? Thx:)

**Comment by bradyoo** [comment]
LGTM

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Pull request merged**
