### PR TITLE
Update alluxio-start.sh for fix the hub manager command name

### PR DESCRIPTION
**Pull request by maobaolong**
Minor fix

### CODE REVIEW

**Review by tieujason330 — APPROVED** [review]
thanks for fixing this!

**Comment by tieujason330** [comment]
alluxio-bot, merge this please

**Comment by tieujason330** [comment]
@Xenorith can you cherry-pick this to `branch-2.7`?

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
