### PR TITLE
[MERGE] Update master branch with new project name Alluxio

### PR DESCRIPTION
**Pull request by apc999**
Project Tachyon is renamed to Alluxio. See more details in:
http://www.alluxio.com/2016/02/alluxio-formerly-tachyon-is-entering-a-new-era-with-1-0-release/

This PR aims to implement this change, along with many small fixes/documentation improvement.

### CODE REVIEW

**Comment by haoyuan** [comment]
LGTM +1

**Comment by jsimsa** [comment]
LGTM 250+

**Comment by ifcharming** [comment]
LGTM ++

**Comment by calvinjia** [comment]
LGTM

**Comment by ameliawong** [comment]
LGTM! =D

**Comment by aaudiber** [comment]
LGTM

**Comment by yupeng9** [comment]
LGTM!

**Pull request merged**
