### PR TITLE
[SMALLFIX] Adding missing newline

### PR DESCRIPTION
**Pull request by jsimsa**
Fixes an issue introduce by https://github.com/Alluxio/alluxio/pull/4824/files

### CODE REVIEW

**Comment by aaudiber** [comment]
@jsimsa what changed and how did you find it?

**Comment by jsimsa** [comment]
The file seems to be missing a newline which does not seem to be noticed by github, but it makes our internal tooling complain.

**Comment by jsimsa** [comment]
Jenkins, test this please

**Comment by jsimsa** [comment]
Jenkins, test this please

**Comment by jsimsa** [comment]
Jenkins, test this please

**Pull request merged**
