### PR TITLE
[SMALLFIX]minor modify, modify the wrong punctuation only

### PR DESCRIPTION
**Pull request by maobaolong**

### CODE REVIEW

**Comment by apc999** [comment]
@maobaolong  could you elaborate on the difference? not very easy to tell from the diff in github

**Comment by maobaolong** [comment]
chinese '，'  covert to english ',' .
sorry it is difficult to diff.

**Comment by maobaolong** [comment]
@apc999, previous version use chinese '，', now convert it to english ',' .
sorry it is difficult to diff.

**Comment by apc999** [comment]
I see. Thanks for the clarification! LGTM

**Comment by maobaolong** [comment]
@apc999 , this part on alluxio webpage didn't update yet.
http://www.alluxio.org/docs/master/en/Debugging-Guide.html

**Pull request merged**
