### PR TITLE
[ALLUXIO-2264] Mark enum PropertyKeyFormat with annotation @ThreadSafe

### PR DESCRIPTION
**Pull request by qldeng**
https://alluxio.atlassian.net/browse/ALLUXIO-2264

### CODE REVIEW

**Comment by qldeng** [comment]
alluxio-bot, check this please.

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by apc999** [comment]
LGTM

**Pull request merged**
