### PR TITLE
[ALLUXIO-2319] Improve lockFullInodePath() in InodeTree.java

### PR DESCRIPTION
**Pull request by jackyangNJ**
https://alluxio.atlassian.net/browse/ALLUXIO-2319

### CODE REVIEW

**Comment by jackyangNJ** [comment]
Additional descriptions of this PR:

In InodeTree.java, for method:

> lockFullInodePath(AlluxioURI` path, LockMode lockMode)

The javadoc for param "path" should link to AlluxioURI.
It should be:
> @param path the {@link AlluxioURI} path to lock

**Comment by jackyangNJ** [comment]
alluxio-bot, check this please

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by jsimsa** [comment]
LGTM

**Pull request merged**
