### PR TITLE
Extract util methods to create GrpcServer for test use

### PR DESCRIPTION
**Pull request by YangchenYe323**
### What changes are proposed in this pull request?
Extracted util methods to create `GrpcServer` for test use

### Why are the changes needed?
Reduce duplicated code and make it easy to implement unit-tests that rely on a `GrpcServer`

### Does this PR introduce any user facing changes?
No

### CODE REVIEW

**Comment by YangchenYe323** [comment]
@dbw9580 Do you mind taking a look at this? Thanks!

**Comment by YangchenYe323** [comment]
@dbw9580 Do you mind taking a look at this? Thanks!

**Review by dbw9580 — APPROVED** [review]

**Comment by YangchenYe323** [comment]
@jiacheliu3 Could we merge the please? Thanks!

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
