### PR TITLE
Add more logging messages to stress master bench

### PR DESCRIPTION
**Pull request by dbw9580**
1. log exceptions and stack trace other than only the error message.
2. add more logs to to provide feedback on where the benchmark is spending its time.

### CODE REVIEW

**Comment by dbw9580** [comment]
> log exceptions and stack trace other than only the error message.

this one is particularly tricky, as when `listStatus` throws a `FileNotFoundException` the error message only contains the file path, but says nothing about that the file does not exist.

https://github.com/Alluxio/alluxio/blob/87fee903186f3f9cf98014c7ed4a88a9f0b30ae3/stress/shell/src/main/java/alluxio/stress/cli/StressMasterBench.java#L540

https://github.com/Alluxio/alluxio/blob/8f74e6584b6d2d71be3a3737057808b6f77c44ae/core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java#L590-L593

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks!

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
