### PR TITLE
Remove duplicate word in comments

### PR DESCRIPTION
**Pull request by Haoning-Sun**
Fixing a typo by removing duplicate word in comments.

### CODE REVIEW

**Comment by ChunxuTang** [comment]
Meanwhile, I triggered a re-run of failed tests as I think the errors are not related to your change.

**Comment by Haoning-Sun** [comment]
@ChunxuTang Done.

**Review by ChunxuTang — APPROVED** [review]
Nice. Thanks!

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
