### PR TITLE
[DOCFIX] Add img links to Overview and Getting Started docs with HTML

### PR DESCRIPTION
**Pull request by wyykwan**
Add HTML img links to Overview and Getting Started pages.

Images will look like: 

Screen Shot 2019-08-07 at 1 17 31 PM

### CODE REVIEW

**Comment by apc999** [comment]
Hi @wyykwan  can you put a screen shot on the pages after your change ?

**Comment by wyykwan** [comment]
> Hi @wyykwan can you put a screen shot on the pages after your change ?

Just updated with screenshot!

**Comment by apc999** [comment]
Thanks! LGTM

**Comment by apc999** [comment]
@Xenorith are we good with this change?

**Comment by Xenorith** [comment]
yes, and please cherry-pick to branch-2.0

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Pull request merged**
