### PR TITLE
Remove useless codes

### PR DESCRIPTION
**Pull request by bzheng888**
Remove useless codes

### What changes are proposed in this pull request?
Remove codes we don't need anymore

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

### CODE REVIEW

**Review by LuQQiu — COMMENTED** [review]
Overall LGTM, any bin/alluxio docs or alluxio docs need to be changed as well?

**Review by maobaolong — COMMENTED** [review]
Thanks for clear the code. Please remove the mesos related from documents.

- ./docs/_data/table/cn/cluster-management-configuration.yml
- ./docs/_data/table/en/cluster-management-configuration.yml
- ./docs/cn/operation/Troubleshooting.md
- ./docs/en/operation/Troubleshooting.md
- ...

**Comment by bzheng888** [comment]
@LuQQiu @maobaolong Update this pr, PTAL, thx!

**Comment by maobaolong** [comment]
@bzheng888 Thanks for the addition improvement, would you like to resolve the conflicts? Otherwise, lt looks  good. @LuQQiu Would you like to take another look?

**Comment by bzheng888** [comment]
@maobaolong @LuQQiu Done!

**Review by maobaolong — APPROVED** [review]
LGTM

**Comment by maobaolong** [comment]
@LuQQiu Would you like to take another look?

**Review by LuQQiu — APPROVED** [review]
LGTM

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
