### PR TITLE
Change member variable in mBlockMeta to private

### PR DESCRIPTION
**Pull request by yyongycy**
The variables are not accessed in other classes so they should be private

### CODE REVIEW

**Comment by maobaolong** [comment]
Hi @yyongycy What is your motivation for this changes?

**Comment by yyongycy** [comment]
The usage was planned, but not actually used. Now rongrong is expecting this change.

**Review by rongrong — APPROVED** [review]

**Comment by rongrong** [comment]
The PR and commit title can have a bit more detail. Something like "Change member variable in XXX to private", with commit summary something like "The variables are not accessed in other classes so they should be private".

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Pull request merged**
