### PR TITLE
[DOCFIX] Tweak FUSE metric and property descriptions

### PR DESCRIPTION
**Pull request by dbw9580**
Minor tweaks to metric descriptions to the metric `FUSE_CACHED_PATH_COUNT`.

### CODE REVIEW

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
@Xenorith cherry-pick?

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
