### PR TITLE
[SMALLFIX]Convert HashMap to ConcurrentHashMap.

### PR DESCRIPTION
**Pull request by maobaolong**
convert HashMap to ConcurrentHashMap.

### CODE REVIEW

**Comment by maobaolong** [comment]
Is it the right? If not, why?

**Comment by apc999** [comment]
hi @maobaolong , simply changing HashMap to ConcurrentHashMap here will not help for the following reason: `try (LockResource r = new LockResource(sLock))` is used to guard the hashmap, so although you are using concurrent data structure, all accesses are still serialized by the lock

**Comment by maobaolong** [comment]
Thank you for your teaching. 
BTW. In class `ContainerAllocatorTest` , Is it use HashMap be a better way?
Because, there are not used in multi-thread.
```java
private void checkMaxHostsLimitNotExceeded(List<Container> containers, int maxContainersPerHost) {
    ConcurrentHashMap<String, Integer> counts = new ConcurrentHashMap<>();
    for (Container container : containers) {
      String host = container.getNodeId().getHost();
      counts.putIfAbsent(host, 0);
      int newCount = counts.get(host) + 1;
      assertTrue(newCount <= maxContainersPerHost);
      counts.put(host, newCount);
    }
  }
```

**Comment by aaudiber** [comment]
@maobaolong `ConcurrentHashMap` supports the putIfAbsent method in all versions of java, while regular `HashMap` doesn't support it until java 8. The only reason it's being used here is for convenience, not concurrency or performance.

**Pull request closed without merging**
