### PR TITLE
Support STS for OSS UFS and refactor Low Level Output Stream

### PR DESCRIPTION
**Pull request by JiamingMai**
This is a PR to cherry-pick committed PR https://github.com/Alluxio/alluxio/pull/16481 and https://github.com/Alluxio/alluxio/pull/16122 into target branch dora.

### CODE REVIEW

**Review by jja725 — APPROVED** [review]
Still have compile issue

**Review by LuQQiu — APPROVED** [review]
LGTM, please double check the test failure

**Comment by JiamingMai** [comment]
alluxio-bot, merge this please

**Comment by JiamingMai** [comment]
alluxio-bot, merge this please

**Pull request merged**
