### PR TITLE
Remove some unused code in AlluxioMasterRestServiceHandler

### PR DESCRIPTION
**Pull request by jianghuazhu**
### What changes are proposed in this pull request?
The purpose of the pr is removed in AlluxioMasterRestServiceHandler some unused code.

### Why are the changes needed?
In some of AlluxioMasterRestServiceHandler unused code, should remove them.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
1.   change in user-facing APIs
2.   addition or removal of property keys
3.   webui

### CODE REVIEW

**Comment by jianghuazhu** [comment]
@jenoudet  @dbw9580, could you please help review this pr?
Thanks.

**Review by jenoudet — APPROVED** [review]

**Comment by jianghuazhu** [comment]
Thanks @jenoudet .

**Review by maobaolong — APPROVED** [review]
LGTM

**Review by dbw9580 — APPROVED** [review]

**Comment by jianghuazhu** [comment]
Could you please join this pr into the master branch, @dbw9580 .
Thanks.

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Pull request merged**
