### PR TITLE
[ALLUXIO-3301] change watermark.high.ratio default value to 0.95

### PR DESCRIPTION
**Pull request by ChangerYoung**
(https://alluxio.atlassian.net/browse/ALLUXIO-3001)

### CODE REVIEW

**Comment by maobaolong** [comment]
@ChangerYoung  You can add `(https://alluxio.atlassian.net/browse/ALLUXIO-3001)` to the description.

**Comment by yupeng9** [comment]
@ChangerYoung Can you sign the CLA? Also, there is a tradeoff of the threshold value that the lower it is the less memory space can be utilized. So I suggest increasing it a bit higher to 0.95 or 0.97

**Comment by ChangerYoung** [comment]
@yupeng9  I have signed the CLA ,and change the default value of watermark.high.ratio to 0.95

**Comment by maobaolong** [comment]
@ChangerYoung Thank you for your contribution, LGTM.

**Comment by maobaolong** [comment]
@yupeng can you merge this PR to the branch-1.5 ?

**Comment by aaudiber** [comment]
@maobaolong To get this into branch-1.5, please re-open the PR targeting branch-1.5 instead. branch-1.5 is regularly merged into master

**Comment by ChangerYoung** [comment]
@aaudiber  @yupeng9 I have a new pull request to branch-1.5 ,
https://github.com/Alluxio/alluxio/pull/5939
PTAL

**Pull request closed without merging**
