### PR TITLE
[SMALLFIX] Replace anonymous type with lambda

### PR DESCRIPTION
**Pull request by amaliujia**
Description: Replace anonymous type with lambda in AlluxioWorkerRestServiceHandler

Fixes Alluxio/new-contributor-tasks#239

New contributor task: https://github.com/Alluxio/new-contributor-tasks/issues/239

### CODE REVIEW

**Comment by amaliujia** [comment]
Newbie here: how to check checkstyle locally?

**Comment by amaliujia** [comment]
Another newbie question: how to retrigger the PR title check?

**Comment by Xenorith** [comment]
the project uses the maven-checkstyle-plugin, so you can run `mvn checkstyle:checkstyle` to run checkstyle locally. the error i'm seeing is `AlluxioWorkerRestServiceHandler.java:43:8: error: Unused import - alluxio.wire.LogInfo`

for PR check errors, at the bottom of the comment from the bot you'll see:
`Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.`
typing in that exact phrase as a comment will trigger the check

**Comment by amaliujia** [comment]
alluxio-bot, check this please

**Comment by amaliujia** [comment]
alluxio-bot, check this please

**Comment by amaliujia** [comment]
alluxio-bot, check this please

**Comment by amaliujia** [comment]
@gpang 

Can you take a look please?

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
