### PR TITLE
Remove deprecated REST endpoints

### PR DESCRIPTION
**Pull request by jiacheliu3**
This resolves https://github.com/Alluxio/alluxio/issues/11010

Removing REST endpoints marked with deprecated and should have been removed in 2.0.

### CODE REVIEW

**Comment by jiacheliu3** [comment]
Updated corresponding integration test.

**Comment by ZacBlanco** [comment]
I'm not sure if we want to remove these right now. We should have a discussion first.

**Comment by ZacBlanco** [comment]
I did some more digging in the codebase for myself and didn't find any usages of these endpoints. I think they are safe to remove for the 2.3 release.

@calvinjia do you have any opinions

**Comment by calvinjia** [comment]
@ZacBlanco @jiacheliu3 I'm onboard with removing the deprecated endpoints

**Comment by jiacheliu3** [comment]
@ZacBlanco Do you mind merging this for me please? Thanks!

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Pull request merged**
