### PR TITLE
[SMALLFIX] fix fuse du command

### PR DESCRIPTION
**Pull request by LuQQiu**

### CODE REVIEW

**Comment by LuQQiu** [comment]
@aaudiber For Alluxio-Fuse du command, which of the following ways would you think is better?
(1) show Alluxio block size and how many blocks we use
```
stat.st_blocks.set(status.getBlockIds().size());
stat.st_blksize.set(status.getBlockSizeBytes());
```
(2) show Linux style block size and block number, which is implemented in this PR.

I set the `FUSE_BLOCK_SIZE` to be 4k as most linux system used, would it be better to make it configurable or get the block size from the underlying system? Thanks

**Comment by aaudiber** [comment]
@LuQQiu do you know how other fuse implementations have done it? Approach (1) seems cleaner, but I'm not sure if there are applications which would react strangely to large block size.

**Comment by LuQQiu** [comment]
@aaudiber Accoring to the hdfs-fuse and Fuse-j-HDFS in https://wiki.apache.org/hadoop/MountableHDFS

They use plan 1: hdfs block number and block size.

Another issue I found is do we want to show users how many blocks a file actually takes? 
```
stat.st_blocks.set(status.getBlockIds().size());
```
which may include replicates.

Or use 
```
stat.st_blocks.set((int) Math.ceil(status.getLength() / status.getBlockSizeBytes()));
```

Because HDFS block number is incorrect, both the hdfs-fuse and Fuse-j-HDFS use the second plan. I feel that it may be better to use the second one(do not consider rep).
Thanks!

**Comment by aaudiber** [comment]
Thanks for researching this! I agree, second options sounds better (not considering reps).

**Pull request merged**
