### PR TITLE
[DOCFIX] Update the Getting Started guide

### PR DESCRIPTION
**Pull request by Limuzhou**
Reworded the part where it asks the contributors to assign themselves to avoid potential confusion. 

Updated the "Sending a Pull Request" section due to the UI change on Github.

### CODE REVIEW

**Comment by Limuzhou** [comment]
alluxio-bot, check this please

**Comment by Limuzhou** [comment]
alluxio-bot, check this please

**Comment by apc999** [comment]
@Limuzhou this PR contains too much change. did you merge your PR with master branch?

**Comment by Limuzhou** [comment]
> @Limuzhou this PR contains too much change. did you merge your PR with master branch?

Yes, I did. I only changed the documentation file but git wouldn't let me push without merging so I thought that was what I was supposed to do. If there's a way to do it without merging please let me know. I can try to redo it on Monday!

**Pull request closed without merging**
