### PR TITLE
Fail TransformDefinitions with no actions

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
@gpang

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by bradyoo** [comment]
@gpang: Yes, I think adding definition is a good idea but I want the error message to contain unnormalized form. So I may later move this error elsewhere.

**Comment by bradyoo** [comment]
@gpang: suggested fix was 1 character too long. Fixed now.

**Comment by bradyoo** [comment]
Failed tests: 
alluxio.client.fs.FileOutStreamAsyncWriteIntegrationTest.asyncPersistNoAutoPersistNoEvict(alluxio.client.fs.FileOutStreamAsyncWriteIntegrationTest)
  Run 1: FileOutStreamAsyncWriteIntegrationTest.asyncPersistNoAutoPersistNoEvict:192->testLostAsyncBlocks:237
  Run 2: FileOutStreamAsyncWriteIntegrationTest.asyncPersistNoAutoPersistNoEvict:192->testLostAsyncBlocks:237

**Comment by bradyoo** [comment]
alluxio-bot, test this please.

**Comment by bradyoo** [comment]
@gpang: mind merging this?

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
