### PR TITLE
Merge master-2.x commits 2023/03/16~2023/03/31 into main

### PR DESCRIPTION
**Pull request by jiacheliu3**
Merge missing commits from master-2.x to main. The commits in 2023/03/16~2023/03/31 from https://github.com/Alluxio/alluxio/compare/main...master-2.x will be included by this PR.

**Exceptions:**

https://github.com/Alluxio/alluxio/commit/e106cc8bbb3d74d876c9869a0b2fe77240e80af9 is not included because it has been manually cherry-picked to dora.

https://github.com/Alluxio/alluxio/commit/71521f631d1bd9c15ffe05634a7251014f4be1a0 is not included due to the same reason as above.

https://github.com/Alluxio/alluxio/commit/73b4d67c8b39a6358897ec349370e7037a6fea7f is not included because we missed https://github.com/Alluxio/alluxio/commit/ebeac49c3cfc9a224cf8772ebe1c3e38ae1a0b5a from https://github.com/Alluxio/alluxio/pull/17435. Instead of resolving conflicts, it's better to cherry-pick those impacted PRs one by one in the time order, in order NOT to lose code.

https://github.com/Alluxio/alluxio/commit/d680e56180ce9a8fc67a878a4e23c62954ac337c is not included because it will been reworked in https://github.com/Alluxio/alluxio/pull/17419

### CODE REVIEW

**Review by huanghua78 — APPROVED** [review]
Looks good.

**Review by Xenorith — APPROVED** [review]

**Review by beinan — APPROVED** [review]
lgtm

**Review by jja725 — APPROVED** [review]
exception commits LGTM

**Review by elega — APPROVED** [review]

**Comment by jiacheliu3** [comment]
alluxio-bot, sync-merge this please

**Pull request merged**
