### PR TITLE
Fix utimens in JNIFuse

### PR DESCRIPTION
**Pull request by apc999**
### What changes are proposed in this pull request?

Add `utimensCallback` in `AbstractFuseFileSystem` for consistency

### Why are the changes needed?

For naming consistency

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Comment by LuQQiu** [comment]
@apc999 i have the https://github.com/Alluxio/alluxio/pull/15000 also changes jnifuse code, no worry about libjnifuse building, i will take care of that part

**Comment by maobaolong** [comment]
@apc999 Thanks for this consistency improvement. It LGTM overall, just curious why you update the libjnifuse*, for this PR, I guess it is not necessary to update the libjnifuse.

**Comment by apc999** [comment]
> @apc999 Thanks for this consistency improvement. It LGTM overall, just curious why you update the libjnifuse*, for this PR, I guess it is not necessary to update the libjnifuse.

You are right. this is unnecessary. Removed

**Review by LuQQiu — APPROVED** [review]
LGTM,thanks!

**Review by maobaolong — APPROVED** [review]
LGTM. Thank you

**Comment by apc999** [comment]
Error: 3.911 [ERROR] alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTestTransferLeadership.repeatedTransferLeadership  Time elapsed: 172.324 s  <<< ERROR!
java.util.concurrent.TimeoutException: Timed out waiting for quorum property options: WaitForOptions{interval=20, timeout=90000} last value: false
	at alluxio.util.CommonUtils.waitForResult(CommonUtils.java:384)
	at alluxio.util.CommonUtils.waitFor(CommonUtils.java:342)
	at alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTestBase.waitForQuorumPropertySize(EmbeddedJournalIntegrationTestBase.java:58)
	at alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTestTransferLeadership.transferAndWait(EmbeddedJournalIntegrationTestTransferLeadership.java:250)
	at alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTestTransferLeadership.repeatedTransferLeadership(EmbeddedJournalIntegrationTestTransferLeadership.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
