### PR TITLE
Add support for publishing REST from root path

### PR DESCRIPTION
**Pull request by ggezer**
With this change Alluxio will serve proxy rest API from root path as well as API specific path.

### CODE REVIEW

**Review by calvinjia — COMMENTED** [review]
Could we add a test to verify the new set of endpoints is accessible?

**Comment by ggezer** [comment]
@calvinjia Changed the logic for publishing at root by config option.

**Review by calvinjia — APPROVED** [review]
Do you mind regenerating the docs?

**Comment by ggezer** [comment]
alluxio-bot, merge this please

**Comment by ggezer** [comment]
alluxio-bot, cherry-pick this to branch-2.6

**Comment by ggezer** [comment]
alluxio-bot, cherry-pick this to branch-2.6 please

**Comment by ggezer** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please

**Comment by ggezer** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
