### PR TITLE
Fix worker fuse metadata cache

### PR DESCRIPTION
**Pull request by LuQQiu**
### What changes are proposed in this pull request?

Allow metadata cache used in process other than alluxio client, e.g. alluxio fuse inside alluxio worker

### Why are the changes needed?
Worker fuse performance with metadata cache option enabled has worse performance because no actual metadata cache happening

### Does this PR introduce any user facing changes?
Performance

### CODE REVIEW

**Review by ssz1997 — APPROVED** [review]

**Comment by LuQQiu** [comment]
Error: 0.724 [ERROR] Errors: 
Error: 0.724 [ERROR] alluxio.client.fs.io.LocalCacheFileInStreamIntegrationTest.cacheAndEvict
Error: 0.724 [ERROR]   Run 1: LocalCacheFileInStreamIntegrationTest.cacheAndEvict:150 » Unavailable No avail...
Error: 0.725 [ERROR]   Run 2: LocalCacheFileInStreamIntegrationTest.cacheAndEvict:150 » Unavailable No avail...
00:49:50.727 [INFO] 
Error: 0.727 [ERROR] alluxio.client.fs.io.LocalCacheFileInStreamIntegrationTest.positionedRead
Error: 0.728 [ERROR]   Run 1: LocalCacheFileInStreamIntegrationTest.positionedRead:108 » Unavailable No avai...
Error: 0.728 [ERROR]   Run 2: LocalCacheFileInStreamIntegrationTest.positionedRead:108 » Unavailable No avai...
00:49:50.729 [INFO] 
Error: 0.729 [ERROR] alluxio.client.fs.io.LocalCacheFileInStreamIntegrationTest.read
Error: 0.730 [ERROR]   Run 1: LocalCacheFileInStreamIntegrationTest.read:89 » Unavailable No available Allux...
Error: 0.731 [ERROR]   Run 2: LocalCacheFileInStreamIntegrationTest.read:89 » Unavailable No available Allux...

**Comment by LuQQiu** [comment]
alluxio.exception.status.UnavailableException: No available Alluxio worker found

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.9 please

**Pull request merged**
