### PR TITLE
[DOCFIX] Configuration files changed

### PR DESCRIPTION
**Pull request by wuzhenwei-xxx**
Alluxio configure S3 interface，we should add those configuration to conf/alluxio-site.properties and then restart alluxio.

### CODE REVIEW

**Review by wuzhenwei-xxx — COMMENTED** [review]
We should add those configuration to conf/alluxio-site.properties,and then restart alluxio.

**Comment by wuzhenwei-xxx** [comment]
alluxio-bot, check this please

**Comment by wuzhenwei-xxx** [comment]
> Automated checks report:
> 
> * Commits associated with Github account: PASS
> * PR title follows the conventions: FAIL
>   
>   * The title of the PR does not pass all the checks. Please fix the following issues:
>     
>     * First word of title ("Alluxio") is not an imperative verb. Please use one of the [valid words](https://raw.githubusercontent.com/Alluxio/alluxio/master/docs/resources/pr/pr_title_words.md)
> 
> Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.

alluxio-bot, check this please

**Comment by wuzhenwei-xxx** [comment]
> > Automated checks report:
> > 
> > * Commits associated with Github account: PASS
> > * PR title follows the conventions: FAIL
> >   
> >   * The title of the PR does not pass all the checks. Please fix the following issues:
> >     
> >     * First word of title ("Alluxio") is not an imperative verb. Please use one of the [valid words](https://raw.githubusercontent.com/Alluxio/alluxio/master/docs/resources/pr/pr_title_words.md)
> > 
> > Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.
> 
> alluxio-bot, check this please
> 
> > Automated checks report:
> > 
> > * Commits associated with Github account: PASS
> > * PR title follows the conventions: FAIL
> >   
> >   * The title of the PR does not pass all the checks. Please fix the following issues:
> >     
> >     * First word of title ("Alluxio") is not an imperative verb. Please use one of the [valid words](https://raw.githubusercontent.com/Alluxio/alluxio/master/docs/resources/pr/pr_title_words.md)
> > 
> > Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.
> 
> alluxio-bot, check this please

>alluxio-bot, check this please

**Comment by wuzhenwei-xxx** [comment]
alluxio-bot, check this please

**Comment by wuzhenwei-xxx** [comment]
> Automated checks report:
> 
> * Commits associated with Github account: PASS
> * PR title follows the conventions: FAIL
>   
>   * The title of the PR does not pass all the checks. Please fix the following issues:
>     
>     * First word must be capitalized
>     * Title must be at least 2 words
>     * First word of title ("") is not an imperative verb. Please use one of the [valid words](https://raw.githubusercontent.com/Alluxio/alluxio/master/docs/resources/pr/pr_title_words.md)
> 
> Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.



> alluxio-bot, check this please

alluxio-bot, check this please

**Comment by wuzhenwei-xxx** [comment]
> > Automated checks report:
> > 
> > * Commits associated with Github account: PASS
> > * PR title follows the conventions: FAIL
> >   
> >   * The title of the PR does not pass all the checks. Please fix the following issues:
> >     
> >     * First word must be capitalized
> >     * Title must be at least 2 words
> >     * First word of title ("") is not an imperative verb. Please use one of the [valid words](https://raw.githubusercontent.com/Alluxio/alluxio/master/docs/resources/pr/pr_title_words.md)
> > 
> > Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.
> 
> > alluxio-bot, check this please
> 
> alluxio-bot, check this please

alluxio-bot, check this please

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
Thanks for fixing the documentation. Failing tests are unrelated.
@wuzhenwei-xxx

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
