### PR TITLE
Upgrade Junit from 4.12 to 4.13

### PR DESCRIPTION
**Pull request by bradyoo**
Junit 4.13 was released with jdk11 CI.

### CODE REVIEW

**Comment by bradyoo** [comment]
@ZacBlanco easy PR.

**Comment by bradyoo** [comment]
I looked but for now, 4.x is fine given the number of other dependencies that needs to get upgraded.

**Comment by ZacBlanco** [comment]
Fair enough

alluxio-bot, merge this please

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Pull request merged**
