### PR TITLE
[ALLUXIO-1748] Fix incompatible type compilation error on Java 8

### PR DESCRIPTION
**Pull request by rnirmal**
https://tachyon.atlassian.net/browse/ALLUXIO-1748

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by rnirmal** [comment]
It will be great if we can get this backported to `branch-1.0`.

**Comment by aaudiber** [comment]
Thanks for the fix! In the future please include a link to the JIRA ticket as the first line of the pull request message - we have a tool which will update automatically update the JIRA ticket if you do this, and the link is convenient for reviewers to get to the ticket.

**Comment by aaudiber** [comment]
LGTM

**Comment by aaudiber** [comment]
@rnirmal I've backported your fix to [branch-1.0](https://github.com/Alluxio/alluxio/commits/branch-1.0)

**Comment by rnirmal** [comment]
@aaudiber thanks for backporting it. I will include a link to the JIRA ticket for future PR's.

**Pull request merged**
