### PR TITLE
Remove the dependency to the master during the registration

### PR DESCRIPTION
**Pull request by yyongycy**
### What changes are proposed in this pull request?

Remove the dependency to the master during the registration

### Why are the changes needed?

Not necessary to connect to the master during registration

### Does this PR introduce any user facing changes?
NA

### CODE REVIEW

**Comment by yyongycy** [comment]
@lucyge2022  I can find this log, looks normal without this connection?

> 
> 2023-08-02 15:17:37,472 DEBUG ManagedSelector - update org.eclipse.jetty.io.ManagedSelector$Start@1868ed54
> 2023-08-02 15:17:37,472 DEBUG ManagedSelector - updates 0
> 2023-08-02 15:17:37,472 DEBUG ManagedSelector - Selector sun.nio.ch.EPollSelectorImpl@1d5fe43f waiting with 0 keys
> 2023-08-02 15:17:37,472 DEBUG AbstractLifeCycle - STARTED @11855ms ManagedSelector@40dee07b{STARTED} id=0 keys=0 selected=0 updates=0
> 2023-08-02 15:17:37,472 DEBUG AbstractLifeCycle - STARTED @11855ms SelectorManager@ServerConnector@62b475e2{HTTP/1.1, (http/1.1)}{0.0.0.0:30000}
> 2023-08-02 15:17:37,473 DEBUG ContainerLifeCycle - ServerConnector@62b475e2{HTTP/1.1, (http/1.1)}{0.0.0.0:30000} added {acceptor-0@2cf88901,POJO}
> 2023-08-02 15:17:37,473 DEBUG QueuedThreadPool - queue acceptor-0@2cf88901 startThread=0
> 2023-08-02 15:17:37,473 INFO  AbstractConnector - Started ServerConnector@62b475e2{HTTP/1.1, (http/1.1)}{0.0.0.0:30000}
> 2023-08-02 15:17:37,473 DEBUG AbstractLifeCycle - STARTED @11856ms ServerConnector@62b475e2{HTTP/1.1, (http/1.1)}{0.0.0.0:30000}
> 2023-08-02 15:17:37,473 INFO  Server - Started @11856ms
> 2023-08-02 15:17:37,473 DEBUG AbstractLifeCycle - STARTED @11856ms Server@72443081{STARTED}[9.4.46.v20220331]
> 2023-08-02 15:17:37,473 INFO  WebServer - Alluxio worker web service started @ /0.0.0.0:30000
> 2023-08-02 15:17:37,479 DEBUG QueuedThreadPool - run acceptor-0@2cf88901 in QueuedThreadPool[ALLUXIO-WORKER-WEB-SERVICE]@5fcd1f0a{STARTED,3<=3<=102,i=1,r=-1,q=0}[ReservedThreadExecutor@e0d1dc4{reserved=0/2,pending=0}]
> 2023-08-02 15:17:37,483 INFO  AlluxioWorkerProcess - Alluxio worker started. id=2930933009, bindHost=0.0.0.0, connectHost=Security3xUfsHdfs-workers-0, rpcPort=29999, webPort=30000

**Comment by yyongycy** [comment]
@apc999  FYI,

**Review by lucyge2022 — APPROVED** [review]
great! we can remove that line! thx!
LGTM.

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Comment by yyongycy** [comment]
alluxio-bot, merge this please

**Pull request merged**
