### PR TITLE
[TACHYON-700] Add test to verify if web server is up

### PR DESCRIPTION
**Pull request by qnu**
https://tachyon.atlassian.net/browse/TACHYON-700

### CODE REVIEW

**Comment by qnu** [comment]
Tests successfully passed on local machine, investigating now.

**Comment by qnu** [comment]
@calvinjia do you think this is related to amplab testing environments? since we got http response code 500.

**Comment by calvinjia** [comment]
@qnu I think the amplab tests are using a different version of jetty since its complaining about method not found.

**Comment by qnu** [comment]
@calvinjia Test build failed because of git fetch problem. How can I trigger the build again? or build system needs to be fixed first?

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by qnu** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
@qnu Are you still working on this one (the added test is commented out)?

**Comment by qnu** [comment]
@calvinjia Yes, I am still working on. Local test passed but failed on Jenkins. Used same routines as in other integration tests. Can you give me some hints on how to debug this one?

**Comment by calvinjia** [comment]
@qnu Could you uncomment the test and try it again? The error output is no longer available.

**Comment by qnu** [comment]
test this please.

**Comment by qnu** [comment]
@calvinjia it always fails with internal server error 500 on Jenkins. The structure of this test is similar as ServiceSocketBindIntegrationTest. Any hints?

**Comment by qnu** [comment]
@calvinjia synced with master branch, now the issue reproduces on local machine too. investigating that.

**Comment by qnu** [comment]
test this please.

**Comment by qnu** [comment]
@calvinjia It seems that Web Serverlet is actually broken recently. The local tachyon cluster web interface gives following error message:
```
HTTP ERROR 500
Problem accessing /home. Reason:
    Server Error
Caused by:
java.lang.NullPointerException
	at tachyon.web.WebInterfaceGeneralServlet.generateOrderedStorageTierInfo(WebInterfaceGeneralServlet.java:129)
	at tachyon.web.WebInterfaceGeneralServlet.populateValues(WebInterfaceGeneralServlet.java:199)
	at tachyon.web.WebInterfaceGeneralServlet.doGet(WebInterfaceGeneralServlet.java:104)
```

`ServiceSocketBindIntegrationTest` succeeded simply because it tests `http://localhost:19999/css/tachyoncustom.min.css` not `http://localhost:19999/home`

**Comment by calvinjia** [comment]
@qnu I think the web server should be fixed in the latest master. The error occurring seems to be different.

**Comment by qnu** [comment]
@calvinjia You are right, I noticed that. Seems that tests for dynamic contents should be done in a different way rather than static ones. Looking into it now.

**Comment by qnu** [comment]
@calvinjia In debug mode,we got
```
2015-11-03 19:18:21,258 WARN  servlet.ServletHandler (ServletHandler.java:doHandle) - /home
java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.CompilationResult.getProblems()[Lorg/eclipse/jdt/core/compiler/IProblem;
	at org.apache.jasper.compiler.JDTCompiler$2.acceptResult(JDTCompiler.java:354)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:478)
	at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:425)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:298)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:277)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:265)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:564)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:299)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:315)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:265)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:445)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:574)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:293)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:120)
	at tachyon.web.WebInterfaceConfigurationServlet.doGet(WebInterfaceConfigurationServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:445)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:556)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```
googled this issue, there are many similar cases, basically all caused by conflicts of packages. This link http://brandnewuser.iteye.com/blog/2208969 gives exactly the same symptom. I am not very familiar with the package dependencies. Can you suggest how to change the pom.xml accordingly?

**Comment by qnu** [comment]
@calvinjia This issue is exactly related to previous one
https://tachyon.atlassian.net/browse/TACHYON-780
where following commit uses static page for testing, but the jetty problem is still there.
https://github.com/amplab/tachyon/commit/9c2de40c5dc56b52255171345a8edf7010c1b69d

**Comment by calvinjia** [comment]
@qnu Thanks for the update, let's wait until that ticket is resolved before merge this then.

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by qnu** [comment]
Jenkins, test this please.

**Comment by qnu** [comment]
seems that jetty package conflicts still exists.

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by yupeng9** [comment]
@qnu Are you still working on this?

**Comment by qnu** [comment]
@yupeng9 Sorry, I thought this issue depends on others and I am fully occupied during this period. I appreciate that you can take over this. Thank you!

**Comment by yupeng9** [comment]
Thanks for the update!

**Comment by yupeng9** [comment]
Closing this since the test is ported to PR https://github.com/Alluxio/alluxio/pull/2696

**Pull request closed without merging**
