### PR TITLE
[SMALLFIX] Fix the alluxio-fuse typo

### PR DESCRIPTION
**Pull request by LuQQiu**
### What changes are proposed in this pull request?

Fix the alluxio-fuse script typo

### CODE REVIEW

**Review by ssz1997 — APPROVED** [review]
LGTM

**Comment by LuQQiu** [comment]
@Xenorith PR for 2.8, FYI

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
@Xenorith Please help cherry-pick to 2.8

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Pull request merged**
