### PR TITLE
Enable java 11 in alluxio base image

### PR DESCRIPTION
**Pull request by ssz1997**
By adding an argument to specify the java version, users will be able to launch Alluxio with java 11 in containers.

Only java 8 and java 11 are supported. If users try build with other versions, the build would fail with error `failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed`. It is not intuitive at all but there is no way to print an custom error message because the error happens when it's trying to load the metadata for all images used in the dockerfile, before any script runs, where we can put our custom error message.

This is the first step of a series of updates of the images. The documentation will be updated later.

### CODE REVIEW

**Comment by ssz1997** [comment]
`alluxio.client.file.cache.LocalCacheManagerTest` timed out

**Comment by ssz1997** [comment]
Error: 6.215 [ERROR] Errors: 
Error: 6.215 [ERROR] alluxio.master.journal.raft.RaftJournalTest.gainPrimacyAfterSuspend
Error: 6.216 [ERROR]   Run 1: RaftJournalTest.gainPrimacyAfterSuspend:349->promoteFollower:403 » Timeout Tim...
Error: 6.216 [ERROR]   Run 2: RaftJournalTest.gainPrimacyAfterSuspend:349->promoteFollower:403 » Timeout Tim...

**Review by LuQQiu — APPROVED** [review]
LGTM, a small question that can these code be shared between Dockerfile and Dockerfile-dev?

**Comment by ssz1997** [comment]
> LGTM, a small question that can these code be shared between Dockerfile and Dockerfile-dev?

Yes. The refactor will be part of the whole process later.

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
@ssz1997 @Xenorith Just a sanity check, any doc update needed for this change?

**Comment by Xenorith** [comment]
the release notes should mention this, but could also mention this within the advanced setup seciton in the docker deploy page https://docs.alluxio.io/os/user/edge/en/deploy/Running-Alluxio-On-Docker.html#launch-alluxio-with-the-development-image

**Comment by ssz1997** [comment]
Yes we need a doc for this. Working on it.

**Pull request merged**
