### PR TITLE
[ALLUXIO-628] Fixed Style checker failed to find an indent problem

### PR DESCRIPTION
**Pull request by HorizonNet**
https://alluxio.atlassian.net/browse/ALLUXIO-628

This one prepares the change in the configuration in Checkstyle.

### CODE REVIEW

**Comment by jsimsa** [comment]
What is the style used here? The IntelliJ formatter recommended for the Alluxio project uses the original formatting.

**Comment by HorizonNet** [comment]
@jsimsa I added ```<property name="forceStrictCondition" value="true"/>``` to the Checkstyle's *Indentation* module as mentioned in the [JIRA ticket](https://alluxio.atlassian.net/browse/ALLUXIO-628) and documented [here](http://checkstyle.sourceforge.net/config_misc.html#Indentation). This PR (and the others) are the preparation for this rule. If that's not the intended behavior the ticket should be closed.

**Comment by jsimsa** [comment]
@HorizonNet thank you for the explanation ... @apc999 is the plan to update the IntelliJ formatter we use to match the style enforced by the checkstyle rule?

**Comment by apc999** [comment]
@HorizonNet Thanks for the formatting fix. The original plan in the JIRA (ALLUXIO-628) is fairly simple:

Just let the style checker to warn
```java
private StorageDirView selectDestDir(BlockMeta block, List<StorageTierView> toTiers,
                                     Map<StorageDirView, Long> pendingBytesInDir) {
```
but be happy with the google style:
```java
private StorageDirView selectDirToTransferBlock(BlockMeta block, List<StorageTierView> toTiers,
    Map<StorageDirView, Long> pendingBytesInDir) {
```
It seems in the current PR, the new line indent changes
```java
    BlockWorkerInfo workerInfo =
         new BlockWorkerInfo(new WorkerNetAddress().setHost("localhost").setRpcPort(1)
             .setDataPort(2).setWebPort(3), Constants.GB, 0);
```
to 
```java
    BlockWorkerInfo workerInfo =
        new BlockWorkerInfo(new WorkerNetAddress().setHost("localhost").setRpcPort(1)
        .setDataPort(2).setWebPort(3), Constants.GB, 0);
``` 
by the default rule for `forceStrictCondition`

I think it is a bit different from what I was imagining. @jsimsa  what's your opinion?

**Comment by jsimsa** [comment]
I agree with @apc999. Ideally, checkstyle would generate warnings for:

```
private StorageDirView selectDestDir(BlockMeta block, List<StorageTierView> toTiers,
                                     Map<StorageDirView, Long> pendingBytesInDir) {
```

but

```
    BlockWorkerInfo workerInfo =
         new BlockWorkerInfo(new WorkerNetAddress().setHost("localhost").setRpcPort(1)
             .setDataPort(2).setWebPort(3), Constants.GB, 0);
```

should be valid formatting seeing as that's how our current IntelliJ formats the code.

**Comment by HorizonNet** [comment]
I had a similar discussion with @aaudiber for this [PR](https://github.com/Alluxio/alluxio/pull/3118). I'm not sure that Checkstyle supports this differentiation in the indentations in different cases.

**Comment by apc999** [comment]
@HorizonNet I doublechecked the stylechecker page for indentation (http://checkstyle.sourceforge.net/config_misc.html). I think you are right that with the current style checker implementation, warning 
```java
private StorageDirView selectDestDir(BlockMeta block, List<StorageTierView> toTiers,
                                     Map<StorageDirView, Long> pendingBytesInDir) {
``` 
is conflicting with having 
 ```java
    BlockWorkerInfo workerInfo =
         new BlockWorkerInfo(new WorkerNetAddress().setHost("localhost").setRpcPort(1)
             .setDataPort(2).setWebPort(3), Constants.GB, 0);
```

So I will probably suggest to  keep the current style checker setting.  What do you think @jsimsa ?

**Comment by jsimsa** [comment]
I agree.

**Comment by HorizonNet** [comment]
Ok, just to make sure: do we close the ticket and leave everything as is? If so, I would close the PRs.

**Comment by jsimsa** [comment]
That sounds good to me. Sorry for the trouble @HorizonNet.

**Pull request closed without merging**
