### PR TITLE
[SMALLFIX] Replace anonymous type with lambda

### PR DESCRIPTION
**Pull request by wmFrank**

### CODE REVIEW

**Comment by wmFrank** [comment]
alluxio-bot, check this please

**Comment by wmFrank** [comment]
alluxio-bot, check this please

**Comment by newnius** [comment]
Jenkins, test this please

**Comment by wmFrank** [comment]
> Jenkins, test this please

Should I commit again? I don't know why there are two other files changed.

**Comment by newnius** [comment]
> > Jenkins, test this please
> 
> Should I commit again? I don't know why there are two other files changed.

You can either reset your commits or just change them back.

**Comment by aaudiber** [comment]
alluxio-bot, merge this please

**Pull request merged**
