### PR TITLE
Reduce wait time for change leader

### PR DESCRIPTION
**Pull request by ccy00808**
### What changes are proposed in this pull request?

reduce waiting time for change leader

### Why are the changes needed?

currently, sleeping 20S is too long.

Does this PR introduce any user facing changes?
No

issue: https://github.com/Alluxio/alluxio/issues/14563

### CODE REVIEW

**Comment by yuzhu** [comment]
@ccy00808 thanks for the improvement, Please sign the CLA when you get a chance.

**Review by jenoudet — APPROVED** [review]
I believe this change will improve the failover time considerably. 
The previous implementation used the sleep time as a heuristic to ensure a smooth transition. The newfound stability brought by the Ratis version upgrade in Alluxio 2.7 allows us to be more conservative with this heuristic.
It also matches the logic found above better.

**Review by maobaolong — APPROVED** [review]
LGTM for this changes, Thanks you @ccy00808

**Comment by yuzhu** [comment]
@ccy00808 the PR looks good, please sign the CLA so we can merge this PR soon. Thanks!

**Comment by apc999** [comment]
@ccy00808 have you signed the CLA https://cla.alluxio.org/? let me know if you have already done so and I will merge your PR

**Review by yuzhu — APPROVED** [review]

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
