### PR TITLE
[ALLUXIO-1893] Support deploying alluxio on secure yarn cluster

### PR DESCRIPTION
**Pull request by lshmouse**
Send a PR because #3060 has been closed.

Thanks for @gpang  @apc999 @aaudiber 's review~

https://alluxio.atlassian.net/browse/ALLUXIO-1893

### CODE REVIEW

**Comment by lshmouse** [comment]
alluxio-bot, check this please

**Comment by lshmouse** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
LGTM

**Comment by apc999** [comment]
LGTM

**Pull request merged**
