### PR TITLE
[SMALLFIX] Shade com.google.protobuf

### PR DESCRIPTION
**Pull request by apc999**

### CODE REVIEW

**Comment by peisun1115** [comment]
LGTM

**Comment by jsimsa** [comment]
I would prefer to use shaded in the package prefix

**Comment by jsimsa** [comment]
so something like `shaded.alluxio.com. ...`

**Comment by jsimsa** [comment]
similarly for thrift

**Comment by apc999** [comment]
@jsimsa PTAL

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
