### PR TITLE
Fix Fuse open with O_WRONLY|O_RDWR

### LINKED ISSUE #15842: Unable to open Fuse file with O_WRONLY|O_RDWR
**Alluxio Version:**
Master

**Describe the bug**
pjdfstest open/23.t
```
expect 0 create ${n0} 0644
expect "0|EINVAL" open ${n0} O_RDONLY,O_RDWR
expect "0|EINVAL" open ${n0} O_WRONLY,O_RDWR
expected 0|EINVAL, got EIO
```
Flag: 0x8003
```
      switch (OpenFlags.valueOf(flags & O_ACCMODE.intValue())) {
        case O_RDONLY:
          return FuseFileInStream.create(mFileSystem, uri, flags, status);
        case O_WRONLY:
          return FuseFileOutStream.create(mFileSystem, mAuthPolicy, uri, flags, mode, status);
        case O_RDWR:
          return FuseFileInOrOutStream.create(mFileSystem, mAuthPolicy, uri, flags, mode, status);
        default:
          throw new RuntimeException(String.format("Cannot create file stream with flag 0x%x. "
              + "Alluxio does not support file modification. "
              + "Cannot open directory in fuse.open().", flags));
      }
```
fall to default with 0x8003, O_ACCMODE

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

### PR DESCRIPTION
**Pull request by LuQQiu**
### What changes are proposed in this pull request?

Fixes #15842

### Why are the changes needed?

Support Fuse open with O_WRONLY|O_RDWR flags

### CODE REVIEW

**Comment by ssz1997** [comment]
This means the flag contains both write only and readwrite, correct? 
Would O_RDONLY|O_RDWR also work with the change?

**Comment by LuQQiu** [comment]
O_WRONLY + O_RDWR = 1 + 2 = 3 O_ACCMODE
O_RDONLY + O_RDWR = 0 + 2 = 2 O_RDWR?
O_WRONLY + O_RDONLY is clearly mentioned by linux doc that is a bug and should not be done like that

**Comment by yyongycy** [comment]
> @yyongycy fall back to O_RDWR by default, not 100% sure it's the correct approach to deal with O_WRONLY|O_RDWR

This mean the caller wants to do read/write on the same fd.  Alluxio can only support either read or write. 
But not sure if one really wants to open a file for both read/write with one fd, let's check how people really uses this flag.

**Comment by LuQQiu** [comment]
@yyongycy because the current Alluxio limitation, we only support read only or write only. If one really wants to open a file for both read and write with one fd, it will be treated as read only or write only by first read or write operation. If later on, a read stream meets a write operation, it will error out.

I saw O_RDWR used for read_only, write_only, or read + write. Those are all valid scenarios and are pretty common.

**Comment by LuQQiu** [comment]
@yyongycy @ssz1997 Treat O_WRONLY | O_RDWR as read-write

**Comment by LuQQiu** [comment]
Ping @yyongycy @ssz1997

**Review by yyongycy — APPROVED** [review]
lgtm

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
