### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Comment by yuzhu** [comment]
@gpang did a pass through the poms to remove unused dependencies, PTAL

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by gpang** [comment]
@yuzhu wow, this is a lot! Have you tried this with a metastore?

**Comment by yuzhu** [comment]
@gpang  yes, I have tested with a metastore

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
