### PR TITLE
Improve job worker health report

### PR DESCRIPTION
**Pull request by vimalKeshu**
### What changes are proposed in this pull request?

Restructure the worker health report class so user of the class can get the worker health report at the point in time plus it will be easy to add many more system information to calculate the worker health. 
#16502

### Why are the changes needed?
It would be easy to add new system information like memory, io etc.. of the worker in calculating the worker health. The new structure of the class provides the worker health report point in time. 

### Does this PR introduce any user facing changes?
No

### CODE REVIEW

**Comment by jja725** [comment]
@vimalKeshu mostly LGTM, please fix the checkStyle. @luzhang6 PTAL since it's observability related

**Comment by vimalKeshu** [comment]
Yes, let me fix the style.thank you @jja725.

**Review by luzhang6 — APPROVED** [review]
LGTM

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Pull request merged**
