### PR TITLE
[DOCFIX] Fix hyper link in Properties-List.md

### PR DESCRIPTION
**Pull request by sg-c**
### What changes are proposed in this pull request?

Hyper links for "alluxio.user.ufs.block.read.location.policy" in https://docs.alluxio.io/os/user/stable/en/reference/Properties-List.html don't work. This PR is for fixing them.

### Why are the changes needed?

N/A

### Does this PR introduce any user facing changes?

N/A

### CODE REVIEW

**Comment by apc999** [comment]
this is actually auto-generated by `alluxio docGen`. We may need to fix there.

**Comment by sg-c** [comment]
Sure, @apc999 , I will take a look there.

**Comment by sg-c** [comment]
@apc999 according to this change: https://github.com/Alluxio/alluxio/pull/9768/files, I think the right files are update. However, I am reverting back part of changes in that commit to fix the problem. In addition, I ran "jekyll serve" and verified the change locally. Please advice. Thanks.

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
