### PR TITLE
Update versions to use 2.0.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by ZacBlanco**

### CODE REVIEW

**Comment by ZacBlanco** [comment]
@madanadit @calvinjia

**Comment by madanadit** [comment]
```
Failed tests: 
alluxio.job.migrate.MigrateIntegrationTest.migrateDirectory[0](alluxio.job.migrate.MigrateIntegrationTest)
  Run 1: MigrateIntegrationTest.migrateDirectory:92
```

**Comment by madanadit** [comment]
jenkins, test this please.

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Pull request merged**
