### PR TITLE
[SMALLFIX] FIX a chinese doc which is Running-Alluxio-Locally.md

### PR DESCRIPTION
**Pull request by Draculair**

### CODE REVIEW

**Comment by Draculair** [comment]
alluxio-bot, check this please

**Comment by Draculair** [comment]
alluxio-bot, check this please

**Comment by Draculair** [comment]
alluxio-bot, check this please

**Comment by Draculair** [comment]
alluxio-bot, check this please

**Comment by Draculair** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
@Draculair thanks for improving the doc. Can you revert the changes to npm-shrinkwrap.json?

**Comment by Draculair** [comment]
alluxio-bot, check this please

**Comment by Draculair** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
@Draculair it looks like the npm-shrinkwrap changes are still there, can you revert them?

**Comment by Draculair** [comment]
> @Draculair it looks like the npm-shrinkwrap changes are still there, can you revert them?

I thought I've done what you said, please check them

**Comment by Draculair** [comment]
> @Draculair it looks like the npm-shrinkwrap changes are still there, can you revert them?

excuse me, can u check my commit, thank u

**Comment by aaudiber** [comment]
alluxio-bot, merge this please

**Pull request merged**
