### PR TITLE
Add short-circuit read to metrics page

### LINKED ISSUE #9450: Short-circuit read metrics got removed from webUI
**Summary**
We should put it back and depending on `alluxio.user.metrics.collection.enabled`, show something like `N/A` if the flag is `false`. The current way to display metrics is confusing and users may have wrong takeaway on data locality
image

**Urgency**
Median

### PR DESCRIPTION
**Pull request by tieujason330**
- Fixes #9450 
Screen Shot 2019-07-24 at 14 25 06

### CODE REVIEW

**Comment by tieujason330** [comment]
@calvinjia PTAL, thanks

**Comment by calvinjia** [comment]
jenkins, test this please.

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
@calvinjia  @tieujason330 
I feel short-circuit read/write is unnecessarily easy to understand, how about:

- Local Read (Short-circuit)

Similarly
- Local Read (Domain Socket)

**Comment by tieujason330** [comment]
@calvinjia @apc999 PTAL, updated with new names (screenshot in description)

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Pull request merged**
