### PR TITLE
Remove deprecated JNR-based FuseFileSystem

### PR DESCRIPTION
**Pull request by apc999**
### What changes are proposed in this pull request?

Remove JNR-based FuseFileSystem

### Why are the changes needed?

JNI-based fuse is preferred since 2.3

### Does this PR introduce any user facing changes?

  1. `alluxio.fuse.jnifuse.enabled` is no longer needed

### CODE REVIEW

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks for the work!

**Comment by jiacheliu3** [comment]
@LuQQiu wanna take a look?

**Review by LuQQiu — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
