### PR TITLE
[SMALLFIX] Fix failing test BufferedBlockInStreamIntegrationTest

### PR DESCRIPTION
**Pull request by apc999**
Fixing the failing integration tests

### CODE REVIEW

**Comment by aaudiber** [comment]
LGTM, thanks for fixing this Bin

**Comment by gpang** [comment]
Will this have to be ported to branch-1.0 as well?

**Comment by gpang** [comment]
LGTM

**Comment by apc999** [comment]
@gpang , no branch-1.0 doesn't have this issue as the pom structure becomes different in master

**Comment by gpang** [comment]
ok, sounds good!

**Pull request merged**
