### PR TITLE
[ALLUXIO-2151] - Removed period from error message

### PR DESCRIPTION
**Pull request by virajago**
https://alluxio.atlassian.net/browse/ALLUXIO-2151

Removed period from error message

### CODE REVIEW

**Comment by virajago** [comment]
alluxio-bot, check this please

**Comment by jsimsa** [comment]
Jenkins, test this please

**Comment by jsimsa** [comment]
Jenkins, ok to test

**Comment by aaudiber** [comment]
LGTM, thanks for making it consistent.

**Pull request merged**
