### PR TITLE
Cleanup HADOOP1 support

### PR DESCRIPTION
**Pull request by maobaolong**
As some people are confused about why we encountered some build error while running alluxio tests.

I will suggest them to remove the HADOOP1 related code to pass the build.

### CODE REVIEW

**Comment by ChunxuTang** [comment]
Thanks for the work!

**Comment by jiacheliu3** [comment]
+1 to removing hadoop 1.

**Review by jja725 — APPROVED** [review]
Thanks for the contribution. It's been annoying for a long time

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Comment by jja725** [comment]
alluxio-bot, cherry-pick this to dora please

**Comment by jja725** [comment]
alluxio-bot, cherry-pick this to main please

**Pull request merged**
