### PR TITLE
Update docker image tags in k8s spec

### PR DESCRIPTION
**Pull request by madanadit**

### CODE REVIEW

**Comment by calvinjia** [comment]
I think master should always just use latest?

**Comment by madanadit** [comment]
@calvinjia since we publish SNAPSHOT docker images, it makes sense to update the tag as well. other someone following along the master docs will end up installing 1.8.1 (or released version) with master docs

**Comment by calvinjia** [comment]
Oh it looks like latest is not really suggested use in Dockerhub.

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Pull request merged**
