### PR TITLE
Support setting JAVA_HOME in alluxio-env.sh

### PR DESCRIPTION
**Pull request by ljk-1993**
Fix https://github.com/Alluxio/alluxio/issues/12250

### CODE REVIEW

**Review by apc999 — APPROVED** [review]
Thanks for the fix! I fixed indentation (replacing tab with space).
LGTM

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
