### PR TITLE
[ALLUXIO-1808] Make BaseKeyValueSystem final

### PR DESCRIPTION
**Pull request by ETsunchao**
Add "final" keyword for jira #1808 new contributor task.

### CODE REVIEW

**Comment by ETsunchao** [comment]
Add "final" keyword for jira #1808 new contributor task.

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Hi @ETsunchao , could you rename your PR to include the ticket number and a short description, like the other PRs? It should look something like this: "[ALLUXIO-1808] Make BaseKeyValueSystem final"

Thanks

**Comment by ETsunchao** [comment]
Hi @gpang , I have been renamed this PR.

**Comment by yupeng9** [comment]
LGTM

**Comment by yupeng9** [comment]
Thanks for the improvement.

**Pull request merged**
