### PR TITLE
 [ALLUXIO-2414] Add TTL directory functionality

### PR DESCRIPTION
**Pull request by gjhkael**
https://alluxio.atlassian.net/browse/ALLUXIO-2414

### CODE REVIEW

**Comment by gjhkael** [comment]
alluxio-bot, check this please

**Comment by gjhkael** [comment]
Now, I adjust the SetTtlCommand to handle directory path with iterative method. This will appear a situation if all the files under the directory have been deleted for ttl act operation , but the directory is still exist. So, is it necessary to delete this directory. If needed, is't need to add the ttl action to InodeDirectory ,or TtlBucketList maintain the relationship of INodeFile？

**Comment by gjhkael** [comment]
alluxio-bot, check this please

**Comment by gjhkael** [comment]
If directory's TTL has been set to a value, and then I set a new TTL value (the value > directory's TTL)  to a file that under the directory. Is it allowable? Should delete this directory  ignore the file's TTL?

**Comment by gjhkael** [comment]
One more question, TtlBucket should manage both INodeFile and INodeDirectory use the base class INode?or use two HashSet manage they?

**Comment by uronce-cc** [comment]
@gjhkael Thanks for looking into this, I think TTL of a file under a directory with existing TTL can be reset if the rules from my comments above are met. 

I prefer to managing INode in TtlBucket.

**Pull request closed without merging**
