### PR TITLE
[ALLUXIO-2873] Rename file MountCommandTest.java to MountCommandIntegrationTest.java

### PR DESCRIPTION
**Pull request by lijiang2**
https://alluxio.atlassian.net/browse/ALLUXIO-2873

### CODE REVIEW

**Comment by lijiang2** [comment]
alluxio-bot, check this please

**Comment by lijiang2** [comment]
alluxio-bot, check this please

**Comment by lijiang2** [comment]
alluxio-bot, check this please

**Comment by apc999** [comment]
@lijiang2 

Can you follow the instructions under "Commits associated with Github account: FAIL" given by alluxio-bot? it fails because the email is not correctly set.

**Comment by apc999** [comment]
also @lijiang2 the CLA is missing.

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](http://cla.alluxio.org). It's all electronic and will take just minutes.

**Comment by lijiang2** [comment]
Updated email address and username. Also re-signed the CLA.

**Comment by apc999** [comment]
@lijiang2 congrats, you did it!

thanks

**Pull request merged**
