### PR TITLE
[DOCFIX] Update Chinese Overview.md and fix typo in English Overview.md

### PR DESCRIPTION
**Pull request by AlexYinHan**
@RongGu

### CODE REVIEW

**Comment by RongGu** [comment]
LGTM. @apc999

**Comment by RongGu** [comment]
Thanks for the update @AlexYinHan . It's fixed. @haoyuan

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Pull request merged**
