### PR TITLE
Fix NPE in UnderFileSystem getLastModifiedDate.getTime

### LINKED ISSUE #14640: NPE in S3AUnderFileSystem getObjectStatus
**Alluxio Version:**
Alluxio 2.6.0
**Describe the bug**
2021-12-08 15:15:18,234 ERROR FileSystemMasterClientServiceHandler - Exit (Error): ListStatus: request=path: "/dell_ecs2"
options {
  loadMetadataType: ONCE
  commonOptions {
    syncIntervalMs: -1
    ttl: -1
    ttlAction: DELETE
  }
  recursive: false
  loadMetadataOnly: false
}

java.lang.NullPointerException
	at alluxio.underfs.s3a.S3AUnderFileSystem.getObjectStatus(S3AUnderFileSystem.java:752)
	at alluxio.underfs.ObjectUnderFileSystem.listInternal(ObjectUnderFileSystem.java:980)
	at alluxio.underfs.ObjectUnderFileSystem.listStatus(ObjectUnderFileSystem.java:604)
	at alluxio.underfs.UnderFileSystemWithLogging$32.call(UnderFileSystemWithLogging.java:733)
	at alluxio.underfs.UnderFileSystemWithLogging$32.call(UnderFileSystemWithLogging.java:730)
	at alluxio.underfs.UnderFileSystemWithLogging.call(UnderFileSystemWithLogging.java:1213)
	at alluxio.underfs.UnderFileSystemWithLogging.listStatus(UnderFileSystemWithLogging.java:730)
	at 

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

### PR DESCRIPTION
**Pull request by LuQQiu**
### What changes are proposed in this pull request?
Fix #14640 

### Why are the changes needed?
Fix NPE in Object stores getLastModifiedDate().getTime()

### Does this PR introduce any user facing changes?
No

### CODE REVIEW

**Comment by LuQQiu** [comment]
@yuzhu Changed from long to Long and use NULL whenever we cannot get last modified time.
This is because ObjectStatus is only used to transfer to UfsStatus with 
```
  /** Last modified epoch time in ms, or null if it is not available. */
  protected final Long mLastModifiedTimeMs;

  /**
   * Gets the UTC time of when the indicated path was modified recently in ms, or null if the last
   * modified time is not available.
   *
   * @return modification time in milliseconds
   */
  @Nullable
  public Long getLastModifiedTime() {
    return mLastModifiedTimeMs;
  }

```

**Comment by LuQQiu** [comment]
Possible NPE throughout all UFSes, and not just for S3A
checked the source code of other UFSes, getLastModifiedTime() also can return null

**Comment by yuzhu** [comment]
```Error: 8.718 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project alluxio-core-server-master: Compilation failure: Compilation failure: 
Error: 8.718 [ERROR] /usr/src/alluxio/core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java:[164,38] no suitable constructor found for UfsFileStatus(java.lang.String,java.lang.String,int,int,java.lang.String,java.lang.String,short,int)
Error: 8.718 [ERROR]     constructor alluxio.underfs.UfsFileStatus.UfsFileStatus(java.lang.String,java.lang.String,long,java.lang.Long,java.lang.String,java.lang.String,short,long) is not applicable
Error: 8.719 [ERROR]       (argument mismatch; int cannot be converted to java.lang.Long)
Error: 8.719 [ERROR]     constructor alluxio.underfs.UfsFileStatus.UfsFileStatus(java.lang.String,java.lang.String,long,java.lang.Long,java.lang.String,java.lang.String,short,java.util.Map<java.lang.String,byte[]>) is not applicable
Error: 8.719 [ERROR]       (argument mismatch; int cannot be converted to java.lang.Long)
Error: 8.719 [ERROR] /usr/src/alluxio/core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java:[180,37] no suitable constructor found for UfsFileStatus(java.lang.String,java.lang.String,int,int,java.lang.String,java.lang.String,short,int)
Error: 8.719 [ERROR]     constructor alluxio.underfs.UfsFileStatus.UfsFileStatus(java.lang.String,java.lang.String,long,java.lang.Long,java.lang.String,java.lang.String,short,long) is not applicable
Error: 8.720 [ERROR]       (argument mismatch; int cannot be converted to java.lang.Long)
Error: 8.720 [ERROR]     constructor alluxio.underfs.UfsFileStatus.UfsFileStatus(java.lang.String,java.lang.String,long,java.lang.Long,java.lang.String,java.lang.String,short,java.util.Map<java.lang.String,byte[]>) is not applicable
Error: 8.728 [ERROR]       (argument mismatch; int cannot be converted to java.lang.Long)
Error: 8.728 [ERROR] -> [Help 1]```

**Review by yuzhu — APPROVED** [review]
Thanks @LuQQiu

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
