### PR TITLE
Bump go from 1.13 to 1.18

### PR DESCRIPTION
**Pull request by fengshunli**
### What changes are proposed in this pull request?

Please outline the changes and how this PR fixes the issue.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

### CODE REVIEW

**Comment by elega** [comment]
@fengshunli can you justify when we are upgrading from go 1.13 to 1.18
@Xenorith  can you take a look?

**Comment by fengshunli** [comment]
> @fengshunli can you justify when we are upgrading from go 1.13 to 1.18 @Xenorith can you take a look?

Now all open source projects are used in version 18, version 18 is more stable, and it is more convenient for management package dependence

**Review by ssz1997 — APPROVED** [review]
@fengshunli Are you planning on using the operator project?

**Comment by fengshunli** [comment]
If the project is deployed in the form of opertor, I think upgrading and splitting into sub-projects is essential

**Comment by elega** [comment]
@Xenorith can you take a look?

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Pull request merged**
