### PR TITLE
[SMALLFIX] Inlined variables, removed explicit parameter type and redundant cast in SwiftUnderFileSystem

### PR DESCRIPTION
**Pull request by HorizonNet**
Inlined variables, removed an explicit parameter type and removed a redundant cast in the *SwiftUnderFileSystem* class.

### CODE REVIEW

**Comment by HorizonNet** [comment]
Jenkins, test this please.

**Comment by HorizonNet** [comment]
This test seems to be flaky.

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by ifcharming** [comment]
LGTM

**Comment by aaudiber** [comment]
LGTM

**Pull request merged**
