### PR TITLE
Remove alluxio presto ami from docs

### PR DESCRIPTION
**Pull request by Xenorith**

### CODE REVIEW

**Review by madanadit — APPROVED** [review]
mind removing the link to the related blog on the overview page as well? thx https://docs.alluxio.io/os/user/stable/en/Overview.html

**Comment by Xenorith** [comment]
good catch, removed the link in both en and cn overview pages

**Review by madanadit — APPROVED** [review]

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.3 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please

**Pull request merged**
