### PR TITLE
Fix Chinese character errors in Security.md

### PR DESCRIPTION
**Pull request by asagjj**
审纪 ---> 审计

### CODE REVIEW

**Comment by apc999** [comment]
@asagjj can you sign the CLA https://cla.alluxio.org/ ?

**Comment by asagjj** [comment]
> @asagjj can you sign the CLA https://cla.alluxio.org/ ?

Sure,I've already did.

**Comment by apc999** [comment]
can you remove your change on `core/common/src/main/java/alluxio/resource/DynamicResourcePool.java` from this PR? each PR is supposed to resolve or fix one issue.

**Comment by apc999** [comment]
@asagjj we shall not delete this `DynamicResourcePool.java` file. It is still used. I was suggesting to make this pull request only on `docs/cn/advanced/Security.md` but making no change to `DynamicResourcePool.java`

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by haoyuan** [comment]
Thanks @asagjj for the contribution!

**Pull request merged**
