### PR TITLE
[ALLUXIO-3243] Optimize getInode

### PR DESCRIPTION
**Pull request by gpang**
https://alluxio.atlassian.net/browse/ALLUXIO-3243

### CODE REVIEW

**Comment by gpang** [comment]
This removes a lot of unnecessary array copies just to get the last inode.

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
@yuzhu

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by yuzhu** [comment]
LGTM

**Pull request merged**
