### PR TITLE
[ALLUXIO-3395] Concurrent copy from local

### PR DESCRIPTION
**Pull request by cheng-chang**
Cherry picked from https://github.com/Alluxio/alluxio/pull/8305.

### CODE REVIEW

**Comment by aaudiber** [comment]
Jenkins, test this please

**Comment by cheng-chang** [comment]
jenkins, test this please

**Comment by cheng-chang** [comment]
jenkins, test this please

**Comment by cheng-chang** [comment]
jenkins, test this please

**Comment by cheng-chang** [comment]
jenkins, test this please

**Comment by cheng-chang** [comment]
jenkins, test this please

**Pull request merged**
