### PR TITLE
Remove unneeded auto-boxing in AsyncJournalWriter

### PR DESCRIPTION
**Pull request by lingbin**
### What changes are proposed in this pull request?

Remove unneeded auto-boxing in `AsyncJournalWriter`.

### Why are the changes needed?

The `mWriteCounter` member only needs to be a primitive `long` type.

### Does this PR introduce any user facing changes?

No.

### CODE REVIEW

**Comment by lingbin** [comment]
@HelloHorizon  
It seems that the test failure has nothing to do with this PR, is there any way to re-run this test?

**Comment by lingbin** [comment]
@tcrain  Please take a look at this PR when you are free, thank you very much.

**Comment by lingbin** [comment]
@jenoudet Thanks for your review. Is there anything I need to do before this PR can be merged?

**Comment by jenoudet** [comment]
alluxio-bot, merge this please

**Pull request merged**
