### PR TITLE
Fix chgrp lose owner issue

### PR DESCRIPTION
**Pull request by secfree**
### What changes are proposed in this pull request?

Fix the issue that chgrp caused ufs lose the file's owner attribute.

### Why are the changes needed?

Fix https://github.com/Alluxio/alluxio/issues/15583

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Review by yyongycy — APPROVED** [review]
LGTM

**Comment by yyongycy** [comment]
This change looks good. How does it fix the owner dropping issue?

**Comment by secfree** [comment]
> This change looks good. How does it fix the owner dropping issue? 

ProtoBuf returns an empty string instead of null for non-set string type values. So the previous version returns an empty string for the "owner" field.

> Had you verified on the same env?

Yes.

**Comment by yyongycy** [comment]
alluxio-bot, merge this please!

**Pull request merged**
