### PR TITLE
Fix some incorrect code in WorkerWebUILogs

### PR DESCRIPTION
**Pull request by jianghuazhu**
### What changes are proposed in this pull request?
The purpose of this pr is to fix some incorrect code in WorkerWebUILogs.

### Why are the changes needed?
There is some incorrect code in WorkerWebUILogs, we should fix them.

 ### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
1.   change in user-facing APIs
2.   addition or removal of property keys
3.   webui

### CODE REVIEW

**Comment by jianghuazhu** [comment]
@jenoudet @JiamingMai @jiacheliu3 , could you please help review this pr?
Thanks.

**Review by jenoudet — APPROVED** [review]

**Comment by jianghuazhu** [comment]
Thanks @jenoudet .

**Comment by dbw9580** [comment]
alluxio-bot, merge this please

**Comment by dbw9580** [comment]
alluxio-bot, merge this please

**Pull request merged**
