### PR TITLE
[SMALLFIX] Remove unused enum field for exception message

### PR DESCRIPTION
**Pull request by BUPTAnderson**
Fix Alluxio/new-contributor-tasks#575
Fix Alluxio/new-contributor-tasks#576
Fix Alluxio/new-contributor-tasks#577
Fix Alluxio/new-contributor-tasks#578
Fix Alluxio/new-contributor-tasks#579
Fix Alluxio/new-contributor-tasks#580
Fix Alluxio/new-contributor-tasks#581
Fix Alluxio/new-contributor-tasks#582
Fix Alluxio/new-contributor-tasks#583
Fix Alluxio/new-contributor-tasks#584

### CODE REVIEW

**Comment by BUPTAnderson** [comment]
> alluxio-bot, check this please

alluxio-bot, check this please

**Comment by BUPTAnderson** [comment]
@ggezer @yuzhu review this pr please.

**Comment by LuQQiu** [comment]
Thanks @BUPTAnderson  for submitting your new contributor tasks and making contribution to the Alluxio community! (hahaha, please left some new contributor tasks for the following people to trying out the contribution process).

**Review by LuQQiu — APPROVED** [review]

**Comment by BUPTAnderson** [comment]
> Thanks @LuQQiu, I have already read the Alluxio Contribution Guide carefully. Since Alluxio/new-contributor-tasks#575~584 are all in the same file, so I changed it all at once, I'm sorry. Alluxio is an amazing project, and we are using it in our production environment. I hope that we will communicate more in GitHub or Slack and I hope to contribute some of my work to the community.

**Comment by LuQQiu** [comment]
No worries @BUPTAnderson Thanks for all the contributions. Bin (github apc999) and I are all the alluxio community channel. Feel free to raise questions there!

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
