### PR TITLE
[ALLUXIO-2069]correct @param descriptions in UnderFileSystemRegistry.java

### PR DESCRIPTION
**Pull request by dantongz**
https://alluxio.atlassian.net/browse/ALLUXIO-2069
Removes capitalization from param descriptions in UnderFileSystemRegistry.java.

### CODE REVIEW

**Comment by jsimsa** [comment]
Jenkins, ok to test

**Comment by jsimsa** [comment]
Thanks for the contribution @dantongz! Seems like the commits are not associated with your github account.

Here are instructions to get your commits associated with your github account: https://help.github.com/articles/setting-your-email-in-git/#commits-on-github-arent-linking-to-my-account

**Comment by dantongz** [comment]
Sorry @jsimsa , I missed a dot in my user.email. I have made a new commit, PTAL.

**Comment by gpang** [comment]
LGTM

**Comment by ifcharming** [comment]
LGTM

**Comment by ifcharming** [comment]
alluxio-bot, check this please

**Pull request merged**
