### PR TITLE
[DOCFIX] Improve and re-organize Logging doc page

### PR DESCRIPTION
**Pull request by apc999**
Manual cherry-pick https://github.com/Alluxio/alluxio/pull/11302 to branch-2.2

- Reorg the docs to have basic logging (very frequently used for both
server and client side) and remote logging (less frequently used)
- Add a bunch more info in basic logging page

The intention is to consolidate the most commonly used functions into
basic logging page, easier fur us to keep it better maintained.

pr-link: Alluxio/alluxio#11302
change-id: cid-b44c76cf3a0634cf8f3f083a7af54eb0b52ddb08

### CODE REVIEW

**Comment by Xenorith** [comment]
from jenkins build:
```
2020/04/17 19:12:06 Errors found in documentation markdown
  /docs/en/operation/Journal.md:
    16: relative link pointed to unknown file en/deploy/Running-Alluxio-On-a-HA-Cluster.html
  /docs/en/operation/Server-Logging.md:
    18: relative link pointed to unknown file /en/operation/Client-Logging.html
```
first one needs a `/` before `en/...`
for the second one, there's a server logging file still?? so many logging related files

**Comment by apc999** [comment]
The first one was due to a missing cherry-pick to branch 2.2, fixed by  https://github.com/Alluxio/alluxio/pull/11312

> for the second one, there's a server logging file still?? so many logging related files

 sorry  this is due to a bad conflict resolving. fixed

**Comment by apc999** [comment]
Merging this docfix cherry-pick PR ignoring unrelated integration tests

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
