### PR TITLE
[DOCFIX] Add title and nickname translation for cache in caching cn doc

### PR DESCRIPTION
**Pull request by JySongWithZhangCe**

### CODE REVIEW

**Comment by JySongWithZhangCe** [comment]
alluxio-bot, test this please

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks for the improvement!

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by JySongWithZhangCe** [comment]
谢谢嘉承！

**Pull request merged**
