### PR TITLE
[ALLUXIO-1933] use <> operator

### PR DESCRIPTION
**Pull request by nolansemrau**
https://alluxio.atlassian.net/browse/ALLUXIO-1933

### CODE REVIEW

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
ok to test

**Comment by apc999** [comment]
LGTM

**Comment by gpang** [comment]
LGTM

**Comment by calvinjia** [comment]
Jenkins, ok to test.

**Comment by jsimsa** [comment]
LGTM

**Pull request merged**
