### PR TITLE
[ALLUXIO-2344]Improve error handling in SwiftUnderFileFactory#Improvement

### PR DESCRIPTION
**Pull request by KickCellarDoor**
[getaddress](https://alluxio.atlassian.net/browse/ALLUXIO-2344)

### CODE REVIEW

**Comment by KickCellarDoor** [comment]
alluxio-bot, check this please

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
add to whitelist

**Comment by KickCellarDoor** [comment]
@ifcharming Excuse me, but I do not know what's wrong with my changes and the tests can be passed locally.

**Comment by ifcharming** [comment]
Jenkins, test this please

**Pull request merged**
