### PR TITLE
Upgrade slf4j from 1.7.2 to 1.7.30

### PR DESCRIPTION
**Pull request by HelloHorizon**
Dependency diff
```
< [INFO] +- org.slf4j:slf4j-api:jar:1.7.2:compile
< [INFO] +- org.slf4j:slf4j-log4j12:jar:1.7.2:compile
---
> [INFO] +- org.slf4j:slf4j-api:jar:1.7.30:compile
> [INFO] +- org.slf4j:slf4j-log4j12:jar:1.7.30:compile
```

### CODE REVIEW

**Comment by HelloHorizon** [comment]
jenkins, test this please

**Comment by ZacBlanco** [comment]
the slf4j upgrade is not independent of and needs matching versions with the correct API binding for the log4j updates. Please coordinate with @ns1123 on which versions should be used

**Comment by ns1123** [comment]
@HelloHorizon Can you take a look at this PR instead? I needed to upgrade slf4j as part of moving to log4j2

https://github.com/Alluxio/alluxio/pull/11905

**Comment by HelloHorizon** [comment]
@ns1123 if so, we can close this pr. Is it feasible for you to change the slf4j version to 1.7.30?

**Comment by HelloHorizon** [comment]
Close slf4j upgrade pr, upgrade from log4j2 pr.

**Pull request closed without merging**
