### PR TITLE
Change Alluxio master in K8s to use PVC for RocksDB

### PR DESCRIPTION
**Pull request by jiacheliu3**
This resolves point 3 in https://github.com/Alluxio/alluxio/issues/10253

Alluxio master Pods now use PVC for RocksDB as metastore instead of `emptyDir`.

### CODE REVIEW

**Comment by jiacheliu3** [comment]
@madanadit Do you think it makes sense to take `emptyDir` off the options? Now we are switching to only supporting a PVC for Rocks. Do you think `emptyDir` should still exist as a valid option, maybe the user just wants a try?

**Comment by madanadit** [comment]
@jiacheliu3  we should remove the option to prevent mis-configuration and confusion

**Comment by jiacheliu3** [comment]
@madanadit Originally I was planning to update the docs in one go after the batch of PRs are in, but I guess putting the docs next to the code change makes more sense.

I will bump on the helm chart version after #11171, #11173 and this one are all in.

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Pull request merged**
