### PR TITLE
Update protobuf version

### PR DESCRIPTION
**Pull request by ddadaal**
### What changes are proposed in this pull request?

Try updating protobuf to resolve some CVEs.

### Why are the changes needed?

Some CVEs are caused by protobuf version. This PR updates protobuf to a fixed version.

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Review by yuzhu — APPROVED** [review]
Thanks for your contribution. LGTM

**Comment by ddadaal** [comment]
Java 8 Integration test (module (alluxio.client.fs.**,!alluxio.client.fs.concurrent.**,!alluxio.client.fs.io.**)) reports no test failure but the following compilation error
```
2022-01-11T15:56:55.9674636Z 15:56:55.960 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project alluxio-integration-yarn: Compilation failure: Compilation failure: 
2022-01-11T15:56:55.9676655Z 15:56:55.966 [ERROR] error reading /home/jenkins/.m2/repository/org/apache/hadoop/hadoop-yarn-api/3.3.0/hadoop-yarn-api-3.3.0.jar; zip file is empty
2022-01-11T15:56:55.9678269Z 15:56:55.966 [ERROR] error reading /home/jenkins/.m2/repository/org/apache/hadoop/hadoop-yarn-api/3.3.0/hadoop-yarn-api-3.3.0.jar; zip file is empty
2022-01-11T15:56:55.9679903Z 15:56:55.966 [ERROR] /usr/src/alluxio/integration/yarn/src/test/java/alluxio/yarn/ClientTest.java:[23,50] package org.apache.hadoop.yarn.api.protocolrecords does not exist
2022-01-11T15:56:55.9688111Z 15:56:55.966 [ERROR] /usr/src/alluxio/integration/yarn/src/test/java/alluxio/yarn/ClientTest.java:[24,42] package org.apache.hadoop.yarn.api.records does not exist
2022-01-11T15:56:55.9696393Z 15:56:55.968 [ERROR] /usr/src/alluxio/integration/yarn/src/test/java/alluxio/yarn/ClientTest.java:[171,38] cannot find symbol
2022-01-11T15:56:55.9697140Z 15:56:55.969 [ERROR]   symbol:   class Resource
2022-01-11T15:56:55.9697771Z 15:56:55.969 [ERROR]   location: class alluxio.yarn.ClientTest
2022-01-11T15:56:55.9708517Z 15:56:55.969 [ERROR] /usr/src/alluxio/integration/yarn/src/test/java/alluxio/yarn/ContainerAllocatorTest.java:[23,42] package org.apache.hadoop.yarn.api.records does not exist
2022-01-11T15:56:55.9710418Z 15:56:55.970 [ERROR] /usr/src/alluxio/integration/yarn/src/test/java/alluxio/yarn/ContainerAllocatorTest.java:[24,42] package org.apache.hadoop.yarn.api.records does not exist
2022-01-11T15:56:55.9718613Z 15:56:55.970 [ERROR] /usr/src/alluxio/integration/yarn/src/test/java/alluxio/yarn/ContainerAllocatorTest.java:[25,42] package org.apache.hadoop.yarn.api.records does not exist
2022-01-11T15:56:55.9727509Z 15:56:55.971 [ERROR] /usr/src/alluxio/integration/yarn/src/test/java/alluxio/yarn/ContainerAllocatorTest.java:[26,42] package org.apache.hadoop.yarn.api.records does not exist
2022-01-11T15:56:55.9734427Z 15:56:55.972 [ERROR] /usr/src/alluxio/integration/yarn/src/test/java/alluxio/yarn/ContainerAllocatorTest.java:[27,42] package org.apache.hadoop.yarn.api.records does not exist
2022-01-11T15:56:55.9741590Z 15:56:55.973 [ERROR] /usr/src/alluxio/integration/yarn/src/test/java/alluxio/yarn/ContainerAllocatorTest.java:[31,35] cannot find symbol
2022-01-11T15:56:55.9786486Z 15:56:55.973 [ERROR]   symbol:   class Records
2022-01-11T15:56:55.9787201Z 15:56:55.976 [ERROR]   location: package org.apache.hadoop.yarn.util
2022-01-11T15:56:55.9788363Z 15:56:55.976 [ERROR] /usr/src/alluxio/integration/yarn/src/test/java/alluxio/yarn/ContainerAllocatorTest.java:[52,11] cannot find symbol
2022-01-11T15:56:55.9789213Z 15:56:55.977 [ERROR]   symbol:   class Resource
2022-01-11T15:56:55.9790013Z 15:56:55.977 [ERROR]   location: class alluxio.yarn.ContainerAllocatorTest
2022-01-11T15:56:55.9791198Z 15:56:55.977 [ERROR] /usr/src/alluxio/integration/yarn/src/test/java/alluxio/yarn/ContainerAllocatorTest.java:[131,11] cannot find symbol
2022-01-11T15:56:55.9792118Z 15:56:55.977 [ERROR]   symbol:   class ContainerAllocator
2022-01-11T15:56:55.9793098Z 15:56:55.977 [ERROR]   location: class alluxio.yarn.ContainerAllocatorTest
2022-01-11T15:56:55.9794291Z 15:56:55.977 [ERROR] /usr/src/alluxio/integration/yarn/src/test/java/alluxio/yarn/ContainerAllocatorTest.java:[170,54] cannot find symbol
2022-01-11T15:56:55.9795453Z 15:56:55.977 [ERROR]   symbol:   class ContainerAllocator
2022-01-11T15:56:55.9796304Z 15:56:55.977 [ERROR]   location: class alluxio.yarn.ContainerAllocatorTest
2022-01-11T15:56:55.9797501Z 15:56:55.978 [ERROR] /usr/src/alluxio/integration/yarn/src/test/java/alluxio/yarn/ContainerAllocatorTest.java:[186,51] cannot find symbol
2022-01-11T15:56:55.9798353Z 15:56:55.978 [ERROR]   symbol:   class Container
2022-01-11T15:56:55.9799147Z 15:56:55.978 [ERROR]   location: class alluxio.yarn.ContainerAllocatorTest
```

**Comment by ddadaal** [comment]
The other 2 failed checks report the following test case failures:

- alluxio.client.fs.concurrent.ConcurrentFileInStreamIntegrationTest.FileInStreamConcurrency
- alluxio.client.fs.io.FileOutStreamIntegrationTest.cancelWrite

**Comment by LuQQiu** [comment]
compilation error is real error. @apc999 @madanadit can we fully remove integration/yarn or is there sb still using it?

**Comment by madanadit** [comment]
Can be removed

**Review by yyongycy — APPROVED** [review]
LGTM

**Comment by yuzhu** [comment]
@ddadaal could you create a PR to remove integration/yarn

**Comment by yyongycy** [comment]
@yuzhu  is this one good for checkin so far?

**Comment by yuzhu** [comment]
FileOutStreamIntegrationTest.cancelWrite:248 expected:<0> but was:<1000> known test error

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
