### PR TITLE
[SMALLFIX] Permit underscore as Swift container name

### PR DESCRIPTION
**Pull request by madanadit**
Uri hostname does not permit the underscore character. Using getHost return null for a container name with _ because of validation.

Authority is the combination of any user, host and port.

### CODE REVIEW

**Comment by calvinjia** [comment]
Is there a difference between `getHost` and `getAuthority` for this URI? Perhaps we want to validate we don't get additional info like port / user?

**Comment by madanadit** [comment]
@calvin User and port is actually a valid container name in swift. For example, 'a@b:123' is valid. Only the path separator is not allowed.

**Comment by calvinjia** [comment]
@madanadit Got it, could you add a unit test for this? Otherwise looks good to me.

**Comment by madanadit** [comment]
@calvinjia Please have another look.

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
