### PR TITLE
[ALLUXIO-2625] Make SecurityUtilsTest final

### PR DESCRIPTION
**Pull request by RushSykes**
https://alluxio.atlassian.net/browse/ALLUXIO-2625

To avoid accidental subclass extension

### CODE REVIEW

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
Hi @RushSykes , thanks for your contribution to Alluxio!

The following files have windows line endings:
core/common/src/test/java/alluxio/util/SecurityUtilsTest.java

Can you please use the unix line ending instead? thanks
You should only see one line diff on the github `Files Changed` page.

**Comment by RushSykes** [comment]
Sure i'll fix that tomorrow

**Comment by RushSykes** [comment]
Ok it seems there's sth wrong with my env here, gotta create a new PR

**Pull request closed without merging**
