### PR TITLE
Move metrics handler to webserver

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes are proposed in this pull request?

Support prometheus servlet to all the server, include master, worker, job master, job worker, alluxioProxy.

### Why are the changes needed?

With this PR, we can easily to get prometheus style metrics from all the servers.

### Does this PR introduce any user facing changes?

Add `/metrics/json` and `/metrics/prometheus` servlet to all servers of alluxio.

### CODE REVIEW

**Comment by maobaolong** [comment]
@LuQQiu Please take a look at this PR, thank you.

**Review by LuQQiu — APPROVED** [review]
LGTM！ Thanks for enabling metrics for all web servers/processes

**Comment by LuQQiu** [comment]
@yuzhu PTAL if you have time, otherwise this PR will be merged after two days, thanks!

**Comment by yuzhu** [comment]
@maobaolong  LGTM. 

Btw, do we need to update documentation to tell users about metrics on job master/ job worker? Do we have any metrics there yet?

**Comment by LuQQiu** [comment]
good question... i do think we have some job service related metrics? but not quite sure if how they used

**Comment by maobaolong** [comment]
@LuQQiu @yuzhu Although we didn't have any job service related metrics now, but we have some jvm, memory, thread, gc related metrics as common metrics.

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please!

**Comment by maobaolong** [comment]
@LuQQiu Thanks Lu

**Pull request merged**
