### PR TITLE
[DOCFIX] Translation correction on doc 'Lineage-API.md'

### PR DESCRIPTION
**Pull request by caadecarvalho**

### CODE REVIEW

**Comment by caadecarvalho** [comment]
Jenkins, test this please.

**Comment by caadecarvalho** [comment]
I also added a translation correction on doc 'Contributing-to-Alluxio.md'

**Comment by caadecarvalho** [comment]
Jenkins, test this please.

**Comment by aaudiber** [comment]
LGTM, thanks for the fix

**Pull request merged**
