### PR TITLE
Add make to compile the docker image

### PR DESCRIPTION
**Pull request by fengshunli**
### What changes are proposed in this pull request?

Please outline the changes and how this PR fixes the issue.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

### CODE REVIEW

**Comment by elega** [comment]
@Xenorith can you take a look?

**Comment by ssz1997** [comment]
@fengshunli Could you update the README accordingly too? Thanks!

**Comment by fengshunli** [comment]
> @fengshunli Could you update the README accordingly too? Thanks!

@ssz1997 done

**Comment by Xenorith** [comment]
the commands are not sufficiently complex to hide behind a makefile; none of the existing commands involve more than one call. in fact, the makefile seems to prevent certain commands from working since they are hardcoding the example arguments instead of letting the caller decide the value.

**Comment by fengshunli** [comment]
The way makefile is executed can make it more convenient for users and developers to use and reduce the complexity of use. Now many open source projects are built based on makefile. Using makefile is an indispensable construction tool in the project @Xenorith @ssz1997

**Pull request closed without merging**
