### PR TITLE
[DOCFIX] Update Alluxio architecture diagram.

### PR DESCRIPTION
**Pull request by ifcharming**

### CODE REVIEW

**Comment by ifcharming** [comment]
@waltonryan @jsimsa

**Comment by jsimsa** [comment]
LGTM

**Comment by waltonryan** [comment]
LGTM.

I checked the docs css and it'll make the image responsive regardless of it's size. So we should be good there too. 

screen shot 2016-05-25 at 1 21 10 pm

**Comment by ifcharming** [comment]
thanks @waltonryan for confirming!

**Pull request merged**
