### PR TITLE
Port changes of [#11292] to branch-2.2

### PR DESCRIPTION
**Pull request by jiacheliu3**
This ports PR #11292 to branch 2.2
Author: jiacheliu3

### CODE REVIEW

**Comment by jiacheliu3** [comment]
@apc999 I realized I can cherry pick your missing commit in. The 2 changes are both included, in place of #11285.

**Comment by gpang** [comment]
@jiacheliu3 This should not be performed this way. They should be cherry-picked individually to correctly track the changes.

**Comment by jiacheliu3** [comment]
@gpang I see. I will revert the last commit.

**Comment by gpang** [comment]
@jiacheliu3 I am confused. This should be a cherry-pick PR, so that means there should be 1 commit in the PR which has an existing change-id. Right now, if this is merged, it will not be linked to an existing change-id.

**Comment by jiacheliu3** [comment]
Closed as the auto cherry-pick is unblocked. This manual step is not necessary anymore.

**Pull request closed without merging**
