### PR TITLE
Fix object listing pagination for OSS and COS

### PR DESCRIPTION
**Pull request by calvinjia**
Patch for 2.0.0 preview. Fix to master will be done in #8519

### CODE REVIEW

**Comment by LuQQiu** [comment]
Jenkins, test this please

**Comment by LuQQiu** [comment]
Twice have the same errors:
Tests in error: 
alluxio.master.AlluxioMasterProcessTest.startStopPrimary(alluxio.master.AlluxioMasterProcessTest)
  Run 1: AlluxioMasterProcessTest.startStopPrimary:59 » Runtime java.lang.RuntimeExcept...
  Run 2: AlluxioMasterProcessTest.startStopPrimary:59 » Runtime java.lang.RuntimeExcept...

alluxio.master.AlluxioMasterProcessTest.startStopSecondary(alluxio.master.AlluxioMasterProcessTest)
  Run 1: AlluxioMasterProcessTest.startStopSecondary:73 » Runtime java.lang.RuntimeExce...
  Run 2: AlluxioMasterProcessTest.startStopSecondary:73 » Runtime java.lang.RuntimeExce...

**Comment by LuQQiu** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
@LuQQiu

**Pull request closed without merging**
