### PR TITLE
Fix tarball generating script

### PR DESCRIPTION
**Pull request by secfree**
### What changes are proposed in this pull request?

Fix the wrong file paths in `generate-tarball.go`

### Why are the changes needed?

Without this PR, running `dev/scripts/generate-tarballs` encountered the following exception

```
  copying source from /alluxio to /tmp/alluxio3899733569 ... done
  running git clean -fdx ... done
  grepping for the version ... done
ReadFile() failed: open shaded/hadoop/pom.xml: no such file or directory
```

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Review by apc999 — APPROVED** [review]

**Review by Xenorith — COMMENTED** [review]
@secfree actually this build script is deprecated and should be removed. please use the script at `dev/scripts/build-artifact.sh` as the entrypoint into the new logic, which is located in `dev/scripts/src/alluxio.org/build/`

**Comment by secfree** [comment]
> @secfree actually this build script is deprecated and should be removed. please use the script at `dev/scripts/build-artifact.sh` as the entrypoint into the new logic, which is located in `dev/scripts/src/alluxio.org/build/`

@Xenorith Thank you very much. Is there any doc this this?

**Comment by Xenorith** [comment]
the basic command to build the default tarball is `./dev/scripts/build-artifact.sh tarball`

the execution should be familiar to the previous version if you inspect the `-h` options
```
$ ./dev/scripts/build-artifact.sh
expected a subcommand argument. select one of the following: [docker modules profiles tarball ufsVersionCheck version]
 --- at git/alluxio/dev/scripts/src/alluxio.org/build/main.go:32 (run) ---
$ ./dev/scripts/build-artifact.sh tarball -h
2023/07/18 19:26:36 Repository root at directory: git/alluxio
Usage of tarball:
  -artifact string
    	If set, writes object representing the tarball to YAML output file
  -dryRun
    	If set, writes placeholder files instead of running maven commands to mock the final state of the build directory to be packaged as a tarball
  -libModules string
    	Either a lib modules bundle name or a comma-separated list of lib modules to compile into the tarball; list available lib modules and lib module bundles with the plugins command
  -modulesFile string
    	Path to modules.yml file (default "src/alluxio.org/build/modules.yml")
  -mvnArgs string
    	Comma-separated list of additional Maven arguments to build with, e.g. -mvnArgs "-Pspark,-Dhadoop.version=2.2.0"
  -outputDir string
    	Set output dir for generated tarball (default "/Users/rico/git/alluxio")
  -pluginModules string
    	Either a plugin modules bundle name or a comma-separated list of plugin modules to compile into the tarball; list available plugin modules and plugin module bundles with the plugins command
  -profile string
    	Tarball profile to build; list available profiles with the profiles command
  -profilesFile string
    	Path to profiles.yml file (default "src/alluxio.org/build/profiles.yml")
  -skipRepoCopy
    	Set true to build tarball from local repository instead of making a copy and running git clean
  -suppressMavenOutput
    	Set true to avoid printing maven command stdout to console
  -target string
    	Name for the generated tarball; use '${VERSION}' as a placeholder for the version string
```

let me know if you'd like to see more docs and i can add them

**Comment by secfree** [comment]
> the basic command to build the default tarball is `./dev/scripts/build-artifact.sh tarball`

Thank you. I have tried this and it succeed. 

>  Is there any doc this this?

What I mean is for this part - "actually this build script is deprecated and should be removed. please use the script at dev/scripts/build-artifact.sh". Other users may be still using the old one.

**Comment by secfree** [comment]
As `dev/scripts/generate-tarballs` is already deprecated, I will just close this PR.

**Comment by Xenorith** [comment]
i have created this PR to remove the old pathway: https://github.com/Alluxio/alluxio/pull/17807

**Pull request closed without merging**
