### PR TITLE
[ALLUXIO-1934] Replaced <UnderFileSystemFactory> with <>

### PR DESCRIPTION
**Pull request by ilganeli**
* Replaced all instances of <UnderFileSystemFactory> with <> for conciseness. 

https://alluxio.atlassian.net/browse/ALLUXIO-1934

### CODE REVIEW

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Thanks @ilganeli for the improvement! Could you also add a link back to the JIRA ticket in the PR description?

**Comment by apc999** [comment]
LGTM

**Comment by gpang** [comment]
LGTM

**Pull request merged**
