### PR TITLE
Remove master host check

### PR DESCRIPTION
**Pull request by jja725**
### What changes are proposed in this pull request?

remove master host check

### Why are the changes needed?
master host should not be a hard requirement right now.

### Does this PR introduce any user facing changes?
na

### CODE REVIEW

**Comment by lucyge2022** [comment]
not sure if this is needed, can u confirm? @yyongycy

**Review by lucyge2022 — APPROVED** [review]

**Comment by yyongycy** [comment]
> not sure if this is needed, can u confirm? @yyongycy

The worker doesn't depend on the master now.

**Review by yyongycy — APPROVED** [review]
lgtm

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Pull request merged**
