### PR TITLE
Upgrade OSS Java Client to 3.6.0

### PR DESCRIPTION
**Pull request by cheyang**
- Make OSS Java Client up to date with 3.6.0.
- Change the new API interface.

### CODE REVIEW

**Comment by cheyang** [comment]
/ping @apc999 , I'm testing with this commit. Looks good. And I didn't find the error by using IDEA, could you help? thanks.

**Comment by madanadit** [comment]
Failed check-style: 
```
/usr/src/alluxio/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java:271: error: Line is longer than 100 characters (found 105).
```

**Comment by cheyang** [comment]
> Failed check-style:
> 
> ```
> /usr/src/alluxio/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java:271: error: Line is longer than 100 characters (found 105).
> ```

Thank you!

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please.

**Pull request merged**
