### PR TITLE
Fix job rest api test

### PR DESCRIPTION
**Pull request by yuzhu**
### What changes are proposed in this pull request?

Fix job rest api test introduced in #13895

### CODE REVIEW

**Review by ZhuTopher — APPROVED** [review]
I don't really have context but LGTM

**Review by HelloHorizon — APPROVED** [review]
@yuzhu do you mind also link the pr introduce this issue? otherwise LGTM

**Comment by yuzhu** [comment]
unrelated test failure Error: 1.189 [ERROR] Errors: 
Error: 1.193 [ERROR] alluxio.client.hadoop.FileSystemUriIntegrationTest.multiMasterUriTest
Error: 1.194 [ERROR]   Run 1: FileSystemUriIntegrationTest.multiMasterUriTest:76->testConnection:90 » Timeout
Error: 1.195 [ERROR]   Run 2: FileSystemUriIntegrationTest.multiMasterUriTest:76->testConnection:90 » Timeout

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
