### PR TITLE
[SMALLFIX] Redirect error messages to STDERR in bin/alluxio

### PR DESCRIPTION
**Pull request by dbw9580**
Fixes alluxio/new-contributor-tasks#595, alluxio/new-contributor-tasks#596, alluxio/new-contributor-tasks#597.

### CODE REVIEW

**Comment by dbw9580** [comment]
https://github.com/Alluxio/alluxio/blob/79d7153ac31fd069ea5800ea7bcdc34467c000fa/bin/alluxio#L82-L85

Should we do the same here, too?

**Comment by LuQQiu** [comment]
@dbw9580 Please help fix the conflicting files.
Good catch, the one you found should also go in stderr, thanks!

**Comment by LuQQiu** [comment]
For solving conflicts,
you can do 
```
git fetch upstream master
git pull upstream master
git commit -am "Before solving conflicts"
# do your actual code changes to solve conflicts
git commit -am "Solve conflicts"
git push origin <branch_name>
```

**Comment by LuQQiu** [comment]
@dbw9580 By the way, new contributor tasks are added for new contributors to try out the process, so if you try out one or two of them, you can ask @apc999 for other beginner tasks/projects and leave the other new contributor tasks to other new people. But no worries, it's our docs' problem not mentioning it clear enough

**Comment by dbw9580** [comment]
> By the way, new contributor tasks are added for new contributors to try out the process

Oops, sorry. :-P I was wondering why you split so many identical tasks into separate issues.

**Review by LuQQiu — APPROVED** [review]
LGTM! Thanks for improving the error message!

**Review by apc999 — APPROVED** [review]
Thanks for the improvement!

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
