### PR TITLE
[ALLUXIO-2022] Potential off-heap memory leak on Netty file transfer (MAPPED mode)

### PR DESCRIPTION
**Pull request by pfxuan**
Currently, Worker uses MappedByteBuffer as the default mode for Netty file transfer, which includes a potential memory leak issue increasingly swallowing system memory. Because the off-heap mapping, once established, will not dependent upon the file channel that was used to create it. Closing the channel, in particular, has no effect upon the validity of the mapping. See JDK-4724038 for the details: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4724038
In addition, the use of heap ByteBuffer (ByteBuffer.allocate) would also introduce memory "leak" issues:
http://www.evanjones.ca/java-bytebuffer-leak.html

This PR is used to recall `TRANSFER` (uses Java FileChannel.transferTo) as the default mode for Netty file transfer.

### CODE REVIEW

**Comment by gpang** [comment]
Hi @pfxuan , do you have a small example which shows this memory issue?

Also, do you have any results or experiments on the performance implications on using a different transfer mode?

Thanks!

**Comment by pfxuan** [comment]
@gpang, the problem can be easily reproduced by using Spark-Bench [KMeans workload](https://github.com/SparkTC/spark-bench/tree/master/KMeans) with about 5 ~ 60 GB data sets per node. I uploaded the snapshots of memory usage in the case of 60 GB data sets at [ALLUXIO-2022
](https://alluxio.atlassian.net/browse/ALLUXIO-2022)

So far, I didn't see any observable overhead when using `TRANSFER`. In fact, `MAPPED` is somehow introducing a higher CPU usage.

**Comment by calvinjia** [comment]
@pfxuan 
Thanks for the detailed investigation. We are currently manually cleaning up the mapped byte buffers, see `BufferUtils.cleanDirectBuffer`. With that said, I think we fail to call the method in some cases which is leading to the memory leak you are seeing. Instead of changing the default to `TRANSFER`, a better solution is to fix the code for `MAPPED`.

For the performance test between MAPPED and TRANSFER, how large were your buffer sizes?

**Comment by pfxuan** [comment]
@calvinjia , I'm going to patch `BufferUtils.cleanDirectBuffer` and see if it works. The buffer sizes are:
 
alluxio.user.block.remote.read.buffer.size.bytes=8MB
alluxio.user.file.buffer.bytes=4MB

**Comment by pfxuan** [comment]
@calvinjia 
BTW, Indeed has a special implementation for cleaning up the mapped byte buffers. Can we use it? 
https://github.com/indeedeng/util/tree/master/mmap

**Comment by calvinjia** [comment]
@pfxuan I don't think we have a problem cleaning up the byte buffer, but there are cases where we do not call the method leading to the memory consumption you see. I will see if I can reproduce your problem.

**Comment by pfxuan** [comment]
@calvinjia, can `BufferUtils.cleanDirectBuffer` really clean up the mapped byte buffer? It looks like there is not an effective solution to unmap the allocated memory resources . 
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4724038

**Comment by calvinjia** [comment]
@pfxuan I think it can, but it is not recommended by the poster in the thread you linked.

**Comment by calvinjia** [comment]
@pfxuan if we resolve the memory leak issue, is there any other reason to move to `TRANSFER`?

**Comment by pfxuan** [comment]
Right, I'm going to close this PR since the problem has been solved in https://github.com/Alluxio/alluxio/pull/3565

**Comment by pfxuan** [comment]
https://github.com/Alluxio/alluxio/pull/3565 is used to address the memory leak issue on `MAPPED` mode. So we close this PR.

**Pull request closed without merging**
