### PR TITLE
Remove a lot of miscellaneous IntelliJ warnings

### PR DESCRIPTION
**Pull request by jenoudet**
Remove a lot of miscellaneous IntelliJ warnings.

### CODE REVIEW

**Review by yuzhu — APPROVED** [review]

**Comment by yuzhu** [comment]
@jenoudet what is the state of the PR and why did it pull in all the other commits?

**Comment by jenoudet** [comment]
I'm not sure why all the commits appeared, I rebased master and fixed the conflicts and this happened.

**Comment by yuzhu** [comment]
@jenoudet do you think you can create a fresh PR?

**Comment by jenoudet** [comment]
> @jenoudet do you think you can create a fresh PR?

The redo PR is #15669.

**Pull request closed without merging**
