### PR TITLE
Upgrade jets3t to 0.9.4

### PR DESCRIPTION
**Pull request by LuQQiu**
Jets3t and it's dependencies changed to 0.9.4 in alluxio-underfs-gcs, alluxio-table-server-underdb-glue and alluxio-underfs-wasb

### CODE REVIEW

**Comment by LuQQiu** [comment]
GCSUtilsTest
```
java.lang.NoClassDefFoundError: com/jamesmurty/utils/BaseXMLBuilder

	at alluxio.underfs.gcs.GCSUtilsTest.before(GCSUtilsTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.ClassNotFoundException: com.jamesmurty.utils.BaseXMLBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by yuzhu** [comment]
looks like this has a dependency on java-xmlbuilder. Let's wait until that is upgraded first.  blocked on @bf8086

**Comment by LuQQiu** [comment]
Sounds good!

**Comment by bf8086** [comment]
@LuQQiu @yuzhu  https://github.com/Alluxio/alluxio/pull/11897

**Comment by LuQQiu** [comment]
I included the changes in @bf8086  #11897, the previous error gone. Will wait for #11897 merged, and retest the changes in this PR

**Comment by yuzhu** [comment]
@LuQQiu  pls try again with the latest master

**Comment by LuQQiu** [comment]
@yuzhu Build passed and tarball build passed

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
