### PR TITLE
[SMALLFIX] Fix Alluxio/new-contributor-tasks#624

### PR DESCRIPTION
**Pull request by nand-porko**
Fixes Alluxio/new-contributor-tasks#624
https://github.com/Alluxio/new-contributor-tasks/issues/624

### CODE REVIEW

**Review by dbw9580 — APPROVED** [review]
Thanks for the fix!

**Comment by dbw9580** [comment]
@nand-porko please sign the CLA so that we can accept your contribution.

**Comment by nand-porko** [comment]
I have mailed the CLA. Thank you!

**Comment by fuzhengjia** [comment]
@HelloHorizon please check if the CLA has been received.

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
