### PR TITLE
[ALLUXIO-2463] Replace try-finally with try-with-resource for locks

### PR DESCRIPTION
**Pull request by Reidddddd**
https://alluxio.atlassian.net/browse/ALLUXIO-2463

### CODE REVIEW

**Comment by Reidddddd** [comment]
Rebase master branch and resolve conflicts

**Comment by Reidddddd** [comment]
Fix package conflicts (sorry for those misses)

**Comment by Reidddddd** [comment]
Test passed, sorry for previous oversights on package conflicts.
Please review those "try-with-resource for locks" changes. 
Thanks in advance.

**Comment by yupeng9** [comment]
@peisun1115 can you take another look?

**Pull request merged**
