### PR TITLE
[ALLUXIO-2272] modify a word in file_system_master.thrift from "meta data" to "metadata"

### PR DESCRIPTION
**Pull request by FengJH14**
https://alluxio.atlassian.net/browse/ALLUXIO-2272

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
@FengJH14 Could you sign the CLA? Thanks!

**Comment by ifcharming** [comment]
LGTM, thank you for contributing to Alluxio!

**Pull request merged**
