### PR TITLE
Fix shaded client dependencies for prestodb's alluxio connector

### PR DESCRIPTION
**Pull request by beinan**
### What changes are proposed in this pull request?

Fix shaded client dependencies for prestodb's alluxio connector

### Why are the changes needed?

There is some code in prestodb are still using the alluxio-table-client

### Does this PR introduce any user facing changes?
no

### CODE REVIEW

**Review by Xenorith — APPROVED** [review]
woops

**Comment by Xenorith** [comment]
@apc999 @LuQQiu fyi, we still need this dependency for presto

**Comment by beinan** [comment]
@Xenorith build is good now

@apc999 and @LuQQiu do you want to take a look?

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Pull request merged**
