### PR TITLE
[DOCFIX] Update stress bench doc

### PR DESCRIPTION
**Pull request by dbw9580**
Add docs on new stress bench improvements.

Related PRs: #14842, #14925

### CODE REVIEW

**Review by Xenorith — APPROVED** [review]
these changes look good, and thanks for all the typo fixes

i believe there were other stressbench related changes recently that may also require doc updates. for example, @jenoudet added a new stressbench in https://github.com/Alluxio/alluxio/pull/15194

if you haven't already, could you go through the commit history and ask the corresponding committers to also update the doc if necessary?

**Comment by jenoudet** [comment]
> for example, @jenoudet added a new stressbench in https://github.com/Alluxio/alluxio/pull/15194

I added documentation for `MaxFileBench` in the PR mentioned above.

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Pull request merged**
