### PR TITLE
[SMALLFIX] Use static imports for standard test utilities

### PR DESCRIPTION
**Pull request by RazorX7**
Use static imports for standard test utilities in /alluxio/core/common/src/test/java/alluxio/test/util/ConcurrencyUtils.java, changing "import org.junit.Assert" to "import static org.junit.Assert.assertTrue".

### CODE REVIEW

**Comment by RazorX7** [comment]
alluxio-bot, check this please

**Comment by RazorX7** [comment]
what should I do if the Jenkins test failed?

**Comment by RazorX7** [comment]
I just do the small fix and mvn clean install -DskipTests.

**Comment by newnius** [comment]
```
/usr/src/alluxio/core/common/src/test/java/alluxio/test/util/ConcurrencyUtils.java:14:15: error: Unused import - org.junit.Assert.assertTrue.
```

**Comment by RazorX7** [comment]
alluxio-bot, merge this please

**Comment by aaudiber** [comment]
alluxio-bot, merge this please

**Pull request merged**
