### PR TITLE
[ALLUXIO-2168] Add a debug message in SwiftUnderFileSystem.java::mkdirs

### PR DESCRIPTION
**Pull request by milton0825**
https://alluxio.atlassian.net/browse/ALLUXIO-2168

### CODE REVIEW

**Comment by milton0825** [comment]
alluxio-bot, check this please

**Comment by milton0825** [comment]
alluxio-bot, check this please

**Comment by milton0825** [comment]
alluxio-bot, check this please

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
add to whitelist

**Comment by ifcharming** [comment]
LGTM, thank you for your contribution to Alluxio!

**Comment by ifcharming** [comment]
Hi @milton0825 , can you please sign our [contribution license agreement](http://cla.alluxio.org/) ? It's all electronic and will take just minutes.

**Comment by aaudiber** [comment]
LGTM

**Pull request merged**
