### PR TITLE
[ALLUXIO-2076]Making function args final for isRoot and addFolderSuffixIfNotPresent

### PR DESCRIPTION
**Pull request by pysudhir**
https://alluxio.atlassian.net/browse/ALLUXIO-2076

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
LGTM

**Comment by calvinjia** [comment]
LGTM, thanks for the improvement.

**Pull request merged**
