### PR TITLE
Remove hardcoded version dependency in examples module

### PR DESCRIPTION
**Pull request by maobaolong**
Fix the security issue introduced by following link. The newest version of hadoop fix this issue. 

- http://horus.oa.com/advisory/HOSA-pzst-tfwm6u4cy 
- http://horus.oa.com/advisory/HOSA-n612-2d07um3px
- http://horus.oa.com/advisory/HOSA-yn2x-x9qulrobf
- http://horus.oa.com/advisory/HOSA-jatn-nizpv9w2u

I remove the hadoop.version property to keep consistent with parent module.

### CODE REVIEW

**Comment by LuQQiu** [comment]
@maobaolong is it a in-progress PR?

**Comment by maobaolong** [comment]
@LuQQiu No, this is ready for review, PTAL

**Comment by maobaolong** [comment]
@jiacheliu3 The description has been updated.

**Review by huanghua78 — APPROVED** [review]
Looks good.

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
@Xenorith not sure if you seen this before, all checks are green but the bot doesn't seem to realize. I'll just force merge?

> Check evaluation failed: Github action modules: (alluxio.client.**,alluxio.master.**) concluded as failure, which is not success or skipped

image

**Comment by jiacheliu3** [comment]
Lemme rerun `alluxio.client.*, alluxio.master.*` and see if the bot sees this time.

**Comment by jiacheliu3** [comment]
oops there's a conflict introduced by another PR, do you mind doing a rebase? @maobaolong Thanks!

**Comment by Xenorith** [comment]
> @Xenorith not sure if you seen this before, all checks are green but the bot doesn't seem to realize. I'll just force merge?
> 
> > Check evaluation failed: Github action modules: (alluxio.client.**,alluxio.master.**) concluded as failure, which is not success or skipped
> 
> image

yeah it's strange that there can be build failures when i make this check through the API but it's not showing here on the UI. second time i've seen it. if you can confirm this is the case for future PRs, feel free to make use of force-merge

**Comment by maobaolong** [comment]
@jiacheliu3 @huanghua78 The conflict has been resolved, PTAL.

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Pull request merged**
