### PR TITLE
Rename existing bash scripts with -bash suffix

### PR DESCRIPTION
**Pull request by Xenorith**
this is a no-op change that renames the existing bash scripts with a `-bash` suffix. 
placeholder scripts are added for `bin/alluxio`, `bin/alluxio-start.sh`, and `bin/alluxio-stop.sh` that redirect to their `-bash` script.

this is in preparation for merging https://github.com/Alluxio/alluxio/tree/golangCli to address https://github.com/Alluxio/alluxio/issues/17522
when merging this branch, the `bin/alluxio` script will be replaced completely. the start and stop script will be modified to redirect to the matching `bin/alluxio process` command to preserve some degree of backcompat.

### CODE REVIEW

**Comment by Xenorith** [comment]
for each file in `bin/`
- rename file from "abc" to "abc-bash"
- find and replace all matches for that file string in `bin/`
- create new version of "abc" that blindly redirects everything to "abc-bash"

technically `libexec/alluxio-config.sh` should also be deprecated but i will handle it separately since it is not in `bin/`

**Review by yyongycy — APPROVED** [review]
lgtm

**Comment by yyongycy** [comment]
any replacement?

**Comment by Xenorith** [comment]
> any replacement?

no change in any functionality, just renames and redirects

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Pull request merged**
