### PR TITLE
Avoid scheduling close task if connection is already closed

### PR DESCRIPTION
**Pull request by ggezer**
Closing client-side grpc streams will get pinged ponged from server for gRPC transport. This is to avoid scheduling a new task when it will exit immediately due to being closed already.

### CODE REVIEW

**Comment by gpang** [comment]
failed `alluxio.client.cli.fsadmin.command.QuorumCommandIntegrationTest.quorumRemove`

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by ZacBlanco** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please

**Pull request merged**
