### PR TITLE
[DOCFIX]Improve the Overview page

### PR DESCRIPTION
**Pull request by haoyuan**
1st pass.

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by haoyuan** [comment]
@apc999 @calvinjia 

Please also merge this into 2.0 branch. Thanks.

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Pull request merged**
