### PR TITLE
[DOCFIX] Fix broken link in overview page

### PR DESCRIPTION
**Pull request by apc999**
Fix https://github.com/Alluxio/alluxio/issues/12158

### CODE REVIEW

**Review by Xenorith — CHANGES_REQUESTED** [review]
there is also the same link in the cn version of the Overview page

**Comment by apc999** [comment]
@Xenorith addressed. PTAL

**Review by Xenorith — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.3 please

**Pull request merged**
