### PR TITLE
[ALLUXIO-2663]

### PR DESCRIPTION
**Pull request by zhangweiwei0422**
https://alluxio.atlassian.net/browse/ALLUXIO-2663

Make CountingRetryTest final. V2

### CODE REVIEW

**Comment by zhangweiwei0422** [comment]
alluxio-bot, check this please

**Comment by zhangweiwei0422** [comment]
alluxio-bot, check this please

**Comment by zhangweiwei0422** [comment]
'alluxio-bot, check this please'

**Comment by zhangweiwei0422** [comment]
https://alluxio.atlassian.net/browse/ALLUXIO-2663

**Comment by zhangweiwei0422** [comment]
'alluxio-bot, check this please

**Comment by zhangweiwei0422** [comment]
https://alluxio.atlassian.net/browse/ALLUXIO-2663

**Comment by zhangweiwei0422** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Pull request merged**
