### PR TITLE
[ALLUXIO-3086]update the vagrant module to support ansible 2.x

### PR DESCRIPTION
**Pull request by LuQQiu**
https://alluxio.atlassian.net/browse/ALLUXIO-3086

The vagrant module previously support ansible 1.9.1 and need to be updated to support ansible 2.x.

Summarization of the changes so far:

1. old: sudo: yes 
new: remote_user: root;  become:yes;  become_method:sudo

2. relative file paths in ansible 1.9.X are different from those in ansible 2.x
under deploy/vagrant/provision/roles dir.

Previously each role have files dir and tasks dir and the .yml files in tasks can directly locate .sh files in files dir. However, the way of using relative file path changed in ansible 2.x. I put the files dir under tasks dir and the paths are valid now.

Previous:
common/
-- files/
-- tasks/

Now:
common/
--tasks/
----files/

### CODE REVIEW

**Comment by uronce-cc** [comment]
@LuQQiu Thanks for the contribution. As described in https://github.com/Alluxio/alluxio/blob/master/deploy/vagrant/pip-req.txt, the ansible version supported in this module is 1.9.1, it would be great if you want to take the effort to upgrade the version to 2.x! 

I prefer to have a standalone PR to upgrade the whole vagrant module to ansible 2.x, also, if you summarize the changes with corresponding ansible doc link in the PR description, it would help the maintainers to review your PR because few of the maintainers know ansible 2.x well. What do you think? The community would appreciate and welcome your improvement to this module!

**Comment by LuQQiu** [comment]
It seems that the deploy/vagrant files do not have a lot of intersection with other Alluxio files. Using a standalone PR to update it to support ansible 2.x is a good idea!

I will open a new PR focus on updating the while vagrant module and summarize all the changes in the description part.

Thank you for your advice!

**Comment by uronce-cc** [comment]
@LuQQiu Thanks for taking this effort! Is the PR ready for review now? There is one conflict though.

**Comment by LuQQiu** [comment]
@uronce-cc Thank you! I have solved the conflicts. PTAL

**Comment by uronce-cc** [comment]
@LuQQiu Thanks for the update. For ```old: sudo: yes
new: remote_user: root; become:yes; become_method:sudo```, can we always use `remote_user: root` to be consistent? 

LGTM

**Comment by uronce-cc** [comment]
@LuQQiu I found that in http://docs.ansible.com/ansible/latest/playbooks_reuse_roles.html, the directory structure is the old one you mentioned, where "files" and "tasks" are at the same level.

**Comment by LuQQiu** [comment]
@uronce-cc 
Hi, could you help me to close this pull request?
I have found that I need to test this module with many mode (with all kinds of frameworks, local and cluster), but I do not have enough time to do so.
Besides, I don't think it is necessary and essential to upgrade the ansible version.

This question occurs just because the install python dependencies do not work successfully on my local computer so I manually install the new version of ansible.
It works good on other computers.

Thanks for you help!

**Comment by uronce-cc** [comment]
@LuQQiu Thanks, closed now.

**Pull request closed without merging**
