### PR TITLE
[SMALLFIX] Fix shell command ls sort by size (#8553)

### PR DESCRIPTION
**Pull request by LuQQiu**
Cherry pick #8553

### CODE REVIEW

**Comment by LuQQiu** [comment]
Please merge this PR

**Comment by LuQQiu** [comment]
@calvinjia Could you help merge this PR?

**Comment by LuQQiu** [comment]
@apc999 PTAL this cherry pick pr

**Comment by aaudiber** [comment]
alluxio-bot, merge this please

**Pull request merged**
