### PR TITLE
[SMALLFIX]Improve the Configration pages of the Chinese doc

### PR DESCRIPTION
**Pull request by RongGu**
Improve the Configration pages of the Chinese doc

### CODE REVIEW

**Comment by RongGu** [comment]
I should have used the [DOCFIX] as the prefix. Just be aware of that. Sry about the mistake.

**Comment by ifcharming** [comment]
LGTM

Thanks for the improvements!

**Comment by yupeng9** [comment]
@RongGu  could you resolve the conflicts?

**Comment by RongGu** [comment]
@yupeng9  Thanks for reminding me of this. I have resolved that now.

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
