### PR TITLE
Add Java 11 github-actions

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Review by Xenorith — COMMENTED** [review]
can you rename the corresponding existing github workflow yml files to `java8_*.yml`?

**Comment by bradyoo** [comment]
@Xenorith: Sure. Let me get all of these passing (with no retries) first. I may actually do folders instead and also rename the checks to contains 8 and 11.

**Comment by bradyoo** [comment]
The result looks pretty good so I fixed the name. @Xenorith looks good?

**Review by Xenorith — APPROVED** [review]

**Comment by bradyoo** [comment]
One of the things you have noticed here is that there is a bit of code copying here that I could avoid by putting java8/java11 split into the matrix. I'm intentionally not doing that because putting them in the matrix will prevent us from rerunning separately when they fail.

**Comment by Xenorith** [comment]
so what you're saying is all these problems (cleaner code, no retry runs) will be fixed if there weren't flakey tests. *shake angry fist*

**Comment by bradyoo** [comment]
No for the cleaner code because I can imagine someone committing a bug that is specific to Java 11 and want to rerun just that. For that problem, shake fist at https://github.community/t/ability-to-rerun-just-a-single-job-in-a-workflow/17234 instead. In fact, without this and lots of complaints I might end up having 19 almost duplicate files instead!

**Comment by bradyoo** [comment]
I'm worried at all the 60 second test timeouts in java 11 test so going to run it again.

**Comment by bradyoo** [comment]
Yep the tests seem to reliably hit the 60 second timeout limit on the first try :/

**Comment by bradyoo** [comment]
@gpang Just rebased with master so this should pass and probably be ready to merge.

**Review by gpang — APPROVED** [review]
LGTM

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
