### PR TITLE
Remove Alluxio EMR scripts (#9755)

### PR DESCRIPTION
**Pull request by LuQQiu**
Remove the Alluxio EMR scripts, so we don't have to republish every time
to update the scripts

original PR #9755
original commit 71d07462ace58a471f3674544fdcb33ed512615c
change-id: cid-2e33c827a1a73ef0c9e49ee033607f0f6e8a0d45

### CODE REVIEW

**Comment by LuQQiu** [comment]
@ns1123 @apc999 PTAL, thanks! This is the cherry pick PR

**Comment by ZacBlanco** [comment]
Could you update the P R description with the change is from the original commit?

**Comment by LuQQiu** [comment]
@ZacBlanco Added the change id, what's the change id use for?

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Comment by ZacBlanco** [comment]
@LuQQiu it helps us track which changes have made it from master into the separate feature branches.

**Comment by LuQQiu** [comment]
Got it, thanks for the explanation!

**Pull request merged**
