### PR TITLE
Add compaction benchmark

### PR DESCRIPTION
**Pull request by dbw9580**
### What changes are proposed in this pull request?

A benchmark to that compacts small files into a large one.

The benchmark creates several source directories containing small source files, and partitions these directories into as many batches as there are job workers in the cluster, and assigns each job worker to a batch. Each job worker uses several threads to compact small source files into a large output file. After the compaction is done, the source directories are deleted.

### CODE REVIEW

**Review by yuzhu — APPROVED** [review]
LGTM

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by jenoudet** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Comment by jenoudet** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Comment by jenoudet** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Comment by jenoudet** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please

**Pull request merged**
