### PR TITLE
Make dockerfile extendable

### PR DESCRIPTION
**Pull request by ssz1997**
1. Move env setup to a base image for better extendability
2. Remove the copy configuration during build time. If users need the files they can (and should because it's more flexible) use `--volume` to mount the files into containers at runtime.

### CODE REVIEW

**Comment by ssz1997** [comment]
@Kai-Zhang PTAL. Thanks!

**Comment by Kai-Zhang** [comment]
Why do we need a golang dependency in the base image? I thought all the golang code in the repo will be built and used as binary in the image.

**Comment by ssz1997** [comment]
@Kai-Zhang This is for the operator. We are replacing the bash script for load with go code, so to run the script we need the image to have 1. Alluxio tarball, 2. Java, 3. golang. Therefore installing go in the Alluxio image would be the easiest way.

**Comment by Kai-Zhang** [comment]
but i think the go code can be built into a binary beforehand. the compiled golang program does not need the golang development environment when it runs. so maybe it's not necessary here?

**Comment by ssz1997** [comment]
@Kai-Zhang Let's sync offline about this

**Comment by Kai-Zhang** [comment]
as what we synced, the golang code may need to be in the artifacts and delivered to the users, since there would be multiple functions and different users may need different kinds of golang programs. so the users can mount the code into the container and build it by themselves before using it.
the logic can be updated when we confirm that all users can use the same golang program, but for now the golang dependency is necessary

**Review by Kai-Zhang — APPROVED** [review]
LGTM

**Comment by ssz1997** [comment]
alluxio-bot, merge this please

**Comment by ssz1997** [comment]
alluxio-bot, merge this please

**Pull request merged**
