### PR TITLE
Use ALLUXIO_FUSE_OPTS when creating FUSE container

### PR DESCRIPTION
**Pull request by jiacheliu3**
This intends to resolve the below issues by fixing how ALLUXIO_FUSE_JAVA_OPTS is generated and exported
https://github.com/Alluxio/alluxio/issues/11899
https://github.com/Alluxio/alluxio/issues/11802

### CODE REVIEW

**Comment by jiacheliu3** [comment]
Verified by tests and by @cheyang . This PR is good to go @madanadit PTAL, thanks!

**Comment by apc999** [comment]
@madanadit  can you take a look? thanks

**Comment by apc999** [comment]
also this patch is verified by Chao Wang from Microsoft

**Comment by madanadit** [comment]
Thanks @jiacheliu3 and others for verifying.

**Comment by madanadit** [comment]
alluxio-bot, merge this please.

**Comment by madanadit** [comment]
@jiacheliu3 all helm chart changes from 0.6.7 up to this change look like bug fixes. can you cherry-pick these changes to `branch-2.3` manually? thx

@apc999 not sure how you are managing `branch-2.3-fuse`. if you are not merging `branch-2.3` periodically, let us know if you feel a cherry-pick to `branch-2.3-fuse` will be useful for your effort. thx

**Comment by jiacheliu3** [comment]
alluxio-bot, cherry-pick this to branch-2.3 please.

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.3-fuse please

**Comment by apc999** [comment]
manually updated branch-2.3-fuse . thanks adit

**Pull request merged**
