### PR TITLE
Add master_ufs_metadata_access_count metric

### PR DESCRIPTION
**Pull request by kuszz**
#13734

### What changes are proposed in this pull request?

Add a counter metric in InodeSyncStream, increase it when loadMetadata. And initialize it in DefaultFileSystemMaster.

### Why are the changes needed?

We want to add a metric master_ufs_metadata_access_count and now we can not get ufs metadata access num info

### Does this PR introduce any user facing changes?

Users can get a new metric

### CODE REVIEW

**Review by maobaolong — APPROVED** [review]
It LGTM, thanks for the contribution. @yuzhu  Please take another look.

**Review by yuzhu — APPROVED** [review]
LGTM, thanks

**Review by apc999 — COMMENTED** [review]
@maobaolong @kuszz  @yuzhu  is this (https://github.com/Alluxio/alluxio/pull/13735/files#diff-885d20a474b15524a5e7f1de04d3fbe28e10bc01fd7e5630eef5e004402b9f11R756) the only place to access UFS metadata? I don't think so.

**Comment by yuzhu** [comment]
@apc999 It depends on what we are trying to measure.  

If we are measuring the number of metadata accesses to the ufs, the best place to perform this count might be inside UfsStatusCache class, because that's where we actually access ufs. we can accumulate how many accesses to the ufs we do in each UfsStatusCache and then aggregate them together. 

However, if we are counting how many files we synced, then this location or `syncInodeMetadata` might be a good place to perform the count. 

Those two measurements are different because with one listStatus call to the ufs, we can sync many files.

**Comment by apc999** [comment]
Can you take a look at `UnderFileSystemWithLogging`

**Comment by maobaolong** [comment]
@kuszz You can reference this PR https://github.com/Alluxio/alluxio/pull/13671

**Comment by kuszz** [comment]
@yuzhu If the ufsStatus==null, should we count the UFS_METADATA_ACCESS?
try (CloseableResource<UnderFileSystem> ufsResource = resolution.acquireUfsResource()) {
      UnderFileSystem ufs = ufsResource.get();
      UfsStatus ufsStatus = ufs.getStatus(ufsUri.toString());
      Metrics.UFS_METADATA_ACCESS.inc();  // Should put here?
      if (ufsStatus == null) {
        mAbsentCache.addSinglePath(path);
        return null;
      }
      Metrics.UFS_METADATA_ACCESS.inc();  // Or put here?
      ...
}

**Comment by yuzhu** [comment]
@kuszz for your specific question, we should also increment when ufsStatus is null. 
My higher level question is what are we trying to measure? Are we measuring how many metadata accesses we do as part of metadata sync? or in all situations? 
If the first one is the goal, then measuring here is fine. If the second one is the goal, we should instrument `UnderFileSystemWithLogging`  class as suggested by @apc999

**Comment by kuszz** [comment]
> @kuszz for your specific question, we should also increment when ufsStatus is null.
> My higher level question is what are we trying to measure? Are we measuring how many metadata accesses we do as part of metadata sync? or in all situations?
> If the first one is the goal, then measuring here is fine. If the second one is the goal, we should instrument `UnderFileSystemWithLogging` class as suggested by @apc999
Thanks, we want to measure the file num sync, and I have wondered after read codes, and so sorry I have hesitated how to reply so that forget to reply, very sorry...

**Pull request closed without merging**
