### PR TITLE
[SMALLFIX]update docs/cn/Getting-Started.md

### PR DESCRIPTION
**Pull request by DSKtwilight**

### CODE REVIEW

**Comment by DSKtwilight** [comment]
> @LuQQiu
> 
> > @DSKtwilight why we want to change all the `奖励` to `*`? `奖励` is the translation of `Bonus` in our English documentation. We use it to let users know that those functionalities are not the basic requirements or must-do. If users want to walk deeper into Alluxio, they can try those `bonus` functionality. Thanks for your contribution!
> 
> `奖励` is not a good translation for this situation, and looks a little confusing. `*` sometimes means uncessary, and can be ignored in Chinese culture. I think a better choice can be `可选` which means `optional`.

Could you please tell me why the pull request is not merged?

**Comment by DSKtwilight** [comment]
> Hi @DSKtwilight, thanks for your contribution!
> 
> In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://cla.alluxio.org). It's all electronic and will take just minutes.

**Comment by LuQQiu** [comment]
@apc999 what's your opinion about `奖励` vs `可选` vs `*`?

**Comment by aaudiber** [comment]
ping @apc999

**Comment by apc999** [comment]
It is already translated as "加分项" in the latest master branch which I am ok with. Close this PR now.

**Pull request closed without merging**
