### PR TITLE
[DOCFIX] Correct relative doc link in Journal.md

### PR DESCRIPTION
**Pull request by jiacheliu3**

### CODE REVIEW

**Comment by bf8086** [comment]
alluxio-bot, merge this please.

**Comment by bf8086** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please.

**Comment by jiacheliu3** [comment]
@bf8086 Do you mind doing the auto cherry-pick again pls?

**Comment by jiacheliu3** [comment]
The last attempt didn't succeed as #11285 failed to go into 2.2. Now that #11285 is manually picked into 2.2, this fix can be applied to "fix" it.

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please

**Pull request merged**
