### PR TITLE
[DOCFIX]Modify some inappropriate descriptions in FAQ.md

### PR DESCRIPTION
**Pull request by jianghuazhu**
### What changes are proposed in this pull request?
The purpose of this pr is to try to fix some comments that were out of place in FAQ.md and make it more complete.

### Why are the changes needed?
This needs to be modified, otherwise it will affect the user's use.

### Does this PR introduce any user facing changes?
The purpose of this pr is to make it easier for users to use alluxio.

### CODE REVIEW

**Comment by jianghuazhu** [comment]
I have signed the CLA and have sent it to cla@alluxio.org.

**Comment by jianghuazhu** [comment]
Can you help review this pr, @beinan  @rongrong  @maobaolong .
Thank you very much.

**Review by HelloHorizon — APPROVED** [review]
Thank you for you contribution @jianghuazhu

**Comment by jianghuazhu** [comment]
Thanks @HelloHorizon .

**Pull request merged**
