### PR TITLE
Fix failures in mem page store when zero copy enabled

### PR DESCRIPTION
**Pull request by beinan**
### What changes are proposed in this pull request?
Fix failures in mem page store when zero copy enabled

### Why are the changes needed?
Worker crash when using mem page store

### Does this PR introduce any user facing changes?
no

### CODE REVIEW

**Review by jja725 — APPROVED** [review]
the update seems correct to me. But could you elaborate on why we would have worker crash?

**Comment by dbw9580** [comment]
> the update seems correct to me. But could you elaborate on why we would have worker crash?

Probably because we are using `ByteBufferTargetBuffer` in `PagedBlockReader` to get pages from page store, and it does not support getting a byte array out of it.

**Comment by beinan** [comment]
> > the update seems correct to me. But could you elaborate on why we would have worker crash?
> 
> Probably because we are using `ByteBufferTargetBuffer` in `PagedBlockReader` to get pages from page store, and it does not support getting a byte array out of it.

yes, exactly, thanks for the reply!

**Comment by beinan** [comment]
alluxio-bot, merge this please.

**Pull request merged**
