### PR TITLE
Update Performance-Tuning.md

### PR DESCRIPTION
**Pull request by bf8086**
Updated configuration properties and added some notes.

### CODE REVIEW

**Comment by bf8086** [comment]
Jenkins, test this please.

**Comment by bf8086** [comment]
Jenkins, test this please.

**Comment by bf8086** [comment]
@calvinjia PTAL.

**Comment by bf8086** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please.

**Pull request merged**
