### PR TITLE
Provide a slf4jSink to sink metrics to a logger

### PR DESCRIPTION
**Pull request by maobaolong**

### CODE REVIEW

**Comment by apc999** [comment]
Thanks for the contribution @maobaolong .
@calvinjia I remember there is license compliance requirement here, can you help @maobaolong  check if it is met?

**Comment by calvinjia** [comment]
@maobaolong Thanks for adding this new functionality! There are not any additional dependencies added here, I don't think there should be any licensing concern.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by maobaolong** [comment]
@apc999 @calvinjia  the license header has been added to the new file,  thank you for your review

**Pull request merged**
