### PR TITLE
Reduce the CPU usage of the alluxio master process

### PR DESCRIPTION
**Pull request by witgo**
[`./profiler.sh -d 30 pid`](https://github.com/jvm-profiling-tools/async-profiler) => 
```
          ns  percent  samples  top
  ----------  -------  -------  ---
 15747991110   52.61%     1564  gettimeofday
 12484184818   41.70%     1238  [unknown]
   804458218    2.69%       80  alluxio.master.metastore.caching.Cache$EvictionThread.evictToLowWaterMark
   333278940    1.11%       33  os::javaTimeMillis()
   160014616    0.53%       16  alluxio.master.metastore.caching.Cache$EvictionThread.run
    65950919    0.22%        8  KlassScanClosure::do_klass(Klass*)
    40337398    0.13%        5  FastScanClosure::do_oop(oopDesc**)
    31711313    0.11%        3  __pthread_cond_timedwait
    22996059    0.08%        3  ClassLoaderData::oops_do(OopClosure*, KlassClosure*, bool)
    21247918    0.07%        1  __pthread_disable_asynccancel
    17538526    0.06%        2  frame::sender(RegisterMap*) const
    11612687    0.04%        1  jlong_disjoint_arraycopy
    11407171    0.04%        1  Unsafe_Park
    10902626    0.04%        1  io.netty.channel.epoll.EpollEventLoop.run
    10756523    0.04%        1  __pthread_getspecific
    10734461    0.04%        1  java.util.concurrent.locks.AbstractQueuedSynchronizer.hasQueuedPredecessors
    10585585    0.04%        1  java.util.stream.AbstractPipeline.wrapAndCopyInto
    10575251    0.04%        1  BlockOffsetArrayContigSpace::block_start_unsafe(void const*) const
    10503642    0.04%        1  java.lang.Thread.interrupted
    10491283    0.04%        1  /lib/x86_64-linux-gnu/libc-2.27.so
    10475662    0.03%        1  _init
    10455985    0.03%        1  Parker::park(bool, long)
    10425816    0.03%        1  java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos
    10031570    0.03%        1  OopMapSet::oops_do(frame const*, RegisterMap const*, OopClosure*)
     9999568    0.03%        1  AllocTracer::send_allocation_in_new_tlab_event(KlassHandle, unsigned long, unsigned long)
     9999125    0.03%        1  InstanceKlass::allocate_instance(Thread*)
     9019689    0.03%        1  CollectedHeap::oop_extra_words()
     8368977    0.03%        1  SafepointSynchronize::do_cleanup_tasks()
     8065174    0.03%        1  ContiguousSpace::block_size(HeapWord const*) const
     7797838    0.03%        1  InstanceKlass::oop_oop_iterate_nv(oopDesc*, FastScanClosure*)
     7751152    0.03%        1  mprotect
     6361080    0.02%        1  SymbolPropertyTable::oops_do(OopClosure*)

```

### CODE REVIEW

**Comment by gpang** [comment]
@witgo Thanks! Is there a profile before this change and a profile after this change?

**Comment by witgo** [comment]
```

          ns  percent  samples  top
  ----------  -------  -------  ---
    56309766    8.38%        5  __vdso_clock_gettime
    54289631    8.08%        5  arch_local_irq_restore_[k]
    45182252    6.73%        4  arch_local_irq_enable_[k]
    22649522    3.37%        1  java.lang.Thread.interrupted
    22632080    3.37%        2  arch_local_irq_disable_[k]
    22530732    3.35%        2  Unsafe_Park
    22462062    3.34%        2  java_lang_Thread::set_thread_status(oopDesc*, java_lang_Thread::ThreadStatus)
    22419550    3.34%        2  read_hv_clock_tsc_[k]
    22397279    3.33%        2  java.util.concurrent.Semaphore.tryAcquire
    11379087    1.69%        1  plist_del_[k]
    11377213    1.69%        1  java.util.concurrent.locks.LockSupport.parkNanos
    11371911    1.69%        1  Parker::park(bool, long)
    11357446    1.69%        1  syscall_return_slowpath_[k]
    11328683    1.69%        1  pthread_cond_init@@GLIBC_2.3.2
    11324802    1.69%        1  __pthread_cond_timedwait
    11322300    1.69%        1  __lll_unlock_wake
    11291233    1.68%        1  posix_ktime_get_ts_[k]
    11225665    1.67%        1  futex_wait_queue_me_[k]
    11222114    1.67%        1  Thread::is_interrupted(Thread*, bool)
    11190106    1.67%        1  java.util.concurrent.locks.AbstractQueuedSynchronizer.hasQueuedPredecessors
    11185519    1.67%        1  ktime_get_ts64_[k]
    11070928    1.65%        1  io.grpc.internal.CompositeReadableBuffer$1.readInternal
    10898087    1.62%        1  io.grpc.netty.NettyServerStream.transportState
    10887304    1.62%        1  com.google.protobuf.Utf8$UnsafeProcessor.decodeUtf8
    10885670    1.62%        1  __raw_spin_unlock_irq_[k]
    10873209    1.62%        1  java.util.stream.Sink$ChainedReference.begin
    10856866    1.62%        1  UseCountComputer::visit(Instruction**)
    10850728    1.62%        1  nmethodLocker::lock_nmethod(nmethod*, bool)
    10846321    1.61%        1  DebugInformationRecorder::find_sharable_decode_offset(int) [clone .part.26]
    10815049    1.61%        1  State::_sub_Op_ConvI2L(Node const*)
    10804051    1.61%        1  Node::pinned() const
    10791115    1.61%        1  __list_add_[k]
    10771387    1.60%        1  alluxio.concurrent.jsr.ForkJoinPool.runWorker
    10764528    1.60%        1  ciObjectFactory::get_symbol(Symbol*)
    10752053    1.60%        1  io.netty.util.internal.ObjectUtil.checkNotNull
    10695643    1.59%        1  CodeHeap::allocate(unsigned long, bool)
    10658329    1.59%        1  ciObjectFactory::get_metadata(Metadata*)
    10645638    1.58%        1  InlineCacheBuffer::contains(unsigned char*)
    10595018    1.58%        1  LIRGenerator::walk(Instruction*)
    10394761    1.55%        1  PhaseCFG::build_dominator_tree()
    10356943    1.54%        1  IndexSetIterator::advance_and_next()
    10007366    1.49%        1  Node::unique_ctrl_out()
     9998464    1.49%        1  RegMask::clear_to_sets(int)
     9983842    1.49%        1  PhaseChaitin::build_ifg_physical(ResourceArea*)

```

**Comment by calvinjia** [comment]
@witgo Thanks for the fix, I think the huge difference in performance might be OS dependent, but in general we should use `nanotime` for calculating time differences.

**Comment by calvinjia** [comment]
@witgo Could you please fix the checkstyle errors?
```
/usr/src/alluxio/core/server/master/src/main/java/alluxio/master/metastore/caching/Cache.java:25:8: error: Unused import - java.time.Duration.
/usr/src/alluxio/core/server/master/src/main/java/alluxio/master/metastore/caching/Cache.java:26:8: error: Unused import - java.time.Instant.
```

**Comment by witgo** [comment]
@calvinjia done

**Comment by calvinjia** [comment]
@witgo Thanks for addressing the comments, code wise this PR is good to go. Could you resolve the `PR-EMAIL` check (see the message from `alluxio-bot`) so we can properly credit you with the contribution?

**Comment by calvinjia** [comment]
alluxio-bot, check this please.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
@witgo Thanks for the contribution!

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please.

**Pull request merged**
