### PR TITLE
Add hadoop3 jar to the artifacts

### PR DESCRIPTION
**Pull request by Kai-Zhang**
### What changes are proposed in this pull request?
Add the alluxio hadoop3 jar client to the artifacts

### Why are the changes needed?
Some users may want to use hadoop3

### Does this PR introduce any user facing changes?
no

### CODE REVIEW

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks!

**Comment by jiacheliu3** [comment]
fyi @maobaolong

**Comment by Kai-Zhang** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
@Kai-Zhang could you double check if the new generate-artifact is including hadoop 3.x jar? Thanks a lot!

**Pull request merged**
