### PR TITLE
[ALLUXIO-1741] Improve the shell command of 'copyFromLocal'

### PR DESCRIPTION
**Pull request by ConeyLiu**
When run `bin/alluxio fs copyFromLoca /src /dsc` , even though set `alluxio.user.lineage.enabled	=true`.
Restart the alluxio for some reason. When you try to get the file just copied, you will get a error. Such as `Error: File /data.txt is not available Block 150994944 is not available in Alluxio`
So, to improve the shell command. I think when set 'alluxio.user.lineage.enabled=true', the file which copied should be persisted to an underlying fs.

### CODE REVIEW

**Comment by yupeng9** [comment]
Hi @ConeyLiu I don't think the error is related to the configuration of `alluxio.user.lineage.enabled `, because to use lineage, you need to create lineage first. `copyFromLocal` command only copies file into Alluxio space, and you need to run the `persist` command if you want it to be persisted.

**Comment by ConeyLiu** [comment]
Hi @yupeng9. Mayb the description is not clear enough.
The PR names "Improve the shell command of `copyFromLocal`", not names fixs.
A user uses `copyFromLocal` copy a file from local to Alluxio. The destination file will be missing when restart the Alluxion system. This is ok if don't use lineage. But if lineage has been set up, the file should not missing when the system restart. As described in the paper of `tachyon`, we should keep the first file in the under fs synchronously. And this is convenient for users.

**Comment by yupeng9** [comment]
I think I understood what you meant. However, the lineage is not in effect if the users do not create lineage first. In fact, you can read more about lineage at http://alluxio.org/documentation/en/Lineage-API.html.

The destination file is missing after restart because the data in memory was wiped out. But enabling lineage doesn't mean changing all the write behavior to synchronous persist. 

Does this make sense to you?

**Comment by ConeyLiu** [comment]
Yeah, I just want to make convenient for users. Because the lineage seem has little use for users.

**Pull request closed without merging**
