### PR TITLE
[ALLUXIO-1736] Add logging in BaseFileSystem.

### PR DESCRIPTION
**Pull request by ConeyLiu**
Because Alluxio is a filesystem, so logging which file or directory has created is useful to top applications.
Now the log records is more unreadable. So I add logging in BaseFilySystem.

### CODE REVIEW

**Comment by apc999** [comment]
+1 LGTM

**Comment by gpang** [comment]
Will this be too noisy, or is it ok since it is on the user/client side?

**Comment by apc999** [comment]
@gpang , this logging is at per file level. I feel it is probably fine for now since it is on user side as you mentioned. in the long run, we probably want a better logging story e.g., introducing audit log.

**Comment by gpang** [comment]
LGTM

**Pull request merged**
