### PR TITLE
[SMALLFIX] Fix Preconditions.checkNotNull in BlockStoreMeta.java

### PR DESCRIPTION
**Pull request by chenminzoe**

### CODE REVIEW

**Comment by chenminzoe** [comment]
alluxio-bot , please check it.

**Comment by chenminzoe** [comment]
alluxio-bot, check this please

**Comment by chenminzoe** [comment]
jenkins, test this please.

**Comment by chenminzoe** [comment]
alluxio-bot, check this please

**Comment by chenminzoe** [comment]
Jenkins, test this please.

**Comment by chenminzoe** [comment]
I cannot figure out, why would this failed ? Can anyone help me? @gpang

**Comment by aaudiber** [comment]
Jenkins, test this please

**Comment by yupeng9** [comment]
Jenkins, test this please

**Pull request merged**
