### PR TITLE
Fix Journal doc for ratis [WIP]

### PR DESCRIPTION
**Pull request by LuQQiu**

### CODE REVIEW

**Comment by LuQQiu** [comment]
alluxio-bot, test this with java 11 please

**Comment by LuQQiu** [comment]
jenkins, test this with java 11 please

**Comment by LuQQiu** [comment]
jenkins, test this with java 11 please

**Comment by bf8086** [comment]
It looks like the PR does not trigger the full build?

**Comment by LuQQiu** [comment]
@yuzhu Any requirements for triggering the java 11 build?
I ran the `jenkins, test this with java 11 please` which doesn't work

**Comment by yuzhu** [comment]
i think it is still triggered but we don't show the status here. once we move everything to github actions, you will see results here.

**Comment by LuQQiu** [comment]
jenkins, test this with java 11 please

**Comment by LuQQiu** [comment]
21:21:25.634 [ERROR] alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTest.copySnapshotToMaster  Time elapsed: 168.847 s  <<< ERROR!
alluxio.exception.FileAlreadyExistsException: /dir/file1981 already exists
	at alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTest.copySnapshotToMaster(EmbeddedJournalIntegrationTest.java:129)

21:21:25.635 [ERROR] alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTest.copySnapshotToMaster  Time elapsed: 170.413 s  <<< ERROR!
alluxio.exception.FileAlreadyExistsException: /dir/file1992 already exists
	at alluxio.server.ft.journal.raft.EmbeddedJournalIntegrationTest.copySnapshotToMaster(EmbeddedJournalIntegrationTest.java:129)

21:21:26.122 [INFO]

**Comment by LuQQiu** [comment]
jenkins, test this with java 11 please

**Comment by LuQQiu** [comment]
jenkins, test this with java 11 please

**Pull request closed without merging**
