### PR TITLE
[SMALLFIX] Consolidate conf validation from different entry point to its init process

### PR DESCRIPTION
**Pull request by apc999**
So configuration is forced to be checked.

### CODE REVIEW

**Comment by calvinjia** [comment]
LGTM, is there already unit test coverage for this?

**Comment by uronce-cc** [comment]
LGTM

**Comment by apc999** [comment]
@calvinjia  No unit test yet. Actually, currently it is not even possible to insert invalid properties to `Configuration` singleton as merge or set (only two ways to add to `Configuration`) are both guarded by validation from `PropertyKey.isValid()`. So  I am not even sure if we need to keep `Configuration.validate`. What do you think?

**Comment by calvinjia** [comment]
@apc999 Let's open another ticket for investigating if it is ok to remove `validate`. I think this change is an improvement and will make that easier either way.

**Pull request merged**
