### PR TITLE
[WIP] Avoid unnecessary get worker infos

### PR DESCRIPTION
**Pull request by hustnn**

### CODE REVIEW

**Comment by hustnn** [comment]
@apc999 Can reduce resource usage in terms of CPU and network usage when the scale becomes larger.

**Comment by apc999** [comment]
@hustnn  can you sign the CLA : https://cla.alluxio.org/?

**Comment by hustnn** [comment]
@apc999  I already signed.

**Comment by yuzhu** [comment]
@hustnn could you address the checkstyle errors below? 
```
/usr/src/alluxio/core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java:175: error: Line is longer than 100 characters (found 112).
/usr/src/alluxio/core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java:202:28: error: '&&' should be on a new line.
/usr/src/alluxio/core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java:203: error: Line is longer than 100 characters (found 117).
/usr/src/alluxio/core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java:208: error: Line is longer than 100 characters (found 106).
/usr/src/alluxio/core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java:227:5: error: '}' at column 5 should be on the same line as the next part of a multi-block statement.```

**Comment by hustnn** [comment]
@yuzhu Thanks. Fixed.

**Comment by hustnn** [comment]
btw, why I cannot see this checkstyle error when building locally?

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
@hustnn did you accidentally have '-Dcheckstyle.skip=true' flag in your mvn build? I always run `mvn checkstyle:checkstyle` explicitly to see the checkstyle errors. Btw, it looks like there are some failed tests? 
```Failed tests: 
alluxio.client.block.AlluxioBlockStoreTest.getInStreamPersistedAndInAlluxioFallbackToUFS(alluxio.client.block.AlluxioBlockStoreTest)
  Run 1: AlluxioBlockStoreTest.getInStreamPersistedAndInAlluxioFallbackToUFS:410->testGetInStreamFallback:520 expected:<WorkerNetAddress{host=worker-1, rpcPort=0, dataPort=0, webPort=0, domainSocketPath=, tieredIdentity=null}> but was:<WorkerNetAddress{host=worker-2, rpcPort=0, dataPort=0, webPort=0, domainSocketPath=, tieredIdentity=null}>
  Run 2: AlluxioBlockStoreTest.getInStreamPersistedAndInAlluxioFallbackToUFS:410->testGetInStreamFallback:520 expected:<WorkerNetAddress{host=worker-1, rpcPort=0, dataPort=0, webPort=0, domainSocketPath=, tieredIdentity=null}> but was:<WorkerNetAddress{host=worker-2, rpcPort=0, dataPort=0, webPort=0, domainSocketPath=, tieredIdentity=null}>
Tests in error: 
alluxio.client.block.AlluxioBlockStoreTest.getInStreamMissingBlock(alluxio.client.block.AlluxioBlockStoreTest)
  Run 1: AlluxioBlockStoreTest.getInStreamMissingBlock:338 » NotFound Block 0 is unavai...
  Run 2: AlluxioBlockStoreTest.getInStreamMissingBlock:338 » NotFound Block 0 is unavai...
alluxio.client.block.AlluxioBlockStoreTest.getInStreamNoWorkers(alluxio.client.block.AlluxioBlockStoreTest)
  Run 1: AlluxioBlockStoreTest.getInStreamNoWorkers:325 » Unavailable No Alluxio worker...
  Run 2: AlluxioBlockStoreTest.getInStreamNoWorkers:325 » Unavailable No Alluxio worker...
alluxio.client.block.AlluxioBlockStoreTest.getInStreamPersistedFallbackToLeastRecentlyFailed(alluxio.client.block.AlluxioBlockStoreTest)
  Run 1: AlluxioBlockStoreTest.getInStreamPersistedFallbackToLeastRecentlyFailed:423->testGetInStreamFallback:518 » Unavailable
  Run 2: AlluxioBlockStoreTest.getInStreamPersistedFallbackToLeastRecentlyFailed:423->testGetInStreamFallback:518 » Unavailable```

**Comment by hustnn** [comment]
@yuzhu 

Will `when(mMasterClient.getWorkerInfoList()).thenReturn(Arrays.stream(workers)` in test case set the result when `getEligibleWorkers`

**Comment by yuzhu** [comment]
@hustnn yes, basically any time the code calls `mMasterClient.getWorkerInfoList()`, it will return `Arrays.stream(workers)`, since `getEligibleWorkers` calls `mMasterClient.getWorkerInfoList()`, it will also return `Arrays.stream(workers)`

**Comment by hustnn** [comment]
@yuzhu I see. Then it is strange, Can you help to take a look? From my understanding, the test should read worker-1.

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by calvinjia** [comment]
@hustnn Thanks for the performance improvement! I think another thing we can do is reduce the cost of `getWorkerInfoList` by both improving the server side synchronization as well as not fetching the entire worker info list from the client.

**Comment by calvinjia** [comment]
jenkins, test this please.

**Comment by calvinjia** [comment]
@hustnn Some of the unit tests need to be modified, could you take a look?

**Comment by hustnn** [comment]
> @hustnn Thanks for the performance improvement! I think another thing we can do is reduce the cost of `getWorkerInfoList` by both improving the server side synchronization as well as not fetching the entire worker info list from the client.

Do you already have some idea on it?

**Comment by hustnn** [comment]
> @hustnn Some of the unit tests need to be modified, could you take a look?

Sure. I have looked at the test case before. Haven't figure out the reason why it failed at that time.

**Pull request closed without merging**
