### PR TITLE
[DOCFIX] Update NFS UFS doc

### PR DESCRIPTION
**Pull request by rastogiasr**

### CODE REVIEW

**Review by Xenorith — APPROVED** [review]

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, merge this to branch-2.5 please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please

**Pull request merged**
