### PR TITLE
[ALLUXIO-2743] Followup to refactor UFS related classes

### PR DESCRIPTION
**Pull request by apc999**
https://alluxio.atlassian.net/browse/ALLUXIO-2743

Changes include:

- Rename `UnderFileSystemRegistry` to `UnderFileSystemFactoryRegistry` as it is really the collection of UFS factory instances
- Rename `UnderFileSystem.Factory#get` to `UnderFileSystem.Factory#create` since no caching is used now for these methods
- Move `UnderFileSystemRegistry#create` to `UnderFileSystem.Factory#create` as this method is really about create UFS.

### CODE REVIEW

**Comment by jsimsa** [comment]
@apc999 please fix the build (Mesos)

**Comment by apc999** [comment]
@jsimsa fixed. PTAL

**Comment by jsimsa** [comment]
@apc999 please resolve merge conflicts

**Comment by apc999** [comment]
@jsimsa updated

**Comment by jsimsa** [comment]
@apc999 please fix the build

**Comment by apc999** [comment]
Jenkins, test this please

**Pull request merged**
