### PR TITLE
[ALLUXIO-2270] delete all 'the' in the line. #4154

### PR DESCRIPTION
**Pull request by smartxingyu**
https://alluxio.atlassian.net/browse/ALLUXIO-2270

### CODE REVIEW

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
ok to test

**Comment by aaudiber** [comment]
Jenkins, add to whitelist

**Comment by apc999** [comment]
LGTM

**Pull request merged**
