### PR TITLE
Make copy & move return list of tasks

### PR DESCRIPTION
**Pull request by jja725**
### What changes are proposed in this pull request?

Make copy & move return list of tasks

### Why are the changes needed?
make worker busy
### Does this PR introduce any user facing changes?
na

### CODE REVIEW

**Review by lucyge2022 — APPROVED** [review]
LGTM

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Comment by jja725** [comment]
@Xenorith needs to cherry-pick but not sure which branch we are working on

**Comment by jja725** [comment]
alluxio-bot, cherry-pick this to branch-3-0.0.x please

**Pull request merged**
