### PR TITLE
[ALLUXIO-2795] Use precondition check chaining in CommandLineJobInfo

### PR DESCRIPTION
**Pull request by wanghaocun**
https://alluxio.atlassian.net/browse/ALLUXIO-2795

The preconditions check in setCommand(String command) can be chained to save a statement:
mCommand = Preconditions.checkNotNull(command);

### CODE REVIEW

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
@wanghaocun Thanks for the contribution, please fix the email issue raised by `alluxio-bot`

**Comment by yupeng9** [comment]
@wanghaocun any update on this?

**Comment by yupeng9** [comment]
@wanghaocun  feel free to reopen this PR after you fix the email issue.

**Pull request closed without merging**
