### PR TITLE
Fix some codestyle

### PR DESCRIPTION
**Pull request by bzheng888**
### What changes are proposed in this pull request?
Code style problem
### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
No

### CODE REVIEW

**Comment by maobaolong** [comment]
@bzheng888 Good catch, look forward further contribution in FUSE module from you. LGTM.

**Review by maobaolong — APPROVED** [review]
@bzheng888 Good catch, look forward further contribution in FUSE module from you. LGTM.

**Comment by maobaolong** [comment]
@LuQQiu Would you please take another look?

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks!

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
