### PR TITLE
[ALLUXIO-2276] Fix javadoc in BlockStore.java

### PR DESCRIPTION
**Pull request by magiclogy-**
https://alluxio.atlassian.net/browse/ALLUXIO-2276
modified by MG1633034
Correct "meta data" in this file to "metadata".

### CODE REVIEW

**Comment by aaudiber** [comment]
jenkins, ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
