### PR TITLE
Increase worker heartbeat time for asyncCache tests

### PR DESCRIPTION
**Pull request by luzhang6**
Currently the test asyncCacheFirstBlock is flaky, when the test is running extremely slow, and after the worker reports the newly cached blocks to master, the test will fail. The original time interval is 1000ms and may be small. Increasing the worker heartbeat in the test to 2000ms may allow the test to pass before worker reporting to master.

### CODE REVIEW

**Comment by luzhang6** [comment]
@dbw9580 Can you review this? thanks

**Review by dbw9580 — APPROVED** [review]
Lgtm

**Comment by luzhang6** [comment]
@dbw9580 Can you merge this PR? thanks

**Comment by dbw9580** [comment]
I have to ask @jiacheliu3 to merge this :)

**Comment by luzhang6** [comment]
Thanks! @dbw9580 @jiacheliu3

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.9 please

**Pull request merged**
