### PR TITLE
Relocate erasure coding

### PR DESCRIPTION
**Pull request by yuzhu**
This fixes classloading issue related to erasure coding by making sure the UFS has a private copy of the class.

### CODE REVIEW

**Comment by yuzhu** [comment]
@ns1123 FYI

**Review by gpang — COMMENTED** [review]
@yuzhu I *think* this is good, but I'm not completely sure.

@apc999 do you have any thoughts on this?

**Comment by yuzhu** [comment]
@apc999 ping?

**Review by gpang — APPROVED** [review]
LGTM

**Review by LuQQiu — APPROVED** [review]

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
