### PR TITLE
Change the way get "index"

### PR DESCRIPTION
**Pull request by bzheng888**

### CODE REVIEW

**Comment by LuQQiu** [comment]
@bzheng888 Thanks for contributing! Looks like our PR-EMAIL check failed 
```
@alluxio-bot
PR-EMAIL — Email not linked to a valid Github account
```
can you help check if your account is linked with an email address?

**Review by LuQQiu — APPROVED** [review]
LGTM! Please help link your github account to an email. Otherwise, the PR merge function will be blocked, thanks!

**Review by apc999 — APPROVED** [review]

**Comment by maobaolong** [comment]
@LuQQiu @apc999 Thank you for the help. I'll help @bzheng888 to resolve the issue about email.

**Review by maobaolong — APPROVED** [review]
LGTM

**Comment by bzheng888** [comment]
> @bzheng888 Thanks for contributing! Looks like our PR-EMAIL check failed
> 
> ```
> @alluxio-bot
> PR-EMAIL — Email not linked to a valid Github account
> ```
> 
> can you help check if your account is linked with an email address?

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
