### PR TITLE
[DOCFIX] Update System Configuration to Configuration in docs/en/Web-…

### PR DESCRIPTION
**Pull request by summer9090**
This PR fixes the issue "ALLUXIO-2008" in JIRA.

Update "System Configuration" to "Configuration" in docs/en/Web-Interface.md to be consistent with the Web UI navigation bar

### CODE REVIEW

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
Thanks for the contribution @summer9090 ! Seems like the commits are associated with another github account "PingLi"? is this intended? 

Here are instructions to get your commits associated with your github account: https://help.github.com/articles/setting-your-email-in-git/#commits-on-github-arent-linking-to-my-account

**Comment by summer9090** [comment]
@ifcharming Sorry, I have changed another file - docs/en/Running-Alluxio-on-EC2-Yarn.md to update "Browse File System" to "Browse", but I commit to the same branch

**Comment by summer9090** [comment]
Thanks for your advice

**Comment by apc999** [comment]
LGTM

**Pull request merged**
