### PR TITLE
Implement non-intrusive locking for backups

### PR DESCRIPTION
**Pull request by ggezer**
This is to eliminate the impact of backups when the leader has hung
RPCs.
Backup not backing off from an exclusive lock acquisition was causing a
pile of shared acquisition attempts.

pr-link: Alluxio/alluxio#11478
change-id: cid-780e620bf903dcb69a3e375c6bbd937b6dfb43db

### CODE REVIEW

**Comment by ggezer** [comment]
> TriggeredCheckpointTest.ufsJournal

**Comment by ggezer** [comment]
jenkins, test this please

**Comment by ggezer** [comment]
alluxio-bot, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by ggezer** [comment]
alluxio-bot, merge this please

**Pull request merged**
