### PR TITLE
Prevent async eviction of ASYNC_THROUGH because of race condition

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Comment by yuzhu** [comment]
@calvinjia could you take a look, particularly the second commit, as I am not very familiar with the original PR so I might miss certain cases where we need to set pin_on_create flag.

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by calvinjia** [comment]
@yuzhu Are you planning to cherry-pick the other fixes and performance improvements as well? (ie. https://github.com/Alluxio/alluxio/pull/9052, https://github.com/Alluxio/alluxio/pull/9335).

**Comment by yuzhu** [comment]
@calvinjia maybe #9052 ? #9335 sounds more like a feature than a bug fix right?

**Pull request closed without merging**
