### PR TITLE
[SMALLFIX] Use static test imports in TimeoutRefreshTest

### PR DESCRIPTION
**Pull request by Asalea**
Use static imports for standard test utilities in /alluxio/core/common/src/test/java/alluxio/refresh/TimeoutRefreshTest.java

### CODE REVIEW

**Comment by newnius** [comment]
> /usr/src/alluxio/core/common/src/test/java/alluxio/refresh/TimeoutRefreshTest.java:19: error: Extra newline

**Comment by Asalea** [comment]
alluxio-bot, check this please.

**Comment by Asalea** [comment]
Jenkins, test this please.

**Comment by Asalea** [comment]
Jenkins, test this please.

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
