### PR TITLE
Invalid parent cache if it does not have a known child

### LINKED ISSUE #18270: "ls" a file and its parent directory may have inconsistent results
**Alluxio Version:**
The latest "master" branch - "305-SNAPSHOT"

**Describe the bug**
"ls" a file and its parent directory may have inconsistent results

**To Reproduce** 
Here is an example

```
$ ./bin/alluxio fs ls -f /
-rw-rw-r--  test   test             1366                 10-02-2023 17:39:54:284 FILE /file.01
-rw-rw-r--  test   test             1366                 10-02-2023 17:41:37:496 FILE /file.02
-rw-rw-r--  test   test             1366                 10-03-2023 11:04:18:177 FILE /file.03

// create a new file "/file.04" in UFS

$ ./bin/alluxio fs ls /file.04
-rw-rw-r--  test   test             1366                 10-03-2023 11:12:57:668 FILE /file.04

$ ./bin/alluxio fs ls /
-rw-rw-r--  test   test             1366                 10-02-2023 17:39:54:284 FILE /file.01
-rw-rw-r--  test   test             1366                 10-02-2023 17:41:37:496 FILE /file.02
-rw-rw-r--  test   test             1366                 10-03-2023 11:04:18:177 FILE /file.03
```

**Expected behavior**
"ls" a file and its parent directory should have consistent results.

### PR DESCRIPTION
**Pull request by secfree**
### What changes are proposed in this pull request?

Invalid parent cache if it does not have a known child.

### Why are the changes needed?

Fix #18270

### Does this PR introduce any user facing changes?

NO

### CODE REVIEW

**Comment by yyongycy** [comment]
Could you please describe a little about the implementation? How is the parent cache invalided?

**Comment by secfree** [comment]
> Could you please describe a little about the implementation? How is the parent cache invalided?

Sure. Below is the logic
1. When adding a new path to cache, it checks if the path exists in the cache of its parent directory. 
2. If not, it means that the cache of its parent directory has outdated information about its children.
3. Because the cache of its parent directory is outdated, so the corresponding item should be invalidated - calls `mListStatusCache.invalidate(parent)`.

**Comment by yyongycy** [comment]
> > Could you please describe a little about the implementation? How is the parent cache invalided?
> 
> Sure. Below is the logic
> 
> 1. When adding a new path to cache, it checks if the path exists in the cache of its parent directory.
> 2. If not, it means that the cache of its parent directory has outdated information about its children.
> 3. Because the cache of its parent directory is outdated, so the corresponding item should be invalidated - calls `mListStatusCache.invalidate(parent)`.

What if the node to store the parent is offline? How is that handled?

**Comment by yyongycy** [comment]
@huanghua78   What is your opinion? This looks like an improvement, but still have some uncovered areas.

**Comment by secfree** [comment]
> What if the node to store the parent is offline? How is that handled?

If the parent is not in the same worker, then `mListStatusCache.getIfPresent(parent)` will return `null` and the `invalidate` logic will not be triggered.

**Comment by secfree** [comment]
> It seems that this PR cannot solve this issue completely. It only works if the file and its parent directory are located in the same worker.

I will create a dedicated issue for this: #18270 and will just close this PR.

**Pull request closed without merging**
