### PR TITLE
Update jersey version

### PR DESCRIPTION
**Pull request by ddadaal**
### What changes are proposed in this pull request?

Try updating jersey to resolve some CVEs.

### Why are the changes needed?

Some CVEs are caused by jersey. This PR updates jersey to a fixed version.

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Comment by ddadaal** [comment]
Failed test cases:

- ConcurrentFileInStreamIntegrationTest: flaky
- FileOutStreamIntegrationTest: flaky

**Comment by ddadaal** [comment]
Failed test cases.
- alluxio.client.fs.io.FileOutStreamIntegrationTest.cancelWrite: flaky

Success at 2nd attempt:
- alluxio.client.fs.concurrent.ConcurrentFileInStreamIntegrationTest.FileInStreamConcurrency

**Comment by yyongycy** [comment]
@apc999 @yuzhu @ggezer please take a look at this upgrade.

**Comment by yyongycy** [comment]
@ddadaal  please check the test failure, see if those fall into the excel.

**Review by yuzhu — APPROVED** [review]

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by ddadaal** [comment]
Old failures: #15, #7, #17, #18, #19, #20, #21, #22

**Pull request merged**
