### PR TITLE
Fix loadCacheSmallerNewCacheSizeLocal Test

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
I don't understand why this code assumed that the very first pageoffset was going to be there in a downsized local cache 100% of the time.

**Review by apc999 — APPROVED** [review]
thanks for fixing this!

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Comment by bradyoo** [comment]
alluxio-bot, cherry-pick this to enterprise-2.4 please

**Comment by bradyoo** [comment]
alluxio-bot, cherry-pick this to 2.4 please

**Comment by bradyoo** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
