### PR TITLE
Fix table mount option description in docs to "mount.option."

### PR DESCRIPTION
**Pull request by liupan664021**
Fix: #12675
The mount option of attachdb differs from docs and code.

### CODE REVIEW

**Review by maobaolong — APPROVED** [review]
Good catch. +1

**Comment by yuzhu** [comment]
@liupan664021  Thanks for the fix! In this case, could we fix the doc rather than the code? to be backwards compatible?

**Review by yuzhu — APPROVED** [review]
LGTM

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please

**Pull request merged**
