### PR TITLE
Add per minute description to cluster throughput metric

### PR DESCRIPTION
**Pull request by LuQQiu**
Add per minute description to cluster throughput metrics.
Cluster throughput metrics are calculated by (total cluster bytes / minutes lasted)

### CODE REVIEW

**Review by tieujason330 — APPROVED** [review]

**Review by gpang — APPROVED** [review]
LGTM

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please

**Pull request merged**
