### PR TITLE
Try to fix duplicate logging library

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Comment by yuzhu** [comment]
@LuQQiu we have to merge this to get nightly running, but I want you to have a look at the exclusions and shading part of the pom file.

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
@yuzhu Changes LGTM

**Pull request merged**
