### PR TITLE
Move commits to branch 1.8

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by yuzhu** [comment]
alluxio-bot, check this please

**Comment by yuzhu** [comment]
jenkins, test this please

**Comment by gpang** [comment]
@yuzhu 
A PR is only allowed to have a single cherry-pick commit. This should be split up so each PR is a single cherry-pick commit. Thanks!

**Pull request closed without merging**
