### PR TITLE
Bump rocksdb version to 6.25.3

### PR DESCRIPTION
**Pull request by yuzhu**
### What changes are proposed in this pull request?

Bump rocksdb to 6.25.3 to possibly address segfault issue

### CODE REVIEW

**Review by ggezer — APPROVED** [review]
lgtm after test pass.

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Comment by jayzhenghan** [comment]
This has been stably reproduced, and has it been verified to be effective? @yuzhu

**Pull request merged**
