### PR TITLE
Fix lerna version

### PR DESCRIPTION
**Pull request by yuzhu**

### CODE REVIEW

**Comment by yuzhu** [comment]
@tieujason330 @Xenorith PTAL at this fix.

**Comment by tieujason330** [comment]
LGTM, tested locally as well

**Comment by yuzhu** [comment]
```Tests in error: 
alluxio.server.ft.journal.MultiMasterJournalTest.testTtl(alluxio.server.ft.journal.MultiMasterJournalTest)
  Run 1: MultiMasterJournalTest.before:53 » IO java.lang.RuntimeException: alluxio.exce...
  Run 2: MultiMasterJournalTest.before:53 » IO java.lang.RuntimeException: alluxio.exce...

Flaked tests: 
alluxio.server.ft.journal.MultiMasterJournalTest.testCheckpointReplay(alluxio.server.ft.journal.MultiMasterJournalTest)
  Run 1: MultiMasterJournalTest.before:53 » IO java.lang.RuntimeException: alluxio.exce...
  Run 2: PASS
``` unrelated flakey test, merging this

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to enterprise-2.0 please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Pull request merged**
