### PR TITLE
Remove unnecessary directory created metrics inc

### LINKED ISSUE #8254: Incorrect directories created metric
**Alluxio Version:**
1.8.1

**Describe the bug**
The "Directories Created" metric in the web ui includes created files in its count.

**To Reproduce**
Create a bunch of files and look at http://localhost:19999/metricsui

**Expected behavior**
"Directories Created" should only count directories

**Additional context**
It looks like we increment both files and directory count here: https://github.com/Alluxio/alluxio/blob/master/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java#L1343

### PR DESCRIPTION
**Pull request by tahakashaf**
https://github.com/Alluxio/alluxio/issues/8254 Incorrect directories created metric

### CODE REVIEW

**Comment by tahakashaf** [comment]
Jenkins, please test this

**Comment by aaudiber** [comment]
Thanks for the fix @tahakashaf!

**Comment by calvinjia** [comment]
@tahakashaf This change looks good, please sign the contributor license agreement.

**Comment by tahakashaf** [comment]
> @tahakashaf This change looks good, please sign the contributor license agreement.

@calvinjia  Already signed but its still showing status as pending.Similarly issue I faced with previous pull request #8395 ,it was manually removed by @apc999 at that time.

**Comment by aaudiber** [comment]
@tahakashaf sorry for the trouble. The original error was caused by by an expired SSL certificate for our CLA checker. We've renewed the SSL certificate now, so it shouldn't happen again. I've deleted the pending entry from the database, so you can start fresh. Can you go through a CLA signing process again?

**Comment by tahakashaf** [comment]
> @tahakashaf sorry for the trouble. The original error was caused by by an expired SSL certificate for our CLA checker. We've renewed the SSL certificate now, so it shouldn't happen again. I've deleted the pending entry from the database, so you can start fresh. Can you go through the CLA signing process again?

@aaudiber np.Thank you for the help.

**Comment by aaudiber** [comment]
Thanks for your patience, and thanks for fixing this bug!

**Pull request merged**
