### PR TITLE
Enhance and stabilize the `quorum elect` command

### PR DESCRIPTION
**Pull request by jenoudet**
### Why are the changes needed?
The `quorum elect` command can be slow, hang, incorrectly display error messages, and has many small shortcomings. This PR tackles those problems.

### Does this PR introduce any user facing changes?
No

### CODE REVIEW

**Comment by maobaolong** [comment]
@codings-dan Would you please take a look at this PR? Thanks

**Comment by codings-dan** [comment]
@jenoudet If resetPriority is not executed after the transfer leadership is completed, will subsequent elections be affected?

**Review by ggezer — CHANGES_REQUESTED** [review]
Thanks for the improvement. 
Can you also add a test for validating the auto-reset behavior you observed?

**Comment by jenoudet** [comment]
> @jenoudet If resetPriority is not executed after the transfer leadership is completed, will subsequent elections be affected?

@codings-dan In our testing we have observed that resetting priorities after the transfer of leadership has no impact on the peer priorities.  To ensure that removing this final step has no impact on subsequent elections (and the overall well being of the cluster) we've added new tests to cover these use cases. These test are contained within this PR.

**Review by jenoudet — COMMENTED** [review]
Added a test that checks that the peer priorities are reset to 1 for all members, except the new leader to 0.

**Review by ggezer — APPROVED** [review]

**Comment by ggezer** [comment]
alluxio-bot, merge this please

**Pull request merged**
