### PR TITLE
[ALLUXIO-1821][ALLUXIO-1822]Fix a bug in which the metric of RemoteBlockXXXStream is incorrect 

### PR DESCRIPTION
**Pull request by ETsunchao**
Also delete an error logic which is to increment metrics in RemoteBlockInStream because the increment logic is already exist in BufferedBlockInStream.

### CODE REVIEW

**Comment by yupeng9** [comment]
LGTM.

**Comment by yupeng9** [comment]
Thanks for the patch

**Comment by yupeng9** [comment]
ok to test

**Comment by apc999** [comment]
+1 LGTM. Thanks for fixing the bug!

**Pull request merged**
