### PR TITLE
[DOCFIX] Update unified namespace doc example comment

### PR DESCRIPTION
**Pull request by Limuzhou**
the alluxio fs ls -R / command with the R flag will list out the files recursively, including the /demo/hello file

### CODE REVIEW

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
@Xenorith cherry-pick?

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.7 please

**Pull request merged**
