### PR TITLE
Support utimens for JNI-FUSE

### LINKED ISSUE #13090: Support JNI Fuse touch command
**Alluxio Version:**
Alluxio master - 2.6.0-SNAPSHOT

**Describe the bug**
Running `touch` command with JNI-Fuse mount point fails.
```
$touch /tmp/alluxio/fuseMount/a.file
touch: setting times of ‘/tmp/alluxio/fuseMount/a.file’: Function not implemented
```
Looks like JNI-Fuse need to support `setattr` operation to be able to get `touch` to work

**To Reproduce**
- Create an Alluxio cluster
- Create a fuse mount point `fuseMount` and grant permissions
- Mount JNI-Fuse with `integration/fuse/bin/alluxio-fuse mount fuseMount /`
- Run `touch` command against the mount point

**Expected behavior**
Touch should succeed without exceptions

**Urgency**
Not urgent

**Additional context**
JNR-FUSE touch succeed without error

### PR DESCRIPTION
**Pull request by maobaolong**
Fix #13090

### CODE REVIEW

**Comment by maobaolong** [comment]
@apc999 @LuQQiu I have tested this PR can solve the #13090, please take a look, thank you.

**Comment by maobaolong** [comment]
I do the following test

```
[root@9 ~/alluxio-github/alluxio]# integration/fuse/bin/alluxio-fuse mount fuseMount /
[root@9 ~/alluxio-github/alluxio]# touch fuseMount/iamok.txt
[root@9 ~/alluxio-github/alluxio]# ll fuseMount/iamok.txt
-rw-r--r-- 1 root root 0 Apr 13 14:45 fuseMount/iamok.txt
```

with the alluxio-site.properties like this,

```
alluxio.fuse.debug.enabled=true
```

see the fuse.out like this,

```
LOOKUP /iamok.txt
getattr /iamok.txt
   unique: 64, error: -2 (No such file or directory), outsize: 16
unique: 65, opcode: CREATE (35), nodeid: 1, insize: 66, pid: 29470
create flags: 0x8841 /iamok.txt 0100644 umask=0022
   create[7] flags: 0x8841 /iamok.txt
getattr /iamok.txt
   NODEID: 4
   unique: 65, success, outsize: 160
unique: 66, opcode: FLUSH (25), nodeid: 4, insize: 64, pid: 29470
flush[7]
   unique: 66, success, outsize: 16
unique: 67, opcode: SETATTR (4), nodeid: 4, insize: 128, pid: 29470
utimens /iamok.txt 1618296326.713091734 1618296326.713091734
getattr /iamok.txt
   unique: 67, success, outsize: 120
unique: 68, opcode: FLUSH (25), nodeid: 4, insize: 64, pid: 29470
flush[7]
   unique: 68, success, outsize: 16
unique: 69, opcode: RELEASE (18), nodeid: 4, insize: 64, pid: 0
release[7] flags: 0x8801
   unique: 69, success, outsize: 16
```

It seems looking good.

**Review by apc999 — APPROVED** [review]
Thanks @maobaolong for fixing this issue!

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
