### PR TITLE
Check errorMessage in TableMasterJournalIntegrationTest

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
alluxio-bot, test this please.

**Comment by bradyoo** [comment]
@gpang easy change

**Comment by bradyoo** [comment]
@gpang

**Review by gpang — APPROVED** [review]
LGTM

**Comment by bradyoo** [comment]
Can you merge it for me? I don't have permission.

**Comment by gpang** [comment]
allluxio-bot, merge this please

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Pull request merged**
