### PR TITLE
Send incrementals for counter metrics

### PR DESCRIPTION
**Pull request by ns1123**

### CODE REVIEW

**Comment by ns1123** [comment]
@calvinjia PTAL

**Comment by calvinjia** [comment]
@ns1123 Thanks for the fix, could you write a unit test for this?

**Comment by calvinjia** [comment]
@ns1123 merging this for now, please add a test in a follow up PR.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please.

**Pull request merged**
