### PR TITLE
[ALLUXIO-2341]Improve error handling in AlluxioMaster#startMasters

### PR DESCRIPTION
**Pull request by justsozl**
https://alluxio.atlassian.net/browse/ALLUXIO-2341

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
@justsozl Thanks!

Your commits are not associated with a github account. You can [add the email address to your github account](https://help.github.com/articles/adding-an-email-address-to-your-github-account/), or [change email address of your commits](http://stackoverflow.com/a/1320317/401884).

**Comment by justsozl** [comment]
Jenkins,why not merged?

**Comment by justsozl** [comment]
alluxio-bot, check this please'

**Comment by justsozl** [comment]
alluxio-bot,check this please

**Comment by justsozl** [comment]
alluxio-bot,check this please

**Comment by gpang** [comment]
@justsozl Thanks for the PR! It looks like your commit email is not associated with your github account. Could you [add the commit email address to your github account](https://help.github.com/articles/adding-an-email-address-to-your-github-account/), or [modify your commit email](http://stackoverflow.com/a/1320317/401884)?

**Comment by justsozl** [comment]
I have modified my commit email . So could you please check this please again?

**Comment by justsozl** [comment]
alluxio-bot,check this please

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
It looks like the commits are being made with email `774338628@.com`

**Comment by calvinjia** [comment]
@justsozl Could you update your github info?

**Comment by justsozl** [comment]
Sorry for making my commit with wrong eamil address 774338628@com,and I tried in vain to  make it right!

**Comment by aaudiber** [comment]
@justsozl Starting over might be easier than trying to fix this PR. Could you close this and reopen a new PR?

**Pull request closed without merging**
