### PR TITLE
[SMALLFIX] Remove extraneous unboxing of Long

### PR DESCRIPTION
**Pull request by bradyoo**

### CODE REVIEW

**Comment by bradyoo** [comment]
Can you merge this for me?

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
@bradyoo should this PR be cherry-picked to branch-2.2?

**Comment by LuQQiu** [comment]
@ZacBlanco Do you think those small fix PRs should be goin in branch-2.2?

**Comment by ZacBlanco** [comment]
I will comb through this weekend and determine which ones to cherry-pick

**Comment by ZacBlanco** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please

**Pull request merged**
