### PR TITLE
[SMALLFIX] add @Nullable for GlusterFSUnderFileSystem.java

### PR DESCRIPTION
**Pull request by whatbeg**
add @Nullable for GlusterFSUnderFileSystem.java

### CODE REVIEW

**Comment by calvinjia** [comment]
@whatbeg Thanks for the improvement. Should we annotate the interface instead of the implementing class?

**Comment by calvinjia** [comment]
@whatbeg any updates on this? thanks.

**Comment by whatbeg** [comment]
@calvinjia what do you mean? which @nullable annotation should not be added?

**Comment by calvinjia** [comment]
@whatbeg If the interface contract is to return null in certain cases, I think we should annotate the interface (`UnderFileSystem`) as well

**Comment by yupeng9** [comment]
@whatbeg Thanks for the contribution. Can you address the comment and resolve the conflict?

**Comment by yupeng9** [comment]
@whatbeg feel free to reopen this PR after you address the comments.

**Pull request closed without merging**
