### PR TITLE
[ALLUXIO-3300] more speed up to lsr and du -r

### PR DESCRIPTION
**Pull request by yuzhu**
https://alluxio.atlassian.net/browse/ALLUXIO-3300

further speed up recursive ls by not syncpersist when we are create a file as part of loadMetadata

### CODE REVIEW

**Comment by yuzhu** [comment]
@gpang PTAL, thanks. This reduced (first time) running time of 10k lsr further to 23 secs from 490 secs.

**Comment by gpang** [comment]
@yuzhu Should a new ticket be created to track this improvement?

**Comment by yuzhu** [comment]
@gpang JIRA created to track this, PTAL.

**Comment by yuzhu** [comment]
@calvinjia I think if we follow a `copy` semantics, we should set the creation time to be the time when it is loaded into Alluxio. (It is similar to making a copy of the file)  
It is a different story for modification time though. I think we should take the modification time from the UFS.

**Pull request merged**
