### PR TITLE
[DOCFIX] Update unified-namespace doc

### PR DESCRIPTION
**Pull request by wangao1236**
### What changes are proposed in this pull request?

Please outline the changes and how this PR fixes the issue.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

### CODE REVIEW

**Comment by maobaolong** [comment]
@wangao1236 Please sign the cla [sign a contribution license agreement](https://cla.alluxio.org/)

**Comment by maobaolong** [comment]
@wangao1236 Please add a prefix `[DOCFIX]` to the title of this PR.

**Review by maobaolong — APPROVED** [review]
Thanks for the contribution. It LGTM. @LuQQiu Would you like to have a double check?

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Pull request merged**
