### PR TITLE
[DOCFIX] Improve Quick Start Guide for 1.1

### PR DESCRIPTION
**Pull request by gpang**

### CODE REVIEW

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by aaudiber** [comment]
LGTM assuming this is just a backport of https://github.com/Alluxio/alluxio/pull/3594

**Comment by gpang** [comment]
Yes, this is a backport, plus a few fixes (latest 3 commits)

**Comment by apc999** [comment]
LGTM

**Pull request merged**
