### PR TITLE
[DOCFIX] Update Mesos doc

### PR DESCRIPTION
**Pull request by tieujason330**
pr-link: Alluxio/alluxio#9272
change-id: cid-a2af7961c51306b7aaee8cee6dbffa2615e15660

### CODE REVIEW

**Comment by tieujason330** [comment]
@cheng-chang, PTAL thanks!

**Comment by tieujason330** [comment]
jenkins, test this please

**Comment by tieujason330** [comment]
jenkins, test this please

**Comment by tieujason330** [comment]
jenkins, test this please

**Comment by cheng-chang** [comment]
alluxio-bot, merge this please

**Pull request merged**
