### PR TITLE
Increase block heartbeat interval from worker from 1s to 10s

### PR DESCRIPTION
**Pull request by ns1123**
This change will reduce the load on the Alluxio Master when running a large number of workers. However, it will also impact the ability of the Alluxio Master to provide the most up-to-date block locations of a block in a cluster with a high eviction rate.

### CODE REVIEW

**Comment by gpang** [comment]
@ns1123 Can you update the PR description with the potential implications of a longer heartbeat? I know less frequent heartbeat processing will use fewer resources, but what else can be affected by a less frequent heartbeat? accurate block locations? anything else?

**Comment by ns1123** [comment]
@gpang done.

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Comment by gpang** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please

**Comment by gpang** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Comment by gpang** [comment]
alluxio-bot, cherry-pick this to branch-1.8 please

**Pull request merged**
