### PR TITLE
Merge master to ratis-journal branch

### PR DESCRIPTION
**Pull request by LuQQiu**
Merge changes in master branch to ratis-journal branch.
Bring ratis-journal branch up-to-date

### CODE REVIEW

**Comment by LuQQiu** [comment]
jenkins, test this with java 11 please

**Comment by LuQQiu** [comment]
jenkins, test this with java 11 please

**Comment by bf8086** [comment]
jenkins, test this please.

**Review by bf8086 — APPROVED** [review]
LGTM.

**Comment by bf8086** [comment]
alluxio-bot, feature-merge this please.

**Pull request merged**
