### PR TITLE
[ALLUXIO-2061] Fix typo in BlockWorkerClientServiceHandler javadoc

### PR DESCRIPTION
**Pull request by arthursunbao**
https://alluxio.atlassian.net/browse/ALLUXIO-2061

### CODE REVIEW

**Comment by gpang** [comment]
alluxio-bot, check this please

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
LGTM

**Comment by aaudiber** [comment]
@arthursunbao Could you sign the [contribution license agreement](http://cla.alluxio.org/)? After that this is good to merge.

**Comment by aaudiber** [comment]
LGTM

**Pull request merged**
