### PR TITLE
[ALLUXIO-2524] fixed typo in ALLUXIO-2524

### PR DESCRIPTION
**Pull request by larrymalin**
https://alluxio.atlassian.net/browse/ALLUXIO-2524

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, add to whitelist

**Comment by aaudiber** [comment]
@larrymalin Thanks for the fix, do you mind signing the CLA? You can follow this link: http://cla.alluxio.org/

**Comment by larrymalin** [comment]
I've already signed the CLA.

Thanks.

Larry

-

**Comment by aaudiber** [comment]
Sorry, something must have gone wrong during the submission. I've resent the CLA, could you fill it out again and submit it?

**Comment by larrymalin** [comment]
Sure, I just signed this. Please check.

Lin

--

**Comment by aaudiber** [comment]
Thanks!

**Pull request merged**
