### PR TITLE
Remove hostname from metrics key

### PR DESCRIPTION
**Pull request by beinan**
### What changes are proposed in this pull request?

Remove hostname from metrics key

### Why are the changes needed?

For easy aggregation on prometheus and grafana side

### Does this PR introduce any user facing changes?

Add a flag to disable this for compatibility

### CODE REVIEW

**Review by LuQQiu — APPROVED** [review]
LGTM

**Review by maobaolong — APPROVED** [review]
LGTM, This make metrics easy to collect and recognized.

**Comment by beinan** [comment]
alluxio-bot, merge this please.

**Comment by beinan** [comment]
alluxio-bot, merge this please.

**Comment by jja725** [comment]
alluxio-bot, cherry-pick this to master-2.x please

**Pull request merged**
