### PR TITLE
Upgrade RocksDB to 6.15.2

### PR DESCRIPTION
**Pull request by bradyoo**
There are occasionally SIGSEGVs in RocksDB and there is some suggestion that this may help.

### CODE REVIEW

**Comment by bf8086** [comment]
@bradyoo Thanks for the improvement. Do you mind adding a short description on why we need to upgrade RocksDB?

**Comment by bradyoo** [comment]
Added description.

**Review by bf8086 — APPROVED** [review]

**Comment by bradyoo** [comment]
alluxio-bot, merge this please.

**Comment by jiacheliu3** [comment]
Related to https://github.com/Alluxio/alluxio/issues/12999

**Comment by bradyoo** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please.

**Pull request merged**
