### PR TITLE
[DOCFIX] Clean up Eng Doc - remove catalog and transformation

### PR DESCRIPTION
**Pull request by jingwenouyang**
### What changes are proposed in this pull request?

Removing document for 
- transformation
- catalog

### Why are the changes needed?

As part of effort of Eng Doc clean up, we have decided to remove the document of experimental / deprecated features to avoid confusion. 

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. Eng document

### CODE REVIEW

**Comment by jingwenouyang** [comment]
@yuzhu @Rianico @binarylu my first try on doc removal, please review. Once approved, I will merge this one when i get confirmation from field. Thanks!

**Comment by jingwenouyang** [comment]
@apc999 hi Bin, i see that Trino official doc has info related to Alluxio catalog service too, when this pushes, we should work with them to take it out too?

**Review by apc999 — APPROVED** [review]

**Review by Xenorith — CHANGES_REQUESTED** [review]
also remove the pages:
- cn/core-services/Catalog.md
- cn/core-services/Transformation.md

**Review by Xenorith — APPROVED** [review]

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Comment by Xenorith** [comment]
alluxio-bot, merge this please

**Pull request merged**
