### PR TITLE
[DOCFIX] Add a `bootstrap-conf` command snippet in the Chinese version of `docs/en/Configuring-Alluxio-with-Swift.md`

### PR DESCRIPTION
**Pull request by xyguo**
This PR fixes issue with JIRA ticket [ALLUXIO-1982](https://alluxio.atlassian.net/browse/ALLUXIO-1982)

In `docs/en/Configuring-Alluxio-with-Swift.md` of the English version there is a `bootstrap-conf` command snippet added in the `Initial Setup` section. This PR translate it into Chinese and add it in the corresponding page of the Chinese version.

### CODE REVIEW

**Comment by ifcharming** [comment]
Seems like this ticket has already been taken in https://github.com/Alluxio/alluxio/pull/3456 
Before working on one JIRA ticket, please assign it to yourself first to avoid duplicate work...

**Comment by ifcharming** [comment]
If you don't mind, can you please close this PR since the other (#3456) was submitted first.

**Comment by xyguo** [comment]
@ifcharming Actually we are not duplicated. the #3456 is fixing a different file (Configuring-Alluxio-with-**GlusterFS**.md), while my PR fixes the docs/en/Configuring-Alluxio-with-**Swift**.md

**Comment by xyguo** [comment]
And by the way the JIRA has indeed been assigned to me :-)

**Comment by ifcharming** [comment]
oops, sorry they look too similar...

LGTM, thanks for the improvement!

**Comment by ifcharming** [comment]
ok to test

**Pull request merged**
