### PR TITLE
[ALLUXIO-1937] remove extra newline at the end of alluxio_stop.sh

### PR DESCRIPTION
**Pull request by vijaysbhat**

### CODE REVIEW

**Comment by gpang** [comment]
Thanks for the contribution, @vijaysbhat ! Could you prefix the title of this PR with "[ALLUXIO-####]" where #### is the number for your JIRA ticket?

Also, could you add a link back to the jira ticket in the PR description? Thanks!

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
ok to test

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
