### PR TITLE
[ALLUXIO-2182] Add hostname to worker metrics name

### PR DESCRIPTION
**Pull request by peisun1115**
https://alluxio.atlassian.net/browse/ALLUXIO-2182

### CODE REVIEW

**Comment by peisun1115** [comment]
Jenkins, test this please

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by apc999** [comment]
LGTM

**Comment by peisun1115** [comment]
@apc999 can you merge it for me?

**Pull request merged**
