### PR TITLE
Update version to 2.6.3-SNAPSHOT for branch-2.6

### PR DESCRIPTION
**Pull request by ferhui**
### What changes are proposed in this pull request?

Change version to 2.6.3-SNAPSHOT

### Why are the changes needed?

Since 2.6.2 has been released, need to update version to 2.6.3-SNAPSHOT for branch-2.6

### Does this PR introduce any user facing changes?

No changes

### CODE REVIEW

**Comment by ferhui** [comment]
@yuzhu Could you please take a look? Thanks

**Comment by yuzhu** [comment]
@LuQQiu could you review this since you did the last edge release?

**Comment by ferhui** [comment]
@LuQQiu Hi, I want to find the latest stable version and find that v2.6.2 is the new. And I want to maintain inner branch, there are 2 choices: 1) checkout the released tag v2.6.2; 2) the branch 2.6. Here I have a question about the release, I find that maybe v2.6.2 does not cut from branch-2.6, is it? What is the release process of Alluxio?

**Comment by LuQQiu** [comment]
@ferhui targetting for faster release circle, we are doing release much more frequent and directly cutting releases from master branch. Yeah all 2.6.1, 2.6.2, 2.6.3 are cutting from Master branch directly and we are not back porting changes from master branch to this branch-2.6 branch.

Then actually 2.6.1-SNAPSHOT is the correct version for this branch.

**Comment by LuQQiu** [comment]
In the future, we may not cut branch-2.7

**Comment by ferhui** [comment]
> LGTM, thanks for updating the branch version



> @ferhui targetting for faster release circle, we are doing release much more frequent and directly cutting releases from master branch. Yeah all 2.6.1, 2.6.2, 2.6.3 are cutting from Master branch directly and we are not back porting changes from master branch to this branch-2.6 branch.

Got it, thank you very much. So we should choose v2.6.2 directly.

**Pull request closed without merging**
