### PR TITLE
[SMALLFIX] Use static imports for standard test utilities

### PR DESCRIPTION
**Pull request by shizihao123**

### CODE REVIEW

**Comment by apc999** [comment]
@shizihao123 can you resolve the conflict? thanks

**Comment by shizihao123** [comment]
Have resolved conflicts，please review again！ @apc999

**Comment by apc999** [comment]
@shizihao123 can you merge with master again?

**Comment by apc999** [comment]
@shizihao123 can you merge with master again?

**Comment by shizihao123** [comment]
Have merged master, please check it again, thank you! @apc999

**Comment by shizihao123** [comment]
Jenkins, test this please

**Pull request merged**
