### PR TITLE
[ALLUXIO-2750] Make BlockInfoTest final

### PR DESCRIPTION
**Pull request by gaoxielao**
https://alluxio.atlassian.net/browse/ALLUXIO-2750
Make BlockInfoTest final to avoid accidental subclass extension

### CODE REVIEW

**Comment by gaoxielao** [comment]
alluxio-bot, check this please

**Comment by gaoxielao** [comment]
alluxio-bot, check this please

**Comment by gaoxielao** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
alluxio-bot, check this please

**Comment by aaudiber** [comment]
It looks like this is a duplicate of https://github.com/Alluxio/alluxio/pull/5415

**Pull request closed without merging**
