### PR TITLE
Upgrade Apache Ratis from 2.0.0 to 2.3.0

### PR DESCRIPTION
**Pull request by jenoudet**
### What changes are proposed in this pull request?
Upgrade Apache Ratis dependency from 2.0.0 to 2.3.0

### Why are the changes needed?
2.3.0 brings increased stability, especially around the snapshotting mechanism.

### Does this PR introduce any user facing changes?
No

### CODE REVIEW

**Review by tcrain — APPROVED** [review]

**Review by codings-dan — COMMENTED** [review]
@jenoudet Ratis 2.3.1 will be released recently, it will contain some bug fixes, should you upgrade 2.3.1 directly?

**Comment by jenoudet** [comment]
> @jenoudet Ratis 2.3.1 will be released recently, it will contain some bug fixes, should you upgrade 2.3.1 directly?

@codings-dan Do you know when exactly? It would make sense to upgrade to 2.3.1 directly indeed if it's right around the corner.

**Comment by codings-dan** [comment]
> > @jenoudet Ratis 2.3.1 will be released recently, it will contain some bug fixes, should you upgrade 2.3.1 directly?
> 
> @codings-dan Do you know when exactly? It would make sense to upgrade to 2.3.1 directly indeed if it's right around the corner.

@jenoudet At present, Ratis still has some PRs that need to be merged, and it may take some time. If it affects the progress here, we can also upgrade to 2.3.0 first, and then upgrade to 2.3.1 later.

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Pull request merged**
