### PR TITLE
Add Fuse in worker integration test

### PR DESCRIPTION
**Pull request by LuQQiu**

### CODE REVIEW

**Comment by LuQQiu** [comment]
WorkerFuseIntegrationTest

[ERROR] alluxio.server.worker.WorkerFuseIntegrationTest.touchAndLs  Time elapsed: 5.421 s  <<< ERROR!
ExitCodeException exitCode=1: touch: setting times of '/tmp/alluxio-tests/WorkerFuseIntegrationTest-touchAndLs-a047e623-11f7-401f-9e78-b4b33e80aac7/touchTestFile': Function not implemented

**Comment by LuQQiu** [comment]
[INFO] Running alluxio.server.worker.WorkerFuseIntegrationTest
[ERROR] ERROR ../../src/main/native/libjnifuse/jnifuse_fs.cc:94 you cant initialize more than once
[ERROR] ERROR ../../src/main/native/libjnifuse/jnifuse_fs.cc:94 you cant initialize more than once

**Comment by LuQQiu** [comment]
From manual testing, both standalone Fuse and worker fuse do not support `touch`.
Not quite sure why `JNIFuseIntegrationTest` passed while `WorkerFuseIntegrationTest` failed.
// fuseMount is mounted by setting worker properties
[ec2-user@AlluxioSandbox-workers-1 alluxio]$ touch /tmp/alluxio/fuseMount/touchTestFile
touch: setting times of ‘/tmp/alluxio/fuseMount/touchTestFile’: Function not implemented
[ec2-user@AlluxioSandbox-workers-1 alluxio]$ integration/fuse/bin/alluxio-fuse mount fuseMount2 /
Starting AlluxioFuse process: mounting alluxio path "/" to local mount point "fuseMount2" with options="big_writes"
Successfully mounted Alluxio path "/" to fuseMount2.
See /tmp/alluxio/logs/fuse.log for logging messages
[ec2-user@AlluxioSandbox-workers-1 alluxio]$ touch /tmp/alluxio/fuseMount2/touchTestFile
touch: setting times of ‘/tmp/alluxio/fuseMount2/touchTestFile’: Function not implemented

**Comment by LuQQiu** [comment]
Investigating the following errors:
```
Error: 5.949 [ERROR] Failures: 
Error: 5.949 [ERROR] alluxio.server.worker.WorkerFuseIntegrationTest.ls
Error: 5.949 [ERROR]   Run 1: WorkerFuseIntegrationTest>AbstractFuseIntegrationTest.ls:245 expected:<[40K]> but was:<[0]>
Error: 5.952 [ERROR]   Run 2: WorkerFuseIntegrationTest>AbstractFuseIntegrationTest.ls:245 expected:<[40K]> but was:<[0]>
17:48:15.952 [INFO] 
Error: 5.952 [ERROR] Errors: 
Error: 5.952 [ERROR] alluxio.server.worker.WorkerFuseIntegrationTest.ddDuAndRm
Error: 5.952 [ERROR]   Run 1: WorkerFuseIntegrationTest>AbstractFuseIntegrationTest.ddDuAndRm:210 » ExitCode
Error: 5.952 [ERROR]   Run 2: WorkerFuseIntegrationTest>AbstractFuseIntegrationTest.ddDuAndRm:210 » ExitCode
```
Those commands passed in my linux env testing and local docker testing using the same docker image as the PR build. 
Still not able to get the error repo in my testing.

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Pull request merged**
