### PR TITLE
[ALLUXIO-2347] Improve error handling in S3UnderFileSystemFactory#create

### PR DESCRIPTION
**Pull request by ninjatop**
https://alluxio.atlassian.net/browse/ALLUXIO-2347
remove log statement

### CODE REVIEW

**Comment by aaudiber** [comment]
ok to test

**Comment by aaudiber** [comment]
Jenkins, add to whitelist

**Comment by aaudiber** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
@ninjatop this looks good after you sign the CLA. Thanks!

**Pull request merged**
