### PR TITLE
Remove duplicate entries in BlockInfo tab of worker WEBUI

### LINKED ISSUE #9518: Display three the same records in  BlockInfo tab of worker node WEBUI
**Alluxio Version:**
2.1.0-SNAPSHOT

**Describe the bug**
when entering page of **BlockInfo** of worker node , each file has three the same records in WEBUI.
clicked the link of file which three the same records, display the same information in WEBUI.
图片

图片

**To Reproduce**
enter page of BlockInfo of worker node 

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

### PR DESCRIPTION
**Pull request by tieujason330**
- Fixes #9518
- following up on style fixes for #9577

pr-link: Alluxio/alluxio#9734
change-id: cid-678633ac37aea6d7712ac2a7bef4db2ed1f28168

### CODE REVIEW

**Comment by calvinjia** [comment]
jenkins, test this please.

**Comment by apc999** [comment]
jenkins, test this please.

**Comment by calvinjia** [comment]
jenkins, test this please.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Pull request merged**
