### PR TITLE
Fix web interface doc

### PR DESCRIPTION
**Pull request by tieujason330**

### CODE REVIEW

**Comment by tieujason330** [comment]
@ZacBlanco PTAL, thanks!

**Comment by tieujason330** [comment]
@calvinjia - PTAL - a small doc change I made while reviewing for ee. Let me know if this is worth merging at this time

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please

**Pull request merged**
