### PR TITLE
[ALLUXIO-2349]Improve error handling in GCSUnderFileSystemFactory#create

### PR DESCRIPTION
**Pull request by nicefish666**
https://alluxio.atlassian.net/browse/ALLUXIO-2349
Right now we handle an exception by both logging and rethrowing the exception. This isn't great because the code which catches the thrown exception will also log it, so we will log the same exception multiple times.
We should remove the log statement.

### CODE REVIEW

**Comment by aaudiber** [comment]
@nicefish666 do you know where the three "Signed-off-by: nicefish666" commits are coming from? Could we remove those?

**Comment by nicefish666** [comment]
yes,these could be removed

**Comment by nicefish666** [comment]
please check my lastest pr

**Comment by aaudiber** [comment]
Thanks for fixing - I'll close this PR and we can move to the new one

**Pull request closed without merging**
