### PR TITLE
[SMALLFIX]Java 8 Improvement: replace anonymous type with lambda in RetryHandlingMetaMasterClient#getInfo

### PR DESCRIPTION
**Pull request by Ls1234567**

### CODE REVIEW

**Comment by Ls1234567** [comment]
?

**Comment by aaudiber** [comment]
@Ls1234567 The build is failing because `TException` is now an unused import - please remove the import so that the build passes

**Comment by Ls1234567** [comment]
@aaudiber I removed the TException import, but the build still failed

**Comment by aaudiber** [comment]
@Ls1234567 It looks like there's a findbugs warning that `mClient` is never initialized. You can fix this by setting `mClient = null;` in the second line of the constructor

**Comment by aaudiber** [comment]
to verify, run `mvn findbugs:check` from the `core/client/fs` directory

**Pull request merged**
