### PR TITLE
Prevent asyncUpdateFileAccessTime to bring down applications

### PR DESCRIPTION
**Pull request by apc999**
Fixes https://github.com/Alluxio/alluxio/issues/10681

@cheyang FYI

### CODE REVIEW

**Comment by calvinjia** [comment]
@apc999 Thanks for the fix. In the issue, it reports that only 123 threads are in the threadpool when 128 master client threads are configured, do you know why that would be the case?

**Comment by apc999** [comment]
@calvinjia PTAL

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please

**Pull request merged**
