### PR TITLE
Update comment in alluxio.master.LocalAlluxioMaster#kill

### PR DESCRIPTION
**Pull request by dh-song**
Update comment in alluxio.master.LocalAlluxioMaster#kill

### CODE REVIEW

**Comment by aaudiber** [comment]
ok to test

**Comment by aaudiber** [comment]
Thanks for the PR @dh-song! LGTM.

**Comment by aaudiber** [comment]
+1 LGTM

**Comment by aaudiber** [comment]
@dh-song For future reference, we usually put [SMALLFIX] at the start of the PR title for PRs like this.

**Comment by dh-song** [comment]
got it. Thank you.

**Pull request merged**
